# Config for OpenAI's ChatGPT
#

[config]
# API type ('openai', 'google', ...)
api = 'openai'

# Name of the model to use ('openai', 'google', ...)
name = "gpt-4-turbo-preview"

# API KEY or other authentication token
auth = "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"

# Non-zero temperature for a little bit of variability
temp = 0.05