# Config for OpenAI's ChatGPT
#

[config]
# API type ('openai', 'google', ...)
api = 'openai'

# Name of the model to use ('chatgpt', ...)
name = "gpt-4-turbo-preview"

# API KEY or other authentication token
# NOTE: Can be set here for convenience, but should ideally be given
#       on the command line or in the execution environment
# auth = 

# Non-zero temperature for a little bit of variability
temp = 0.05