# Config for ZORK 1, in an LLM style
#
#

########
## ZORK1
########
[game]
path = "./infocom/zork1/COMPILED/zork1.z3"

# setup text copied from wikipedia
setup = '''
Zork is a text-based adventure game wherein the player explores the ruins of the Great Underground Empire. The player types text commands for their character to traverse locations, solve puzzles, and collect treasure. The game has hundreds of locations, each with a name and description, and the player's commands interact with the objects, obstacles, and creatures within them. Commands can be one or two words (e.g., "get lamp" or "north") or more complex phrases (e.g., "put the lamp and sword in the case"). The command must fit the location's context (e.g., "get lamp" works only if a lamp is present). The program acts as a narrator, describing to the player their location and the results of certain actions. If the game does not understand the player's commands, it asks for the player to retype their actions. The program's replies are typically in a sarcastic, conversational tone, much as a Game Master would use in leading players in a tabletop role-playing game.

Much of the game world is composed of puzzles that must eventually be solved, such as a set of buttons on a dam or a maze to be traversed. Some puzzles have more than one solution. For instance, since the "Loud Room" is too overwhelmingly loud for the player to perform actions, the player can either empty the nearby dam to stop the sound of water falling, or shout "echo" in the room to change its acoustics.[3][6] In the first episode, or Zork I, a thief character is wandering the underground as well, taking items that have been left behind or even stealing from the player's possessions. The player can fight or evade the thief, and can recover stolen items from the thief's treasure room. Some locations contain antagonists that the player must fight or overcome. Beginning in Zork II the player can learn magic spells to use in puzzles and combat.[5] In dark areas, the player must carry a lantern or other light source to avoid being eaten by a monster called a grue. There is a limit to how much "inventory" one can carry, determined by the combined weight of objects, rather than the quantity.

A principal goal of each episode is to collect all the treasures, many of which are hidden behind puzzles. As treasures are collected or tasks are accomplished, the player's score increases, providing a rough measure of how much of the game has been completed. The player may traverse the game world and solve puzzles in almost any order, although some passageways require problem-solving to get through, and some puzzles require the player to possess something gained from solving a different puzzle.

Plot
Zork does not follow a linear storyline. Most of the setting is established through the game's written descriptions of items and locations, as well as manuals in later game releases. Long before the time the game is set in, the Quendor empire, having conquered everywhere above ground, built a massive cave complex to expand. Two hundred years later, the ruler Lord Dimwit Flathead renamed the empire to the Great Underground Empire and spent his reign building massive, largely pointless projects such as an underground dam and the royal museum. A century later, the empire's overspending caused it to collapse, and all the residents left. The abandoned empire is the setting of the three episodes of Zork.

Zork I begins with the unnamed player character near a white house in a small, self-contained area; most of the game occurs underground, as do the subsequent episodes.
'''

# no text files giving descriptions for the ZORK series
background_files = [
]

background_urls = [
    ["https://www.retrogamedeconstructionzone.com/2020/06/zork-1-review-fully-realized-fantasy.html",
    "Among the canon of early text adventures(.*)the true stuff of fantasy."
    ],
    ["https://www.metzomagic.com/showArticle.php?index=145",
    "You are standing in an open field(.*)go a little bit mad in the process."
    ]
]

## Not making use of the walkthrough, so far
walkthrough_urls = [
    ["https://web.mit.edu/marleigh/www/portfolio/Files/zork/transcript.html",
    "(.*)"
    ]
]
