# Config for ABYSS, in LLM style
#
#

[game]
path = "./infocom/abyss/COMPILED/abyss.z6"

setup = '''
abyss is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "using", "with" ],
    [ "toward", "towards", "to" ],
    [ "along", "around" ],
    [ "all", "both" ],
    [ "through", "thru" ],
    [ "in", "into", "inside" ],
    [ "onto", "on" ],
    [ "brief", "super", "superbrief", "verbose" ],
    [ "q", "quit" ],
    [ "unscript", "script" ],
    [ "version" ],
    [ "attach", "connect" ],
    [ "close", "shut" ],
    [ "empty", "pour" ],
    [ "x", "examine" ],
    [ "chase", "follow", "tail" ],
    [ "loan", "deliver", "give", "offer", "hand", "lend", "grant" ],
    [ "hit", "swat", "strike", "punch", "slap", "whack" ],
    [ "invent", "i", "inventory" ],
    [ "raise", "lift" ],
    [ "l", "look" ],
    [ "place", "put" ],
    [ "skim", "browse", "leaf", "read" ],
    [ "talk", "converse", "speak" ],
    [ "catch", "grasp", "take", "pluck", "grab" ],
    [ "z", "wait" ],
    [ "walk", "swim", "head", "go", "proceed", "run" ],
    [ "wear", "don" ],
    [ "y", "yes" ],
    [ "color", "colour" ],
    [ "be" ],
    [ "be?" ],
    [ "who" ],
    [ "what" ],
    [ "where" ],
    [ "when" ],
    [ "why" ],
    [ "how" ],
    [ "can" ],
    [ "may" ],
    [ "do" ],
    [ "could" ],
    [ "would" ],
    [ "should" ],
    [ "might" ],
    [ "will" ],
    [ "must" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "start" ],
    [ "undo" ],
    [ "score" ],
    [ "diagnose" ],
    [ "ask" ],
    [ "blow" ],
    [ "clamp" ],
    [ "cut" ],
    [ "drop" ],
    [ "enter" ],
    [ "exit" ],
    [ "extinguish" ],
    [ "get" ],
    [ "hold" ],
    [ "inflate" ],
    [ "jump" ],
    [ "let" ],
    [ "listen" ],
    [ "lock" ],
    [ "move" ],
    [ "no" ],
    [ "open" ],
    [ "pick" ],
    [ "plug" ],
    [ "press" ],
    [ "pull" ],
    [ "push" ],
    [ "reach" ],
    [ "remove" ],
    [ "set" ],
    [ "show" ],
    [ "sit" ],
    [ "slide" ],
    [ "stick" ],
    [ "switch" ],
    [ "tell" ],
    [ "thank" ],
    [ "tie" ],
    [ "throw" ],
    [ "turn" ],
    [ "unlock" ],
    [ "weld" ],
] # verbs

nouns = [
    [ "button", "purple button" ],
    [ "ship", "alien ship" ],
    [ "button", "fuschia button" ],
    [ "alien" ],
    [ "monitor", "monitors" ],
    [ "chair" ],
    [ "descrambler control box", "box", "descrambler" ],
    [ "fuel cell", "cell", "powercel" ],
    [ "pool", "water" ],
    [ "crack" ],
    [ "welder", "arc welder", "arc-welder" ],
    [ "rod", "welding rod" ],
    [ "clamp", "cable", "red cable" ],
    [ "cup", "black cable", "electrode", "cable" ],
    [ "plug", "power switch", "switch" ],
    [ "power cord", "cord" ],
    [ "button" ],
    [ "gear locker", "locker" ],
    [ "big locker", "locker" ],
    [ "door", "fore door" ],
    [ "barbell", "bar" ],
    [ "weights" ],
    [ "bench" ],
    [ "treadmill" ],
    [ "bicycle", "cycle" ],
    [ "hydraulic hose", "hose" ],
    [ "hydraulic fluid", "fluid" ],
    [ "door", "flood door" ],
    [ "knife", "dive knife" ],
    [ "north", "east", "fore", "aft", "south", "west", "port", "starboard", "direction" ],
    [ "bench", "seat" ],
    [ "lever" ],
    [ "thermometer" ],
    [ "that" ],
    [ "GO" ],
    [ "LG", "l.g" ],
    [ "area", "here", "room", "place" ],
    [ "it", "this" ],
    [ "them" ],
    [ "int.num", "number" ],
    [ "you", "yourself" ],
    [ "her" ],
    [ "him" ],
    [ "body" ],
    [ "head" ],
    [ "hand", "hands" ],
    [ "hours", "turn", "turns", "time", "minute", "min", "hour", "minutes" ],
    [ "wall", "walls", "bulkhead" ],
    [ "flatbed", "Flatbed" ],
    [ "UFO", "ufo" ],
    [ "deepcore", "Deepcore" ],
    [ "Cayman trough", "trough" ],
    [ "montana", "submarine", "Montana", "sub" ],
    [ "outlet", "socket" ],
    [ "yourself", "myself", "bud", "brigman", "me", "self" ],
    [ "hatch", "midship hatch" ],
    [ "missile" ],
    [ "timer" ],
    [ "plate", "panel", "access panel", "hatch" ],
    [ "wires" ],
    [ "wire", "red wire" ],
    [ "wire", "blue wire" ],
    [ "green wire", "wire" ],
    [ "wire", "yellow wire" ],
    [ "orange wire", "wire" ],
    [ "wire", "white wire" ],
    [ "wire cutters", "cutters" ],
    [ "key", "access key" ],
    [ "door" ],
    [ "photograph", "picture", "frame" ],
    [ "dial", "safe" ],
    [ "plastic card", "card", "codes", "code" ],
    [ "tape", "explosive", "plastique" ],
    [ "detonator", "switch", "dial", "timer" ],
    [ "locker" ],
    [ "box" ],
    [ "paper" ],
    [ "key", "steel key" ],
    [ "dryer" ],
    [ "passport" ],
    [ "discharge" ],
    [ "gun", "pistol" ],
    [ "suit", "FBS suit" ],
    [ "dive locker", "locker" ],
    [ "lock" ],
    [ "device" ],
    [ "nitrogen tank", "tank", "base" ],
    [ "k-valve", "nitrogen valve", "valve" ],
    [ "stopper", "nitrogen stopper" ],
    [ "tank", "base", "oxygen tank" ],
    [ "k-valve", "valve", "oxygen valve" ],
    [ "stopper", "oxygen stopper" ],
    [ "tank", "base", "helium tank" ],
    [ "helium valve", "k-valve", "valve" ],
    [ "stopper", "helium stopper" ],
    [ "bins", "bin" ],
    [ "probe", "magnet" ],
    [ "pool", "moon pool" ],
    [ "fire" ],
    [ "hose" ],
    [ "nozzle" ],
    [ "oxygen cylinder", "cylinder" ],
    [ "woman", "person", "Lindsey", "lindsey" ],
    [ "person", "diver", "coffey", "Coffey", "man" ],
    [ "one-night", "person", "One-night", "woman", "night" ],
    [ "hippy", "person", "Hippy", "man" ],
    [ "fish", "person", "Catfish", "catfish", "devries", "man" ],
    [ "SEALs" ],
    [ "suit", "dry suit" ],
    [ "plate", "faceplate" ],
    [ "helmet" ],
    [ "hook" ],
    [ "lift bag", "bag" ],
    [ "CO2 cannister", "cannister" ],
    [ "button", "red button" ],
    [ "compression chamber hatch", "hatch" ],
    [ "hookah" ],
    [ "door", "compression chamber door" ],
    [ "panel" ],
    [ "game bag", "bag" ],
    [ "compressor" ],
    [ "drawer", "center drawer" ],
    [ "floor", "ground" ],
    [ "ceiling", "sky" ],
] # nouns

rooms = [
    "starboard head",
    "Cab three",
    "mess hall",
    "recreation room",
    "torpedo room",
    "fresh water storage",
    "ladderwell A",
    "motel Quick",
    "command module",
    "sonar room",
    "comm room",
    "personal storage",
    "ocean floor",
    "lounge",
    "Zootown",
    "The Waldorf",
    "tri-mix storage",
    "alien chamber",
    "missile launching room",
    "tool room",
    "pump room",
    "laundry",
    "tape library",
    "ladderwell B",
    "captain's quarters",
    "Stu's galley",
    "missile hatch",
    "pantry",
    "tool pusher's office",
    "port head",
    "corridor",
    "ladderwell D",
    "compressor room",
    "port observation deck",
    "engine room",
    "trough lip",
    "lab",
    "bottom of trench",
    "electronics shop",
    "midship hatch",
    "drill room",
    "port battery room",
    "bow",
    "infirmary",
    "dive gear storage",
    "the Swamp",
    "under moonpool",
    "sub bay",
    "ladderwell C",
    "port life support",
    "attack center",
    "starboard life support",
    "ladder well A",
    "computer center",
    "starboard battery room",
    "starboard observation deck",
] # rooms

