# Config for ARTHUR, in LLM style
#
#

[game]
path = "./infocom/arthur/COMPILED/arthur.z3"

setup = '''
arthur is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "with", "using" ],
    [ "toward", "to", "towards" ],
    [ "around", "along" ],
    [ "all", "both" ],
    [ "thru", "through" ],
    [ "under", "beneath", "underneath" ],
    [ "inside", "into", "in" ],
    [ "outside", "out" ],
    [ "on", "onto" ],
    [ "north", "n" ],
    [ "s", "south" ],
    [ "e", "east" ],
    [ "west", "w" ],
    [ "nw", "northwest" ],
    [ "northeast", "ne" ],
    [ "sw", "southwest" ],
    [ "southeast", "se" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "quit", "q" ],
    [ "unscript", "script" ],
    [ "verbose", "super", "superbrief", "brief" ],
    [ "version" ],
    [ "kill", "attack" ],
    [ "destroy", "smash", "break", "damage", "wreck" ],
    [ "bye", "goodbye", "farewell" ],
    [ "shut", "close" ],
    [ "slice", "slash", "cut", "chop" ],
    [ "drink", "sip" ],
    [ "eat", "taste", "lick" ],
    [ "empty", "pour" ],
    [ "x", "examine" ],
    [ "exit", "vacate", "leave" ],
    [ "hand", "grant", "give" ],
    [ "hello", "salute", "greetings", "greet", "hi" ],
    [ "clue", "clues", "hint", "invisiclues", "hints", "help" ],
    [ "slap", "swat", "whack", "hit", "strike" ],
    [ "inventory", "i", "invent" ],
    [ "jump", "hurdle", "dive", "bound", "vault", "leap" ],
    [ "kiss", "smooch" ],
    [ "bow", "kneel" ],
    [ "pound", "rap", "knock", "tap" ],
    [ "l", "look" ],
    [ "place", "put" ],
    [ "lift", "raise" ],
    [ "read", "skim", "browse", "leaf" ],
    [ "free", "unjam", "release" ],
    [ "withdraw", "retract" ],
    [ "mark", "claw", "scratch" ],
    [ "shock", "zap", "fry", "electrocute" ],
    [ "show", "display" ],
    [ "crouch", "squat", "settle", "sit" ],
    [ "sleep", "rest" ],
    [ "talk", "speak", "converse" ],
    [ "catch", "take", "pluck", "grab" ],
    [ "hurl", "fling", "chuck", "toss", "pitch", "throw", "heave" ],
    [ "t", "time" ],
    [ "exchange", "swap", "trade" ],
    [ "unhook", "untie", "unfasten" ],
    [ "z", "wait" ],
    [ "crawl", "go", "head", "proceed", "run", "swim", "walk", "fly" ],
    [ "don", "wear" ],
    [ "shout", "howl", "cry", "yell", "scream" ],
    [ "yes", "y" ],
    [ "ozmoo", "quendor", "frotz", "plugh", "zork", "gnusto", "yoho", "frobozz", "xyzzy" ],
    [ "credits", "credit" ],
    [ "be" ],
    [ "be?" ],
    [ "who" ],
    [ "what" ],
    [ "where" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "start" ],
    [ "undo" ],
    [ "score" ],
    [ "ask" ],
    [ "bar" ],
    [ "bite" ],
    [ "blow" ],
    [ "buy" ],
    [ "call" ],
    [ "challenge" ],
    [ "chew" ],
    [ "climb" ],
    [ "descend" ],
    [ "dig" ],
    [ "dip" ],
    [ "dismount" ],
    [ "distract" ],
    [ "drop" ],
    [ "eavesdrop" ],
    [ "enter" ],
    [ "extend" ],
    [ "extinguish" ],
    [ "fill" ],
    [ "get" ],
    [ "hide" ],
    [ "hold" ],
    [ "joust" ],
    [ "kick" ],
    [ "land" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "melt" ],
    [ "mount" ],
    [ "move" ],
    [ "no" ],
    [ "open" ],
    [ "pick" ],
    [ "point" ],
    [ "poke" ],
    [ "polish" ],
    [ "pray" ],
    [ "pull" ],
    [ "push" ],
    [ "remove" ],
    [ "rub" ],
    [ "say" ],
    [ "shield" ],
    [ "shine" ],
    [ "slide" ],
    [ "spare" ],
    [ "stand" ],
    [ "stick" ],
    [ "tell" ],
    [ "thank" ],
    [ "thanks" ],
    [ "tip" ],
    [ "touch" ],
    [ "unbar" ],
    [ "unlock" ],
    [ "undress" ],
    [ "wake" ],
    [ "wave" ],
    [ "cyr" ],
    [ "cyr-jones" ],
    [ "notify" ],
    [ "color" ],
    [ "map" ],
] # verbs

nouns = [
    [ "basilisk" ],
    [ "chasm", "cliff", "side" ],
    [ "branch", "branches", "tree" ],
    [ "apple", "food", "fruit" ],
    [ "handle", "slean" ],
    [ "peat" ],
    [ "door" ],
    [ "stilicho", "person", "cottager", "hand", "arm", "peasant", "arms", "man", "leg", "legs", "hands" ],
    [ "directions" ],
    [ "splint" ],
    [ "bed", "pallet" ],
    [ "crutch" ],
    [ "table", "kitchen table" ],
    [ "barrel" ],
    [ "water" ],
    [ "bar", "door", "kitchen door" ],
    [ "cloth", "tapestry" ],
    [ "table", "armoury table" ],
    [ "dagger", "knife" ],
    [ "castle", "fortress", "fort" ],
    [ "behind the door" ],
    [ "person", "smith", "prisoner", "blacksmith", "craftsman", "casso", "man" ],
    [ "rock", "building stone", "stone" ],
    [ "keyhole", "lock", "door", "cell door" ],
    [ "chain", "chains" ],
    [ "padlock", "lock", "keyhole" ],
    [ "dent", "helmet" ],
    [ "pants", "clothes", "clothing", "shirt" ],
    [ "person", "man", "guard", "soldier" ],
    [ "cell key", "key" ],
    [ "conkers", "conker" ],
    [ "trees", "chestnut trees", "branch", "branches", "tree" ],
    [ "tomb", "stone", "tombstone", "grave", "gravestone" ],
    [ "behind the gravestone" ],
    [ "door", "gate" ],
    [ "altar" ],
    [ "tunic", "shirt" ],
    [ "breeches", "trousers", "pants" ],
    [ "glass", "piece", "red piece of glass" ],
    [ "sw", "north", "west", "direction", "se", "nw", "ne", "east", "south" ],
    [ "girl", "woman", "person" ],
    [ "person", "nudd", "demon", "teeth" ],
    [ "gold key", "key" ],
    [ "left manacle", "manacle" ],
    [ "right manacle", "manacle" ],
    [ "manacles" ],
    [ "arms", "chair", "throne", "arm" ],
    [ "mountain" ],
    [ "dragon", "pearlfender" ],
    [ "body", "claw", "head", "nose", "mouth", "skin", "that part of the dragon's body", "foot", "legs", "leg", "feet", "eye", "eyes", "neck", "tail" ],
    [ "ghosts", "ghost", "apparition" ],
    [ "tentacle", "kraken", "squid", "octopus", "tentacles", "giant kraken" ],
    [ "lake", "water" ],
    [ "water", "river" ],
    [ "rock", "stone" ],
    [ "sword", "hilt", "runes", "shaft", "excalibur" ],
    [ "jewel", "jewels" ],
    [ "cheese", "food", "piece", "piece of cheese", "stilton" ],
    [ "enchanted trees", "tree", "trees", "branch", "branches" ],
    [ "woods", "enchanted forest", "forest" ],
    [ "that" ],
    [ "GO" ],
    [ "LG", "l.g" ],
    [ "room", "place", "here", "area" ],
    [ "it", "this" ],
    [ "them" ],
    [ "int.num", "number" ],
    [ "yourself", "you" ],
    [ "her" ],
    [ "him" ],
    [ "their body" ],
    [ "body" ],
    [ "mouth" ],
    [ "shell" ],
    [ "head" ],
    [ "legs", "leg" ],
    [ "feet", "foot", "toes", "toe" ],
    [ "hole" ],
    [ "hour" ],
    [ "bell", "bells" ],
    [ "name" ],
    [ "master" ],
    [ "magic" ],
    [ "Riothamus", "riothamus" ],
    [ "mom", "mother", "igraine", "ygraine" ],
    [ "Sherlock", "holmes", "sherlock" ],
    [ "steven", "meretzky", "Meretzky", "steve" ],
    [ "bates", "robert", "bob", "Bates" ],
    [ "Beck", "beck", "duane" ],
    [ "three", "iii", "two", "zork", "ii", "trilogy", "i", "Zork", "one" ],
    [ "trilogy", "sorcerer", "spellbreaker", "series", "enchanter", "Enchanter" ],
    [ "stationfall", "game", "planetfall" ],
    [ "Infocom", "infocom" ],
    [ "everything", "anything" ],
    [ "jousting", "joust" ],
    [ "chivalry" ],
    [ "britain", "england", "England" ],
    [ "uther", "Uther Pendragon", "pendragon" ],
    [ "gods" ],
    [ "christ", "God", "god", "jesus" ],
    [ "wall", "walls" ],
    [ "stairs", "staircase" ],
    [ "road", "path" ],
    [ "block of ice", "block", "words", "ice", "word" ],
    [ "idiot" ],
    [ "glitter", "object", "glittering object" ],
    [ "counter" ],
    [ "person", "man", "knight", "invisible knight" ],
    [ "red", "red lance", "lances", "lance" ],
    [ "green", "green lance", "lance" ],
    [ "horn" ],
    [ "horses", "horse", "blue knight's horse" ],
    [ "horse", "white horse" ],
    [ "person", "blue knight", "man", "knight" ],
    [ "pavilion", "door", "pavillion", "tent" ],
    [ "person", "man", "cook", "ruffian" ],
    [ "birdcage", "cage" ],
    [ "bird" ],
    [ "cabinet", "door", "cupboard" ],
    [ "spice", "spices", "cinnamon" ],
    [ "table" ],
    [ "present", "dropping", "bird dropping" ],
    [ "beautiful woman", "nimue", "person", "woman", "lady" ],
    [ "nose" ],
    [ "bier", "stone bier" ],
    [ "blossom", "sprig of hawthorn", "bud", "twig", "flower", "hawthorn", "hawthorne", "bloom", "sprig", "thorn" ],
    [ "window" ],
    [ "murmur", "sound", "murmuring", "murmurring", "stone", "voice", "rock" ],
    [ "behind the rock" ],
    [ "whisky jug", "whisky", "whiskey", "neck", "jug" ],
    [ "whiskey", "elixir", "whisky" ],
    [ "person", "Merlin", "merlin" ],
    [ "scroll" ],
    [ "symbols", "symbol" ],
    [ "bag" ],
    [ "crystal ball", "ball", "crystal" ],
    [ "pedestal" ],
    [ "peter", "torque" ],
    [ "knob", "sliver of crystal", "knobs", "sliver", "crystal" ],
    [ "key", "silver key" ],
    [ "table", "grail", "mordred", "future", "that", "camelot", "guinevere", "launcelot" ],
    [ "hill" ],
    [ "owl", "person", "salamander", "yourself", "myself", "eel", "boy", "human", "arthur", "turtle", "badger", "me", "self" ],
    [ "axe", "pollaxe" ],
    [ "there", "lot", "words", "word", "password", "fair", "begot", "passwords" ],
    [ "door", "gate", "castle gate" ],
    [ "throne", "chair" ],
    [ "King Lot", "person", "man", "king", "lot" ],
    [ "sword" ],
    [ "tapestry" ],
    [ "egg", "gold egg" ],
    [ "raven", "giant raven", "bird" ],
    [ "person", "armour", "man", "knight", "armor", "red knight" ],
    [ "black knight", "man", "knight", "person" ],
    [ "armour", "black armour", "armor" ],
    [ "medallion", "medal" ],
    [ "fire" ],
    [ "roof", "hole", "thatch" ],
    [ "men", "farmers", "people", "conversation", "farmer" ],
    [ "mug", "tankards", "tankard", "mugs" ],
    [ "beer", "ale", "drink" ],
    [ "person", "man", "old man", "thomas", "rhymer" ],
    [ "chair" ],
    [ "rhyme", "rhymes", "verse", "poetry" ],
    [ "door", "wooden door" ],
    [ "stone", "crack", "stones", "hole" ],
    [ "key", "ivory key" ],
    [ "ivory tower", "tower" ],
    [ "gate", "town gate" ],
    [ "oak", "roots", "tree", "branch", "branches" ],
    [ "stone", "hearth", "slab" ],
    [ "town" ],
    [ "animal", "boar" ],
    [ "fire", "coal", "hearth", "ashes", "coals", "ash" ],
    [ "place", "fire", "flames", "fireplace" ],
    [ "hole", "boat", "rowboat" ],
    [ "food", "mouse" ],
    [ "food", "weeds", "weed" ],
    [ "fish", "morsel", "minnow", "food", "tasty-looking" ],
    [ "bugs", "midges", "midge", "bug", "food" ],
    [ "claw", "talon", "claws", "hand", "hands", "talons" ],
    [ "ground", "dirt", "floor" ],
    [ "ceiling", "sky" ],
    [ "leprechaun", "person", "sprite", "man" ],
    [ "person", "soldier", "man", "men", "guards", "people", "guard", "soldiers" ],
    [ "courtier", "courtiers", "people", "crowd", "mob" ],
] # nouns

rooms = [
    "giant raven's nest",
    "above moor",
    "foot of mountain",
    "outside town gate",
    "outside Merlin's cave",
    "moor",
    "hot room",
    "end of causeway",
    "above merlin's cave",
    "river",
    "shallows",
    "edge of woods",
    "underground chamber",
    "track",
    "stairs",
    "above the town",
    "enchanted forest",
    "above bog",
    "crystal cave",
    "parade area",
    "above the lake",
    "meadow",
    "huge tree",
    "east of ford",
    "above the field",
    "above the ford",
    "end of hall",
    "bottom of stairs",
    "tavern kitchen",
    "above the castle",
    "trail",
    "grove",
    "above the meadow",
    "outside castle gate",
    "great hall",
    "field of honour",
    "ice room",
    "lake",
    "village green",
    "behind the throne",
    "road",
    "den",
    "dark passage",
    "path",
    "peat bog",
    "above edge of the woods",
    "ford",
    "basilisk's lair",
] # rooms

