# Config for BALLYHOO, in LLM style
#
#

[game]
path = "./infocom/ballyhoo/COMPILED/m4.z3"

setup = '''
ballyhoo is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "to", "toward" ],
    [ "with", "using" ],
    [ "through", "thru" ],
    [ "onto", "across", "on" ],
    [ "outside", "out" ],
    [ "inside", "in", "into" ],
    [ "beneath", "underneath", "under", "below" ],
    [ "around", "along" ],
    [ "both", "all" ],
    [ "north", "n" ],
    [ "s", "south" ],
    [ "east", "e" ],
    [ "west", "w" ],
    [ "down", "d" ],
    [ "u", "up" ],
    [ "northwest", "nw" ],
    [ "ne", "northe" ],
    [ "sw", "southwest" ],
    [ "southe", "se" ],
    [ "super", "superbrief" ],
    [ "q", "quit" ],
    [ "reply", "answer" ],
    [ "applaud", "cheer" ],
    [ "query", "ask", "consul" ],
    [ "strike", "murder", "assault", "slap", "kill", "attack", "fight", "hit" ],
    [ "bet", "wager" ],
    [ "embark", "board" ],
    [ "suck", "inhale", "breathe" ],
    [ "buy", "order", "purchase" ],
    [ "capture", "catch" ],
    [ "climb", "crawl", "scale", "creep" ],
    [ "unset", "close", "shut" ],
    [ "match", "compar" ],
    [ "perfor", "cut", "slice" ],
    [ "break", "smash", "pop", "demoli", "destro", "damage", "wreck", "peel" ],
    [ "disembark", "debark" ],
    [ "doze", "sleep", "nap", "snooze" ],
    [ "swill", "drink", "quaff", "sip", "guzzle", "imbibe", "swallow" ],
    [ "eat", "devour", "gobble", "ingest" ],
    [ "withdr", "exit", "depart" ],
    [ "observe", "scour", "watch", "describe", "examine", "see", "inspect", "study" ],
    [ "seek", "find" ],
    [ "chase", "pursue", "follow" ],
    [ "donate", "give", "hand", "send", "offer", "sell" ],
    [ "howdy", "hi", "hello" ],
    [ "hints", "help", "hint" ],
    [ "crouch", "hide", "duck" ],
    [ "mesmer", "hypnot" ],
    [ "jump", "bounce", "dive", "fall", "leap" ],
    [ "knock", "rap" ],
    [ "reclin", "lie" ],
    [ "l", "gaze", "look", "squint", "stare" ],
    [ "move" ],
    [ "nope", "wrong", "no" ],
    [ "pry", "draw", "open", "part" ],
    [ "pay", "pass" ],
    [ "phone", "teleph", "dial" ],
    [ "jimmy", "pick" ],
    [ "sprinkle", "pour", "spill" ],
    [ "shove", "press", "pull", "push" ],
    [ "put", "insert", "place", "lay", "hang", "stuff" ],
    [ "boost", "lift", "raise" ],
    [ "read", "skim" ],
    [ "shed", "doff", "remove" ],
    [ "talk", "speak" ],
    [ "frisk", "search", "rummag" ],
    [ "rest", "squat", "sit" ],
    [ "hop", "skip" ],
    [ "whiff", "smell", "sniff" ],
    [ "whirl", "spin" ],
    [ "rise", "stand" ],
    [ "start", "activa" ],
    [ "hold", "get", "grab", "carry", "take" ],
    [ "lick", "taste" ],
    [ "thank", "thanks" ],
    [ "throw", "hurl", "toss" ],
    [ "tie", "secure", "fasten", "attach" ],
    [ "feel", "tap", "pat", "tickle", "pet", "poke", "touch", "rub" ],
    [ "turn", "set" ],
    [ "adjust", "tune" ],
    [ "untie", "unfast", "unatta", "unknot", "untangle", "free" ],
    [ "polevault", "vault" ],
    [ "wait", "z", "stay" ],
    [ "wake", "awake", "rouse" ],
    [ "step", "run", "walk", "procee" ],
    [ "clean", "wash", "tidy" ],
    [ "wear", "don" ],
    [ "whats", "what" ],
    [ "where", "wheres" ],
    [ "crack", "whip", "snap" ],
    [ "who", "whos" ],
    [ "yell", "howl", "shout", "scream" ],
    [ "yes", "yea", "okay", "sure", "y", "ok" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "invent" ],
    [ "i" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "addres" ],
    [ "advance" ],
    [ "approa" ],
    [ "arrest" ],
    [ "balance" ],
    [ "bite" ],
    [ "bribe" ],
    [ "call" ],
    [ "cheat" ],
    [ "clap" ],
    [ "cover" ],
    [ "count" ],
    [ "cross" ],
    [ "descen" ],
    [ "did" ],
    [ "dig" ],
    [ "drive" ],
    [ "drop" ],
    [ "eject" ],
    [ "enter" ],
    [ "extinguish" ],
    [ "feed" ],
    [ "fill" ],
    [ "hear" ],
    [ "kick" ],
    [ "kiss" ],
    [ "lean" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "play" ],
    [ "punch" ],
    [ "empty" ],
    [ "reach" ],
    [ "record" ],
    [ "rewind" ],
    [ "shake" ],
    [ "show" ],
    [ "sidewa" ],
    [ "slide" ],
    [ "smile" ],
    [ "stop" ],
    [ "tame" ],
    [ "tell" ],
    [ "unlock" ],
    [ "go" ],
    [ "let" ],
    [ "wave" ],
    [ "why" ],
    [ "you" ],
] # verbs

nouns = [
    [ "act", "feat", "show", "circus" ],
    [ "trash", "garbage" ],
    [ "seats", "stand", "stands", "seat", "grandstand" ],
    [ "refreshment", "candy", "food", "nuts", "coke" ],
    [ "hawker", "man", "conces" ],
    [ "crowd", "people" ],
    [ "tent", "big top", "top", "wall", "bigtop" ],
    [ "sawdust", "pole", "center pole" ],
    [ "ring" ],
    [ "pole", "fiberglass pole" ],
    [ "balloon" ],
    [ "helium" ],
    [ "net", "safety net" ],
    [ "stool" ],
    [ "rope", "high-", "tightr", "wire", "tightrope" ],
    [ "wires", "apparatus", "wire" ],
    [ "platform" ],
    [ "bar", "den", "lions' den", "bars", "cage" ],
    [ "stand", "lion stand", "pedestal" ],
    [ "lion", "shaggy lion", "cat", "mane", "animal" ],
    [ "smooth-bodied lion", "lion", "cat", "animal" ],
    [ "lion", "elsie", "nimrod", "lions", "cats" ],
    [ "meat", "lump", "corpuscular lump of meat", "food" ],
    [ "pail", "bucket" ],
    [ "water" ],
    [ "bullwhip", "rawhide bullwhip", "whip" ],
    [ "gate", "lock", "door", "cage door" ],
    [ "stomach", "back", "your back", "shoulder" ],
    [ "direction" ],
    [ "intnum", "number" ],
    [ "money", "cash" ],
    [ "dollar", "buck", "bucks", "bill" ],
    [ "pseudo" ],
    [ "him", "her", "them", "it" ],
    [ "it" ],
    [ "spotlight", "lamp", "light", "lights" ],
    [ "darkness", "dark" ],
    [ "field", "floor", "ground" ],
    [ "wall", "walls" ],
    [ "home" ],
    [ "ceiling", "ceilin", "roof" ],
    [ "corner" ],
    [ "egress" ],
    [ "ladder" ],
    [ "air" ],
    [ "palm", "hands", "hand", "your hand" ],
    [ "monkey", "mugsy", "animal" ],
    [ "head", "bumps", "bump", "skull", "your head" ],
    [ "protag", "it" ],
    [ "himself or herself", "herself", "himself", "yourself", "you" ],
    [ "sucker", "me", "myself", "yourself", "i" ],
    [ "room", "arena", "place" ],
    [ "voice", "conver", "voices", "conversation" ],
    [ "voice" ],
    [ "growl", "roar" ],
    [ "banner", "sagging banner" ],
    [ "sucker", "front", "long line", "line", "people" ],
    [ "sucker", "front", "line", "people", "short line" ],
    [ "one-dollar-and-85-cent granola bar", "food", "bar", "granola", "bars" ],
    [ "chocolate", "two-dollar-and-25-cent frozen banana", "banana", "food", "fruit" ],
    [ "pitcher", "jerry", "man", "Jerry" ],
    [ "ballplayers", "fielder", "group of ballplayers", "baseman", "group" ],
    [ "bloomer", "concession stand", "stand" ],
    [ "conces", "concessionaire" ],
    [ "fountain", "drinking fountain" ],
    [ "button" ],
    [ "water", "drink" ],
    [ "barred passage", "chute", "passage", "bar", "bars" ],
    [ "passage", "rusty grate", "grate", "chute" ],
    [ "logo", "wagon", "trailer", "white wagon" ],
    [ "crank" ],
    [ "panel", "opening", "square aluminum panel" ],
    [ "sheet", "printout", "spreadsheet" ],
    [ "phone", "teleph", "telephone" ],
    [ "police", "cops", "station" ],
    [ "hole", "chain link fence", "fence" ],
    [ "Eddie Smaldone", "eddie", "smaldo", "man" ],
    [ "office door", "lock", "door" ],
    [ "office" ],
    [ "desk", "cherry-hardwood desk", "drawer" ],
    [ "chair" ],
    [ "desk" ],
    [ "sheepskin", "diploma" ],
    [ "biographies", "shelf", "shelf of books", "books", "book" ],
    [ "cage", "booth", "burned cage" ],
    [ "silhoette", "man", "guard", "harry" ],
    [ "pair of sunglasses", "glasses", "sunglasses", "shades", "pair" ],
    [ "turnstile", "stile" ],
    [ "turnstile", "skeleton" ],
    [ "slot", "hole", "narrow slot" ],
    [ "cheese morsel", "morsel", "cheese", "food" ],
    [ "rodent", "dead mouse", "mouse" ],
    [ "mask", "clown mask" ],
    [ "suit", "heap", "gorilla suit" ],
    [ "car", "seat", "auto", "automobile", "midget car" ],
    [ "switch", "ignition switch" ],
    [ "taft", "character", "figure of President Taft", "prop", "figure" ],
    [ "man", "munrab", "owner", "Mr. Munrab" ],
    [ "gaggle", "company", "group", "circle" ],
    [ "drunk", "dick", "detective", "man" ],
    [ "trench", "coat", "rumpled trenchcoat" ],
    [ "picture", "card", "trade card" ],
    [ "ransom note", "note" ],
    [ "wall", "canvas wall", "pleats", "pleat" ],
    [ "Gottfried Wilhelm von Katzenjammer", "katz", "tamer", "trainer", "katzen" ],
    [ "head", "trophy", "antler", "moose head" ],
    [ "hole", "crawl space", "opening", "space" ],
    [ "window" ],
    [ "curtain", "curtains", "decoration" ],
    [ "wagon", "siding", "trailer" ],
    [ "sign" ],
    [ "camp" ],
    [ "trailer door", "lock", "door" ],
    [ "bar", "crowbar", "tool" ],
    [ "chelsea", "girl", "Chelsea" ],
    [ "whimper" ],
    [ "compartment", "compar" ],
    [ "general", "midget", "thumb", "man", "Comrade Thumb" ],
    [ "uniform" ],
    [ "flower", "daisy" ],
    [ "joey", "clown", "Chuckles", "man", "chuckles" ],
    [ "wagon", "trailer", "alley" ],
    [ "tray", "ash tray", "ashtray" ],
    [ "heap of black ash", "ashes", "heap", "ash" ],
    [ "scrap of newsprint", "newsprint", "m", "print", "scrap" ],
    [ "costum", "costume" ],
    [ "mirror" ],
    [ "bunks", "bunk", "upper bunk", "bed" ],
    [ "bunks", "bunk", "bed", "lower bunk" ],
    [ "beast", "ape", "Mahler", "mahler", "gorilla" ],
    [ "door", "outline", "trap door", "trap" ],
    [ "ribbon" ],
    [ "bar", "bars", "cage" ],
    [ "closet" ],
    [ "suit", "pocket", "dress-suit combination", "combination", "dress" ],
    [ "veil" ],
    [ "shawl-jacket combo", "shawl", "jacket", "combo" ],
    [ "shaft", "prod", "elephant prod", "stunner" ],
    [ "holes", "hole", "burn hole" ],
    [ "canvas", "entrance", "tent" ],
    [ "trunk", "elephant", "hannibal", "bull" ],
    [ "menagerie", "chain", "chains", "massive chain" ],
    [ "path", "passage" ],
    [ "layer", "straw", "bed" ],
    [ "sawdust" ],
    [ "skeleton key", "key", "ring", "keys" ],
    [ "roustabout", "man" ],
    [ "roustabout" ],
    [ "Malcom", "malcom" ],
    [ "brother", "Genatossio" ],
    [ "Gloria", "gloria" ],
    [ "Sgt. Duffy", "duffy" ],
    [ "headphones", "player", "pair", "pair of headphones", "counter" ],
    [ "music" ],
    [ "parlor" ],
    [ "light", "chandelier" ],
    [ "oakley", "ducket", "ticket", "your ticket", "ducat" ],
    [ "blue dot", "dot" ],
    [ "dot", "pink dot" ],
    [ "Rimshaw the Incomparable", "man" ],
    [ "sofa", "leather sofa", "couch" ],
    [ "tux", "tuxedo" ],
    [ "future", "fortune" ],
    [ "midway" ],
    [ "menagerie" ],
    [ "front", "entrance", "sideshow front", "fronts", "placard" ],
    [ "panel", "secret panel", "opening", "door" ],
    [ "tina", "woman", "fat lady", "lady" ],
    [ "fat lady's hand", "hand" ],
    [ "transistor radio", "radio" ],
    [ "wpdl", "WPDL" ],
    [ "radio dial", "dial" ],
    [ "stairw", "stairs", "stair", "spiral staircase", "staircase" ],
    [ "hermaphrodite", "Andrew Jenny", "attraction", "pair", "jenny" ],
    [ "Andrew", "man", "andrew", "andy" ],
    [ "outfit", "boot", "helmet", "Andrew's outfit", "holster" ],
    [ "Jenny", "jennif", "woman", "jenny" ],
    [ "arangement", "boa", "Jenny's apparel", "apparel", "dress" ],
    [ "cigarette case", "case" ],
    [ "Billy Monday", "billy", "monday", "pitchman", "bill" ],
    [ "cloud of smoke", "cloud", "smoke" ],
    [ "dealer", "man" ],
    [ "blackjack table", "tablecloth", "table", "cloth" ],
    [ "deck", "blackjack", "cards", "game", "deck of cards" ],
    [ "table", "poker", "poker game", "game" ],
    [ "suitcase", "trunk", "keister", "case" ],
    [ "jumble of trinkets", "jumble", "trinket" ],
    [ "rag", "dirty rag" ],
    [ "zzmgck" ],
    [ "piece", "wood", "mousetrap", "trap" ],
    [ "rodent", "mouse" ],
    [ "flask", "extract", "nostrum" ],
] # nouns

rooms = [
    "In the Wings",
    "Menagerie",
    "Inside Cage",
    "Under the Bleachers",
    "Walking a Tightrope",
    "East Half of Fat Lady",
    "Inside Prop Tent",
    "Inside Trailer",
    "Camp, West",
    "Lions' Den",
    "Near White Wagon",
    "West Half of Fat Lady",
    "Platform",
    "Back Yard",
    "Beside the Big Top",
    "Far End of Midway",
    "Office",
    "Midway of Midway",
    "Camp, East",
    "Menagerie Nook",
    "Performance Ring",
    "Inside Mahler's Cage",
    "Wardrobe Closet",
    "Left Hanging",
    "Clown Alley",
    "Top of Cage",
    "On the Wagon",
    "Jennifer's Boudoir",
    "Standing Room Only",
    "Midway Entrance",
    "Elephant Tent",
    "Hypnotist's Parlor",
    "On the Tent",
    "Blue Room",
] # rooms

