# Config for BORDERZONE, in LLM style
#
#

[game]
path = "./infocom/borderzone/COMPILED/spy.z5"

setup = '''
borderzone is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "both", "all", "everything" ],
    [ "north", "n" ],
    [ "south", "s" ],
    [ "east", "e" ],
    [ "w", "west" ],
    [ "down", "d" ],
    [ "up", "u" ],
    [ "nw", "northwest" ],
    [ "ne", "northeast" ],
    [ "sw", "southwest" ],
    [ "se", "southeast" ],
    [ "i", "inventory" ],
    [ "quit", "q" ],
    [ "answer", "reply" ],
    [ "stab", "assault", "murder", "kill" ],
    [ "hit", "slap", "attack", "strike", "punch" ],
    [ "order", "buy", "purchase" ],
    [ "creep", "climb", "crawl", "scale" ],
    [ "shut", "close" ],
    [ "break", "damage", "wreck", "pop", "destroy", "demolish", "smash" ],
    [ "sip", "drink", "swallow" ],
    [ "drop", "dump" ],
    [ "taste", "eat" ],
    [ "depart", "exit" ],
    [ "x", "inspect", "see", "study", "describe", "examine", "scour" ],
    [ "find", "seek" ],
    [ "pursue", "chase", "follow" ],
    [ "offer", "hand", "give", "send", "pass" ],
    [ "hi", "hello" ],
    [ "hide", "crouch" ],
    [ "dive", "leap", "jump" ],
    [ "knock", "rap" ],
    [ "tip", "upset", "topple" ],
    [ "recline", "lie" ],
    [ "smoke", "light" ],
    [ "stare", "look", "l" ],
    [ "spread", "widen", "stretch" ],
    [ "draw", "part", "open" ],
    [ "shine", "point" ],
    [ "pour", "spill" ],
    [ "trip", "press", "push" ],
    [ "lay", "insert", "place", "put", "replace", "stuff", "stick", "plug" ],
    [ "raise", "lift" ],
    [ "skim", "read" ],
    [ "shed", "unwrap", "remove" ],
    [ "tear", "shred", "rip" ],
    [ "rummage", "search", "frisk" ],
    [ "shoot", "fire" ],
    [ "squat", "rest", "sit" ],
    [ "hop", "skip" ],
    [ "nap", "doze", "sleep" ],
    [ "slice", "cut", "chop" ],
    [ "smell", "sniff" ],
    [ "whirl", "spin" ],
    [ "stand", "rise" ],
    [ "start", "activate" ],
    [ "stop", "deactivate" ],
    [ "zero", "reset" ],
    [ "grab", "take", "get", "catch" ],
    [ "talk", "speak" ],
    [ "tell", "warn" ],
    [ "thank", "thanks" ],
    [ "throw", "hurl", "toss" ],
    [ "tie", "secure", "attach", "connect", "fasten" ],
    [ "feel", "touch", "poke" ],
    [ "toggle", "flick", "set", "flip", "turn", "switch" ],
    [ "unattach", "free", "unfasten", "untie" ],
    [ "wait", "z" ],
    [ "awake", "wake", "rouse" ],
    [ "proceed", "walk", "run" ],
    [ "wash", "brush", "tidy", "clean", "wipe" ],
    [ "wear", "don" ],
    [ "what", "whats" ],
    [ "wheres", "where" ],
    [ "whos", "who" ],
    [ "shout", "yell", "scream" ],
    [ "lubricate", "oil" ],
    [ "ok", "y", "okay", "yes" ],
    [ "watch", "observe" ],
    [ "clue", "hint", "hints" ],
    [ "unwind", "rewind", "wind", "unroll" ],
    [ "crumple", "fold" ],
    [ "uncrumple", "unfold" ],
    [ "wet", "soak" ],
    [ "stack", "pile" ],
    [ "verbose" ],
    [ "brief" ],
    [ "superbrief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "address" ],
    [ "advance" ],
    [ "approach" ],
    [ "arrest" ],
    [ "ask" ],
    [ "strangle" ],
    [ "bend" ],
    [ "bite" ],
    [ "blow" ],
    [ "call" ],
    [ "cover" ],
    [ "count" ],
    [ "descend" ],
    [ "dig" ],
    [ "empty" ],
    [ "enter" ],
    [ "extinguish" ],
    [ "feed" ],
    [ "fill" ],
    [ "flush" ],
    [ "go" ],
    [ "hear" ],
    [ "help" ],
    [ "hold" ],
    [ "inflate" ],
    [ "kick" ],
    [ "kiss" ],
    [ "leave" ],
    [ "let" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "move" ],
    [ "pull" ],
    [ "no" ],
    [ "pay" ],
    [ "pick" ],
    [ "play" ],
    [ "reach" ],
    [ "say" ],
    [ "score" ],
    [ "shake" ],
    [ "show" ],
    [ "sign" ],
    [ "slide" ],
    [ "smile" ],
    [ "tap" ],
    [ "unlock" ],
    [ "use" ],
    [ "cross" ],
    [ "wave" ],
    [ "why" ],
    [ "wrap" ],
    [ "slow" ],
    [ "fast" ],
    [ "load" ],
    [ "photograph" ],
    [ "surrender" ],
    [ "bribe" ],
    [ "pause" ],
] # verbs

nouns = [
    [ "Gurthark Mark VI revolver", "gurthark", "revolver", "pistol", "gun" ],
    [ "watch", "wristwatch", "clock" ],
    [ "match", "matchbook", "book", "matches" ],
    [ "cigarette" ],
    [ "building", "store", "shop", "bookstore", "storefront" ],
    [ "sign" ],
    [ "tourist", "crowd", "masses", "tourists", "people", "spectators", "crowd of people" ],
    [ "antique", "antiques", "curio", "curios" ],
    [ "rare book", "folio", "books", "manuscript", "book", "folios" ],
    [ "door", "side door" ],
    [ "door", "counter door" ],
    [ "conversation" ],
    [ "police", "policeman" ],
    [ "cordon", "barricade" ],
    [ "door", "metal door" ],
    [ "riznik", "agent", "spy", "man", "contact", "proprietor" ],
    [ "counter" ],
    [ "customer", "man" ],
    [ "buildings", "windows", "building" ],
    [ "window" ],
    [ "buildings", "windows", "building", "apartment", "window" ],
    [ "column", "tall column" ],
    [ "podium", "dais" ],
    [ "Huttinger", "ambassador", "huttinger" ],
    [ "mayor" ],
    [ "dignitaries", "dignitary" ],
    [ "police", "guards", "policeman", "guard" ],
    [ "listing", "directory", "list" ],
    [ "elevator", "lift" ],
    [ "operator", "woman", "older woman" ],
    [ "waitress", "waiter" ],
    [ "eats", "lunch", "food", "meal" ],
    [ "chair", "seat", "table" ],
    [ "card", "business card" ],
    [ "pants", "clothing", "cloth", "shirt", "clothes", "socks", "coat", "your clothes" ],
    [ "peddler", "salesman", "man", "vendor" ],
    [ "can", "soda", "can of soda" ],
    [ "cans", "drink", "can", "soda", "bunch of soda cans", "bunch" ],
    [ "bunch of pretzels", "pretzels", "pretzel", "food", "bunch" ],
    [ "pretzel" ],
    [ "hot dog", "hot-dog", "food", "dog", "hotdog" ],
    [ "vendor's cart", "stand", "cart" ],
    [ "can", "trash can" ],
    [ "boxes", "box" ],
    [ "alley" ],
    [ "ladder", "fire-escape", "escape", "rung", "rungs" ],
    [ "door", "elevator door" ],
    [ "button", "call button" ],
    [ "door", "eastern door" ],
    [ "door", "western door" ],
    [ "iranian", "sniper", "man", "assassin" ],
    [ "corpse", "iranian", "sniper", "sniper's corpse" ],
    [ "rifle", "high-powered rifle" ],
    [ "agent", "Topaz", "topaz" ],
    [ "agent", "Topaz", "topaz", "man" ],
    [ "remington", "Remington", "revolver", "pistol", "gun" ],
    [ "men from the car", "guards", "men" ],
    [ "guard" ],
    [ "scout", "guard" ],
    [ "guards", "guard" ],
    [ "break", "hole", "slit", "cut" ],
    [ "machine gun", "machine-gun", "guns", "gun" ],
    [ "machine gun", "machine-gun", "gun" ],
    [ "post", "posts" ],
    [ "door" ],
    [ "guard's leg", "leg", "guard" ],
    [ "crumpled body", "machine-gun", "heap", "body", "gun" ],
    [ "brace" ],
    [ "pair", "binoculars", "glasses", "pair of binoculars", "binocs" ],
    [ "pen", "explosive" ],
    [ "automobile", "car", "burning car" ],
    [ "cap", "cover" ],
    [ "timer button", "button" ],
    [ "ladder" ],
    [ "posts" ],
    [ "post", "northwest post" ],
    [ "northeast post", "post" ],
    [ "southwest post", "post" ],
    [ "post", "southeast post" ],
    [ "border fence", "fence", "links", "link" ],
    [ "towers", "tower" ],
    [ "fence", "link", "first fence", "links", "chain-link" ],
    [ "warning sign", "notices", "notice", "sign", "signs" ],
    [ "pair", "pair of rubber gloves", "gloves" ],
    [ "field", "open field", "land" ],
    [ "tracks" ],
    [ "road", "roadway", "pavement" ],
    [ "shed door", "door" ],
    [ "wood", "pile of wood", "pile", "log", "logs" ],
    [ "gloves" ],
    [ "hammer" ],
    [ "saw", "wood-saw" ],
    [ "bolt cutters", "cutters", "bolt-cutter", "cutter" ],
    [ "tools", "tool", "assorted tools" ],
    [ "handle", "tools", "hammer", "tool" ],
    [ "tools", "saw", "wood saw", "tool" ],
    [ "tools", "cutters", "cutter", "tool", "bolt-cutter" ],
    [ "window", "shed window" ],
    [ "shed", "building", "hut", "woodshed" ],
    [ "building", "hut", "house", "home" ],
    [ "chimney" ],
    [ "door", "hinges", "back door", "hinge" ],
    [ "man" ],
    [ "door", "front door" ],
    [ "wood", "pile", "wood pile" ],
    [ "owner", "man", "hut owner" ],
    [ "diagram", "map" ],
    [ "couch", "table", "bulb", "living room item", "woodstove", "chair", "chairs", "lightbulb", "stove" ],
    [ "pair", "shoes", "pair of everyday black shoes" ],
    [ "overcoat", "white down parka", "parka", "coat" ],
    [ "can", "oil", "can of household oil" ],
    [ "pair", "workshoes", "pair of work shoes", "shoes" ],
    [ "pair", "boots", "knee-boots", "pair of knee-boots" ],
    [ "pack", "knapsack", "sack" ],
    [ "clothes", "clothing", "jumbled clothing" ],
    [ "bed", "furniture", "chair" ],
    [ "block", "roadblock" ],
    [ "train", "choo-choo" ],
    [ "forest" ],
    [ "hut" ],
    [ "tunnel" ],
    [ "snow", "ice" ],
    [ "trees", "tree" ],
    [ "border" ],
    [ "fence" ],
    [ "women", "crowd", "men", "people", "throng", "children", "crowd of people" ],
    [ "contact" ],
    [ "compartment" ],
    [ "handle", "rope", "emergency stop cord", "cord" ],
    [ "luggage rack", "rack" ],
    [ "seat", "bench", "rear-facing seat" ],
    [ "space under the rear bench" ],
    [ "front-facing seat", "seat", "bench" ],
    [ "compartment door", "door" ],
    [ "lavatory door", "door" ],
    [ "handle", "bowl", "toilet" ],
    [ "lavatory", "bathroom", "wc" ],
    [ "briefcase", "case" ],
    [ "camera bag", "bag" ],
    [ "camera" ],
    [ "roll", "film", "old roll of film" ],
    [ "film" ],
    [ "kit", "toilet kit" ],
    [ "brush", "toothbrush" ],
    [ "your teeth", "teeth" ],
    [ "pair of tweezers", "tweezers", "pair" ],
    [ "picture", "photo", "photograph" ],
    [ "pants", "clothing", "cloth", "shirt", "clothes", "suit", "socks", "your clothes" ],
    [ "flower", "carnation", "rumpled white carnation" ],
    [ "man in a trench coat", "man", "viper", "spy" ],
    [ "stain", "blood stain", "blood" ],
    [ "writing", "graffiti", "words", "grafitti" ],
    [ "dispenser", "towel dispenser", "machine" ],
    [ "towel", "paper towel" ],
    [ "towel", "blood-stained paper towel" ],
    [ "towel", "wet paper towel" ],
    [ "sink" ],
    [ "water" ],
    [ "faucet" ],
    [ "paper", "document", "drawing" ],
    [ "shred of the document", "document", "shred" ],
    [ "handful of shreds", "handful", "pile", "shreds", "pieces", "shred" ],
    [ "mirror" ],
    [ "guns", "gun" ],
    [ "guide", "book", "tourist guide and phrase book" ],
    [ "passport" ],
    [ "ticket", "train ticket" ],
    [ "train" ],
    [ "zzmgck", "mr", "GloObj", "front" ],
    [ "Rms" ],
    [ "intnum", "number" ],
    [ "them", "it" ],
    [ "himself", "him" ],
    [ "herself", "her" ],
    [ "it" ],
    [ "floor", "ground" ],
    [ "wall", "walls" ],
    [ "roof", "ceiling" ],
    [ "hand", "palm", "hands", "fingers" ],
    [ "eye", "your eyes", "eyes" ],
    [ "it", "protag" ],
    [ "yourself", "me", "self", "myself" ],
    [ "location", "room", "area", "place" ],
    [ "way" ],
    [ "sky" ],
    [ "tourniquet" ],
    [ "scrap", "piece of ripped fabric", "tourniquet", "rag", "piece", "fabric" ],
    [ "foot", "leg", "nose", "body part", "eye", "head" ],
    [ "arm", "your left arm" ],
    [ "arm", "your left arm", "wound", "blood" ],
    [ "arm", "your right arm" ],
    [ "pants", "clothing", "socks", "clothes", "shirt", "your everyday clothes" ],
    [ "watching" ],
    [ "timer", "clock", "watch", "stopwatch", "chronometer", "timing", "chronograph", "time" ],
    [ "searchlight", "lights", "light" ],
    [ "pack", "pack of dogs", "dogs" ],
    [ "automobile", "door", "auto", "car" ],
    [ "window", "car window" ],
    [ "trunk", "car part", "hood" ],
    [ "automobile", "auto", "car" ],
    [ "marsh", "swamp" ],
    [ "lights", "searchlight", "searchlights", "light" ],
] # nouns

rooms = [
    "Side Entrance",
    "Border",
    "Platform, North End",
    "Behind the Cart",
    "Outside Shed",
    "Tower Entrance",
    "Railroad Tracks",
    "Outside Hut",
    "Road Spur",
    "Chemist's Shop",
    "Fire Escape, 3rd Floor",
    "automobile",
    "Outside 1st Compartment",
    "Topaz Start Point",
    "Hallway, North End",
    "Lavatory",
    "Hallway, South",
    "End of Blind Alley",
    "Mouth of Tunnel",
    "Behind Apartments",
    "Inside Fence",
    "Ostnitz Square, SW",
    "Outside Your Compartment",
    "Hallway, Fire Escape",
    "Hallway, Middle",
    "Border Zone, Tracks",
    "On the Roadway",
    "Outside 4th Compartment",
    "Sniper's Room",
    "Clearing",
    "Your Compartment",
    "Fire Escape, 5th Floor",
    "Compartment",
    "North Side of Hut",
    "Tower, South Side",
    "Apartment Building",
    "Ostnitz Square",
    "Antique Shop",
    "Inside Shed",
    "Fire Escape, 2nd Floor",
    "Antique Shop, Counter",
    "Outside Lavatory",
    "Sidewalk Cafe",
    "Tailor's Shop",
    "Street Vendor",
    "Fire Escape, 1st Floor",
    "South Side of Hut",
    "Storage Area",
    "In the Elevator",
    "Near Empty Lot",
    "Living Room",
    "Bedroom",
    "End of the Road",
    "Behind Offices",
    "Edge of Swamp",
    "Fire Escape, 4th Floor",
    "Bookstore",
    "Train Platform",
    "Street Corner",
    "Outside Antique Shop",
    "Outside 2nd Compartment",
    "Platform, South End",
    "Outside 3rd Compartment",
    "Empty Storefront",
    "Storage Room",
    "Inside the Forest",
    "Apartment Lobby",
    "Border Zone, Station",
    "Hardware Store",
    "Behind Hut",
    "Center Tower",
    "Ostnitz Square, NW",
] # rooms

