# Config for BUREAUCRACY, in LLM style
#
#

[game]
path = "./infocom/bureaucracy/COMPILED/bureaucracy.z3"

setup = '''
bureaucracy is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "n", "north" ],
    [ "south", "s" ],
    [ "e", "east" ],
    [ "west", "w" ],
    [ "u", "up" ],
    [ "northwest", "southeast", "northeast", "se", "southwest", "sw", "nw", "ne" ],
    [ "superbrief", "super" ],
    [ "i", "inventory" ],
    [ "quit", "q" ],
    [ "t", "time" ],
    [ "respond", "reply" ],
    [ "deny", "denied" ],
    [ "granted", "grant" ],
    [ "exchange", "trade" ],
    [ "interrogate", "query", "quiz", "question" ],
    [ "fight", "hurt", "attack", "injure", "assault" ],
    [ "withdraw", "buy" ],
    [ "wipe", "dry", "clean", "sweep" ],
    [ "slam", "close", "shut" ],
    [ "count", "tally" ],
    [ "cross", "traverse" ],
    [ "sever", "lacerate", "split", "saw", "cleave", "chop", "slice", "slash", "gash", "cut" ],
    [ "tear", "rip" ],
    [ "wreck", "smash", "crumble", "trash", "crack", "demolish", "destroy", "damage", "break" ],
    [ "excavate", "dig" ],
    [ "quaff", "sip", "imbibe", "swill", "guzzle", "drink" ],
    [ "drop", "deposit", "dump" ],
    [ "consume", "swallow", "nibble", "devour", "gobble", "eat", "ingest" ],
    [ "depart", "scram", "exit" ],
    [ "x", "inspect", "describe", "examine" ],
    [ "observe", "watch" ],
    [ "snuff", "quench", "extinguish", "douse" ],
    [ "find", "seek", "discover" ],
    [ "wrap", "roll", "fold" ],
    [ "extend", "unroll", "unflatten", "unfold" ],
    [ "follow", "pursue", "chase" ],
    [ "hand", "donate", "bestow", "offer", "give", "present", "deliver" ],
    [ "show", "display" ],
    [ "salute", "hello", "hi", "greet", "greetings" ],
    [ "farewell", "goodbye", "bye" ],
    [ "hint", "hints" ],
    [ "help", "preserve", "aid", "rescue" ],
    [ "shield", "block", "cover" ],
    [ "hurdle", "bound", "leap", "jump", "vault" ],
    [ "bounce" ],
    [ "trample", "stamp" ],
    [ "punch", "stab", "wound", "slay", "murder", "kill" ],
    [ "hit", "whack", "strike", "swat", "slap" ],
    [ "smooch", "kiss" ],
    [ "pound", "rap", "knock" ],
    [ "lie", "recline" ],
    [ "look", "stare", "gaze", "peer", "l", "peek" ],
    [ "wiggle", "jiggle", "loosen", "hook", "wobble" ],
    [ "dislocate", "move", "shift" ],
    [ "open", "disassemble", "unseal" ],
    [ "tug", "yank", "pull", "drag" ],
    [ "entice", "renumerate", "bribe", "pay" ],
    [ "play", "toy", "cavort", "fiddle" ],
    [ "poke", "jab", "blind" ],
    [ "spill", "pour" ],
    [ "empty", "clear" ],
    [ "shove", "thrust", "nudge", "press", "stick", "push" ],
    [ "insert", "put", "stash", "stuff", "lay", "place" ],
    [ "attach", "connect" ],
    [ "reconnect", "reattach" ],
    [ "detach", "unattach", "disconnec", "disengage", "unplug" ],
    [ "raise", "lift", "elevate", "hoist" ],
    [ "reach", "grope" ],
    [ "read", "leaf", "browse", "skim" ],
    [ "free", "release" ],
    [ "undo", "untie", "unfasten", "unhook" ],
    [ "repair", "service" ],
    [ "kneel", "genuflect", "grovel", "bow" ],
    [ "say", "proclaim", "speak", "utter", "talk", "maybe" ],
    [ "phone", "dial", "telephone" ],
    [ "search", "rummage", "frisk", "sift", "ransack" ],
    [ "mail", "send" ],
    [ "rattle", "jostle" ],
    [ "shoot" ],
    [ "sit", "settle", "squat", "crouch" ],
    [ "sleep", "nap", "rest", "snooze" ],
    [ "inhale", "whiff", "sniff", "smell" ],
    [ "whirl", "spin" ],
    [ "rise", "stand" ],
    [ "wade", "swim" ],
    [ "steal", "catch", "confiscate", "carry", "take", "seize", "prince", "keep", "grab", "snatch" ],
    [ "mount", "board" ],
    [ "lick", "taste" ],
    [ "tell", "inform", "advise" ],
    [ "thanks", "thank" ],
    [ "hurl", "chuck", "pitch", "toss", "throw", "fling" ],
    [ "buckle", "fasten", "tie", "secure" ],
    [ "rotate", "toggle", "flip", "turn" ],
    [ "halt", "stop" ],
    [ "operate", "use", "pedal", "exploit", "employ" ],
    [ "loiter", "wait", "z" ],
    [ "awake", "awaken", "rouse", "wake" ],
    [ "startle", "surprise", "frighten", "arouse", "scare" ],
    [ "advance", "crawl", "jog", "stroll", "run", "trudge", "hop", "saunter", "skip", "walk", "tramp", "hike", "step", "proceed" ],
    [ "grin", "smile", "sneer", "beckon", "nod", "laugh", "motion" ],
    [ "don", "wear" ],
    [ "what", "whats" ],
    [ "wheres", "where" ],
    [ "whos", "who" ],
    [ "yell", "shout", "scream", "howl" ],
    [ "no", "negative", "ok", "affirmative", "positive", "okay", "sure", "naw", "yup", "nope", "y", "yes", "yeah", "aye", "nay" ],
    [ "undress", "disrobe", "strip" ],
    [ "escape", "flee" ],
    [ "verbose" ],
    [ "brief" ],
    [ "restart" ],
    [ "save" ],
    [ "restore" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "notify" ],
    [ "diagnose" ],
    [ "answer" ],
    [ "ask" ],
    [ "order" ],
    [ "request" ],
    [ "back" ],
    [ "circle" ],
    [ "retreat" ],
    [ "bite" ],
    [ "blow" ],
    [ "climb" ],
    [ "scale" ],
    [ "ascend" ],
    [ "descend" ],
    [ "fell" ],
    [ "hang" ],
    [ "enter" ],
    [ "leave" ],
    [ "fill" ],
    [ "complete" ],
    [ "write" ],
    [ "erase" ],
    [ "rub" ],
    [ "fly" ],
    [ "retract" ],
    [ "refuse" ],
    [ "flatten" ],
    [ "untangle" ],
    [ "sell" ],
    [ "feed" ],
    [ "hear" ],
    [ "conceal" ],
    [ "hide" ],
    [ "inflate" ],
    [ "kick" ],
    [ "listen" ],
    [ "lock" ],
    [ "adjust" ],
    [ "pry" ],
    [ "lower" ],
    [ "make" ],
    [ "lean" ],
    [ "prop" ],
    [ "pray" ],
    [ "cash" ],
    [ "pick" ],
    [ "point" ],
    [ "ring" ],
    [ "call" ],
    [ "aim" ],
    [ "pocket" ],
    [ "plug" ],
    [ "stow" ],
    [ "fix" ],
    [ "work" ],
    [ "replace" ],
    [ "ride" ],
    [ "shake" ],
    [ "slide" ],
    [ "duck" ],
    [ "dive" ],
    [ "swing" ],
    [ "remove" ],
    [ "hold" ],
    [ "get" ],
    [ "bring" ],
    [ "embark" ],
    [ "disembark" ],
    [ "short" ],
    [ "touch" ],
    [ "disturb" ],
    [ "pet" ],
    [ "pat" ],
    [ "feel" ],
    [ "recall" ],
    [ "type" ],
    [ "twist" ],
    [ "start" ],
    [ "unlock" ],
    [ "approach" ],
    [ "go" ],
    [ "return" ],
    [ "wave" ],
    [ "hail" ],
    [ "wind" ],
    [ "melt" ],
    [ "dress" ],
    [ "stinglai" ],
] # verbs

nouns = [
    [ "slip", "withdrawal", "minimum", "withdrawal slip", "balance", "form" ],
    [ "deposit", "slip", "deposit slip", "form" ],
    [ "teller window", "window", "windows" ],
    [ "lady", "bank teller", "teller", "woman" ],
    [ "sign", "teller window sign" ],
    [ "nancy", "zzzp", "parrot", "dog", "sound", "paulette", "that sound", "bongo", "pongo" ],
    [ "cockpit door", "door" ],
    [ "lavatory door", "door" ],
    [ "emergency door", "door" ],
    [ "movie", "flick", "in-flight movie", "film" ],
    [ "window", "door", "exit", "emergency exit" ],
    [ "strap", "chute", "parachute" ],
    [ "handle", "red handle", "cord" ],
    [ "stewardess", "attendant" ],
    [ "stewardess", "attendant", "steward" ],
    [ "purser" ],
    [ "form", "immigration form" ],
    [ "visa number", "number" ],
    [ "hijacker", "man" ],
    [ "sticks", "dynamite", "explosives", "stick", "grenade", "grenades" ],
    [ "grenade" ],
    [ "antenna", "walkie-talkie", "talkie", "yellow device", "device", "transmitter" ],
    [ "meal", "snack", "breakfast", "lunch", "dinner", "food" ],
    [ "drink" ],
    [ "blanket" ],
    [ "pillow" ],
    [ "window", "pillow" ],
    [ "plane", "aircraft", "airplane", "jet" ],
    [ "chairs", "chair", "seat", "seats" ],
    [ "pocket", "seat", "seat pocket" ],
    [ "magazine", "airline", "airline magazine" ],
    [ "safety card", "card" ],
    [ "discomfort bag", "bag" ],
    [ "knife" ],
    [ "fork" ],
    [ "spoon" ],
    [ "platter", "tray" ],
    [ "Airlock" ],
    [ "door", "hole", "slot", "reader", "airlock door", "lock", "airlock" ],
    [ "complex", "hall", "Persecution Complex" ],
    [ "notice", "sign" ],
    [ "screens", "screen", "right observation screen", "monitor" ],
    [ "screens", "screen", "left observation screen", "monitor" ],
    [ "airshaft", "graffiti", "air shaft", "shaft", "graffito" ],
    [ "strip", "jungle", "landing strip" ],
    [ "new letter", "letter" ],
    [ "that" ],
    [ "number", "intnum", "page" ],
    [ "it", "that", "itself", "this" ],
    [ "protagonist", "yourself" ],
    [ "room", "area", "place" ],
    [ "herself", "she", "her" ],
    [ "himself", "him", "he" ],
    [ "airport", "terminal", "building", "gate" ],
    [ "skycap", "handler", "handlers", "skycaps" ],
    [ "signs", "sign" ],
    [ "pillar" ],
    [ "tannoy", "speaker", "loudspeaker" ],
    [ "wires", "black wire", "pair", "wire" ],
    [ "wires", "red wire", "pair", "wire" ],
    [ "console", "controls", "readout", "readouts", "consoles", "radio" ],
    [ "desk", "zzzp" ],
    [ "grating", "grate" ],
    [ "duct", "tube" ],
    [ "control tower", "tower" ],
    [ "visa requirements", "requirements", "visa" ],
    [ "passport", "visa", "your passport" ],
    [ "system", "pa", "music", "muzak", "sound", "announcements" ],
    [ "Airport Entrance" ],
    [ "airlines", "Random Airline", "airline" ],
    [ "Top of Pillar" ],
    [ "Duct" ],
    [ "tower", "Control Tower" ],
    [ "Lost and Found" ],
    [ "fat man", "fellow", "man", "guy" ],
    [ "clerk", "zzzp" ],
    [ "controllers", "folks", "bunch", "crowd", "group", "people", "group of air traffic controllers" ],
    [ "plane", "jet", "flight 42", "flight", "airplane", "forty-two" ],
    [ "folks", "everyone", "people", "crowd", "everybody", "onlookers" ],
    [ "plane", "aircraft", "aeroplane", "airplane", "jet" ],
    [ "seat belt", "belt", "buckle", "seatbelt" ],
    [ "floor" ],
    [ "your seat", "chair", "seat" ],
    [ "plug", "set", "headphone", "pair", "bulge", "phones", "earphone", "pair of headphones", "earphones" ],
    [ "magazine", "odyssey", "airline magazine" ],
    [ "socket", "headphone receptacle", "receptacle", "outlet", "jack", "receptable" ],
    [ "paper", "form", "immigration form" ],
    [ "line", "lines", "straps", "chute", "strap", "shroud", "parachute" ],
    [ "handle", "cord", "ripcord" ],
    [ "pencil", "eraser" ],
    [ "hatch", "hatchway", "door", "exit", "emergency exit" ],
    [ "Airplane Seat" ],
    [ "Outside Plane" ],
    [ "Falling" ],
    [ "Tree", "branches", "tree" ],
    [ "Cooking Pot", "pot" ],
    [ "lady", "stewardess", "woman", "attendant" ],
    [ "purser", "fellow", "man", "guy" ],
    [ "Airport Concourse" ],
    [ "Air Zalagasa desk", "desk" ],
    [ "Pillar" ],
    [ "speaker", "loudspeaker" ],
    [ "airline ticket", "ticket", "paper" ],
    [ "trip", "intnum", "Air Zalagasa flight 42", "flight", "forty-two" ],
    [ "sign", "seatbelt light", "light" ],
    [ "galley", "Airplane Galley" ],
    [ "Rear of Airplane" ],
    [ "paper towel", "towel" ],
    [ "lavatory", "lav", "bathroom", "Lavatory", "can" ],
    [ "sign" ],
    [ "zzzp", "attendant", "flight attendant" ],
    [ "dish", "plate" ],
    [ "tooth", "your teeth", "teeth" ],
    [ "brush", "toothbrush" ],
    [ "meal", "llama", "stew", "specialty", "plate", "bowl", "noisome stew", "dinner", "food" ],
    [ "telephone", "phone", "slot", "airphone" ],
    [ "wall", "walls" ],
    [ "ceiling" ],
    [ "fingers", "your hand", "hands", "thumbs", "thumb", "palm", "hand", "palms", "finger" ],
    [ "toe", "your foot", "sneakers", "toes", "foot", "feet", "sneaker" ],
    [ "your mouth", "mouth" ],
    [ "yourself", "i", "body", "myself", "me" ],
    [ "you", "myself", "yourself" ],
    [ "your clothes", "apparel", "clothing", "shorts", "outfit", "clothes" ],
    [ "themselves", "them", "they" ],
    [ "direction" ],
    [ "pockets", "pocket", "your pocket" ],
    [ "sounds", "sound" ],
    [ "corner", "corners" ],
    [ "weirdo", "oddity", "man", "fellow", "woody", "guy", "stranger" ],
    [ "paranoid", "owner", "man", "rambo", "guy", "fellow", "survivalist" ],
    [ "Dead End" ],
    [ "bar", "gaol door", "bars", "doorway", "door" ],
    [ "stairway", "stairs", "stair" ],
    [ "saw", "hacksaw" ],
    [ "Swiss army knife", "button", "lever", "knife", "buttons" ],
    [ "plug", "power", "power saw", "saw" ],
    [ "portable foot-powered generator", "generator" ],
    [ "home", "house", "camouflaged house", "building" ],
    [ "actually", "that" ],
    [ "unfortunately", "that" ],
    [ "machine", "gun", "machine gun" ],
    [ "box", "loudspeaker", "voice", "intercom", "sound", "speaker" ],
    [ "fence", "wall", "gate", "door", "gateway" ],
    [ "some mail", "mail" ],
    [ "Popular Paranoia magazine", "zzzp", "sticker", "address", "magazine", "mag", "periodical", "mail", "blurb", "paranoia" ],
    [ "camera" ],
    [ "goodbye", "hello", "hi", "that", "bye" ],
    [ "beast", "llama", "animal" ],
    [ "guy", "salesclerk", "salesman", "fellow", "man", "clerk" ],
    [ "lady", "waitress", "waitperson", "woman" ],
    [ "waitperson", "fellow", "waiter", "man", "guy" ],
    [ "agent", "lady", "travel agent", "woman" ],
    [ "California", "california" ],
    [ "optometrists" ],
    [ "matron", "lady", "woman" ],
    [ "bird", "macaw", "merlin" ],
    [ "philatelist", "mister", "fellow", "collector", "man", "guy", "mousy man" ],
    [ "fellow", "guy", "man", "delivery man" ],
    [ "fellow", "nerd", "man", "guy" ],
    [ "Street" ],
    [ "Downtown" ],
    [ "meal", "beer", "your meal", "sandwich", "wine", "food", "burger", "hamburger", "soda", "drink", "fries" ],
    [ "door", "doorway", "back door" ],
    [ "home", "house", "noarticle", "building", "mansion", "Street" ],
    [ "gap", "fence" ],
    [ "behind mansion" ],
    [ "tenement", "hall", "corridor", "building", "tenements", "hallway" ],
    [ "flat" ],
    [ "Death" ],
    [ "Queen Mum", "mum" ],
    [ "door", "doorway", "front door" ],
    [ "bell", "doorbell" ],
    [ "road", "street" ],
    [ "wristwatch", "clock", "time", "digital wristwatch", "watch" ],
    [ "home", "your new house", "house" ],
    [ "home", "house", "your old house" ],
    [ "window", "windows", "pane" ],
    [ "doorway", "office doorway", "door" ],
    [ "table" ],
    [ "billfold", "wallet" ],
    [ "beezer", "cards", "card", "Beezer card" ],
    [ "hologram", "US Excess card", "yak", "card", "excess", "cards" ],
    [ "paper", "piece", "letter" ],
    [ "computer", "slot", "your Boysenberry computer", "jack", "screen", "boysenberry", "keyboard" ],
    [ "plug", "modular plug" ],
    [ "cart", "software", "carts", "cartridge", "rom", "program", "eclipse predicting cartridge", "predictor" ],
    [ "carts", "cart", "software", "rom", "cartridge", "program", "recipe cartridge" ],
    [ "cart", "game", "software", "adventure", "carts", "adventure game cartridge", "cartridge", "rom", "program" ],
    [ "small case", "case" ],
    [ "box", "mailbox" ],
    [ "bag of llama treats", "treats", "supersack", "treat", "feed", "bag", "food", "order", "sack" ],
    [ "treats", "Llamex(R) brand High-Fibre Llama Treats", "treat", "food", "feed" ],
    [ "pen", "cage" ],
    [ "lock", "fence" ],
    [ "stamps", "collection" ],
    [ "advertisement", "leaflet", "stamp", "monkey", "intnum", "address", "ad", "paper", "ape", "piece", "name", "mail" ],
    [ "downtown", "town" ],
    [ "shelf", "shelves", "shelving" ],
    [ "books", "bestseller", "title", "sellers", "titles", "book", "best sellers", "seller" ],
    [ "books", "cutout", "remainder", "title", "cutouts", "titles", "book", "remainders" ],
    [ "software", "cartridge", "stock", "stock of software" ],
    [ "cash register", "drawer", "register" ],
    [ "burger", "meal", "hamburger", "sandwich", "food" ],
    [ "desk" ],
    [ "trough" ],
    [ "notice", "sign", "words" ],
    [ "bunch", "papers", "paper", "newspapers", "pile of newspapers", "stack", "pile" ],
    [ "corridor", "hallway", "hall" ],
    [ "screen door", "doorway", "door" ],
    [ "recording", "music", "sound", "radio" ],
    [ "trumpet", "aid", "ear trumpet" ],
    [ "elephant gun", "gun", "rifle", "weapon" ],
    [ "doorway", "door" ],
    [ "home", "apartment", "flat" ],
    [ "perch" ],
    [ "floor", "zzzp" ],
    [ "machine", "phone", "combination telephone/answering machine", "telephone" ],
    [ "message", "button", "messages", "messages button" ],
    [ "addresses", "address", "book", "address book" ],
    [ "last page", "pages", "three", "leaf", "page" ],
    [ "pages", "middle page", "two", "leaf", "page" ],
    [ "one", "first page", "pages", "leaf", "page" ],
    [ "trust", "bank" ],
    [ "that", "zzzp" ],
    [ "number", "address" ],
    [ "some mail", "address", "mail", "piece" ],
    [ "zzzp", "mail", "sticker", "address", "flyer" ],
    [ "booklet", "coupon booklet", "coupons", "zzzp", "sticker", "mail", "book" ],
    [ "envelope", "zzzp", "sticker", "address", "mail" ],
    [ "paper", "memo" ],
    [ "door", "cab", "taxi" ],
    [ "cabbie", "driver", "man", "cab driver" ],
    [ "notice", "sign", "cab notice" ],
    [ "denied", "permission", "that", "request", "granted" ],
    [ "button", "attendant button" ],
    [ "switch", "button", "light button" ],
    [ "recline button", "button" ],
    [ "small piece of laminated card", "piece", "card" ],
    [ "table", "seat table" ],
    [ "tribe", "natives", "zalagasan", "Zalagasans", "native" ],
    [ "grubby antechamber" ],
    [ "locker door", "door" ],
    [ "handle", "arm", "left handle", "knob", "handles" ],
    [ "handle", "middle handle", "arm", "knob", "handles" ],
    [ "handle", "arm", "knob", "handles", "right handle" ],
    [ "locker" ],
    [ "magnetic key-card", "key-card", "card", "key", "keycard" ],
    [ "carts", "unlabelled cartridge", "cart", "software", "rom", "cartridge", "program" ],
    [ "handgun", "pistol", "gun" ],
    [ "number", "inscription", "switchgear", "gear" ],
    [ "zzzp" ],
    [ "row", "aisle" ],
    [ "sink", "basin" ],
    [ "head", "eyes" ],
    [ "ground", "grounds", "surface", "floor", "earth" ],
    [ "portrait", "painting", "picture", "zzzp" ],
    [ "sign", "-", "plussign", "cheque", "check" ],
    [ "dollars", "cash", "change", "dollar", "money", "bucks", "cent", "cents", "buck" ],
] # nouns

rooms = [
    "Galley",
    "Aisle 1",
    "Aisle 12",
    "behind mansion",
    "Aisle 14",
    "Airport Entrance",
    "Tree",
    "Airplane Entrance",
    "Aisle 9",
    "Aisle 10",
    "Midair",
    "airplane seat",
    "hallway",
    "locker",
    "Falling",
    "Rear of Airplane",
    "Airplane Seat",
    "Airplane Galley",
    "Downtown",
    "In the Cab",
    "air shaft",
    "Aisle 11",
    "Lavatory",
    "Death",
    "Aisle 13",
    "Aisle 8",
    "Control Tower",
    "Street",
    "Aisle 6",
    "Airplane, near Tail",
    "Cockpit",
    "Pillar",
    "East Emergency Exit",
    "Persecution Complex",
    "Duct",
    "Aisle 4",
    "Top of Pillar",
    "grubby antechamber",
    "Airlock",
    "Airport Concourse",
    "Aisle 5",
    "Outside Plane",
    "Lost and Found",
    "Aisle 3",
    "Cooking Pot",
    "flat",
    "Aisle 7",
    "Dead End",
    "Aisle 2",
    "West Emergency Exit",
] # rooms

