# Config for CHECKPOINT, in LLM style
#
#

[game]
path = "./infocom/checkpoint/COMPILED/spy.z5"

setup = '''
checkpoint is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "photograph", "photo", "picture", "snapshot" ],
    [ "with", "using", "by" ],
    [ "through", "thru" ],
    [ "in", "inside", "into" ],
    [ "onto", "on" ],
    [ "out", "outside" ],
    [ "underneath", "below", "beneath", "under" ],
    [ "fore", "north", "forward", "n", "f", "front" ],
    [ "e", "right", "east" ],
    [ "r", "south", "rear", "aft", "s" ],
    [ "w", "left", "west" ],
    [ "down", "d" ],
    [ "up", "u" ],
    [ "nw", "northwest" ],
    [ "northeast", "ne" ],
    [ "sw", "southwest" ],
    [ "se", "southeast" ],
    [ "point", "aim" ],
    [ "check", "test", "analyze", "analyse" ],
    [ "respond", "reply", "answer" ],
    [ "consult", "ask", "inquire", "question" ],
    [ "assault", "attack", "fight", "rape", "repel", "molest" ],
    [ "bring", "fetch" ],
    [ "clean", "brush", "wipe" ],
    [ "ignite", "incinerate", "burn" ],
    [ "buy", "purchase", "order" ],
    [ "call" ],
    [ "alter", "change" ],
    [ "board", "climb" ],
    [ "draw", "close" ],
    [ "cut" ],
    [ "break", "crush", "crumble", "smash", "damage", "destroy", "kick" ],
    [ "sip", "swallow", "drink" ],
    [ "drop", "lower" ],
    [ "eat", "dine", "taste", "consume" ],
    [ "drain", "blow", "empty" ],
    [ "study", "describe", "inspect", "examin", "explore", "scrutinize", "examine", "observe" ],
    [ "douse", "extinguish" ],
    [ "head", "face" ],
    [ "sleep", "snooze", "nap", "faint" ],
    [ "flood", "fill" ],
    [ "find", "locate", "detect" ],
    [ "repair", "fix" ],
    [ "chase", "pursue", "follow", "trace" ],
    [ "offer", "donate", "give", "hand" ],
    [ "goodbye", "bye", "good-bye" ],
    [ "howdy", "hi", "greet", "hello", "greetings" ],
    [ "hide" ],
    [ "kill", "murder", "stab", "waste", "strangle" ],
    [ "hug", "kiss" ],
    [ "rap", "knock" ],
    [ "evacuate", "exit", "abandon", "detrain", "scram", "debark", "leave", "disembark", "emerge" ],
    [ "look", "l", "peek", "see", "stare", "gaze" ],
    [ "build", "prepare", "make" ],
    [ "no", "negative", "nope", "nay" ],
    [ "pour", "spill" ],
    [ "pull", "tug" ],
    [ "press", "push", "shove" ],
    [ "insert", "install", "dip", "stuff", "put", "deposit", "place" ],
    [ "quit", "logoff", "logout", "q" ],
    [ "lift", "raise" ],
    [ "peruse", "read", "skim" ],
    [ "remove", "doff", "shed" ],
    [ "restore", "restor" ],
    [ "peal", "ring" ],
    [ "tear", "rip" ],
    [ "rise", "ascend" ],
    [ "feel", "touch", "rub", "shade" ],
    [ "pause", "suspend", "save" ],
    [ "state", "whisper", "talk", "speak", "say", "explain" ],
    [ "dig", "search" ],
    [ "blast", "shoot", "fire" ],
    [ "display", "show" ],
    [ "squat", "hunker", "stoop", "sit", "crouch" ],
    [ "slap", "strike", "hurt", "injure", "hit", "punch" ],
    [ "sniff", "smell" ],
    [ "wink", "smile", "grin" ],
    [ "start", "activate", "engage" ],
    [ "superb", "superbrief", "super" ],
    [ "swim", "bathe", "wade" ],
    [ "take" ],
    [ "thank", "thanks" ],
    [ "chuck", "hurl", "throw", "toss" ],
    [ "tie", "fasten", "secure", "attach" ],
    [ "time", "t" ],
    [ "turn", "switch", "swing", "flip" ],
    [ "unfasten", "free", "uncuff", "unattach", "untie", "unhook" ],
    [ "use", "cash" ],
    [ "release", "edition", "variation", "revision", "version" ],
    [ "relax", "stay", "z", "meditate", "wait" ],
    [ "wake", "surprise", "startle", "awake" ],
    [ "drive", "steer", "proceed", "walk", "run", "go" ],
    [ "don", "wear" ],
    [ "advance", "cock", "wind" ],
    [ "name", "identify" ],
    [ "yell", "shout", "scream" ],
    [ "yes", "okay", "y", "10-4", "yup", "affirm", "sure", "wilco", "yeah", "ok", "aye", "roger" ],
    [ "arrest" ],
    [ "brief" ],
    [ "bribe" ],
    [ "come" ],
    [ "compare" ],
    [ "confront" ],
    [ "count" ],
    [ "develop" ],
    [ "diagnose" ],
    [ "discuss" ],
    [ "enter" ],
    [ "flush" ],
    [ "gesture" ],
    [ "get" ],
    [ "hang" ],
    [ "heat" ],
    [ "help" ],
    [ "hold" ],
    [ "i" ],
    [ "invent" ],
    [ "jump" ],
    [ "learn" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "load" ],
    [ "lock" ],
    [ "lunge" ],
    [ "move" ],
    [ "nod" ],
    [ "open" ],
    [ "pass" ],
    [ "pick" ],
    [ "play" ],
    [ "pocket" ],
    [ "request" ],
    [ "restart" ],
    [ "script" ],
    [ "send" ],
    [ "set" ],
    [ "shake" ],
    [ "shut" ],
    [ "sign" ],
    [ "slide" ],
    [ "smoke" ],
    [ "stand" ],
    [ "stop" ],
    [ "tell" ],
    [ "unlock" ],
    [ "unscript" ],
    [ "verbose" ],
    [ "watch" ],
    [ "write" ],
] # verbs

nouns = [
    [ "diner", "car", "dining car", "carriage" ],
    [ "dining table", "table" ],
    [ "supplies", "equipment" ],
    [ "counter" ],
    [ "message", "something", "writing", "window writing" ],
    [ "door", "restroom door" ],
    [ "machine", "cigarette machine", "panel" ],
    [ "compartment door", "door" ],
    [ "GO" ],
    [ "zzzzlg", "LG" ],
    [ "minute", "turn", "turns" ],
    [ "this", "it" ],
    [ "floor" ],
    [ "slimpuk" ],
    [ "number" ],
    [ "yourself", "herself", "himself", "you", "himself or herself" ],
    [ "corridor" ],
    [ "area", "here", "room", "place" ],
    [ "air" ],
    [ "chair" ],
    [ "(something)" ],
    [ "bunch", "fixtures", "bunch of fixtures", "fixture" ],
    [ "toilet" ],
    [ "sink", "faucet", "bowl", "basin" ],
    [ "dispenser", "towel dispenser" ],
    [ "portion", "towel" ],
    [ "remnant", "towel remnant", "portion", "towel" ],
    [ "paper dispenser", "dispenser" ],
    [ "tissue", "portion", "paper" ],
    [ "mirror" ],
    [ "pockets", "your pocket", "pocket" ],
    [ "pockets", "conductor's pocket", "pocket" ],
    [ "money", "cash" ],
    [ "menu" ],
    [ "item" ],
    [ "food" ],
    [ "drink" ],
    [ "beer", "coffee", "tea", "drink" ],
    [ "dish", "gruel", "food", "plate", "item", "plate of thin gruel" ],
    [ "china cup", "cup" ],
    [ "cup", "enamel cup" ],
    [ "food", "lice", "fish", "heads", "skin" ],
    [ "sandwich", "lunch", "meal", "breakfast", "bread", "snack", "food", "dinner" ],
    [ "frotzian", "language" ],
    [ "gesture" ],
    [ "moonlight", "light", "sunlight" ],
    [ "your hands", "hands" ],
    [ "your head", "head" ],
    [ "she", "her" ],
    [ "he", "him" ],
    [ "they", "them" ],
    [ "yourself" ],
    [ "collector", "conductor", "conduc" ],
    [ "agent", "inspector", "customs agent" ],
    [ "waiter" ],
    [ "waiter's towel", "towel" ],
    [ "cook" ],
    [ "man", "clerk" ],
    [ "stranger" ],
    [ "stranger", "man", "spy" ],
    [ "other spy" ],
    [ "stranger", "man", "other spy", "spy" ],
    [ "man", "thin man" ],
    [ "man", "fat man" ],
    [ "attractive man", "man" ],
    [ "attractive woman", "woman" ],
    [ "woman", "regal woman" ],
    [ "thin woman", "woman" ],
    [ "woman", "guard" ],
    [ "gorilla", "man", "large man", "thug" ],
    [ "small man", "defector", "man" ],
    [ "waitress" ],
    [ "officer", "man", "police officer" ],
    [ "man", "young man" ],
    [ "young woman", "woman" ],
    [ "boy" ],
    [ "girl" ],
    [ "old man", "man" ],
    [ "woman", "old woman" ],
    [ "couple", "young couple" ],
    [ "couple", "middle-aged couple" ],
    [ "couple", "old couple" ],
    [ "dead body", "stiff", "corpse", "body" ],
    [ "that" ],
    [ "gun" ],
    [ "platform" ],
    [ "people", "crowd", "crowd of people", "passenger" ],
    [ "bunch of luggage", "bunch", "luggage" ],
    [ "that thing" ],
    [ "ticket", "your ticket" ],
    [ "ticket", "other ticket" ],
    [ "your passport", "passport" ],
    [ "traveler's check", "cheque", "check" ],
    [ "miniature camera", "camera", "shutter" ],
    [ "photo", "picture" ],
    [ "microfilm", "film", "cassette", "cassette of film" ],
    [ "magnifying glass", "glass", "lens" ],
    [ "valise", "briefc", "briefcase", "bag", "case" ],
    [ "lock", "briefcase latch", "clasp", "latch", "bar" ],
    [ "handle", "briefcase handle" ],
    [ "newspaper", "papers", "paper" ],
    [ "cig", "cigarette" ],
    [ "lighter" ],
    [ "flower", "wildflower" ],
    [ "wildflower", "flower", "yellow flower" ],
    [ "blue flower", "flower", "wildflower" ],
    [ "pen" ],
    [ "handkerch", "red handkerchief", "hanky" ],
    [ "scarf", "white scarf" ],
    [ "blood", "spot of blood", "spot" ],
    [ "knife" ],
    [ "white napkin" ],
    [ "mark", "scratches", "scratch", "marks" ],
    [ "worn spot", "spot" ],
    [ "graffiti" ],
    [ "train" ],
    [ "scenery" ],
    [ "crossing" ],
    [ "cross-country vehicle", "vehicle" ],
    [ "flare" ],
    [ "river", "bank" ],
    [ "tunnel" ],
    [ "meadow" ],
    [ "plain", "stubble", "edge" ],
    [ "forest" ],
    [ "edge", "cliff", "precipice" ],
    [ "town" ],
    [ "station", "frbz", "Frbz" ],
    [ "Grnz", "grnz", "station" ],
    [ "Gola", "station", "gola" ],
    [ "knut", "Knut", "station" ],
    [ "hrng", "Hrng", "station" ],
    [ "Wien", "wien", "station", "vienna" ],
    [ "potrzebie", "station", "Potrzebie" ],
    [ "timetable", "schedule", "table" ],
    [ "ladder", "metal ladder" ],
    [ "luggage rack", "rack", "shelf" ],
    [ "other luggage rack" ],
    [ "swinging door", "door" ],
    [ "window", "forward window" ],
    [ "window", "rear window" ],
    [ "window", "corridor window" ],
    [ "stop cord", "handle", "cord" ],
    [ "shade", "curtain" ],
    [ "seat", "seats", "chair", "fabric", "upholstery", "train seat", "lace", "couch" ],
    [ "other train seat 1" ],
    [ "under the seat" ],
    [ "other under seat 1" ],
    [ "other train seat 2" ],
    [ "other under seat 2" ],
    [ "other train seat 3" ],
    [ "other under seat 3" ],
    [ "other train seat 4" ],
    [ "other under seat 4" ],
    [ "other train seat 5" ],
    [ "other under seat 5" ],
    [ "window", "first window" ],
    [ "second window", "window" ],
    [ "window", "third window" ],
    [ "window", "fourth window" ],
    [ "fifth window", "window" ],
    [ "wine" ],
    [ "thriller", "checkpoint", "game" ],
    [ "direction" ],
    [ "hat" ],
    [ "docume", "document", "paper", "plan", "mcguffin", "macguffin" ],
    [ "print", "scrap", "note", "paper", "writing", "newsprint", "message" ],
    [ "sign", "letter" ],
] # nouns

rooms = [
    "other rear restroom",
    "forward end",
    "other rear limbo",
    "second compartment",
    "other rear end",
    "first booth",
    "other fifth compartment",
    "ticket area",
    "first suite",
    "other roof",
    "other forward restroom",
    "rear limbo",
    "middle",
    "women's restroom",
    "pantry",
    "forward vestibule",
    "rear middle",
    "diner forward limbo",
    "fancy forward limbo",
    "luggage room",
    "other beside the tracks",
    "other third compartment",
    "rear restroom",
    "diner rear limbo",
    "rear vestibule",
    "forward limbo",
    "fifth compartment",
    "forward middle",
    "rear end",
    "other second compartment",
    "forward restroom",
    "other forward limbo",
    "men's restroom",
    "sidewalk",
    "other fourth compartment",
    "other rear middle",
    "third compartment",
    "fancy rear limbo",
    "other forward end",
    "third suite",
    "second booth",
    "other forward middle",
    "roof",
    "other middle",
    "limbo",
    "other front vestibule",
    "other rear vestibule",
    "beside the tracks",
    "galley",
    "cafe",
    "first compartment",
    "fourth compartment",
    "platform",
    "waiting room",
    "other first compartment",
    "third booth",
    "second suite",
] # rooms

