# Config for CUTTHROATS, in LLM style
#
#

[game]
path = "./infocom/cutthroats/COMPILED/toa.z3"

setup = '''
cutthroats is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "thru", "through" ],
    [ "onto", "on" ],
    [ "inside", "in", "into" ],
    [ "beneath", "underneath", "under", "below" ],
    [ "n", "north", "fore", "f", "forward" ],
    [ "s", "south", "abaft", "aft" ],
    [ "east", "e", "starbo", "sb" ],
    [ "p", "w", "west", "port" ],
    [ "d", "down", "downstairs" ],
    [ "u", "upstairs", "up" ],
    [ "northwest", "nw" ],
    [ "ne", "northe" ],
    [ "sw", "southwest" ],
    [ "southe", "se" ],
    [ "superbrief", "super" ],
    [ "inventory", "i" ],
    [ "quit", "q" ],
    [ "score", "progress", "rating" ],
    [ "g", "again" ],
    [ "point", "aim" ],
    [ "inquire", "ask", "question" ],
    [ "fight", "injure", "hurt", "attack" ],
    [ "brace", "support" ],
    [ "incinerate", "burn", "ignite" ],
    [ "buy", "purchase", "order" ],
    [ "lose", "barf", "chomp" ],
    [ "polish", "clean", "scrub" ],
    [ "climb" ],
    [ "close", "shut" ],
    [ "cross", "ford" ],
    [ "scrape", "pierce", "slice", "cut" ],
    [ "cuss", "swear", "shit", "hell", "damn", "curse", "fuck" ],
    [ "sip", "guzzle", "swallow", "drink", "imbibe" ],
    [ "drop", "release" ],
    [ "consume", "nibble", "chew", "bite", "eat", "munch" ],
    [ "describe", "examine" ],
    [ "extinguish", "douse" ],
    [ "find", "seek", "where", "see" ],
    [ "follow", "pursue", "chase", "come" ],
    [ "donate", "pay", "give", "offer", "hand", "feed" ],
    [ "bye", "goodbye" ],
    [ "hi", "hello" ],
    [ "leap", "jump" ],
    [ "kick" ],
    [ "kill", "slay", "dispatch", "murder", "stab" ],
    [ "rap", "knock" ],
    [ "start", "light" ],
    [ "l", "look", "gaze", "peer", "stare" ],
    [ "maybe", "dunno" ],
    [ "melt", "liquify" ],
    [ "pull", "yank", "tug" ],
    [ "mumble", "sigh" ],
    [ "hit", "chop", "smash", "destroy", "chip", "damage", "break" ],
    [ "lubricate", "grease" ],
    [ "uh-uh", "no", "negative", "nope" ],
    [ "patch", "repair", "plug", "fix", "glue" ],
    [ "jab", "blind", "poke" ],
    [ "pour", "spill" ],
    [ "shove", "press", "push" ],
    [ "stuff", "put", "insert", "wedge", "place" ],
    [ "raise", "lift" ],
    [ "rape", "molest" ],
    [ "read", "skim" ],
    [ "lease", "rent" ],
    [ "feel", "pet", "touch", "rub", "pat" ],
    [ "flash", "show" ],
    [ "skip", "hop" ],
    [ "smell", "sniff" ],
    [ "swim", "bathe", "wade" ],
    [ "thrust", "swing" ],
    [ "hold", "remove", "get", "grab", "take", "carry" ],
    [ "talk", "speak", "say", "chat" ],
    [ "rest", "sleep", "lie", "nap" ],
    [ "toss", "chuck", "throw", "cast", "hurl" ],
    [ "tie", "attach", "connect", "fasten", "secure" ],
    [ "t", "time" ],
    [ "set", "flip", "turn" ],
    [ "free", "unfasten", "detach", "disconnect", "unhook", "untie" ],
    [ "z", "wait" ],
    [ "awake", "surprise", "wake", "startle" ],
    [ "go", "step", "run", "proceed", "walk" ],
    [ "brandish", "wave" ],
    [ "winnage", "win" ],
    [ "shout", "yell", "scream" ],
    [ "affirmative", "okay", "y", "yes", "yup", "sure", "uh-huh", "ok", "yeah" ],
    [ "whos", "who", "whats", "what" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "version" ],
    [ "verbose" ],
    [ "apply" ],
    [ "back" ],
    [ "board" ],
    [ "breathe" ],
    [ "call" ],
    [ "check" ],
    [ "sit" ],
    [ "count" ],
    [ "deflate" ],
    [ "deposit" ],
    [ "dig" ],
    [ "disembark" ],
    [ "dive" ],
    [ "drill" ],
    [ "lean" ],
    [ "taste" ],
    [ "empty" ],
    [ "enter" ],
    [ "exit" ],
    [ "fill" ],
    [ "help" ],
    [ "hide" ],
    [ "blow" ],
    [ "inflat" ],
    [ "kiss" ],
    [ "latitude" ],
    [ "longitude" ],
    [ "launch" ],
    [ "leave" ],
    [ "listen" ],
    [ "lock" ],
    [ "search" ],
    [ "lower" ],
    [ "make" ],
    [ "move" ],
    [ "roll" ],
    [ "play" ],
    [ "open" ],
    [ "pick" ],
    [ "pray" ],
    [ "pump" ],
    [ "reach" ],
    [ "rob" ],
    [ "script" ],
    [ "unscript" ],
    [ "send" ],
    [ "shake" ],
    [ "slide" ],
    [ "smoke" ],
    [ "spin" ],
    [ "spray" ],
    [ "squeeze" ],
    [ "stand" ],
    [ "stay" ],
    [ "strike" ],
    [ "tell" ],
    [ "unfold" ],
    [ "fold" ],
    [ "unlock" ],
    [ "wear" ],
    [ "weigh" ],
    [ "wind" ],
    [ "withdraw" ],
] # verbs

nouns = [
    [ "ship", "engine", "ferry", "boat" ],
    [ "ferry" ],
    [ "chair", "armcha", "seat" ],
    [ "line", "rope", "orange line" ],
    [ "switch", "compre", "large air compressor" ],
    [ "airhose", "hose" ],
    [ "machin", "detect", "device", "small machine" ],
    [ "label", "sticke", "tag", "machine label", "logo" ],
    [ "switch", "machine switch" ],
    [ "machine compartment", "compar", "panel", "recess" ],
    [ "hood", "deep-sea diving suit", "suit" ],
    [ "mattre", "bed", "bunk" ],
    [ "under the bunk" ],
    [ "stove", "gimbal", "range" ],
    [ "chairs", "chair", "seat" ],
    [ "mattre", "bed", "large bunk", "bunk" ],
    [ "drill", "panel", "portable drill", "bit", "switch" ],
    [ "drille", "hole" ],
    [ "escudo", "gold coin", "coin", "doublo" ],
    [ "plate", "dinner plate", "dish" ],
    [ "combin", "thingy" ],
    [ "intnum", "number" ],
    [ "direction", "intdir" ],
    [ "pseudo" ],
    [ "it", "him", "her", "that", "random object" ],
    [ "oxygen", "air" ],
    [ "ground", "floor" ],
    [ "deck" ],
    [ "hatch", "hatchw", "hole" ],
    [ "hole" ],
    [ "bulkhe", "bulkhead" ],
    [ "walls", "wall" ],
    [ "ceiling", "ceilin" ],
    [ "masts", "mast" ],
    [ "lighthouse", "beacon", "lighth" ],
    [ "treasure", "treasu" ],
    [ "ship", "wind", "trawle", "Night Wind", "boat" ],
    [ "salvag", "ship", "margar", "Mary Margaret", "boat" ],
    [ "ship", "wreck", "shipwr", "shipwreck" ],
    [ "sleep" ],
    [ "abandoned field", "field", "weeds" ],
    [ "rocky coastline", "coastl", "rocks" ],
    [ "pocket" ],
    [ "bunch of people", "people" ],
    [ "wallpa", "wallpaper" ],
    [ "carpet", "rug", "carpeting" ],
    [ "counter", "table", "desk", "drawer", "counte" ],
    [ "bank", "trust" ],
    [ "cash", "money" ],
    [ "ferry token", "token" ],
    [ "time" ],
    [ "day" ],
    [ "advent", "player", "cretin" ],
    [ "me", "myself", "you" ],
    [ "yourself", "self", "yourse" ],
    [ "room", "cabin" ],
    [ "window" ],
    [ "door", "bedroom door" ],
    [ "water", "waves", "sea", "ocean" ],
    [ "steps", "stairw", "stairs" ],
    [ "top", "ladder", "ladder top" ],
    [ "ladder", "bottom", "ladder bottom" ],
    [ "railin", "rail", "railing" ],
    [ "collec", "bunks", "beds", "collection of decrepit bunks", "bunk" ],
    [ "front door", "door" ],
    [ "back window", "window" ],
    [ "door", "back door" ],
    [ "cot", "mattre", "bed" ],
    [ "dresser", "drawer", "dresse", "bureau" ],
    [ "bankbook", "Mariners' Trust passbook", "passbook" ],
    [ "room key", "key" ],
    [ "note" ],
    [ "text", "book", "book of shipwrecks", "shipwr" ],
    [ "closet" ],
    [ "suit", "wet suit" ],
    [ "pair", "fins", "fin", "pair of flippers", "flippe" ],
    [ "diving mask", "mask" ],
    [ "tank", "air tank", "gauge" ],
    [ "stub", "butts", "cigar stub", "butt", "stubs" ],
    [ "envelo", "envelope", "writin" ],
    [ "list", "catalo", "price list", "listin" ],
    [ "gun", "spear gun" ],
    [ "compass", "compas" ],
    [ "winch" ],
    [ "batter", "dry cell", "cell" ],
    [ "net" ],
    [ "batter", "C battery", "cell" ],
    [ "anchor" ],
    [ "putty", "tube", "tube of putty" ],
    [ "putty", "glob", "glob of putty", "gunk" ],
    [ "small air compressor", "compre" ],
    [ "location box", "box", "button" ],
    [ "book", "diving book" ],
    [ "electr", "magnet", "portable electromagnet" ],
    [ "flashl", "lanter", "flashlight", "lamp", "light" ],
    [ "label", "can", "canist", "repell", "shark repellent canister" ],
    [ "chart", "maps", "set", "set of nautical charts", "charts" ],
    [ "diving cage", "cage" ],
    [ "parrot", "bird", "leg" ],
    [ "patch", "small eyepatch", "eyepat" ],
    [ "table" ],
    [ "chair", "seat" ],
    [ "surfac", "bar" ],
    [ "mirror" ],
    [ "meal", "stew", "food" ],
    [ "water", "glass" ],
    [ "booze", "grog", "liquor", "drink" ],
    [ "wine", "liquor", "whisky", "whiske", "beer" ],
    [ "bills", "cash", "money" ],
    [ "McGinty", "mcginty" ],
    [ "cheroo", "cigar", "stogie" ],
    [ "red", "johnny", "Johnny Red", "john" ],
    [ "Pete the Rat", "cook", "rat" ],
    [ "Pete's eyepatch", "eyepat", "patch" ],
    [ "the Weasel", "weasel", "webste" ],
    [ "blade", "knife", "Weasel's knife" ],
    [ "card", "Merchant Seaman's card" ],
    [ "wrist watch", "watch", "wristw", "timepi" ],
    [ "boy", "Outfitters' delivery boy", "kid" ],
    [ "hevlin", "dead man", "man" ],
    [ "shark", "fish" ],
    [ "wood", "piece", "pieces", "ladder" ],
    [ "rope" ],
    [ "mast" ],
    [ "door" ],
    [ "bar", "iron bar", "rod", "pike" ],
    [ "bars", "lot of iron bars", "bar", "pike", "pikes" ],
    [ "wooden cask", "cask", "barrel" ],
    [ "row of fallen bunks", "bunks", "bunk", "row" ],
    [ "rungs", "ladder", "rung" ],
    [ "door", "safe", "lock", "vault" ],
    [ "collection of rare stamps", "stamps", "collec" ],
    [ "trunk", "chest", "maple chest" ],
    [ "hole", "jagged hole" ],
    [ "door", "sign" ],
    [ "skeleton", "bones", "skelet" ],
    [ "scabba", "scabbard" ],
    [ "barnacle", "barnac" ],
    [ "rapier", "sword", "blade" ],
    [ "chest", "trunk", "oak chest" ],
    [ "bomb", "spike", "spikes", "loose mine", "mine" ],
    [ "bunch of mines", "points", "bombs", "mines" ],
    [ "giant squid", "squid" ],
    [ "zzmgck" ],
    [ "teller", "clerk", "barten", "salesm" ],
    [ "crack", "shelf", "case" ],
] # nouns

rooms = [
    "Point Lookout",
    "Red Boar Inn",
    "Mariners' Trust",
    "Back Alley",
    "Storage Locker",
    "Underwater",
    "Wheelhouse",
    "The Shanty",
    "Wharf",
    "Outfitters Int'l",
    "Wharf Road",
    "Fore Deck",
    "Captain's Cabin",
    "Engine Room",
    "Your Room",
    "Port Deck",
    "Below Decks",
    "Top Deck",
    "Aft Deck",
    "Galley",
    "Crew's Quarters",
    "Middle Deck",
    "Lounge",
    "Upstairs Hallway",
    "Ocean Road",
    "Vacant Lot",
    "Shore Road",
    "Ocean Floor",
    "Ferry Landing",
    "Starboard Deck",
    "Winding Road",
    "McGinty Salvage",
] # rooms

