# Config for DEADLINE, in LLM style
#
#

[game]
path = "./infocom/deadline/COMPILED/deadline.z3"

setup = '''
deadline is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "using", "through", "with" ],
    [ "into", "in", "inside" ],
    [ "under", "underneath", "beneath" ],
    [ "n", "north" ],
    [ "s", "south" ],
    [ "e", "east" ],
    [ "w", "west" ],
    [ "down", "d", "downstairs" ],
    [ "u", "up", "upstairs" ],
    [ "nw", "northwest" ],
    [ "northeast", "ne" ],
    [ "southwest", "sw" ],
    [ "southe", "se" ],
    [ "super", "superbrief" ],
    [ "i", "inventory" ],
    [ "time", "t" ],
    [ "q", "quit" ],
    [ "check", "analyze", "analyse", "test", "dust" ],
    [ "reply", "answer" ],
    [ "inquire", "question", "ask" ],
    [ "attack", "hurt", "fight", "injure", "hit" ],
    [ "wipe", "brush", "clean" ],
    [ "burn", "incinerate", "ignite" ],
    [ "hey", "call", "dial" ],
    [ "climb", "sit", "hatch" ],
    [ "count" ],
    [ "ford", "cross" ],
    [ "cut", "slice", "pierce" ],
    [ "curse", "damn" ],
    [ "swallow", "drink", "imbibe" ],
    [ "release", "drop" ],
    [ "consume", "eat" ],
    [ "describe", "examine" ],
    [ "extinguish", "douse" ],
    [ "where", "there", "seen", "find" ],
    [ "pursue", "chase", "follow" ],
    [ "donate", "hand", "offer", "give" ],
    [ "hi", "hello" ],
    [ "jump", "leap" ],
    [ "kick", "taunt", "bite" ],
    [ "strangle", "dispatch", "kill" ],
    [ "rap", "knock" ],
    [ "stand", "lean", "prop" ],
    [ "stare", "l", "look", "gaze" ],
    [ "search", "dig" ],
    [ "move" ],
    [ "pull", "tug" ],
    [ "sigh", "mumble" ],
    [ "destroy", "damage", "break", "smash" ],
    [ "poke", "jab", "blind" ],
    [ "spill", "pour" ],
    [ "push", "press" ],
    [ "place", "stuff", "put", "insert" ],
    [ "lift", "raise" ],
    [ "molest", "rape" ],
    [ "read", "skim" ],
    [ "ring", "peal" ],
    [ "touch", "rub", "shade", "feel" ],
    [ "hop", "skip" ],
    [ "sniff", "smell" ],
    [ "wade", "swim", "bathe" ],
    [ "swing", "thrust" ],
    [ "take", "get", "hold", "lead", "carry", "remove" ],
    [ "say", "talk" ],
    [ "throw", "toss", "chuck", "hurl" ],
    [ "attach", "secure", "tie", "fasten" ],
    [ "shut", "turn", "flip" ],
    [ "unfasten", "free", "untie", "unattach", "unhook" ],
    [ "awake", "surprise", "wake", "startle" ],
    [ "proceed", "run", "go", "walk" ],
    [ "wave", "brandish" ],
    [ "whats", "what", "who" ],
    [ "yes", "maybe", "no" ],
    [ "thanks", "thank" ],
    [ "did", "how", "why", "when" ],
    [ "brief" ],
    [ "space" ],
    [ "unspace" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "version" ],
    [ "verbose" ],
    [ "accuse" ],
    [ "again" ],
    [ "apply" ],
    [ "arrest" ],
    [ "bug" ],
    [ "close" ],
    [ "confront" ],
    [ "enter" ],
    [ "exit" ],
    [ "fill" ],
    [ "fingerprint" ],
    [ "flush" ],
    [ "goodbye" ],
    [ "hide" ],
    [ "blow" ],
    [ "kiss" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "watch" ],
    [ "lower" ],
    [ "roll" ],
    [ "play" ],
    [ "open" ],
    [ "peek" ],
    [ "pick" ],
    [ "script" ],
    [ "unscript" ],
    [ "send" ],
    [ "shake" ],
    [ "show" ],
    [ "slide" ],
    [ "squeeze" ],
    [ "strike" ],
    [ "taste" ],
    [ "tell" ],
    [ "unlock" ],
    [ "use" ],
    [ "wait" ],
    [ "write" ],
    [ "know" ],
] # verbs

nouns = [
    [ "it", "them", "X" ],
    [ "him", "she", "he", "X", "her" ],
    [ "south closet door", "door" ],
    [ "front door", "door" ],
    [ "door" ],
    [ "door", "south door" ],
    [ "door", "bathroom door" ],
    [ "door", "bedroom door" ],
    [ "hidden door", "door" ],
    [ "doors", "window", "door", "balcony door" ],
    [ "roses", "bed", "rose" ],
    [ "house", "wall" ],
    [ "lawn", "grass" ],
    [ "dirt", "ground", "mud", "soil" ],
    [ "air", "wind", "breeze" ],
    [ "shed", "cabin" ],
    [ "lake", "water" ],
    [ "balcony" ],
    [ "bay window", "window" ],
    [ "player", "inspector", "me" ],
    [ "mcnabb", "Mr. McNabb" ],
    [ "baxter", "Mr. Baxter" ],
    [ "dunbar", "Ms. Dunbar" ],
    [ "george", "George", "robner" ],
    [ "mother", "Mrs. Robner", "leslie", "robner" ],
    [ "Mrs. Rourke", "rourke" ],
    [ "desk" ],
    [ "note pad", "pad", "paper", "notepad" ],
    [ "calendar", "desk calendar", "july" ],
    [ "papers", "stack of papers", "stack" ],
    [ "new will", "will" ],
    [ "Daily Herald", "paper", "herald", "newspaper", "section" ],
    [ "second section of the Herald", "section" ],
    [ "handwritten envelope", "envelope" ],
    [ "letter" ],
    [ "killing", "murder", "crime" ],
    [ "suicide" ],
    [ "omnidyne", "Omnidyne Corporation" ],
    [ "roses", "garden", "rose" ],
    [ "weather", "problem", "wrong", "climate" ],
    [ "sunlight", "light" ],
    [ "present will", "will" ],
    [ "table", "marble-top table" ],
    [ "telephone", "phone", "receiver" ],
    [ "scandal", "case", "Focus", "focus" ],
    [ "Mr. Robner", "father", "marshall", "robner" ],
    [ "book", "bookshelves", "books", "shelves", "set of bookshelves" ],
    [ "button", "black button" ],
    [ "button", "red button" ],
    [ "button", "blue button" ],
    [ "wooden ladder", "ladder" ],
    [ "ladder" ],
    [ "tools", "rope", "collection of carpentry tools", "saw", "hammer" ],
    [ "hoe", "spade", "collection of garden tools", "rake", "hose" ],
    [ "shelf", "shelves" ],
    [ "group", "group of cups", "cups", "teacup" ],
    [ "group", "saucer", "group of saucers" ],
    [ "china" ],
    [ "plates", "plate" ],
    [ "cup", "teacup" ],
    [ "saucer" ],
    [ "wastepaper basket", "basket" ],
    [ "papers", "bunch of crumpled papers", "trash" ],
    [ "fingerprint", "fingerprints" ],
    [ "carpet", "rug" ],
    [ "oak door", "door" ],
    [ "spot", "mark", "mud spots", "dirt", "mud" ],
    [ "sinks", "sink", "bowl", "basin" ],
    [ "toilet" ],
    [ "tub", "bathtub", "shower", "bath" ],
    [ "chest", "cabinet" ],
    [ "bathtub", "tub" ],
    [ "counter" ],
    [ "chairs", "chair" ],
    [ "couch", "sofa", "couches" ],
    [ "table", "tables" ],
    [ "table", "tables", "pair of end tables" ],
    [ "table", "living room table", "tables" ],
    [ "bed" ],
    [ "window" ],
    [ "kitchen window", "window" ],
    [ "window", "dining room window" ],
    [ "dresser" ],
    [ "hole", "holes" ],
    [ "shard", "fragment", "porcelain", "piece" ],
    [ "powder", "bowl", "sugar", "substance", "sugar bowl" ],
    [ "tray" ],
    [ "combination", "safe", "door" ],
    [ "cornerstone", "stone" ],
    [ "bottle", "loblo", "bottle of LoBlo", "label" ],
    [ "ebullion", "pills", "Ebullion tablets", "tablets" ],
    [ "pills", "tablets", "LoBlo tablets", "loblo" ],
    [ "tablets", "loblo", "couple", "pills", "couple of LoBLO tablets" ],
    [ "bottle", "aspirin", "bottle of aspirin", "label" ],
    [ "handful of aspirin tablets", "aspirin", "tablets", "pills", "handful" ],
    [ "dum-kof", "bottle of cough medicine", "medicine", "label", "bottle" ],
    [ "quantity of cough syrup", "syrup" ],
    [ "bottle", "ebullion", "bottle of Ebullion", "label" ],
    [ "ebullion", "couple of Ebullion tablets", "tablets", "couple" ],
    [ "paper", "slip", "report", "lab report", "note" ],
    [ "meeting", "tryst", "rendezvous" ],
    [ "call", "right", "telephone conversation", "conversation", "left" ],
    [ "number", "intnum" ],
    [ "gun", "pistol", "smoking gun" ],
    [ "stiff", "dunbar", "body of Ms. Dunbar", "corpse", "body" ],
    [ "note", "handwr", "suicide note" ],
    [ "pool", "blood", "pool of blood" ],
    [ "pen" ],
    [ "Seurat", "seurat" ],
    [ "collection of paintings", "painting", "collection", "picture" ],
    [ "shelf", "shelf unit", "unit" ],
    [ "stove", "appliance", "refrigerator", "oven" ],
    [ "dishwasher", "disposal", "washer", "appliance", "compactor" ],
    [ "table", "long table" ],
    [ "table", "trestle table" ],
    [ "blue pen", "pen" ],
    [ "steven", "steve", "Steven" ],
    [ "combination", "safe" ],
    [ "today" ],
    [ "search warrant", "warrant" ],
    [ "water" ],
    [ "circular" ],
    [ "duffy", "Sergeant Duffy" ],
    [ "railing" ],
    [ "merger" ],
    [ "walls", "wall", "room" ],
    [ "coates", "Mr. Coates" ],
    [ "combination of objects specified" ],
    [ "noontime", "noon" ],
    [ "crystal lamp", "lamp", "chandelier" ],
    [ "firepl", "fieldstone fireplace" ],
    [ "pile", "wood pile" ],
    [ "collection", "portraits", "painting", "collection of portraits", "picture" ],
    [ "fine wooden cabinets", "cabinet" ],
    [ "cabinet" ],
    [ "silver", "set of silverware" ],
    [ "glasses", "collection", "glass", "glass collection" ],
    [ "shelves", "set of wooden shelves" ],
    [ "cans", "can", "foods", "food assortment", "food" ],
    [ "tree", "fruit tree" ],
    [ "berry bush", "bush" ],
    [ "mirror" ],
    [ "hanging plant", "plant", "plants" ],
    [ "dust", "dust and cobwebs", "cobwebs" ],
    [ "hidden closet", "closet" ],
    [ "top", "treetop" ],
    [ "four-poster bed", "poster", "bed" ],
    [ "lounge" ],
    [ "mirror", "large mirror", "frame" ],
    [ "razor", "shaving gear", "gear", "cream" ],
    [ "liquor cabinet", "cabinet" ],
    [ "bottle", "scotch", "bottle of Scotch" ],
    [ "bottle", "bottle of Bourbon", "bourbon" ],
    [ "stereo", "hifi", "music", "volume" ],
    [ "record", "record collection" ],
    [ "tapes", "cassette", "tape", "tape collection" ],
    [ "sheets", "linen", "linens" ],
    [ "towel", "towels" ],
    [ "bottle", "bottle of Sneezo brand decongestant", "sneezo", "decong" ],
    [ "decong", "sneezo", "tablets", "pills", "Sneezo tablets" ],
    [ "decong", "handful of Sneezo tablets", "sneezo", "tablets", "handful" ],
    [ "bottle", "allergone", "bottle of Allergone" ],
    [ "allergone", "pills", "tablets", "Allergone tablets" ],
    [ "allergone", "tablets", "bunch", "bunch of Allergone tablets" ],
    [ "closet" ],
    [ "wet piece of paper", "piece", "paper" ],
    [ "pencil" ],
    [ "here" ],
    [ "red herring", "herring" ],
    [ "book", "mystery book" ],
    [ "ending", "page", "end", "book" ],
    [ "ticket", "stub", "ticket stub" ],
    [ "dinner", "breakfast", "lunch", "meal" ],
    [ "house" ],
    [ "grape arbor", "grape", "arbor" ],
    [ "symphony", "concert", "performance" ],
    [ "zzkjlk" ],
] # nouns

rooms = [
    "Top of Stairs",
    "Master Bedroom",
    "Dunbar's Bedroom",
    "Dining Room",
    "Foyer",
    "End of South Hall",
    "Mrs. Rourke's Bathroom",
    "Corner",
    "George's Bedroom",
    "West of Front Door",
    "Living Room",
    "Orchard Path",
    "Kitchen",
    "Front Path",
    "Library",
    "Guest Room",
    "Library Balcony",
    "Bedroom Balcony",
    "X",
    "East of Front Door",
    "Closet",
    "South Lawn",
    "South Closet",
    "Hidden Closet",
    "North Upstairs Hall",
    "Shed",
    "Behind the Shed",
    "North Lawn",
    "South Hallway",
    "End of Hallway",
    "Garden Path",
    "Dunbar's Bathroom",
    "Upstairs Closet",
    "George's Bathroom",
    "Master Bathroom",
    "South Upstairs Hall",
    "Among the Roses",
    "Hallway",
    "Pantry",
    "Bottom of Stairs",
    "Mrs. Rourke's Room",
    "Stairs",
    "In the Orchard",
    "East Lawn",
    "North of Foyer",
    "West Side of House",
    "East Side of House",
] # rooms

