# Config for ENCHANTER, in LLM style
#
#

[game]
path = "./infocom/enchanter/COMPILED/enchanter.z3"

setup = '''
enchanter is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "between", "going" ],
    [ "using", "with", "thru", "through" ],
    [ "onto", "on" ],
    [ "inside", "in", "into" ],
    [ "under", "below", "underneath", "beneath" ],
    [ "north", "n" ],
    [ "s", "south" ],
    [ "east", "e" ],
    [ "w", "west" ],
    [ "down", "d" ],
    [ "u", "up" ],
    [ "superbrief", "super" ],
    [ "inventory", "i" ],
    [ "quit", "q" ],
    [ "answer", "reply" ],
    [ "fight", "hurt", "hit", "injure", "attack" ],
    [ "burn", "ignite" ],
    [ "climb", "sit", "scale" ],
    [ "count" ],
    [ "ford", "cross" ],
    [ "cut", "pierce", "slice" ],
    [ "curse", "damn" ],
    [ "sip", "drink", "swallow" ],
    [ "exit", "release", "drop" ],
    [ "consume", "taste", "eat" ],
    [ "examine", "describe", "inspect", "whats", "what" ],
    [ "drive", "begone", "exorcise", "banish" ],
    [ "extinguish", "douse" ],
    [ "see", "seek", "where", "find" ],
    [ "follow", "pursue", "chase", "come" ],
    [ "forget", "unlearn", "unmemorize" ],
    [ "hand", "offer", "donate", "feed", "give" ],
    [ "hi", "hello" ],
    [ "dive", "leap", "jump" ],
    [ "bite", "kick" ],
    [ "kill", "slay", "dispatch", "murder", "stab" ],
    [ "knock", "rap" ],
    [ "l", "look", "stare", "gaze" ],
    [ "liquify", "melt" ],
    [ "tug", "pull" ],
    [ "sigh", "mumble" ],
    [ "smash", "break", "damage", "hatch", "crack", "destroy" ],
    [ "grease", "oil", "lubricate" ],
    [ "plug", "patch", "repair", "glue", "fix" ],
    [ "plugh", "xyzzy" ],
    [ "gesture", "point" ],
    [ "blind", "jab", "poke" ],
    [ "pour", "spill" ],
    [ "press", "push" ],
    [ "place", "put", "lay", "insert", "stuff" ],
    [ "conceal", "hide" ],
    [ "lift", "raise" ],
    [ "molest", "rape" ],
    [ "skim", "read" ],
    [ "pat", "feel", "pet", "touch" ],
    [ "sleep", "nap", "snooze" ],
    [ "hop", "skip" ],
    [ "sniff", "smell" ],
    [ "swim", "wade", "bathe" ],
    [ "thrust", "swing" ],
    [ "take", "hold", "grab", "get", "carry", "remove" ],
    [ "talk", "call", "say" ],
    [ "thanks", "thank" ],
    [ "throw", "chuck", "toss", "hurl" ],
    [ "attach", "tie", "fasten", "secure" ],
    [ "shut", "flip", "set", "turn" ],
    [ "unhook", "untie", "free", "unattach", "unfasten" ],
    [ "wait", "z" ],
    [ "wake", "startle", "awake", "surprise" ],
    [ "step", "go", "run", "proceed", "walk" ],
    [ "motion", "brandish", "wave", "beckon" ],
    [ "scream", "yell", "shout" ],
    [ "make", "draw" ],
    [ "erase", "rub", "disconnect" ],
    [ "cast", "incant" ],
    [ "t", "time" ],
    [ "hone", "sharpen" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "version" ],
    [ "verbose" ],
    [ "apply" ],
    [ "back" ],
    [ "board" ],
    [ "lie" ],
    [ "close" ],
    [ "deflate" ],
    [ "dig" ],
    [ "disembark" ],
    [ "lean" ],
    [ "enter" ],
    [ "exit" ],
    [ "escape" ],
    [ "who" ],
    [ "fill" ],
    [ "blow" ],
    [ "inflat" ],
    [ "kiss" ],
    [ "launch" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "search" ],
    [ "lower" ],
    [ "move" ],
    [ "roll" ],
    [ "play" ],
    [ "open" ],
    [ "pick" ],
    [ "pray" ],
    [ "pump" ],
    [ "reach" ],
    [ "repent" ],
    [ "script" ],
    [ "unscript" ],
    [ "send" ],
    [ "shake" ],
    [ "slide" ],
    [ "spin" ],
    [ "spray" ],
    [ "squeeze" ],
    [ "stand" ],
    [ "stay" ],
    [ "strike" ],
    [ "tell" ],
    [ "bring" ],
    [ "ask" ],
    [ "unlock" ],
    [ "fly" ],
    [ "wear" ],
    [ "wind" ],
    [ "zork" ],
    [ "show" ],
    [ "connect" ],
    [ "learn" ],
    [ "memorize" ],
    [ "spells" ],
    [ "gondar" ],
    [ "gnusto" ],
    [ "frotz" ],
    [ "ozmoo" ],
    [ "zifmia" ],
    [ "vaxum" ],
    [ "rezrov" ],
    [ "nitfol" ],
    [ "exex" ],
    [ "kulcad" ],
    [ "melbor" ],
    [ "blorb" ],
    [ "guncho" ],
    [ "krebf" ],
    [ "cleesh" ],
    [ "izyuk" ],
    [ "filfre" ],
    [ "write" ],
    [ "avoid" ],
    [ "gag" ],
    [ "gross" ],
] # verbs

nouns = [
    [ "iron gate", "gate" ],
    [ "chains", "chain" ],
    [ "archway", "arch" ],
    [ "fourposter feather bed", "bed" ],
    [ "bedpost", "post" ],
    [ "compartment" ],
    [ "ornate button", "button", "carving", "orname" ],
    [ "door", "cell door" ],
    [ "scratchings", "wall", "stone wall", "writing", "graffiti" ],
    [ "block", "square block of stone" ],
    [ "spoon", "worn silver spoon" ],
    [ "gate", "rusty gate" ],
    [ "festive decorations", "decorations" ],
    [ "table", "tables" ],
    [ "bench", "benches" ],
    [ "golden cutlery", "crystal", "cutlery" ],
    [ "food", "luscious food" ],
    [ "banquet candles", "candle" ],
    [ "shapes", "group of hairy shapes", "beings", "couple", "guards" ],
    [ "knife", "bones", "various and sundry items", "cobwebs", "knives" ],
    [ "nest", "rat nest" ],
    [ "oven" ],
    [ "heap", "food", "heap of garbage" ],
    [ "skeleton", "bones", "heap" ],
    [ "droning", "noises", "noise", "voices" ],
    [ "tracks", "track" ],
    [ "hole", "rat hole" ],
    [ "gate" ],
    [ "frog", "frogs" ],
    [ "lilies", "lily pad", "pad", "pads" ],
    [ "chest", "chests", "cabinet", "collection of chests and cabinets" ],
    [ "egg", "beautiful, ornamented egg" ],
    [ "lapis handle", "handle" ],
    [ "emerald knob", "knob" ],
    [ "silver slide", "slide" ],
    [ "golden crank", "crank" ],
    [ "button", "diamond-studded button" ],
    [ "scrambled egg", "egg" ],
    [ "scroll", "shredded scroll" ],
    [ "person", "portraits of unknown persons", "canvas", "portrait", "painting" ],
    [ "portrait", "Flathead portrait" ],
    [ "portrait", "Frobozz portrait" ],
    [ "painting", "canvas", "portrait", "lighted portrait" ],
    [ "niche" ],
    [ "black candle", "flame", "candle" ],
    [ "machine", "machinery" ],
    [ "blinking display", "lights", "light", "display" ],
    [ "dial", "control", "button", "dials", "glowing button" ],
    [ "heather", "thistle", "local vegetation" ],
    [ "seaweed", "shells", "jetsam", "flotsam" ],
    [ "rainbow turtle", "turtle", "shell" ],
    [ "rainbow turtle", "turtle" ],
    [ "intnum", "number" ],
    [ "pseudo" ],
    [ "it", "that", "him", "her", "random object" ],
    [ "ground", "floor" ],
    [ "entrance", "passage", "corridor" ],
    [ "castle", "castle wall", "wall", "walls" ],
    [ "ceiling", "ceilin" ],
    [ "hands", "bare hands of a novice enchanter", "hand" ],
    [ "enchanter", "cretin" ],
    [ "me", "you", "self", "face", "myself" ],
    [ "window" ],
    [ "sea", "ocean" ],
    [ "forest" ],
    [ "temple" ],
    [ "lawns", "grass", "lawn", "courtyard" ],
    [ "tower" ],
    [ "turret" ],
    [ "lawn" ],
    [ "meadow" ],
    [ "beach" ],
    [ "brook", "water" ],
    [ "quantity of water", "quantity", "water" ],
    [ "jug" ],
    [ "stars", "sky" ],
    [ "necromancer", "belboz", "Necromancer Belboz" ],
    [ "room", "place", "area", "here" ],
    [ "bramble" ],
    [ "hole" ],
    [ "jewelled box", "box" ],
    [ "tangle of rope", "coils", "coil", "knot", "rope" ],
    [ "knife", "sacrificial dagger", "blade", "dagger" ],
    [ "spell book", "book" ],
    [ "gnusto spell", "spell" ],
    [ "spell", "frotz spell" ],
    [ "scroll", "black scroll" ],
    [ "spell", "ozmoo spell" ],
    [ "scroll", "faded scroll" ],
    [ "zifmia spell", "spell" ],
    [ "scroll", "gold leaf scroll" ],
    [ "spell", "vaxum spell" ],
    [ "scribbled scroll", "scroll" ],
    [ "spell", "rezrov spell" ],
    [ "scroll", "frayed scroll" ],
    [ "spell", "gondar spell" ],
    [ "nitfol spell", "spell" ],
    [ "scroll", "stained scroll" ],
    [ "exex spell", "spell" ],
    [ "scroll", "parchment", "paper", "brittle scroll" ],
    [ "kulcad spell", "spell" ],
    [ "scroll", "vellum scroll" ],
    [ "spell", "melbor spell" ],
    [ "blorb spell", "spell" ],
    [ "scroll", "powerful scroll" ],
    [ "guncho spell", "spell" ],
    [ "slightly crumpled scroll", "scroll" ],
    [ "spell", "krebf spell" ],
    [ "scroll", "damp scroll" ],
    [ "spell", "cleesh spell" ],
    [ "scroll", "ornate scroll" ],
    [ "spell", "izyuk spell" ],
    [ "purple scroll", "scroll" ],
    [ "spell", "filfre spell" ],
    [ "strong box", "safe", "box" ],
    [ "undergrowth" ],
    [ "sign" ],
    [ "foundation", "house" ],
    [ "castle", "tower", "towers", "turret" ],
    [ "shack", "wooden shack" ],
    [ "battered lantern", "lantern", "lamp" ],
    [ "oven", "fixture" ],
    [ "loaf of bread", "bread", "loaf", "food" ],
    [ "branch", "tree", "trees" ],
    [ "hovel" ],
    [ "crone", "creature swathed in rags" ],
    [ "trail", "road", "path" ],
    [ "hill", "hills" ],
    [ "mountain", "peak" ],
    [ "rat", "bats", "dog", "glimpse", "bat" ],
    [ "bluebottle", "fly", "outline", "glimpse", "mist" ],
    [ "door", "simple wooden door" ],
    [ "wall", "walls", "maps" ],
    [ "entharion", "Entharion" ],
    [ "golden globe", "globe" ],
    [ "pedestal" ],
    [ "door", "guarded door" ],
    [ "letter", "sign" ],
    [ "tentacle", "monster", "gargoyle", "dragon" ],
    [ "chains", "iron chain", "chain" ],
    [ "tongue", "spear", "spears" ],
    [ "adventurer" ],
    [ "mirror" ],
    [ "glass", "shards of glass", "shards" ],
    [ "formation", "labyrinth", "tunnel", "mirror environment", "cave" ],
    [ "adventurer", "person" ],
    [ "brass lantern", "lantern" ],
    [ "sword" ],
    [ "sleep" ],
    [ "stairs", "stairway", "stair", "steps" ],
    [ "krill", "warlock", "warlock Krill" ],
    [ "dragon", "flame", "flames" ],
    [ "monster", "shape", "being" ],
    [ "fangs", "statue", "talons" ],
    [ "shapes", "men", "mass", "figure", "huddled mass, yearning to drink blood" ],
    [ "guard", "shapes", "shape", "guards" ],
    [ "door", "north cell door" ],
    [ "south cell door", "door" ],
    [ "force", "terror", "presence", "lurking evil presence" ],
    [ "map" ],
    [ "badly worn pencil", "runes", "eraser", "pencil" ],
    [ "point B", "b" ],
    [ "point R", "r" ],
    [ "k", "point K" ],
    [ "h", "point H" ],
    [ "point J", "j" ],
    [ "point M", "m" ],
    [ "point V", "v" ],
    [ "f", "point F" ],
    [ "p", "point P" ],
    [ "passage", "black passage" ],
    [ "dusty book", "book", "page" ],
    [ "Legend of the Unseen Terror", "terror", "legend" ],
    [ "zzmgck" ],
    [ "implementers", "legend" ],
] # nouns

rooms = [
    "North Gate",
    "Bottomless Pit",
    "Trail",
    "Trail Head",
    "East Hall",
    "Forest",
    "Eastern Fork",
    "Kitchen",
    "Western Road",
    "Gallery",
    "Dungeon",
    "Engine Room",
    "Warlock's Tower",
    "Control Room",
    "Cell",
    "Dusty Trail",
    "Outside of Shack",
    "Secret Passage",
    "South Hall",
    "Bedroom",
    "Jewel Room",
    "Tower",
    "Meadow",
    "Guarded Door",
    "Courtyard",
    "Swamp",
    "South Gate",
    "Hall of Mirrors Two",
    "Long Road",
    "Hall of Mirrors Three",
    "Sacrificial Altar",
    "Hall of Mirrors One",
    "Loop",
    "Landing",
    "Pebbled Path",
    "Beach",
    "Deserted Village",
    "Lonely Mountain",
    "Junction",
    "Temple",
    "Village Outskirts",
    "Outside Gate",
    "Inside Gate",
    "Fork",
    "Map Room",
    "West Hall",
    "Mountain Trail",
    "Hall of Mirrors Four",
    "Closet",
    "Banquet Hall",
    "Shady Brook",
    "Winding Stair",
    "Inside Shack",
    "Library",
] # rooms

