# Config for HITCHHIKERSGUIDE, in LLM style
#
#

[game]
path = "./infocom/hitchhikersguide/COMPILED/hitchhikersguide.z3"

setup = '''
hitchhikersguide is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "toward", "to" ],
    [ "with", "using" ],
    [ "thru", "through" ],
    [ "on", "onto" ],
    [ "outside", "out" ],
    [ "in", "inside", "into" ],
    [ "below", "under", "underneath", "beneath" ],
    [ "along", "around" ],
    [ "before", "next", "near", "against" ],
    [ "both", "all" ],
    [ "bombed", "drunk", "plaste", "smashe" ],
    [ "north", "n", "forewa", "fore", "f" ],
    [ "south", "aft", "s" ],
    [ "e", "east", "starbo", "sb" ],
    [ "w", "p", "port", "west" ],
    [ "down", "d" ],
    [ "u", "up" ],
    [ "nw", "northwest" ],
    [ "ne", "northe" ],
    [ "sw", "southwest" ],
    [ "se", "southe" ],
    [ "superbrief", "super" ],
    [ "i", "im" ],
    [ "q", "quit" ],
    [ "again", "g" ],
    [ "reply", "answer" ],
    [ "clap", "cheer", "applau" ],
    [ "query", "ask", "consul" ],
    [ "slap", "hit", "strike", "attack", "punch", "murder", "assault", "fight", "kill" ],
    [ "stop", "block" ],
    [ "board", "embark" ],
    [ "brush" ],
    [ "order", "buy", "purchase" ],
    [ "inscri", "carve", "scratc", "write" ],
    [ "scale", "climb" ],
    [ "shut", "close" ],
    [ "cut", "slice" ],
    [ "break", "demoli", "smash", "crack", "damage", "destro", "wreck" ],
    [ "debark", "disembark" ],
    [ "snooze", "nap", "doze" ],
    [ "swill", "drink", "swallow", "sip", "quaff", "imbibe", "guzzle" ],
    [ "eat", "devour", "gobble", "ingest" ],
    [ "exit", "withdr", "depart" ],
    [ "escape", "flee" ],
    [ "observe", "describe", "study", "scour", "inspect", "examine", "see" ],
    [ "seek", "find" ],
    [ "pursue", "chase", "follow" ],
    [ "frippi", "lyshus", "wimbgu", "thou", "venchi", "bleem", "misera", "gashee", "morpho" ],
    [ "donate", "hand", "give", "sell", "offer" ],
    [ "hello", "hi" ],
    [ "help", "hint", "hints" ],
    [ "hitchh", "hitch" ],
    [ "idiot" ],
    [ "jump", "dive", "leap" ],
    [ "peek", "kneel", "crawl" ],
    [ "knock", "rap" ],
    [ "lie", "reclin" ],
    [ "look", "stare", "l", "gaze" ],
    [ "pull", "move" ],
    [ "draw", "open", "part" ],
    [ "call", "phone" ],
    [ "plant", "bury" ],
    [ "point", "steer" ],
    [ "spill", "pour", "sprink" ],
    [ "protest", "argue" ],
    [ "press", "push" ],
    [ "lay", "insert", "place", "stuff", "put" ],
    [ "raise", "lift" ],
    [ "read", "skim" ],
    [ "doff", "shed", "remove" ],
    [ "fix", "repair", "unjam" ],
    [ "talk", "say", "speak" ],
    [ "frisk", "rummag", "search" ],
    [ "shoot", "blast", "fire" ],
    [ "sit", "rest", "squat" ],
    [ "skip", "hop" ],
    [ "whiff", "smell", "sniff" ],
    [ "spin", "rotate", "whirl" ],
    [ "rise", "stand" ],
    [ "start", "activa" ],
    [ "turn", "switch", "flip", "toggle", "flick" ],
    [ "hold", "catch", "take", "carry", "get", "grab" ],
    [ "lick", "taste" ],
    [ "thank", "thanks" ],
    [ "toss", "hurl", "throw" ],
    [ "attach", "secure", "tie", "fasten" ],
    [ "feel", "pet", "rub", "pat", "touch" ],
    [ "unplug", "discon" ],
    [ "unfast", "free", "unatta", "untie", "unknot" ],
    [ "wait", "z", "stay" ],
    [ "wake", "rouse", "awake" ],
    [ "step", "procee", "go", "walk", "run" ],
    [ "tidy", "wash", "clean" ],
    [ "don", "wear" ],
    [ "whats", "what" ],
    [ "where", "wheres" ],
    [ "who", "whos" ],
    [ "drape", "wrap" ],
    [ "howl", "scream", "shout", "yell" ],
    [ "okay", "sure", "y", "yes", "ok" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "invent" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "addres" ],
    [ "apprec" ],
    [ "approa" ],
    [ "bite" ],
    [ "connect" ],
    [ "cover" ],
    [ "count" ],
    [ "dangle" ],
    [ "descen" ],
    [ "dig" ],
    [ "disrobe" ],
    [ "drop" ],
    [ "enjoy" ],
    [ "enter" ],
    [ "extinguish" ],
    [ "feed" ],
    [ "fill" ],
    [ "footnote" ],
    [ "hang" ],
    [ "hear" ],
    [ "hide" ],
    [ "kick" ],
    [ "kiss" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "my" ],
    [ "no" ],
    [ "panic" ],
    [ "pay" ],
    [ "pick" ],
    [ "plug" ],
    [ "rape" ],
    [ "refuse" ],
    [ "relax" ],
    [ "replace" ],
    [ "shake" ],
    [ "show" ],
    [ "sleep" ],
    [ "slide" ],
    [ "smile" ],
    [ "tell" ],
    [ "type" ],
    [ "unlock" ],
    [ "water" ],
    [ "wave" ],
    [ "why" ],
] # verbs

nouns = [
    [ "your home", "home" ],
    [ "it", "house" ],
    [ "pile of rubble", "pile", "debris", "rubble" ],
    [ "splitting headache", "hangov", "throbb", "headac" ],
    [ "telephone", "receiv", "teleph", "phone" ],
    [ "door" ],
    [ "bed" ],
    [ "handke", "coins", "coin", "book", "it" ],
    [ "shade", "curtai", "your curtains", "shades" ],
    [ "loop", "robe", "pocket", "gown", "your gown" ],
    [ "sleeve" ],
    [ "gift", "thing", "thing your aunt gave you which you don't know what it is" ],
    [ "fluff", "pocket fluff", "lint" ],
    [ "buffered analgesic", "aspiri", "pill", "analge", "tablet" ],
    [ "basin", "washba", "sink", "it" ],
    [ "wallpa", "paper", "it", "carpet", "chair" ],
    [ "loose pile of junk mail", "mail", "letter", "order", "pile" ],
    [ "bed", "roses", "rose", "rosebe", "it" ],
    [ "bulldozer driver", "driver" ],
    [ "dozer", "bulldo", "bulldozer" ],
    [ "Mr. Prosser", "crew", "prosse", "forema" ],
    [ "watche", "watch", "digital watch" ],
    [ "time" ],
    [ "prefec", "Ford Prefect", "ford" ],
    [ "satchel", "satche" ],
    [ "fluff", "satchel fluff", "lint" ],
    [ "towel", "towels" ],
    [ "dog", "mongre" ],
    [ "Pub", "pub", "groom" ],
    [ "counte", "bar" ],
    [ "shelve", "items", "shelf of items", "shelf" ],
    [ "songs", "song", "music" ],
    [ "box", "jukebox", "jukebo" ],
    [ "glasse", "beerma", "it", "bottle", "glass" ],
    [ "barten", "barman" ],
    [ "bitter", "lots", "lots of beer", "beer", "pint" ],
    [ "nut", "packet", "peanuts", "nuts", "peanut" ],
    [ "sandwi", "plate", "cheese sandwich" ],
    [ "spaces", "ship", "ships", "fleet", "fleet of Vogon Constructor ships" ],
    [ "Arthur Dent", "arthur", "dent" ],
    [ "number", "intnum" ],
    [ "pseudo" ],
    [ "him", "her", "it", "them" ],
    [ "it" ],
    [ "lights", "lamp", "light" ],
    [ "snooze", "nap", "sleep" ],
    [ "speech" ],
    [ "floor", "ground", "mud" ],
    [ "wall", "walls" ],
    [ "ceilin", "ceiling", "roof" ],
    [ "window" ],
    [ "gangwa", "stair", "stairw", "stairs" ],
    [ "air" ],
    [ "sky" ],
    [ "sun", "system", "sol", "star" ],
    [ "your hand", "hands", "hand" ],
    [ "teeth", "your teeth" ],
    [ "head", "your head", "face" ],
    [ "your eyes", "eye", "eyes" ],
    [ "ear", "ears", "your ears" ],
    [ "protag", "it" ],
    [ "yourself", "self", "i", "me", "myself" ],
    [ "place", "chamber", "hall", "room" ],
    [ "object", "object of the game", "goal", "game" ],
    [ "the controls", "panel", "consol", "contro" ],
    [ "conversation", "conver" ],
    [ "one", "one of the guards", "guards", "guard" ],
    [ "proble", "problem", "frustr", "puzzle" ],
    [ "dark", "darkness", "darkne", "nothin" ],
    [ "shadow" ],
    [ "liquid" ],
    [ "light" ],
    [ "drive", "star drive", "hum" ],
    [ "toothbrush", "toothb", "brush", "tool", "tools" ],
    [ "screwd", "tool", "tools", "flathead screwdriver" ],
    [ "wrench", "laser-assisted monkey wrench", "tool", "tools" ],
    [ "tool", "tools", "thermo-fusion chisel", "chisel" ],
    [ "tool", "tools", "ultra-plasmic vacuum awl", "awl" ],
    [ "pair of hypersonic pliers", "tool", "pliers", "tools", "pair" ],
    [ "tool", "pair of tweezers", "tweeze", "tools", "pair" ],
    [ "pincer", "tool", "tools", "molecular hyperwave pincer" ],
    [ "rasp", "tools", "tool", "ionic diffusion rasp" ],
    [ "chippe", "tool", "tools", "number twelve asteroid paint chipper" ],
    [ "tea", "cup" ],
    [ "tea", "no tea" ],
    [ "device", "thumb", "senso", "electronic Sub-Etha signaling device" ],
    [ "button", "red button" ],
    [ "button", "green button" ],
    [ "plaque", "guaran", "warran", "guarantee" ],
    [ "engine", "Engineer robot", "robot" ],
    [ "bike", "cycle" ],
    [ "guide", "copy", "The Hitchhiker's Guide" ],
    [ "spaces", "ship", "gold", "heart", "the Heart of Gold" ],
    [ "screening door", "door" ],
    [ "marv", "androi", "Marvin", "marvin", "robot" ],
    [ "flower", "pot", "flowerpot", "soil", "dirt" ],
    [ "stem", "sprout", "plant", "stalk" ],
    [ "fruit" ],
    [ "machin", "Nutrimat", "nutrim", "panel" ],
    [ "touch-sensitive pad", "pad" ],
    [ "slot" ],
    [ "letter", "messag", "circuit board", "board", "microc" ],
    [ "dipswitch", "switch", "dipswi" ],
    [ "cupful", "cup", "ats", "substi", "Advanced Tea Substitute" ],
    [ "shipping carton", "carton", "box" ],
    [ "strange gun", "weapon", "gun" ],
    [ "ed", "eddie", "comput", "Eddie (the shipboard computer)" ],
    [ "recept", "large receptacle" ],
    [ "phil", "Phil" ],
    [ "beeble", "Zaphod Beeblebrox", "zaphod", "presid" ],
    [ "tricia", "trilli", "woman", "Trillian", "mcmill" ],
    [ "bag", "purse", "handba", "handbag" ],
    [ "brochure", "sales brochure" ],
    [ "drive", "genera", "main Improbability Drive" ],
    [ "drive", "spare Improbability Drive", "genera" ],
    [ "plug", "large plug", "cord" ],
    [ "plug", "cord", "small plug" ],
    [ "generator switch", "switch" ],
    [ "atomic vector plotter", "plotte" ],
    [ "recept", "small receptacle" ],
    [ "bit", "long, dangly bit" ],
    [ "hatchw", "hatch" ],
    [ "mechan", "mechanism" ],
    [ "courty", "lair", "yard" ],
    [ "list", "monume", "rememb", "memori", "sandstone memorial" ],
    [ "sharp stone", "rocks", "stones", "stone", "rock" ],
    [ "beast", "Ravenous Bugblatter Beast of Traal", "traal" ],
    [ "name" ],
    [ "fred", "buddha", "other name", "aunt", "name" ],
    [ "your name", "name" ],
    [ "Beast's name", "name" ],
    [ "skeleton", "beasth", "bone", "bones" ],
    [ "interf", "Nutrimat/Computer Interface" ],
    [ "spaces", "ship", "battle fleet", "ships", "fleet" ],
    [ "dome", "window", "domed canopy", "canopy" ],
    [ "creatu", "Vl'Hurg leader", "leader" ],
    [ "creatu", "G'Gugvunt leader", "leader" ],
    [ "planet", "other planets" ],
    [ "earth", "planet", "third planet" ],
    [ "brain" ],
    [ "gap", "synapse", "synaps" ],
    [ "partic", "letter", "markin", "sense", "particle" ],
    [ "apartment", "apartm" ],
    [ "glass of white wine", "wine", "glass" ],
    [ "snacks", "plate", "plate of hors d'oeuvres", "appeti" ],
    [ "hostess" ],
    [ "fluff", "jacket fluff", "lint" ],
    [ "cage", "drape", "snorin", "it", "birdca" ],
    [ "Damogran", "damogr" ],
    [ "speedb", "boat", "speedboat" ],
    [ "cushion", "seat", "pilot seat", "chair" ],
    [ "key", "small key" ],
    [ "fluff", "seat cushion fluff", "lint" ],
    [ "tool box", "box", "toolbo", "lock" ],
    [ "magnifying glass", "glass" ],
    [ "autopilot button", "autopi", "pilot", "button" ],
    [ "channel", "openin", "narrow channel" ],
    [ "spire", "rock", "rocky spire", "rocks" ],
    [ "cliffs", "france", "towering cliffs", "cliff", "island" ],
    [ "platfo", "Dais", "dais" ],
    [ "banner" ],
    [ "weapon", "blaster", "blaste" ],
    [ "pile", "weapon", "photon rifle", "rifle", "rifles" ],
    [ "stomac", "innard", "whale", "innard of a whale" ],
    [ "Santraginean Mineral Water", "water", "bottle" ],
    [ "underw", "mattre", "cups", "cup", "it" ],
    [ "machin", "slot", "dispen", "babel fish dispenser" ],
    [ "dispenser button", "button" ],
    [ "small hole", "hole" ],
    [ "hook", "metal hook" ],
    [ "grating", "grate", "drain" ],
    [ "panel", "tiny robot panel" ],
    [ "fish", "babel fish" ],
    [ "lid", "case", "glass case", "glass" ],
    [ "keyboa", "keyboard" ],
    [ "switch" ],
    [ "chairs", "seat", "poetry appreciation chair", "chair" ],
    [ "captain", "Vogon Captain", "vogons" ],
    [ "poem", "sample", "Vogon poetry", "verse", "poetry" ],
    [ "door", "corridor door" ],
    [ "door", "inner door" ],
    [ "outer door", "door" ],
    [ "airlock", "airloc" ],
    [ "equati", "number", "pencil", "it" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Beast's Outer Lair",
    "Living Room",
    "War Chamber",
    "Bedroom",
    "Presidential Speedboat",
    "Front Porch",
    "Vogon Hold",
    "Airlock",
    "Marvin's Pantry",
    "Maze",
    "Hatchway",
    "Dais",
    "Kitchen",
    "Entry Bay Number Two",
    "Inner Lair",
    "Front of House",
    "Country Lane",
    "Corridor, Aft End",
    "Corridor, Fore End",
    "Access Space",
    "Back of House",
    "Inside the Sperm Whale",
    "Bridge",
    "Captain's Quarters",
    "Pub",
    "Dark",
    "Galley",
    "Dining Room",
    "Lair",
    "Ramp",
    "Engine Room",
] # rooms

