# Config for HOLLYWOODHIJINX, in LLM style
#
#

[game]
path = "./infocom/hollywoodhijinx/COMPILED/anthill.z3"

setup = '''
hollywoodhijinx is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "all", "everything", "both" ],
    [ "n", "north" ],
    [ "s", "south" ],
    [ "east", "e" ],
    [ "west", "w" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "ne", "northe" ],
    [ "nw", "northw" ],
    [ "southe", "se" ],
    [ "sw", "southw" ],
    [ "super", "superbrief" ],
    [ "inventory", "i" ],
    [ "q", "quit" ],
    [ "time", "t" ],
    [ "g", "again" ],
    [ "respond", "answer", "reply" ],
    [ "query", "ask", "interrogate", "question", "quiz" ],
    [ "embark", "board" ],
    [ "destroy", "crack", "trash", "erase", "smash", "damage", "demolish", "wreck", "break" ],
    [ "call", "phone", "dial" ],
    [ "sweep", "clean" ],
    [ "scale", "climb" ],
    [ "shut", "slam", "close" ],
    [ "tally", "count" ],
    [ "traverse", "cross" ],
    [ "clip", "slash", "cut" ],
    [ "excavate", "dig" ],
    [ "disembark", "debark" ],
    [ "drink", "guzzle", "sip" ],
    [ "dump", "drop" ],
    [ "eat", "devour", "swallow", "consume", "nibble", "gobble" ],
    [ "enter" ],
    [ "withdraw", "scram", "depart", "exit" ],
    [ "examine" ],
    [ "quench", "extinguish", "douse", "snuff" ],
    [ "seek", "find" ],
    [ "pursue", "follow", "chase" ],
    [ "deliver", "donate", "offer", "give", "bestow", "hand", "present" ],
    [ "farewell", "goodbye", "hello", "bye", "greet", "hi", "greetings", "afternoon", "salute" ],
    [ "aid", "rescue", "help" ],
    [ "hide", "conceal" ],
    [ "hints", "hint" ],
    [ "leap", "jump", "dive" ],
    [ "hurt", "slay", "wound", "stab", "slap", "whack", "kill", "murder", "attack", "hit", "assault", "fight", "injure", "strike", "punch" ],
    [ "smooch", "kiss" ],
    [ "rap", "pound", "knock" ],
    [ "lie", "recline" ],
    [ "light", "ignite" ],
    [ "l", "gaze", "peek", "look", "stare", "peer" ],
    [ "roll", "shift", "move" ],
    [ "unseal", "open", "pry" ],
    [ "poke", "jab", "blind" ],
    [ "spill", "pour", "drip", "sprinkle" ],
    [ "tug", "shove", "drag", "yank", "pull" ],
    [ "ring", "thrust", "nudge", "press", "push" ],
    [ "place", "thread", "lay", "stash", "dip", "stuff", "put", "force", "wedge", "insert", "load" ],
    [ "lift", "elevate", "raise", "hoist" ],
    [ "defile", "molest", "rape" ],
    [ "skim", "read" ],
    [ "shed", "remove", "doff" ],
    [ "utter", "speak", "say", "talk" ],
    [ "rummage", "ransack", "search", "frisk" ],
    [ "jostle", "rattle", "shake" ],
    [ "fire", "shoot" ],
    [ "squat", "sit" ],
    [ "snooze", "sleep", "rest", "nap" ],
    [ "smell", "sniff" ],
    [ "squash", "squeeze", "crush" ],
    [ "stand", "rise" ],
    [ "bathe", "swim" ],
    [ "hold", "get", "snatch", "confiscate", "carry", "steal", "seize", "catch", "grab", "take" ],
    [ "fling", "chuck", "hurl", "pitch", "throw", "toss" ],
    [ "hook", "secure", "tie", "attach", "fasten" ],
    [ "touch", "pat", "rub", "feel", "disturb", "pet" ],
    [ "turn", "rotate", "spin", "whirl", "twist", "flip", "set", "face" ],
    [ "unfasten", "unattach", "unhook", "free", "detach", "undo", "untie" ],
    [ "exploit", "use", "employ" ],
    [ "wait", "loiter", "z" ],
    [ "awake", "rouse", "startle", "surprise", "wake", "awaken" ],
    [ "run", "crawl", "step", "walk", "hike", "skip", "tramp", "hop", "advanc", "proceed", "trudge" ],
    [ "wave", "smile", "nod", "grin", "laugh", "sneer" ],
    [ "wear", "don" ],
    [ "howl", "scream", "yell", "shout" ],
    [ "okay", "y", "naw", "positi", "no", "yes", "nay", "negative", "aye", "yup", "nope", "affirm", "ok", "sure" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "ascend" ],
    [ "back" ],
    [ "bite" ],
    [ "blow" ],
    [ "burn" ],
    [ "buy" ],
    [ "compar" ],
    [ "cover" ],
    [ "descend" ],
    [ "empty" ],
    [ "fill" ],
    [ "flush" ],
    [ "fly" ],
    [ "focus" ],
    [ "go" ],
    [ "hang" ],
    [ "hear" ],
    [ "kick" ],
    [ "leave" ],
    [ "let" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "pick" ],
    [ "play" ],
    [ "pray" ],
    [ "reach" ],
    [ "release" ],
    [ "replace" ],
    [ "reset" ],
    [ "ride" ],
    [ "scrape" ],
    [ "show" ],
    [ "ski" ],
    [ "splice" ],
    [ "stop" ],
    [ "swing" ],
    [ "taste" ],
    [ "tell" ],
    [ "unlock" ],
    [ "unroll" ],
    [ "water" ],
] # verbs

nouns = [
    [ "matchbox", "box" ],
    [ "wax", "coating", "wax coating" ],
    [ "red match", "match", "matches" ],
    [ "green match", "match", "matches" ],
    [ "water" ],
    [ "ocean", "water", "sea", "pool" ],
    [ "sawhorse" ],
    [ "hatch" ],
    [ "chain", "long, greasy chain" ],
    [ "left end of the plank", "plank", "end", "board" ],
    [ "plank", "right end of the plank", "end", "board" ],
    [ "heavy wooden plank" ],
    [ "pipe" ],
    [ "safe", "dial" ],
    [ "plaque" ],
    [ "rope" ],
    [ "peg", "sawed-off peg" ],
    [ "chute" ],
    [ "closet" ],
    [ "pegs", "set of coat pegs" ],
    [ "peg", "third coat peg" ],
    [ "peg", "second coat peg" ],
    [ "peg", "first coat peg" ],
    [ "peg", "chipped peg" ],
    [ "paper", "note" ],
    [ "rusty bucket", "handle", "pail", "bucket" ],
    [ "closet door", "door" ],
    [ "trunk", "dusty trunk" ],
    [ "fire hydrant", "hydrant" ],
    [ "panel", "ladder" ],
    [ "aunt", "Aunt Hildegarde", "burban", "hildeg" ],
    [ "herman", "Cousin Herman", "beaumont" ],
    [ "hairy club", "club" ],
    [ "stick", "big stick" ],
    [ "gun" ],
    [ "mop", "glowing mop" ],
    [ "mailbag", "boomerang mail bag", "bag" ],
    [ "clippers", "giant nail clippers" ],
    [ "salivating hedge shears", "shears" ],
    [ "elvish sword of great antiquity", "sword" ],
    [ "saw", "buzz saw", "belt", "blade" ],
    [ "letter", "Aunt Hildegarde's letter" ],
    [ "uncle", "photo of Uncle Buddy", "photo", "buddy" ],
    [ "statue", "palace", "statue of Buck Palace, the fighting letter carrier", "carrier", "buck" ],
    [ "torch", "light", "lamp", "flashlight" ],
    [ "staircase", "stairs", "steps" ],
    [ "roger", "newel", "corman", "head", "newel in the shape of Roger Corman's head" ],
    [ "display", "lights", "display lights" ],
    [ "computer", "slot" ],
    [ "reset button", "button" ],
    [ "card", "business card" ],
    [ "hopper" ],
    [ "piece", "toupee", "Uncle Buddy's toupee", "rug", "hair" ],
    [ "indigo punch card", "card", "cards" ],
    [ "yellow punch card", "card", "cards" ],
    [ "card", "green punch card", "cards" ],
    [ "card", "cards", "red punch card" ],
    [ "blue punch card", "card", "cards" ],
    [ "card", "orange punch card", "cards" ],
    [ "card", "violet punch card", "cards" ],
    [ "rug", "carpet", "Persian rug" ],
    [ "mantle" ],
    [ "candle", "statue", "blue wax statuette", "wick" ],
    [ "candle", "statue", "white wax statuette", "wick" ],
    [ "candle", "statue", "wick", "red wax statuette" ],
    [ "feet", "pair of red wax feet", "candle" ],
    [ "feet", "pair of white wax feet", "candle" ],
    [ "pair of blue wax feet", "feet", "candle" ],
    [ "red candle wax", "wax" ],
    [ "wax", "white candle wax" ],
    [ "wax", "blue candle wax" ],
    [ "portrait of Aunt Hildegarde and Uncle Buddy", "portrait", "picture", "painting" ],
    [ "wall safe", "safe", "dial" ],
    [ "shredder", "Mama Maggio's cheese grater", "grater" ],
    [ "mortar", "fireplace" ],
    [ "hole", "hold" ],
    [ "brick" ],
    [ "penguin", "bird", "stuffed penguin" ],
    [ "catcher's mask", "mask" ],
    [ "chimney", "brick chimney" ],
    [ "yellowed piece of paper", "paper", "map" ],
    [ "thin piece of paper", "paper", "map" ],
    [ "table" ],
    [ "number", "intnum" ],
    [ "pseudo" ],
    [ "it", "that" ],
    [ "lights", "light" ],
    [ "ground", "floor" ],
    [ "hole" ],
    [ "walls", "wall" ],
    [ "ceiling" ],
    [ "your hand", "hands", "hand" ],
    [ "your feet", "foot", "feet" ],
    [ "player", "yourself" ],
    [ "me", "i", "yourself", "myself" ],
    [ "place", "area", "room" ],
    [ "she", "her" ],
    [ "he", "him" ],
    [ "them", "they" ],
    [ "direction" ],
    [ "window", "glass" ],
    [ "scale model of downtown Tokyo", "tokyo", "model", "downto", "city" ],
    [ "monument" ],
    [ "ring", "Big Diamond Ring" ],
    [ "chihuahua", "Atomic Chihuahua", "monster", "dog" ],
    [ "button", "red button" ],
    [ "button", "white button" ],
    [ "green button", "button" ],
    [ "button", "blue button" ],
    [ "button", "black button" ],
    [ "maze", "labyrintyh", "hedge maze" ],
    [ "Buck Palace's large rubber stamp", "stamp" ],
    [ "shovel", "spade" ],
    [ "Aunt Hildegarde's house", "hildebud", "house" ],
    [ "bazooka" ],
    [ "door", "patio door" ],
    [ "Aunt Hildegarde's garden", "garden" ],
    [ "stone wall", "wall" ],
    [ "orchid", "orchids" ],
    [ "small pond", "pond" ],
    [ "ladder" ],
    [ "pair of metal hooks", "hook", "hooks" ],
    [ "cannon ball", "ball" ],
    [ "pile", "balls", "ball", "pile of cannon balls" ],
    [ "fuse" ],
    [ "cannon", "wheel" ],
    [ "small compartment", "compar" ],
    [ "doorbell", "bell", "chime", "buzzer" ],
    [ "Buck Palace-endorsed, regulation mailbox", "mailbox", "box" ],
    [ "oak door", "door" ],
    [ "pair of skis", "skis" ],
    [ "gap" ],
    [ "fire", "pit", "small, smoldering fire" ],
    [ "sand" ],
    [ "strip of film", "strip", "film" ],
    [ "transparency", "slide" ],
    [ "film projector", "projec" ],
    [ "slide projector", "projec" ],
    [ "pieces", "image", "bits", "words" ],
    [ "viewing screen", "screen" ],
    [ "cap", "cover", "lens cap" ],
    [ "film projector lens", "lens" ],
    [ "slide projector lens", "lens" ],
    [ "door", "crawl space door" ],
    [ "meter", "parking meter" ],
    [ "pillar", "dirty pillar" ],
    [ "pillar", "dusty pillar" ],
    [ "piano", "lid" ],
    [ "niche" ],
    [ "that" ],
    [ "knuel" ],
    [ "suit of armor", "armor", "suit" ],
    [ "white cellar door", "door" ],
    [ "cellar ramp", "ramp" ],
    [ "door", "upstairs closet door" ],
    [ "chandelier bowl", "bowl" ],
    [ "ball", "eight ball" ],
    [ "table", "pool table" ],
    [ "ball pocket", "pocket" ],
    [ "return", "ball return" ],
    [ "cue ball", "ball" ],
    [ "balls", "racked balls" ],
    [ "rack" ],
    [ "pool cue", "cue", "stick" ],
    [ "cloth sack", "sack", "bag", "top" ],
    [ "Room" ],
    [ "window" ],
    [ "handle", "brass handles" ],
    [ "Jack Valenti bath mat", "mat" ],
    [ "line", "copy of The Status Line", "paper", "times", "newsletter" ],
    [ "telephone", "phone", "receiver" ],
    [ "seat", "toilet", "john", "pot" ],
    [ "seat", "chair", "seats", "chairs" ],
    [ "bed", "bunk", "bunks" ],
    [ "couch", "sofa" ],
    [ "corpse", "line", "film", "movie" ],
    [ "zzzp" ],
    [ "tank", "tanks" ],
    [ "plane", "airplane", "planes" ],
    [ "finch", "pieces", "bird" ],
] # nouns

rooms = [
    "Northeast Junction",
    "Middle of Beach Stairs",
    "Grotto, Underwater",
    "Southwest Junction",
    "Top of Closet",
    "Tunnel",
    "Pantry",
    "Underwater Passage",
    "Small Passage",
    "Closet",
    "Guest Room",
    "Foyer",
    "Underwater",
    "Upstairs Hall",
    "Master Bedroom",
    "Prop Vault",
    "Men's Room",
    "Surface of Pool",
    "Entrance to Hedge Maze",
    "Northwest Junction",
    "Inlet",
    "Bedroom",
    "East End of Roof",
    "Game Room",
    "In the Chimney",
    "Beach",
    "Upstairs Hall, East",
    "Attic",
    "Kitchen",
    "Ladies' Room",
    "Upstairs Hall, Middle",
    "Grotto",
    "Living Room",
    "Cellar",
    "Work Room",
    "Hedge Maze",
    "West End of Roof",
    "Hallway",
    "Surface of Grotto Pool",
    "Front Porch",
    "Fireplace",
    "Short Hall",
    "Ledge",
    "Cannon Emplacement",
    "Upstairs Hall, West",
    "Dining Room",
    "Patio",
    "Southeast Junction",
    "Top Landing",
    "Screening Room",
    "Bottom Landing",
    "Shaft Bottom",
] # rooms

