# Config for INFIDEL, in LLM style
#
#

[game]
path = "./infocom/infidel/COMPILED/infidel.z3"

setup = '''
infidel is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "on", "onto" ],
    [ "in", "inside", "into" ],
    [ "under", "below", "underneath", "beneath" ],
    [ "n", "north" ],
    [ "s", "south" ],
    [ "e", "east" ],
    [ "w", "west" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "nw", "northwest" ],
    [ "ne", "northe" ],
    [ "southwest", "sw" ],
    [ "se", "southe" ],
    [ "superbrief", "super" ],
    [ "i", "inventory" ],
    [ "q", "quit" ],
    [ "again", "g" ],
    [ "answer", "reply" ],
    [ "injure", "fight", "attack", "hurt" ],
    [ "ignite", "incinerate", "burn" ],
    [ "barf", "chomp", "lose" ],
    [ "polish", "scrub", "clean" ],
    [ "climb" ],
    [ "count" ],
    [ "ford", "cross" ],
    [ "cut", "slice", "pierce" ],
    [ "shit", "hell", "curse", "fuck", "damn" ],
    [ "immerse", "submerge", "dunk", "dip" ],
    [ "sip", "imbibe", "swallow", "drink" ],
    [ "release", "drop" ],
    [ "consume", "chew", "eat", "bite" ],
    [ "what", "describe", "examine", "whats" ],
    [ "cast", "drive", "exorcise", "banish", "begone" ],
    [ "extinguish", "douse" ],
    [ "see", "find", "seek", "where" ],
    [ "follow", "come", "chase", "pursue" ],
    [ "donate", "hand", "feed", "offer", "give" ],
    [ "hello", "hi" ],
    [ "leap", "jump", "dive" ],
    [ "kick" ],
    [ "slay", "kill", "stab", "murder", "dispatch" ],
    [ "rap", "knock" ],
    [ "stare", "l", "look", "gaze" ],
    [ "melt", "liquify" ],
    [ "pull", "tug", "yank" ],
    [ "sigh", "mumble" ],
    [ "chip", "break", "damage", "destroy", "chop", "hit", "smash" ],
    [ "lubricate", "grease" ],
    [ "plug", "glue", "patch", "fix", "repair" ],
    [ "plugh", "xyzzy" ],
    [ "jab", "blind", "poke" ],
    [ "pour", "spill" ],
    [ "press", "push" ],
    [ "wedge", "put", "stuff", "insert", "hide", "place" ],
    [ "raise", "lift" ],
    [ "rape", "molest" ],
    [ "read", "skim" ],
    [ "rub", "pet", "touch", "pat", "feel" ],
    [ "shake", "empty" ],
    [ "skip", "hop" ],
    [ "smell", "sniff" ],
    [ "wade", "bathe", "swim" ],
    [ "thrust", "swing" ],
    [ "get", "take", "remove", "hold", "grab", "carry" ],
    [ "ask", "tell" ],
    [ "talk", "say" ],
    [ "rest", "sleep", "lie" ],
    [ "incant", "chant" ],
    [ "throw", "toss", "chuck", "hurl" ],
    [ "attach", "tie", "secure", "fasten" ],
    [ "set", "turn", "shut", "flip" ],
    [ "unhook", "unfasten", "untie", "free", "unattach" ],
    [ "z", "wait" ],
    [ "awake", "surprise", "startle", "wake" ],
    [ "go", "run", "step", "walk", "proceed" ],
    [ "brandish", "signal", "wave" ],
    [ "winnage", "win" ],
    [ "shout", "yell", "scream" ],
    [ "brief" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "version" ],
    [ "verbose" ],
    [ "apply" ],
    [ "back" ],
    [ "blast" ],
    [ "board" ],
    [ "bug" ],
    [ "clear" ],
    [ "sit" ],
    [ "close" ],
    [ "compare" ],
    [ "deflate" ],
    [ "dig" ],
    [ "disembark" ],
    [ "lean" ],
    [ "taste" ],
    [ "enter" ],
    [ "exit" ],
    [ "fill" ],
    [ "help" ],
    [ "blow" ],
    [ "inflat" ],
    [ "kiss" ],
    [ "launch" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "search" ],
    [ "lower" ],
    [ "make" ],
    [ "move" ],
    [ "roll" ],
    [ "play" ],
    [ "open" ],
    [ "pick" ],
    [ "pray" ],
    [ "pump" ],
    [ "reach" ],
    [ "repent" ],
    [ "script" ],
    [ "unscript" ],
    [ "send" ],
    [ "slide" ],
    [ "smoke" ],
    [ "spin" ],
    [ "spray" ],
    [ "squeeze" ],
    [ "stand" ],
    [ "stay" ],
    [ "strike" ],
    [ "time" ],
    [ "unfold" ],
    [ "fold" ],
    [ "unlock" ],
    [ "wear" ],
    [ "weigh" ],
    [ "wet" ],
    [ "wind" ],
    [ "zork" ],
    [ "is" ],
] # verbs

nouns = [
    [ "timber lintel", "lintel" ],
    [ "ivory", "tiles" ],
    [ "pit", "deep pit" ],
    [ "timber frame", "frame" ],
    [ "rocks" ],
    [ "chip", "plaster dust", "dust", "chips" ],
    [ "slab" ],
    [ "seam", "thin seam" ],
    [ "holes", "fourth hole", "hole" ],
    [ "holes", "third hole", "hole" ],
    [ "holes", "second hole", "hole" ],
    [ "holes", "first hole", "hole" ],
    [ "table", "granite table" ],
    [ "left disc", "disc" ],
    [ "right disc", "disc" ],
    [ "middle disc", "disc" ],
    [ "small niche", "niche", "niches" ],
    [ "plaster", "plaste" ],
    [ "inner door", "door" ],
    [ "burial door", "door" ],
    [ "seals", "seal" ],
    [ "annex door", "door" ],
    [ "statue", "Isis statue" ],
    [ "statue", "Nephthys statue" ],
    [ "statue", "Neith statue" ],
    [ "statue", "Selkis statue" ],
    [ "arms", "arm" ],
    [ "sarcophagus", "coffin", "sarcop" ],
    [ "cover", "quartz", "quartz cover" ],
    [ "recess", "areas", "smaller recess", "area" ],
    [ "recess", "areas", "larger recess", "area" ],
    [ "scarab" ],
    [ "book", "ancient book" ],
    [ "page" ],
    [ "book", "ancient book", "dead" ],
    [ "spatul", "small spatula" ],
    [ "plank", "ladder" ],
    [ "mast hole", "hole" ],
    [ "knothole", "knotho", "hole" ],
    [ "slot" ],
    [ "wedge", "shim" ],
    [ "wooden beam", "mast", "beam" ],
    [ "papyrus scroll", "scroll" ],
    [ "croc", "crocodile", "reptil", "crocs", "crocod" ],
    [ "Nile", "river", "nile" ],
    [ "thicket", "thicke" ],
    [ "pit" ],
    [ "rock", "stone", "blackened rock" ],
    [ "tent" ],
    [ "pyramid", "pyrami" ],
    [ "blackened rocks", "rocks" ],
    [ "block", "opening", "hole", "openin" ],
    [ "army cot", "cot" ],
    [ "cot", "folded cot" ],
    [ "matchbook", "matchb", "matche", "cover" ],
    [ "few matches", "match" ],
    [ "single match", "match" ],
    [ "match" ],
    [ "burned matchbook", "matchb" ],
    [ "matchbook", "matchb", "matche" ],
    [ "coupon", "manual" ],
    [ "wrappe", "burned wrapper", "pack" ],
    [ "foil", "cigarette pack", "pack" ],
    [ "broken lock", "lock", "padloc" ],
    [ "trunk" ],
    [ "padlock", "lock", "padloc" ],
    [ "pickax", "axe", "ax", "pick axe" ],
    [ "stone cube", "cube" ],
    [ "food", "meat", "beef", "piece of dried beef" ],
    [ "ancient map", "map" ],
    [ "shovel" ],
    [ "rope", "coil", "asp" ],
    [ "farewell note", "note" ],
    [ "water", "quantity of water" ],
    [ "canteen", "cantee" ],
    [ "sticke", "inspection sticker" ],
    [ "buffal", "klaatu", "mirage", "fish", "gort" ],
    [ "sand", "quantity of sand" ],
    [ "knapsack", "sack", "knapsa" ],
    [ "packing crate", "label", "crate" ],
    [ "box", "navigation box" ],
    [ "button" ],
    [ "panel", "recessed panel" ],
    [ "cluste", "diamond cluster" ],
    [ "golden cluster", "cluste" ],
    [ "cluste", "ruby cluster" ],
    [ "cluste", "emerald cluster" ],
    [ "opal cluster", "cluste" ],
    [ "patter", "lights", "chips", "quartz" ],
    [ "gems", "jasper", "obsidi", "lazuli", "gem" ],
    [ "carnel", "gems", "feldsp", "tiles", "tile" ],
    [ "statue", "large statue" ],
    [ "head", "broken head" ],
    [ "stone door", "door" ],
    [ "Basie", "basie" ],
    [ "gasoline", "petrol", "gasoli" ],
    [ "machet", "explos", "crowba", "hammer", "such thing" ],
    [ "Dracula", "dracula" ],
    [ "finger" ],
    [ "blessi", "blessings" ],
    [ "number", "intnum" ],
    [ "intdir", "direction" ],
    [ "pseudo" ],
    [ "it", "random object", "that" ],
    [ "sky", "air", "oxygen" ],
    [ "floor", "ground" ],
    [ "crack" ],
    [ "sand", "desert", "ground" ],
    [ "hole" ],
    [ "writing implement", "pencil", "pen" ],
    [ "blocks", "stones" ],
    [ "key" ],
    [ "bulkhe", "bulkhead" ],
    [ "walls", "wall" ],
    [ "ceiling", "ceilin" ],
    [ "empty hands", "hands" ],
    [ "advent", "player", "cretin" ],
    [ "back", "me", "myself", "self", "you" ],
    [ "doorway", "openin" ],
    [ "panels", "panel" ],
    [ "stairway", "ladder", "steps", "stairs" ],
    [ "parachute", "parach", "chute" ],
    [ "airpla", "pilot", "plane", "airplane" ],
    [ "sip of water", "sip" ],
    [ "glyphs", "symbol", "hierog", "hieroglyphs" ],
    [ "painti", "decorations", "pictur", "scroll" ],
    [ "pillars" ],
    [ "wood", "boat", "ship", "barge" ],
    [ "deckin", "deck" ],
    [ "flap", "flaps" ],
    [ "stairc", "steps", "stairs", "steep staircase", "stair" ],
    [ "wide staircase", "steps", "stairs", "stairc", "stair" ],
    [ "winding staircase", "steps", "stairs", "stairc", "stair" ],
    [ "stairs", "steps", "narrow staircase", "stairc", "stair" ],
    [ "steps", "few steps", "stairs" ],
    [ "altar", "stone altar" ],
    [ "torch", "wick", "bronze torch" ],
    [ "pink jar", "jar" ],
    [ "oil", "liquid" ],
    [ "leaf", "glittering leaf" ],
    [ "table", "slab", "granite table" ],
    [ "cup", "golden chalice", "chalic" ],
    [ "cup", "silver chalice", "chalic" ],
    [ "line" ],
    [ "bones", "remain", "skelet", "skeleton", "advent" ],
    [ "digits", "calcified hand", "hand" ],
    [ "jeweled ring", "ring" ],
    [ "needle", "tiny needle" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Narrow Hallway",
    "Temple Chamber",
    "Middle Path",
    "Desert",
    "Silver Alcove",
    "Southwest Hallway",
    "Northern Path",
    "Northwest Hallway",
    "Fore Cabin",
    "Golden Alcove",
    "Silver Room",
    "Northeast Hallway",
    "Barge Chamber",
    "Southern Path",
    "Outside Work Tent",
    "Room of Neith",
    "Cube",
    "On the Steep Stairs",
    "Antechamber",
    "Outside Your Tent",
    "Steep Passageway",
    "Near the Nile",
    "Circular Room",
    "Inner Chamber",
    "Narrow Passageway",
    "Aft Cabin",
    "Room of Nephthys",
    "Below Deck",
    "Room of Isis",
    "Treasury",
    "Supply Tent",
    "Fire Pit",
    "South Landing",
    "Burial Chamber",
    "Top of Stairway",
    "Chamber of Ra",
    "Your Tent",
    "Golden Room",
    "Turning Passage",
    "River Bank",
    "Outside Supply Tent",
    "Southeast Hallway",
    "Work Tent",
    "Annex",
    "Room of Selkis",
    "Bottom of Stairs",
    "Center of Barge",
    "West End of Hold",
] # rooms

