# Config for LEATHERGODDESSES, in LLM style
#
#

[game]
path = "./infocom/leathergoddesses/COMPILED/x1.z3"

setup = '''
leathergoddesses is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "all", "both", "everyt" ],
    [ "n", "north" ],
    [ "south", "s" ],
    [ "e", "east" ],
    [ "west", "w" ],
    [ "down", "d", "downstairs" ],
    [ "u", "upstairs", "up" ],
    [ "nw", "northwest" ],
    [ "northe", "ne" ],
    [ "sw", "southwest" ],
    [ "southe", "se" ],
    [ "superbrief", "super" ],
    [ "invent", "i" ],
    [ "quit", "q" ],
    [ "reply", "guess", "answer" ],
    [ "applaud", "clap" ],
    [ "stab", "attack", "slay", "hit", "slap", "strike", "fight", "kill", "murder" ],
    [ "exchange", "barter", "trade", "bargain", "swap" ],
    [ "bend", "spread" ],
    [ "board", "mount", "ride" ],
    [ "buy", "order", "purchase" ],
    [ "trap", "catch" ],
    [ "cheer", "comfort", "entertain" ],
    [ "scale", "climb" ],
    [ "close", "shut" ],
    [ "come", "ejaculate", "climax", "cum" ],
    [ "cover", "plug" ],
    [ "ford", "cross" ],
    [ "decode", "decipher" ],
    [ "deflate", "pop" ],
    [ "damage", "demoli", "wreck", "destro", "break", "crush", "trample", "smash" ],
    [ "disembark", "dismount", "debark" ],
    [ "swallow", "sip", "drink" ],
    [ "dump", "drop" ],
    [ "gobble", "devour", "ingest", "eat" ],
    [ "examine", "inspect", "watch", "study", "describe", "observe" ],
    [ "exit", "depart", "withdr" ],
    [ "deactivate", "extinguish" ],
    [ "seek", "find" ],
    [ "chase", "pursue", "follow" ],
    [ "hump", "seduce", "bang", "fuck", "screw", "fornicate", "lay" ],
    [ "giddap", "giddyap" ],
    [ "offer", "give", "hand", "sell", "donate" ],
    [ "hi", "hello" ],
    [ "hint", "hints", "help" ],
    [ "jerk", "jack", "beat" ],
    [ "dive", "vault", "jump", "leap" ],
    [ "bow", "kneel" ],
    [ "knock", "rap" ],
    [ "land", "dock", "moor" ],
    [ "cackle", "laugh" ],
    [ "stretch", "limber" ],
    [ "l", "look" ],
    [ "wed", "marry" ],
    [ "pull", "lead", "move" ],
    [ "uh-uh", "no", "nah", "nope" ],
    [ "urinate", "piddle", "pee-pee", "pee", "tinkle", "leak", "piss", "wee-wee", "wee" ],
    [ "shine", "point", "aim" ],
    [ "spill", "pour" ],
    [ "push", "press" ],
    [ "raise", "lift", "boost" ],
    [ "read", "skim", "browse" ],
    [ "remove", "unwrap" ],
    [ "rip", "shred", "tear" ],
    [ "save", "rescue" ],
    [ "boo", "scram", "scat", "shoo" ],
    [ "rummag", "search" ],
    [ "rock", "rock-a-bye", "bounce", "shake" ],
    [ "poo-poo", "defecate", "crap", "shit" ],
    [ "hop", "skip" ],
    [ "nap", "sleep", "doze", "snooze" ],
    [ "cut", "slice" ],
    [ "smell", "sniff", "whiff" ],
    [ "stain", "paint" ],
    [ "stand", "rise" ],
    [ "start", "activa" ],
    [ "place", "stuff", "put", "stick", "insert" ],
    [ "excite", "stimulate" ],
    [ "nurse", "suckle" ],
    [ "carry", "take", "hold", "grab", "get" ],
    [ "speak", "talk" ],
    [ "taste", "nibble" ],
    [ "thanks", "thank" ],
    [ "throw", "toss", "hurl" ],
    [ "fasten", "attach", "secure", "tie", "strap" ],
    [ "scratch", "poke", "pat", "stroke", "pet", "feel", "touch", "fondle" ],
    [ "turn", "dial", "set", "spin", "switch", "rotate", "steer", "flick", "flip" ],
    [ "uncover", "unplug", "unpin", "unblock" ],
    [ "undres", "strip" ],
    [ "unstrap", "unfast", "unatta", "unknot", "untie", "free" ],
    [ "barf", "regurgitate", "vomit", "puke" ],
    [ "z", "wait" ],
    [ "rouse", "wake", "awake" ],
    [ "walk", "procee", "sidle", "run", "step" ],
    [ "wipe", "clean", "wash" ],
    [ "don", "wear" ],
    [ "whats", "what", "who", "whos" ],
    [ "wheres", "where" ],
    [ "snap", "crack", "whip" ],
    [ "yell", "scream", "shout" ],
    [ "yes", "sure", "yup", "ok", "y", "okay" ],
    [ "verbose" ],
    [ "brief" ],
    [ "tame" ],
    [ "suggestive" ],
    [ "lewd" ],
    [ "diagnose" ],
    [ "restar" ],
    [ "restor" ],
    [ "status" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "apply" ],
    [ "approa" ],
    [ "ask" ],
    [ "bite" ],
    [ "blow" ],
    [ "breathe" ],
    [ "burn" ],
    [ "call" ],
    [ "cast" ],
    [ "circle" ],
    [ "click" ],
    [ "copulate" ],
    [ "count" ],
    [ "descen" ],
    [ "dig" ],
    [ "dress" ],
    [ "empty" ],
    [ "enter" ],
    [ "feed" ],
    [ "fill" ],
    [ "flush" ],
    [ "go" ],
    [ "hear" ],
    [ "hide" ],
    [ "hiss" ],
    [ "inflate" ],
    [ "kick" ],
    [ "kiss" ],
    [ "kweepa" ],
    [ "launch" ],
    [ "lean" ],
    [ "leave" ],
    [ "let" ],
    [ "lick" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "love" ],
    [ "lower" ],
    [ "make" ],
    [ "masturbate" ],
    [ "measure" ],
    [ "moan" ],
    [ "open" ],
    [ "pass" ],
    [ "pay" ],
    [ "phone" ],
    [ "pick" ],
    [ "pin" ],
    [ "play" ],
    [ "rake" ],
    [ "rape" ],
    [ "reach" ],
    [ "relieve" ],
    [ "return" ],
    [ "roll" ],
    [ "rub" ],
    [ "say" ],
    [ "score" ],
    [ "show" ],
    [ "sigh" ],
    [ "sink" ],
    [ "sit" ],
    [ "slide" ],
    [ "smear" ],
    [ "suck" ],
    [ "swim" ],
    [ "swing" ],
    [ "tap" ],
    [ "tell" ],
    [ "unlock" ],
    [ "unroll" ],
    [ "use" ],
    [ "wrap" ],
    [ "zzmgck" ],
] # verbs

nouns = [
    [ "cleveland", "Cleveland" ],
    [ "wooden rake", "rake" ],
    [ "canvas sack", "sack", "bag" ],
    [ "pile", "leaves", "whole bunch of leaves", "leaf", "bunch" ],
    [ "piece", "sod" ],
    [ "trellis", "rellis" ],
    [ "bed" ],
    [ "light", "ligh", "headlight" ],
    [ "ford", "auto", "Ford", "car" ],
    [ "joe", "bartender", "Joe" ],
    [ "drink", "mug of beer", "beer", "mug" ],
    [ "pocket" ],
    [ "light", "flashlight" ],
    [ "room", "bathroom", "restroom", "gents' restroom" ],
    [ "ladies' restroom", "room", "bathroom", "restroom" ],
    [ "toilet" ],
    [ "stool", "sool" ],
    [ "dubious slice of pizza", "slice", "pizza" ],
    [ "zzmgck", "it" ],
    [ "it" ],
    [ "direct", "direction" ],
    [ "number" ],
    [ "pseudo" ],
    [ "them", "it" ],
    [ "him", "himself" ],
    [ "herself", "her" ],
    [ "other", "it", "itself" ],
    [ "love" ],
    [ "nap", "sleep", "snooze" ],
    [ "ceilin", "roof", "ceiling" ],
    [ "smell", "odor", "scent", "aroma" ],
    [ "oasis", "water", "pool", "fountain" ],
    [ "hands", "palm", "finger", "your hand", "hand" ],
    [ "head", "your head" ],
    [ "eye", "your eyes", "eyes" ],
    [ "ear", "your ears", "ears" ],
    [ "nostril", "nose", "your nose" ],
    [ "your mouth", "lips", "mouth", "lip" ],
    [ "your kneecaps", "kneecap", "knees", "knee" ],
    [ "penis", "your naughty bits", "balls", "ass", "cock" ],
    [ "cunt", "pussy", "your naughty bits", "vagina" ],
    [ "breast", "bosom", "your naughty bits", "tits", "tit" ],
    [ "protag", "it" ],
    [ "me", "myself", "yourself", "self", "i" ],
    [ "locati", "room", "area", "place" ],
    [ "home", "house" ],
    [ "sign" ],
    [ "stairw", "stairs", "stair", "step" ],
    [ "viewport", "window", "glass" ],
    [ "trees", "tree" ],
    [ "king", "mitre", "King Mitre" ],
    [ "eighty-two degree angle", "angle" ],
    [ "pile", "angles", "pile of angles" ],
    [ "frog", "prince" ],
    [ "engrav", "blender", "mixer", "common household blender" ],
    [ "marsmouse", "mouse" ],
    [ "royal barge", "barge", "control", "gondola", "boat" ],
    [ "huge orange button", "button" ],
    [ "button", "huge purple button" ],
    [ "canal" ],
    [ "pier", "dock" ],
    [ "dune", "sand dunes", "dunes", "sand" ],
    [ "chapst", "stick of lip balm", "gloss", "stick", "balm" ],
    [ "message", "coded message", "code" ],
    [ "spy", "dead alien", "alien", "body" ],
    [ "owner", "proprietor" ],
    [ "exit", "egress" ],
    [ "dust" ],
    [ "tube", "ube" ],
    [ "exit", "circle", "hole", "flexible black circle" ],
    [ "pin", "clothes pin" ],
    [ "minaret", "tower" ],
    [ "riddle" ],
    [ "harem guard", "guard" ],
    [ "secret map", "map" ],
    [ "phoneb", "direct", "book", "Cleveland phone book" ],
    [ "bunny", "rabbit" ],
    [ "bird", "mass", "penguin", "birds", "mass of penguins" ],
    [ "igloo door", "door" ],
    [ "front stoop", "stoop", "doorstep" ],
    [ "pair of cotton balls", "pair", "ball", "balls" ],
    [ "orphanage", "igloo" ],
    [ "cell" ],
    [ "blanket" ],
    [ "picture", "painting", "paining", "cat" ],
    [ "tray", "ray" ],
    [ "wide cell door", "door" ],
    [ "door", "narrow cell door" ],
    [ "scrap of paper", "scrap", "paper" ],
    [ "door", "metal door" ],
    [ "ledge", "shelf" ],
    [ "basket", "baske", "wicker basket" ],
    [ "mothball", "ball", "mothballs", "balls" ],
    [ "cover", "machbook", "matchbook", "book" ],
    [ "couch", "divan" ],
    [ "shapes", "the Leather Goddesses of Phobos", "phobos", "goddesses", "shape" ],
    [ "Super-Duper Anti-Leather Goddesses of Phobos Attack Machine", "device", "machine" ],
    [ "stud", "mount", "stallion", "horse" ],
    [ "sui", "suit", "therma", "white suit" ],
    [ "hatch", "door", "hatchway" ],
    [ "battleship", "ship", "battle", "flagship", "spaceship" ],
    [ "ship", "yacht", "spaceship", "small passenger spaceship" ],
    [ "squid", "tree-", "monster", "bug-eyed monster", "tree" ],
    [ "door" ],
    [ "Venus", "venus" ],
    [ "lettuce", "Venus flytrap", "flytrap" ],
    [ "hole", "tree hole" ],
    [ "sain", "can of black stain", "can", "paint", "stain" ],
    [ "man", "salesman" ],
    [ "compar", "t-remover", "odd machine", "remove", "machine" ],
    [ "door", "back door" ],
    [ "front door", "door" ],
    [ "mad scientist", "scientist" ],
    [ "switch", "huge red power switch" ],
    [ "cage", "bars", "bar" ],
    [ "gorilla", "ape", "male gorilla", "monkey" ],
    [ "female gorilla", "gorilla", "ape", "monkey" ],
    [ "hose", "rubber hose" ],
    [ "first slab", "slab" ],
    [ "second slab", "slab" ],
    [ "body", "your body" ],
    [ "booth" ],
    [ "vizicomm" ],
    [ "handset" ],
    [ "coin return knob", "knob" ],
    [ "box", "coin return box" ],
    [ "marsmid", "money", "coin" ],
    [ "rope", "end", "sheet", "strips" ],
    [ "loincloth", "bikini", "overall", "clothes" ],
    [ "book", "rules" ],
    [ "woman", "man" ],
    [ "ground", "floor" ],
    [ "hole", "circle" ],
    [ "daughter", "angle", "theta", "prince" ],
    [ "machine", "tower", "structure", "glint" ],
    [ "sultan" ],
    [ "husband", "wife" ],
    [ "torch", "orch" ],
    [ "raf", "liferaft", "raft" ],
    [ "robot", "infant", "baby" ],
    [ "hunk", "candy", "food", "chocolate" ],
    [ "tiff", "trent", "body", "tiffan" ],
    [ "tiff", "bits", "tiffan", "trent" ],
    [ "sword", "blade", "swords" ],
    [ "thorbast", "assassin", "figure" ],
    [ "woman", "man", "elysia", "elysium" ],
    [ "picture", "photo", "fairbanks", "harlow" ],
    [ "ointment", "jar", "cream", "lotion" ],
] # nouns

rooms = [
    "Ruined Castle",
    "Dunetop",
    "Abandoned Dock",
    "Allusion Room",
    "At Main Hatch",
    "Space Yacht",
    "Hold",
    "Hickory & Dickory Dock",
    "Catacombs",
    "Among the Dunes",
    "Donald Dock",
    "Edge of Polar Ice Cap",
    "Cleveland",
    "Penguin Park",
    "Cell",
    "Royal Docks",
    "Base of Tower",
    "Boudoir",
    "Icy Dock",
    "Clearing",
    "Front Door",
    "Other Cell",
    "Minaret",
    "End of Hallway",
    "Spawning Ground",
    "Back Door",
    "Forgotten Storehouse",
    "Jungle",
    "Baby Dock",
    "Fork, Of Sorts",
    "Martian Desert",
    "Stable",
    "Looks Can Be Deceiving",
    "Oasis",
    "WARNING!",
] # rooms

