# Config for LURKINGHORROR, in LLM style
#
#

[game]
path = "./infocom/lurkinghorror/COMPILED/h1.z3"

setup = '''
lurkinghorror is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "n", "north" ],
    [ "s", "south" ],
    [ "e", "east" ],
    [ "west", "w" ],
    [ "down", "d" ],
    [ "u", "up" ],
    [ "northeast", "ne" ],
    [ "nw", "northwest" ],
    [ "se", "southeast" ],
    [ "sw", "southwest" ],
    [ "in", "ahead" ],
    [ "both", "everything", "all" ],
    [ "super", "superbrief" ],
    [ "i", "inventory" ],
    [ "quit", "q" ],
    [ "respond", "reply", "answer" ],
    [ "quiz", "ask" ],
    [ "attack", "strike", "fight", "hit" ],
    [ "ride", "board" ],
    [ "burn", "ignite" ],
    [ "climb", "scale" ],
    [ "close", "shut" ],
    [ "slash", "cut", "chop", "slice" ],
    [ "fuck", "damn", "shit" ],
    [ "crack", "wreck", "smash", "destroy", "break", "scratch" ],
    [ "drink", "sip", "swallow" ],
    [ "drop", "dump" ],
    [ "consume", "eat" ],
    [ "taste", "sample" ],
    [ "withdraw", "exit", "depart" ],
    [ "examine", "x" ],
    [ "follow" ],
    [ "give", "offer", "feed" ],
    [ "hello", "greetings", "hi" ],
    [ "help", "hint" ],
    [ "hide", "conceal" ],
    [ "leap", "dive", "jump" ],
    [ "murder", "slay", "kill", "stab" ],
    [ "knock", "rap" ],
    [ "stare", "l", "look", "gaze" ],
    [ "melt", "thaw" ],
    [ "shift", "move", "clear" ],
    [ "tug", "drag", "pull" ],
    [ "plug" ],
    [ "unplug", "unscrew" ],
    [ "fix", "patch", "repair" ],
    [ "point", "gesture" ],
    [ "pour", "empty", "spill" ],
    [ "shove", "push", "press" ],
    [ "put" ],
    [ "erect", "lift", "raise" ],
    [ "remove", "shed" ],
    [ "say", "talk", "call" ],
    [ "rummage", "search" ],
    [ "shake" ],
    [ "sharpen", "hone" ],
    [ "rest", "sit" ],
    [ "skip", "hop" ],
    [ "sleep", "nap" ],
    [ "sniff", "smell" ],
    [ "stand", "rise" ],
    [ "swim", "wade" ],
    [ "swing", "thrust" ],
    [ "hold", "catch", "take", "get", "snatch", "grab", "carry" ],
    [ "thank", "thanks" ],
    [ "pitch", "toss", "throw", "hurl" ],
    [ "loop", "tie", "wrap", "attach", "hook", "fasten", "connect" ],
    [ "t", "time" ],
    [ "pat", "rub", "pet", "touch", "squeeze", "feel" ],
    [ "set", "turn", "power", "flip" ],
    [ "unwrap", "free", "untie", "unfasten", "unattach", "detach", "disconnect", "unhook" ],
    [ "z", "wait" ],
    [ "curdle", "surprise", "scare", "startle" ],
    [ "wake", "awake" ],
    [ "proceed", "steer", "go", "run", "walk", "drive", "step" ],
    [ "wave" ],
    [ "scream", "yell", "shout" ],
    [ "pry", "lever" ],
    [ "okay", "yes", "y" ],
    [ "nope", "no" ],
    [ "buy", "purchase" ],
    [ "admire", "compliment" ],
    [ "click", "select", "choose" ],
    [ "input", "type" ],
    [ "prop", "wedge" ],
    [ "warm", "heat", "cook" ],
    [ "login" ],
    [ "password" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "apply" ],
    [ "bite" ],
    [ "blow" ],
    [ "cover" ],
    [ "descen" ],
    [ "lie" ],
    [ "compare" ],
    [ "cross" ],
    [ "disembark" ],
    [ "release" ],
    [ "enter" ],
    [ "extinguish" ],
    [ "fill" ],
    [ "find" ],
    [ "kick" ],
    [ "kiss" ],
    [ "lean" ],
    [ "leave" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "roll" ],
    [ "pray" ],
    [ "open" ],
    [ "pick" ],
    [ "reach" ],
    [ "read" ],
    [ "shoot" ],
    [ "show" ],
    [ "slide" ],
    [ "start" ],
    [ "tell" ],
    [ "tortur" ],
    [ "stop" ],
    [ "light" ],
    [ "unlock" ],
    [ "approach" ],
    [ "wear" ],
    [ "what" ],
    [ "where" ],
    [ "who" ],
    [ "yawn" ],
    [ "bury" ],
    [ "sell" ],
    [ "trade" ],
    [ "erase" ],
    [ "bargain" ],
    [ "edit" ],
    [ "let" ],
    [ "hang" ],
    [ "die" ],
    [ "hack" ],
] # verbs

nouns = [
    [ "office", "door", "doors" ],
    [ "debris", "pallet", "pile", "junk" ],
    [ "forklift", "lift" ],
    [ "manhole", "ring", "hole" ],
    [ "cover", "disk", "manhole cover", "disc" ],
    [ "slab of granite", "altar", "slab" ],
    [ "symbol", "incised symbol" ],
    [ "graffiti", "creature", "people", "carvings" ],
    [ "knife", "blade" ],
    [ "panel", "hole", "plate", "iron plate", "opening" ],
    [ "metal flask", "flask" ],
    [ "gas", "mist" ],
    [ "nitrogen", "liquid", "cold liquid" ],
    [ "access panel", "panel" ],
    [ "lamp", "light", "flashlight" ],
    [ "open button", "button" ],
    [ "button", "close button" ],
    [ "button", "floor button" ],
    [ "button", "B button" ],
    [ "alarm button", "button" ],
    [ "switch", "stop switch" ],
    [ "elevator" ],
    [ "doors", "door", "elevator doors" ],
    [ "up-arrow", "arrow", "button" ],
    [ "down-arrow", "arrow", "button" ],
    [ "ladder" ],
    [ "hatch" ],
    [ "lock", "padlock" ],
    [ "letters", "graffiti" ],
    [ "crowbar", "bar" ],
    [ "new brick", "brick" ],
    [ "brick", "broken brick" ],
    [ "rod", "reinforcing rod" ],
    [ "hole" ],
    [ "walls", "bricks", "wall", "brick wall" ],
    [ "machine", "tangle of machinery", "tangle" ],
    [ "elevator shaft", "shaft" ],
    [ "protrusion", "hook" ],
    [ "greasy chain", "chain" ],
    [ "valve", "pressure valve" ],
    [ "pipe", "pipes", "steam pipes" ],
    [ "cable", "wire", "coaxial cable", "channel", "wires" ],
    [ "dead rat", "rat" ],
    [ "symbol", "branded symbol" ],
    [ "rats", "sewer rats", "rat" ],
    [ "door", "Alchemy Department door" ],
    [ "glass", "frosted glass window", "window" ],
    [ "sheet", "sign-up sheet" ],
    [ "arch", "archway" ],
    [ "lab", "laboratory" ],
    [ "line", "pentag", "lines", "shape", "pentagram" ],
    [ "plate", "trapdoor", "door", "metal plate" ],
    [ "missing students", "students", "tools" ],
    [ "kids", "missing urchins", "urchin", "children" ],
    [ "pc", "screen", "computer", "Alchemy Department computer", "lovecraft" ],
    [ "brass hyrax", "hyrax", "ring" ],
    [ "man", "prof", "professor", "alchemy" ],
    [ "lab bench", "bench" ],
    [ "vat", "label" ],
    [ "elixir", "liquid", "tarry liquid", "life" ],
    [ "man", "maintenance man" ],
    [ "floor waxer", "machine", "polisher", "waxer" ],
    [ "wall socket", "socket" ],
    [ "plug", "cord", "power cord" ],
    [ "plastic container", "label", "container" ],
    [ "wax", "topping", "liquid", "floor wax" ],
    [ "glass", "window", "cabinet", "sign", "emergency cabinet" ],
    [ "fire axe", "axe", "ax" ],
    [ "rope", "tentacle", "ropy strand", "strand" ],
    [ "catwalk", "railing", "side", "edge" ],
    [ "wooden ladder", "ladder" ],
    [ "pair of electrician's gloves", "glove", "gloves" ],
    [ "door" ],
    [ "plug", "bronze plug" ],
    [ "hole", "cylindrical hole" ],
    [ "note", "piece of paper", "paper" ],
    [ "kids", "children", "urchins", "kid", "urchin" ],
    [ "clothes", "parka", "hat", "shoes" ],
    [ "child", "kid", "urchin", "yourself" ],
    [ "cutter", "bolt cutter" ],
    [ "rope", "wire", "growth", "wires" ],
    [ "slot", "slots", "identations", "burrow" ],
    [ "slime curtain", "curtain", "slime" ],
    [ "crawling slime", "slime" ],
    [ "ancient door", "door", "lock" ],
    [ "whitish mass", "mass" ],
    [ "repeater", "box", "metal box" ],
    [ "cover", "metal cover", "screws" ],
    [ "cabling", "cable", "coaxial cable" ],
    [ "socket", "connect" ],
    [ "cable", "tentacle", "cabling", "appendage", "cablelike appendage" ],
    [ "line", "power line" ],
    [ "pool", "water", "puddle" ],
    [ "thing", "being", "creature" ],
    [ "boots", "pair of rubber boots" ],
    [ "direction" ],
    [ "intnum", "number" ],
    [ "pseudo" ],
    [ "it", "them", "frob", "object" ],
    [ "her", "him" ],
    [ "it" ],
    [ "light", "lights" ],
    [ "ceilin", "roof", "ceiling" ],
    [ "air", "cold" ],
    [ "feet", "your feet", "foot" ],
    [ "your hand", "hand", "hands" ],
    [ "head", "your head", "face" ],
    [ "eye", "eyes", "your eyes" ],
    [ "it", "protag" ],
    [ "myself", "self", "me", "yourself" ],
    [ "basement", "place", "chamber", "room" ],
    [ "wall", "north wall" ],
    [ "east wall", "wall" ],
    [ "west wall", "wall" ],
    [ "south wall", "wall" ],
    [ "wall", "walls" ],
    [ "debris", "dust", "dirt", "rubble" ],
    [ "ground", "field", "floor" ],
    [ "corridor", "passage", "exit", "tunnel" ],
    [ "sleep", "nap" ],
    [ "sound", "noise" ],
    [ "blizzard", "snowstorm", "snow" ],
    [ "doors", "door", "elevator", "elevator doors" ],
    [ "door", "outside door" ],
    [ "roof door", "door" ],
    [ "sign" ],
    [ "dome" ],
    [ "shape", "flier", "thing", "dark shape" ],
    [ "shape", "flier", "creature" ],
    [ "tree", "peach tree" ],
    [ "tub", "earth", "dirt", "tub of dirt" ],
    [ "tattoo", "symbol" ],
    [ "hand", "human hand" ],
    [ "yourself", "hacker" ],
    [ "keychain", "keyring", "ring" ],
    [ "key", "red aluminum Yale key", "keys" ],
    [ "green aluminum Yale key", "key", "keys" ],
    [ "keys", "key", "green brass Yale key" ],
    [ "key", "green aluminum Medeco key", "keys" ],
    [ "master key", "key" ],
    [ "symbol", "cardboard carton", "carton" ],
    [ "food", "Chinese food", "shrimp" ],
    [ "coca-cola", "two liter bottle of Classic Coke", "coke", "cap" ],
    [ "food", "package of Funny Bones", "wrapper", "package", "bones" ],
    [ "oven", "microwave oven" ],
    [ "display", "readout" ],
    [ "timer", "microwave controls", "control", "button" ],
    [ "counter", "kitchen counter" ],
    [ "fridge", "sign", "refrigerator" ],
    [ "assignment" ],
    [ "chair" ],
    [ "socket", "outlet" ],
    [ "HELP key", "help", "key" ],
    [ "mouse" ],
    [ "pc", "screen", "terminal", "computer" ],
    [ "menu box", "paper", "box", "list" ],
    [ "YAK editor", "box", "window", "paper" ],
    [ "box", "more box" ],
    [ "text", "classics paper", "page", "paper" ],
    [ "program", "bug", "problem" ],
    [ "rocks", "platform", "pile" ],
    [ "stone", "smooth stone" ],
    [ "symbol", "carved symbol" ],
    [ "dark", "darkness", "creature", "thing" ],
    [ "zzmgck" ],
    [ "intname" ],
] # nouns

rooms = [
    "Roof of Great Dome",
    "Renovated Cave",
    "Infinite Corridor",
    "Aero Basement",
    "Lab",
    "Computer Center",
    "Chemistry Building",
    "Subbasement",
    "Brown Building",
    "Top of Dome",
    "Basalt Bowl",
    "Ancient Storage",
    "Before the Altar",
    "Second Floor",
    "Dead Storage",
    "Temporary Basement",
    "Engineering Building",
    "Tomb",
    "Temporary Lab",
    "Tunnel Entrance",
    "Fruits and Nuts",
    "Place",
    "Great Court",
    "At Platform",
    "Cinderblock Tunnel",
    "Kitchen",
    "Top Floor",
    "Great Dome",
    "Large Chamber",
    "Aero Lobby",
    "On the Great Dome",
    "Skyscraper Roof",
    "Muddy Tunnel",
    "Department of Alchemy",
    "Elevator",
    "Roof",
    "Inner Lair",
    "Wet Tunnel",
    "Basement",
    "Stairway",
    "Smith Street",
    "Steam Tunnel",
] # rooms