#!/usr/bin/env sh
./syntax.py abyss abyss/*.zil > abyss.toml
./syntax.py amfv amfv/*.zil > amfv.toml
./syntax.py arthur arthur/*.zil > arthur.toml
./syntax.py ballyhoo ballyhoo/*.zil > ballyhoo.toml
./syntax.py beyondzork beyondzork/*.zil > beyondzork.toml
./syntax.py borderzone borderzone/*.zil > borderzone.toml
./syntax.py bureaucracy bureaucracy/*.zil > bureaucracy.toml
./syntax.py checkpoint checkpoint/*.zil > checkpoint.toml
./syntax.py cutthroats cutthroats/*.zil > cutthroats.toml
./syntax.py deadline deadline/*.zil > deadline.toml
./syntax.py enchanter enchanter/*.zil > enchanter.toml
./syntax.py hitchhikersguide hitchhikersguide/*.zil > hitchhikersguide.toml
./syntax.py hollywoodhijinx hollywoodhijinx/*.zil > hollywoodhijinx.toml
./syntax.py infidel infidel/*.zil > infidel.toml
./syntax.py journey journey/*.zil > journey.toml
./syntax.py leathergoddesses leathergoddesses/*.zil > leathergoddesses.toml
./syntax.py lurkinghorror lurkinghorror/*.zil > lurkinghorror.toml
./syntax.py moonmist moonmist/*.zil > moonmist.toml
./syntax.py nordandbert nordandbert/*.zil > nordandbert.toml
./syntax.py planetfall planetfall/*.zil > planetfall.toml
./syntax.py plunderedhearts plunderedhearts/*.zil > plunderedhearts.toml
./syntax.py restaurant restaurant/*.zil > restaurant.toml
./syntax.py seastalker seastalker/*.zil > seastalker.toml
./syntax.py sherlock sherlock/*.zil > sherlock.toml
./syntax.py shogun shogun/*.zil > shogun.toml
./syntax.py sorcerer sorcerer/*.zil > sorcerer.toml
./syntax.py spellbreaker spellbreaker/*.zil > spellbreaker.toml
./syntax.py starcross starcross/*.zil > starcross.toml
./syntax.py stationfall stationfall/*.zil > stationfall.toml
./syntax.py suspect suspect/*.zil > suspect.toml
./syntax.py suspended suspended/*.zil > suspended.toml
./syntax.py trinity trinity/*.zil > trinity.toml
./syntax.py wishbringer wishbringer/*.zil > wishbringer.toml
./syntax.py witness witness/*.zil > witness.toml
./syntax.py zork1 zork1/*.zil > zork1.toml
./syntax.py zork2 zork2/*.zil > zork2.toml
./syntax.py zork3 zork3/*.zil > zork3.toml
./syntax.py zorkzero zorkzero/*.zil > zorkzero.toml
