# Config for MOONMIST, in LLM style
#
#

[game]
path = "./infocom/moonmist/COMPILED/m5.z3"

setup = '''
moonmist is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "into", "in", "inside" ],
    [ "out", "outside" ],
    [ "north", "n" ],
    [ "east", "e" ],
    [ "south", "s" ],
    [ "w", "west" ],
    [ "d", "downstairs", "down" ],
    [ "up", "u" ],
    [ "northwest", "nw" ],
    [ "northeast", "ne" ],
    [ "southwest", "sw" ],
    [ "se", "southeast" ],
    [ "point", "aim" ],
    [ "test", "analyse", "analyze", "check" ],
    [ "respond", "answer", "reply" ],
    [ "arrest", "capture", "accuse" ],
    [ "question", "inquire", "ask", "consult" ],
    [ "molest", "attack", "fight", "assault", "rape", "repel" ],
    [ "curtsy", "bow", "curtsey" ],
    [  ],
    [ "call", "summon" ],
    [ "board", "climb" ],
    [ "close" ],
    [ "compare", "match" ],
    [ "damage", "smash", "break", "crush", "destroy" ],
    [ "drink", "swallow", "sip" ],
    [ "taste", "eat" ],
    [ "empty", "unpack", "drain" ],
    [ "x", "examine", "inspect" ],
    [ "faint", "sleep" ],
    [ "flood", "fill" ],
    [ "find", "discover", "locate", "detect" ],
    [ "repair", "fix", "adjust" ],
    [ "follow", "stalk", "pursue", "chase" ],
    [ "forgive", "pardon", "excuse" ],
    [ "offer", "pass", "give" ],
    [ "hi", "greetings", "greet", "hello" ],
    [ "conceal", "hide" ],
    [ "i", "invent" ],
    [ "leap", "jump" ],
    [ "waste", "murder", "stab", "kill" ],
    [ "hug", "comfort", "flirt", "console", "kiss" ],
    [ "rap", "knock", "bang" ],
    [ "leave", "exit" ],
    [ "l", "see", "peek", "peep", "peer", "look", "stare", "gaze" ],
    [ "nope", "no" ],
    [ "pour", "spill" ],
    [ "tug", "pull" ],
    [ "push", "press", "shove" ],
    [ "place", "set", "insert", "lay", "put" ],
    [ "q", "logoff", "logout", "quit" ],
    [ "read", "skim" ],
    [ "remove", "doff" ],
    [ "restore" ],
    [ "ring" ],
    [ "touch", "feel", "rub" ],
    [ "talk", "gab", "say", "whisper", "speak", "state", "chat" ],
    [ "search", "dig" ],
    [ "rattle", "shake" ],
    [ "shoot", "fire", "spray" ],
    [ "display", "show" ],
    [ "sit" ],
    [ "kick", "punch", "slap", "hit" ],
    [ "smell", "sniff" ],
    [ "grin", "smile", "wink" ],
    [ "sorry", "apologize" ],
    [ "start" ],
    [ "park", "stop" ],
    [ "wade", "swim", "bathe" ],
    [ "seize", "carry", "steal", "take", "grab" ],
    [ "thank", "thanks" ],
    [ "throw" ],
    [ "time" ],
    [ "swing", "turn", "switch", "flip" ],
    [ "undress", "strip", "unmask" ],
    [ "release", "revision", "version" ],
    [ "pause", "relax", "z", "rest", "wait", "meditate", "stay" ],
    [ "surprise", "startle", "awake", "wake" ],
    [ "go", "steer", "drive", "return", "run", "walk", "head", "step", "come", "proceed" ],
    [ "don", "wear" ],
    [ "shout", "scream", "yell" ],
    [ "okay", "yup", "ok", "yes", "y", "indeed", "yep", "yeah", "aye", "sure" ],
    [ "brief" ],
    [ "bring" ],
    [ "clean" ],
    [ "change" ],
    [ "confront" ],
    [ "dance" ],
    [ "describe" ],
    [ "dine" ],
    [ "dress" ],
    [ "drop" ],
    [ "enter" ],
    [ "explain" ],
    [ "fiddle" ],
    [ "get" ],
    [ "goodbye" ],
    [ "hang" ],
    [ "help" ],
    [ "hold" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "meet" ],
    [ "move" ],
    [ "nod" ],
    [ "open" ],
    [ "pick" ],
    [ "play" ],
    [ "pray" ],
    [ "request" ],
    [ "restart" ],
    [ "rip" ],
    [ "rise" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "send" ],
    [ "share" ],
    [ "shut" ],
    [ "sign" ],
    [ "slide" ],
    [ "sound" ],
    [ "stand" ],
    [ "superbrief" ],
    [ "tell" ],
    [ "tie" ],
    [ "try" ],
    [ "unlock" ],
    [ "unscript" ],
    [ "untie" ],
    [ "use" ],
    [ "verbose" ],
    [ "watch" ],
    [ "wind" ],
    [ "write" ],
] # verbs

nouns = [
    [ "house", "wing", "castle", "Tresyllian Castle" ],
    [ "tower", "keep", "turret" ],
    [ "sky", "full moon", "mist", "moon" ],
    [ "breaker", "sea", "ocean" ],
    [ "loudspeaker", "speaker", "voice" ],
    [ "horn" ],
    [ "wyvern", "ornament", "dragon" ],
    [ "eye", "dragon's eye", "doorbell" ],
    [ "front gate", "gate" ],
    [ "water", "goldfish pond", "pond", "fountain" ],
    [ "door", "front door" ],
    [ "stand", "umbrella stand" ],
    [ "rack", "coat rack" ],
    [ "secret door", "door" ],
    [ "Deirdre's portrait", "watercolor", "picture", "portrait", "painting" ],
    [ "oil painting", "painting", "picture", "portrait" ],
    [ "tapestry", "arm", "maiden", "unicorn" ],
    [ "armchair", "seat", "chair", "cushion" ],
    [ "helmet", "armour", "suit", "armor", "suit of armour" ],
    [ "writing desk", "desk" ],
    [ "piano" ],
    [ "piece of music", "piece" ],
    [ "bronze bust", "sculpt", "bust", "statue", "lionel" ],
    [ "record", "small tape recorder", "tape" ],
    [ "table", "dining table" ],
    [ "seat", "chair", "chairs", "bench" ],
    [ "board", "sideboard" ],
    [ "bowl", "punchbowl" ],
    [ "food", "your dinner", "dinner" ],
    [ "other dinner", "dinner" ],
    [ "lantern", "brass lantern", "lamp" ],
    [ "series", "picture", "portrait", "series of oil paintings", "painting" ],
    [ "bathroom" ],
    [ "place", "fireplace", "chimney", "fender" ],
    [ "night table" ],
    [ "dressing table", "table", "dresse", "bench", "chest" ],
    [ "press", "wardrobe" ],
    [ "mirror", "glass" ],
    [ "bed", "your bed" ],
    [ "your lamp", "lamp" ],
    [ "table", "dressing table" ],
    [ "bench" ],
    [ "mirror", "side mirror" ],
    [ "wall mirror", "mirror" ],
    [ "hidden switch", "switch" ],
    [ "wardrobe" ],
    [ "dresse", "drawer", "chest of drawers", "chest" ],
    [ "wing chair", "chair" ],
    [ "bathroom door", "door" ],
    [ "love seat", "seat", "chair" ],
    [ "sconce", "candle", "ornate candle sconce" ],
    [ "armchair", "seat", "chair" ],
    [ "medical text", "texts", "text", "book", "books" ],
    [ "figure", "sculpted figurine", "figurine" ],
    [ "chair", "longue", "lounge", "chaise", "chaise longue" ],
    [ "head", "andiron" ],
    [ "reclining Morris chair", "seat", "chair" ],
    [ "armchair", "chair" ],
    [ "color", "your favorite color" ],
    [ "handle", "cane" ],
    [ "paint", "coat of paint", "coat" ],
    [ "handle", "club", "war club", "cane" ],
    [ "fossil skull", "skull" ],
    [ "necklace", "string", "pearls", "black pearl necklace" ],
    [ "moonmist", "ink", "mist", "Moonmist" ],
    [ "clue" ],
    [ "card", "clues", "first clue", "clue" ],
    [ "card", "clues", "clue", "second clue", "poem" ],
    [ "card", "clues", "clue", "poem", "third clue" ],
    [ "card", "clues", "clue", "poem", "fourth clue" ],
    [ "GO" ],
    [ "stairs", "stairw", "stair" ],
    [ "turns", "turn", "minute" ],
    [ "it", "this" ],
    [ "floor" ],
    [ "attack", "danger", "threat" ],
    [ "int.num", "number" ],
    [ "walls", "brick", "wall", "bricks" ],
    [ "place", "room", "here", "area" ],
    [ "table", "desk" ],
    [ "tweed outfit", "outfit", "clothes", "suit", "tweeds" ],
    [ "outfit", "clothes", "suit", "sweats", "exercise outfit" ],
    [ "outfit", "clothes", "dinner outfit" ],
    [ "sleep" ],
    [ "moonlight", "light", "lights", "lamp" ],
    [ "case", "attempts", "haunting", "mystery" ],
    [ "keyhole", "hole" ],
    [ "eye", "eyes" ],
    [ "clothes", "outfit", "dress", "gown" ],
    [ "place", "secret passage", "room", "passage", "places" ],
    [ "romance", "engage", "marriage", "love", "Tamara's romance" ],
    [ "drowning", "Deirdre's accident", "death", "accident" ],
    [ "Deirdre's body", "corpse" ],
    [ "undress", "dresse", "undressed" ],
    [ "that thing" ],
    [ "her" ],
    [ "him" ],
    [ "yourself" ],
    [ "tamara", "Tamara", "woman", "lynd", "tammy" ],
    [ "receipt", "evidence", "Tamara's receipt" ],
    [ "jack", "Lord Jack", "lord", "tresyllian", "man" ],
    [ "Deirdre", "deirdre", "woman", "dee", "hallam" ],
    [ "vane", "iris", "Iris", "woman" ],
    [ "ian", "office", "fordyce", "Ian", "man" ],
    [ "wendish", "doctor", "Dr. Wendish", "nicholas", "man" ],
    [ "mustache", "Wendish's mustache" ],
    [ "evidence", "lab notebook", "notebook", "book", "books" ],
    [ "montague", "Hyde" ],
    [ "vivien", "Vivien", "viv", "woman", "pentreath" ],
    [ "evidence", "diary", "Vivien's diary", "book", "books" ],
    [ "lionel", "Lionel Tresyllian" ],
    [ "butler", "bolitho", "Bolitho", "man" ],
    [ "upstairs maid", "maid", "gladys" ],
    [ "ghost costume", "wig", "costume", "disguise", "gown" ],
    [ "such things" ],
    [ "bunch", "guests", "bunch of guests" ],
    [ "that" ],
    [ "handle", "lever" ],
    [ "pseudo" ],
    [ "bag", "case", "suitcase", "luggage", "your luggage" ],
    [ "tourist brochure", "brochure", "book", "books" ],
    [ "gun", "blowgun" ],
    [ "button", "spray", "device", "aerosol device", "weapon" ],
    [ "socket", "setting", "Deirdre's necklace", "necklace", "string" ],
    [ "jewel", "speck", "tiny red jewel", "stone", "gem" ],
    [ "contact lens", "lens", "lenses" ],
    [ "lens", "first contact lens", "lenses" ],
    [ "second contact lens", "lens", "lenses" ],
    [ "small plastic box", "box" ],
    [ "butler's note" ],
    [ "maid's note" ],
    [ "note", "Deirdre's note", "notes" ],
    [ "memento", "painting", "skeleton", "carving" ],
    [ "indian", "figure", "memento", "doctor", "shell" ],
    [ "wine rack", "cellar", "wine", "rack" ],
    [ "bottle", "wine" ],
    [ "bunch", "bricks", "brick", "bunch of loose bricks" ],
    [ "wall", "brick hole", "hole", "opening" ],
    [ "ancient well", "well", "wellshaft" ],
    [ "bones", "skeleton" ],
    [ "hole", "door", "priest hole" ],
    [ "spikes", "spike", "iron maiden", "maiden", "space" ],
    [ "coffin", "stone coffin" ],
    [ "bas-relief", "wyvern", "family crest", "crest" ],
    [ "scope", "telescope" ],
    [ "table" ],
    [ "bunch of books", "book", "bunch", "books" ],
    [ "book", "history book", "books" ],
    [ "journal", "log", "book", "books" ],
    [ "old-fashioned desk", "desk" ],
    [ "inkwell", "well" ],
    [ "computer" ],
    [ "sliding panel", "door", "panel" ],
    [ "case", "box", "jewelry case" ],
    [ "socket", "earring", "setting" ],
    [ "chest", "ancient chest" ],
    [ "hole", "opening", "peephole", "peekhole" ],
    [ "punch", "magazine" ],
    [ "apple", "glass", "stained-glass window", "window" ],
    [ "eye", "head", "buffalo", "stuffed buffalo head" ],
    [ "head", "stuffed rhino head", "rhino" ],
    [ "eye", "glass eye" ],
    [ "bell", "gong" ],
    [ "ladder" ],
    [  ],
    [ "gargoyle", "wyvern", "seat", "dragon" ],
    [ "table", "nightt", "stand" ],
    [ "bag", "kit" ],
    [ "canvas", "supplies", "easel", "pad" ],
    [ "box" ],
    [ "stone" ],
    [ "himself", "you", "herself", "yourself" ],
    [ "outfit", "clothes", "nights", "shirt" ],
    [ "hand", "hands" ],
    [ "head" ],
    [ "treasure", "artifact" ],
    [ "direction" ],
    [ "record", "evidence", "tape" ],
    [ "spirit", "lady", "phantom", "legend" ],
    [ "ghost" ],
    [ "door", "windshield", "window", "windscreen" ],
    [ "case", "bookcase", "shelves", "shelf" ],
    [ "bedpost", "knob", "post", "bed" ],
    [ "handle" ],
] # nouns

rooms = [
    "your entrance",
    "secret tomb",
    "Wendish's entrance",
    "east hall",
    "Tamara's landing",
    "second-floor corridor",
    "hedge maze",
    "drawing-room entrance",
    "drawing room",
    "limbo",
    "path",
    "old great hall",
    "ground-floor corridor",
    "library",
    "Ian's entrance",
    "dead end",
    "Hyde's entrance",
    "tower passage",
    "secret crypt",
    "library landing",
    "sitting room",
    "your bedroom",
    "junction",
    "first-floor corridor",
    "foyer",
    "garden",
    "gallery",
    "west hall",
    "midpoint",
    "dungeon",
    "Vivien's entrance",
    "Iris's entrance",
    "backstairs",
    "sitting passage",
    "Jack's landing",
    "fighting deck",
    "dining passage",
] # rooms

