# Config for NORDANDBERT, in LLM style
#
#

[game]
path = "./infocom/nordandbert/COMPILED/j3.z4"

setup = '''
nordandbert is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "all", "both", "everything" ],
    [ "north", "n" ],
    [ "south", "s" ],
    [ "east", "e" ],
    [ "west", "w" ],
    [ "down", "d" ],
    [ "up", "u" ],
    [ "northwest", "nw" ],
    [ "northe", "ne" ],
    [ "sw", "southwest" ],
    [ "se", "southe" ],
    [ "superbrief", "super" ],
    [ "inventory", "i" ],
    [ "q", "quit" ],
    [ "applaud", "clap" ],
    [ "attack", "murder", "fight", "gore", "slap", "stab", "kill", "slay" ],
    [ "spread", "bend" ],
    [ "blow", "toot" ],
    [ "peddle", "board", "drive", "ride", "mount" ],
    [ "groan", "hiss", "moan", "boo" ],
    [ "purchase", "buy", "order" ],
    [ "trap", "catch" ],
    [ "cheer", "comfort", "entertain" ],
    [ "sneeze", "ahchoo", "choo" ],
    [ "climb", "scale" ],
    [ "shut", "close" ],
    [ "cross", "ford" ],
    [ "decipher", "decode" ],
    [ "pop", "deflate" ],
    [ "destroy", "damage", "trample", "crush", "demolish", "smash", "break", "wreck" ],
    [ "disembark", "dismount", "debark" ],
    [ "drop", "dump" ],
    [ "ingest", "dine", "gobble", "swallow", "devour", "eat", "dining" ],
    [ "tip", "empty" ],
    [ "inspect", "study", "describe", "x", "observe", "watch", "examine" ],
    [ "exit", "withdraw", "depart" ],
    [ "deactivate", "extinguish" ],
    [ "seek", "find" ],
    [ "follow", "pursue", "chase" ],
    [ "grind", "sharpen" ],
    [ "pound", "hammer", "beat", "hit", "strike" ],
    [ "deal", "sell", "hand", "give", "extend", "deliver", "donate", "offer" ],
    [ "hello", "hi" ],
    [ "clue", "hint", "clues", "help", "invisiclue", "hints" ],
    [ "jump", "dive", "vault", "leap" ],
    [ "knock", "rap" ],
    [ "lock" ],
    [ "look", "l" ],
    [ "create", "make" ],
    [ "greet", "meet" ],
    [ "pull", "move", "lead" ],
    [ "nope", "uh-uh", "nah", "no" ],
    [ "harvest", "pick" ],
    [ "play", "act" ],
    [ "plug", "cover" ],
    [ "point", "aim" ],
    [ "pour", "spill" ],
    [ "squeeze", "press", "push" ],
    [ "lift", "boost", "raise" ],
    [ "read", "skim", "browse" ],
    [ "unwrap", "remove" ],
    [ "riddle", "fiddle" ],
    [ "save", "rescue" ],
    [ "status", "score" ],
    [ "rummage", "search" ],
    [ "shake", "bounce" ],
    [ "showing", "show" ],
    [ "hop", "skip" ],
    [ "sleep", "snooze", "rest", "doze", "nap" ],
    [ "chop", "cut", "slice" ],
    [ "smell", "sniff", "whiff" ],
    [ "stand", "rise" ],
    [ "start", "activate" ],
    [ "put", "keep", "place", "insert", "stick", "stuff" ],
    [ "grab", "get", "take", "carry", "hold", "extract" ],
    [ "talk", "speak" ],
    [ "taste", "lick", "nibble" ],
    [ "thanks", "thank" ],
    [ "toss", "hurl", "throw", "cast" ],
    [ "hook", "strap", "hitch", "secure", "tie", "fasten", "attach" ],
    [ "pat", "scratch", "poke", "fondle", "touch", "stroke", "feel", "pet" ],
    [ "wind", "turn", "flick", "spin", "set", "dial", "steer", "rotate", "flip", "switch" ],
    [ "unlox", "unlock" ],
    [ "free", "unknot", "untie", "unfasten", "untangle", "unattach", "unstrap" ],
    [ "z", "wait" ],
    [ "awake", "wake", "rouse" ],
    [ "walk" ],
    [ "clean", "air", "soak", "wash", "wipe" ],
    [ "wear", "don" ],
    [ "whats", "what" ],
    [ "where", "wheres" ],
    [ "who", "whos" ],
    [ "shout", "scream", "yell" ],
    [ "yes", "y", "ok", "sure", "okay", "yup" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "approa" ],
    [ "ask" ],
    [ "bite" ],
    [ "bless" ],
    [ "burn" ],
    [ "bury" ],
    [ "call" ],
    [ "circle" ],
    [ "comb" ],
    [ "cook" ],
    [ "count" ],
    [ "crawl" ],
    [ "cry" ],
    [ "deep-six" ],
    [ "deep" ],
    [ "descend" ],
    [ "dig" ],
    [ "drink" ],
    [ "enter" ],
    [ "feed" ],
    [ "fill" ],
    [ "garble" ],
    [ "go" ],
    [ "goose" ],
    [ "grow" ],
    [ "hair" ],
    [ "hear" ],
    [ "hide" ],
    [ "inflate" ],
    [ "kick" ],
    [ "kiss" ],
    [ "lean" ],
    [ "leave" ],
    [ "let" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "lower" ],
    [ "open" ],
    [ "pass" ],
    [ "pay" ],
    [ "pin" ],
    [ "possession" ],
    [ "rake" ],
    [ "reach" ],
    [ "revolve" ],
    [ "return" ],
    [ "roll" ],
    [ "rub" ],
    [ "say" ],
    [ "shine" ],
    [ "shock" ],
    [ "sign" ],
    [ "sink" ],
    [ "sit" ],
    [ "slide" ],
    [ "smear" ],
    [ "sow" ],
    [ "swim" ],
    [ "swing" ],
    [ "teach" ],
    [ "tell" ],
    [ "unplug" ],
    [ "upset" ],
    [ "use" ],
    [ "vent" ],
    [ "visit" ],
    [ "wave" ],
    [ "wrap" ],
    [ "noverb" ],
] # verbs

nouns = [
    [ "write", "misc", "isle", "aisle", "meets", "dess", "man", "brit", "british", "manicotti", "cellar", "meet", "desert", "dessert", "desserts", "musselaneous" ],
    [ "freezer", "your grocer's freezer" ],
    [ "shelf", "shelves" ],
    [ "cereal", "infinite variety of cereals", "cereals", "variety", "grains" ],
    [ "killer", "vamp", "cereal murderer", "man", "murderer", "vampire", "gentleman" ],
    [ "cardboard boxes", "box", "boxes" ],
    [ "boy", "box boy" ],
    [ "ribbon", "blue ribbon" ],
    [ "door" ],
    [ "restroom", "room", "kitchen", "stage", "bathroom" ],
    [ "crowd", "audience" ],
    [ "coat" ],
    [ "refrigerator", "frig", "fridge" ],
    [ "light", "lamp" ],
    [ "tassel", "shade", "lamp shade", "tassels" ],
    [ "electrical cord", "wire", "plug", "cord" ],
    [ "yellow rubber gloves", "gloves", "glove" ],
    [ "blue sponge", "sponge" ],
    [ "scalpel-like knife", "scalpel", "knife" ],
    [ "hot-water bottle", "cushion", "bottle" ],
    [ "lobotomy", "frontal lobotomy" ],
    [ "dwayne", "your brother-in-law Bob", "bob", "sponge" ],
    [ "shoe", "shoes", "tip", "foot", "Bob's shoe", "hole", "feet" ],
    [ "front door", "door" ],
    [ "door", "bathroom door" ],
    [ "station", "television", "television set", "tv", "set", "channel" ],
    [ "device", "remote control device" ],
    [ "cushion", "seat", "chair", "YOUR comfy chair" ],
    [ "room" ],
    [ "speaking", "manor", "house" ],
    [ "plump, tufted, aristocratic Louis XIV chair", "chair" ],
    [ "multihued textured pillow", "pillow" ],
    [ "mantelpiece", "heroically proportioned mantel", "mantel" ],
    [ "lace tablecloth", "tablecloth" ],
    [ "wasteland", "station", "television", "vast wasteland", "tv", "channel" ],
    [ "cloud" ],
    [ "grass" ],
    [ "yawning chasms", "cliff", "cliffs", "chasm", "chasms" ],
    [ "paint" ],
    [ "clock", "watch", "timepiece", "time" ],
    [ "key", "winding key" ],
    [ "portrait of Karl Marx", "portrait", "marx", "father", "picture", "karl" ],
    [ "lock", "safe" ],
    [ "revolution" ],
    [ "box", "cardboard box" ],
    [ "cabinet", "chest", "medicine cabinet" ],
    [ "pill", "cures", "variety of medicines", "nostrum", "medicine", "elixirs", "losenges", "elixir", "cure", "remedy", "remedies", "pills", "medicines", "variety" ],
    [ "bottle", "old bottle" ],
    [ "mat", "rubber mat" ],
    [ "bathroom", "public", "lobby", "place", "room", "square" ],
    [ "decree" ],
    [ "house", "town house" ],
    [ "bushes", "bush", "branches", "branch", "laurel bushes", "laurel" ],
    [ "stub", "blessings", "blessing", "ticket" ],
    [ "stump", "tree stump", "tree" ],
    [ "nine-tenths", "land", "laws", "tenths", "paper", "law", "sheet", "possession", "laws of the land" ],
    [ "document", "pretense", "pretenses", "paper" ],
    [ "can", "deep-six", "pack", "cans", "six-pack", "six", "beer", "six-pack of beer" ],
    [ "closet" ],
    [ "skeletons", "skeleton" ],
    [ "bathtub" ],
    [ "comb", "hair" ],
    [ "disguise", "mask" ],
    [ "garment", "clothes", "linen", "laundry", "pile", "clothing", "dirty linen" ],
    [ "loft", "stable", "barnyard", "market", "yard", "crop", "field", "stables", "farm", "fields", "road", "barn" ],
    [ "old dog", "dog" ],
    [ "trick", "new tricks", "tricks" ],
    [ "one stone", "stone" ],
    [ "wooden cart", "cart" ],
    [ "tail" ],
    [ "ear", "sow's ear" ],
    [ "purse", "silk purse" ],
    [ "cent", "coin", "pretty penny", "penny" ],
    [ "sword", "full complement of swords", "swords", "complement" ],
    [ "ploughshare", "shares", "plowshares" ],
    [ "side", "broadside", "barn", "broad side of a barn" ],
    [ "ladder", "wooden ladder" ],
    [ "mice", "mouse" ],
    [ "grainfall", "grain", "bags of grain", "stacks", "bags", "bag", "stack" ],
    [ "hammer" ],
    [ "grindstone", "device", "stone" ],
    [ "rusty tin trough", "trough" ],
    [ "wild oats", "food", "oats" ],
    [ "donkey", "mule", "ass" ],
    [ "gift horse", "horse" ],
    [ "bow", "red-ribbon bow", "ribbon" ],
    [ "hay", "stack", "haystack" ],
    [ "needle" ],
    [ "molehill", "hill" ],
    [ "mountains", "mountain", "mt" ],
    [ "crops", "crop" ],
    [ "birds", "two birds", "bird" ],
    [ "peter", "piper" ],
    [ "flute", "pipe" ],
    [ "bag", "canvas bag", "poke" ],
    [ "cat" ],
    [ "pig" ],
    [ "food", "apple" ],
    [ "apples", "cart", "applecart", "apple" ],
    [ "zzmgck", "it" ],
    [ "it" ],
    [ "direct", "direction" ],
    [ "numbers", "number" ],
    [ "it", "them" ],
    [ "himself", "him" ],
    [ "herself", "her" ],
    [ "other", "it", "itself" ],
    [ "snooze", "nap", "sleep" ],
    [ "walls", "wall" ],
    [ "roof", "ceiling" ],
    [ "bathwater", "bath", "water" ],
    [ "palm", "your hand", "hands", "finger", "hand" ],
    [ "your head", "head" ],
    [ "swimming", "shoulder", "breaststroke", "backstroke", "stroke", "shoulders", "crawl", "back-stroke", "your shoulder" ],
    [ "your spleen", "spleen" ],
    [ "your eyes", "eyes", "eye" ],
    [ "your nose", "nose", "nostril" ],
    [ "mouth", "lip", "your mouth", "lips" ],
    [ "word", "mayor", "bizarre", "beginning", "part", "begin", "jacks", "words", "tower", "manor", "scenario", "farm", "speaking", "jack" ],
    [ "guest", "king", "kong", "sodbuster", "ranking", "cong", "comedy", "supersaver", "customer", "saver", "jackster" ],
    [ "protag", "it" ],
    [ "myself", "i", "self", "yourself", "you", "me" ],
    [ "room", "place", "locati", "there", "area" ],
    [ "sign" ],
    [ "staircase", "stairway", "stair", "stairs", "step" ],
    [ "stalk", "shore", "factory", "cloud", "stock", "beanstalk", "room", "place", "clearing", "jack" ],
    [ "key", "shiny key" ],
    [ "rhine", "door", "tributaries", "river", "shore", "tributary", "Rhines" ],
    [ "sanskrit", "lines of sand-script", "message", "script", "line", "lines", "sand-script" ],
    [ "sand", "beach", "shore" ],
    [ "book", "riddle", "riddles", "book of riddles" ],
    [ "foam burning", "foam", "bonfire", "burns", "burning", "rome", "fire" ],
    [ "jean stock", "jeans", "stock", "pile", "stack" ],
    [ "Bean Stalk" ],
    [ "house that Jack built", "built", "jack", "house" ],
    [ "joat", "trait", "Jack of all Traits", "trades", "contraption", "thing", "cloth", "traits", "jack" ],
    [ "tail", "ball of fur", "ball", "fur", "bunny", "jackrabbit", "rabbit" ],
    [ "long piece of metal", "jack", "metal", "knife", "blade", "jackknife", "piece" ],
    [ "lid", "clown", "box", "hand crank", "jack-in-the-box", "jester", "crank", "jack" ],
    [ "water faucet", "jacuzzi", "faucet" ],
    [ "tub", "hot tub", "jacuzzi", "plug", "faucet" ],
    [ "water" ],
    [ "hammer", "switch", "jackhammer", "electrical switch" ],
    [ "sleeves", "coat", "sleeve", "jacket", "pair" ],
    [ "frost", "layer", "layer of frost" ],
    [ "snowball", "ball", "snow" ],
    [ "hole", "ice", "pond" ],
    [ "jack", "man", "Jack Frost", "frost" ],
    [ "gnarled stick", "stick" ],
    [ "fin", "mermaid" ],
    [ "line", "tangle of fishing line", "tangle" ],
    [ "necklace", "shark-tooth necklace" ],
    [ "kitchen", "restaurant" ],
    [ "tables", "table", "your table" ],
    [ "your chair", "chair" ],
    [ "short shrift", "tablecloth", "cloth", "shrift" ],
    [ "shaker", "salt shaker", "salt" ],
    [ "grain", "grain of salt", "salt" ],
    [ "cookie", "fortune cookie", "food" ],
    [ "slip", "fortune", "piece", "paper", "advice" ],
    [ "cheek", "half", "roast", "cheeks", "food", "rump roast" ],
    [ "humble pie", "pie", "food" ],
    [ "pride", "collective", "lions", "meat", "food", "collective of lions' meat" ],
    [ "axe", "ax", "blade", "hatchet" ],
    [ "napkin", "cloth", "white cloth napkin", "flag" ],
    [ "umbrage" ],
    [ "sign", "comeuppance", "Comeuppance" ],
    [ "waitress", "girl", "jen", "jenny" ],
    [ "wool", "headband" ],
    [ "dandruff", "dander" ],
    [ "woodchip", "wood-chip", "chip" ],
    [ "sign", "act", "riot act" ],
    [ "rake" ],
    [ "coal", "hearth", "coals", "fire" ],
    [ "olive", "branches", "branch", "tree", "olive tree" ],
    [ "branch", "olive branch" ],
    [ "desserts", "food", "dessert", "just desserts" ],
    [ "cape", "red velvet curtain", "curtain" ],
    [ "cook" ],
    [ "bad blood", "blood" ],
    [ "card", "recipe card" ],
    [ "can", "laughings", "label", "laughing stock", "stock", "food" ],
    [ "goat", "peeve", "peeves", "cook's goat" ],
    [ "peeve", "goose", "cook's goose", "peeves" ],
    [ "pan", "frying pan", "skillet" ],
    [ "god-awful mess", "flour", "fur" ],
    [ "ingredients", "pot", "meal", "concoction", "food", "brew-haa-haa", "bowl" ],
    [ "flames", "flame", "fire" ],
    [ "devices", "his own devices" ],
    [ "ox" ],
    [ "moose", "mousse" ],
    [ "fraction", "pie", "pi" ],
    [ "clump", "muscles", "mussels", "muscle", "mussel" ],
    [ "sale", "sail" ],
    [ "tax", "tack", "tacks" ],
    [ "pudding", "putting", "section" ],
    [ "stake", "steak", "meat", "stick" ],
    [ "candy", "mints", "candies", "mince", "meat", "mint" ],
    [ "brat", "girl", "sausage", "wurst", "bratwurst", "worst", "niece" ],
    [ "women", "ladies", "ant", "aunt", "lady", "ants", "colony", "aunts", "line" ],
    [ "flower", "flowers", "powder", "flour", "dune" ],
    [ "cent", "cents", "scent", "penny" ],
    [ "claw", "claws", "clause", "paper", "piece", "pair" ],
    [ "reams", "stationary", "stationery", "block", "paper", "ream" ],
    [ "quartz", "quarts", "solid", "pile", "stack", "rubble", "wall", "quart" ],
    [ "lock", "salmon", "lox", "locks" ],
    [ "pool", "jam", "jamb" ],
    [ "seller", "lady", "woman", "cellar" ],
    [ "match", "stick" ],
    [ "girl", "wife", "lady", "gorilla" ],
    [ "laurels", "crown", "branches", "branch", "leaves", "wreath", "laurel" ],
    [ "possession", "horn" ],
    [ "ajar", "door", "jar", "lid" ],
    [ "mayor", "cat", "duck", "baby" ],
    [ "canister", "cannister", "milk" ],
    [ "grainfall", "grain", "spillage", "piles", "pile", "corn" ],
    [ "pepper", "peck", "peppers", "food" ],
    [ "lady", "woman", "man" ],
    [ "rug", "ground", "carpet", "floor" ],
    [ "shoes", "foot", "toes", "shoe", "feet", "toe" ],
    [ "door", "sand", "shore" ],
    [ "house", "louse" ],
    [ "girl", "pearl" ],
    [ "can", "keys", "peas", "pan", "key", "pea" ],
    [ "fox", "pile", "rocks", "rock" ],
    [ "queen", "dean" ],
    [ "experience", "raising", "hair" ],
    [ "shepherd", "leopard" ],
    [ "habit", "cloth", "rabbit" ],
    [ "hat", "rat" ],
    [ "icicle", "bike", "ice", "bicycle" ],
    [ "elf", "self" ],
    [ "talk", "smock" ],
    [ "clean", "giant", "client" ],
    [ "crow", "blow" ],
    [ "meal", "horse", "mare", "squeal" ],
    [ "beets", "sheets", "beet", "sheet", "seat", "shed" ],
    [ "gritty", "nitty-gritty", "bird", "crow", "food" ],
] # nouns

rooms = [
    "Aisle of Manicotti",
    "Jackville",
    "I'll Write",
    "Public Square",
    "Field",
    "On Cloud 673",
    "Musselaneous",
    "Old Factory",
    "Market",
    "Cellar",
    "On the Shore",
    "Bean Stalk",
    "Lobby",
    "Near pond",
    "Before the Manor",
    "On Frozen Pond",
    "Attic",
    "Kremlin",
    "Stable",
    "Interior Decorated",
    "Second floor",
    "Loft",
    "Doldrums",
    "Kitchen",
    "Inside House",
    "Meets",
    "Pharmacy",
    "Bathroom",
    "WARNING!",
    "Jean Stock",
    "Beginning",
    "Barnyard",
    "Your Living Room",
    "Clearing",
    "Barn",
    "British Aisle",
    "Road",
    "Dessert Aisle",
    "First floor",
] # rooms

