# Config for PLANETFALL, in LLM style
#
#

[game]
path = "./infocom/planetfall/COMPILED/planetfall.z3"

setup = '''
planetfall is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "thru", "through", "using", "with" ],
    [ "in", "into", "inside" ],
    [ "all", "both" ],
    [ "onto", "on" ],
    [ "over", "above" ],
    [ "fore", "forward", "f", "foreward", "n", "north" ],
    [ "aft", "south", "s" ],
    [ "sb", "east", "cw", "starboard", "e" ],
    [ "ccw", "west", "port", "w", "p" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "superbrief", "super" ],
    [ "inventory", "i" ],
    [ "quit", "q" ],
    [ "g", "again" ],
    [ "reply", "answer" ],
    [ "slay", "dispatch", "hit", "fight", "injure", "kill", "hurt", "murder", "attack" ],
    [ "lie", "lay", "recline", "sit" ],
    [ "stand" ],
    [ "collapse", "shorten", "fold", "close" ],
    [ "curse", "krip", "trot", "megakrip", "trotting", "fuck", "damn", "shit" ],
    [ "release", "drop" ],
    [ "eat", "drink", "swallow" ],
    [ "whats", "describe", "examine", "what" ],
    [ "find", "where", "see", "seek" ],
    [ "blast", "zap", "fire", "burn", "shoot" ],
    [ "pursue", "follow", "chase" ],
    [ "hand", "offer", "feed", "give", "donate" ],
    [ "hello", "hi" ],
    [ "hints", "help", "hint" ],
    [ "jump", "leap" ],
    [ "knock", "rap" ],
    [ "stare", "l", "look", "gaze" ],
    [ "search", "sift", "sort", "rummage" ],
    [ "gesture", "aim", "point" ],
    [ "pull", "tug" ],
    [ "damage", "break", "smash", "destroy" ],
    [ "lengthen", "extend", "unfold", "open" ],
    [ "push", "press" ],
    [ "place", "insert", "put", "stuff" ],
    [ "rape", "molest" ],
    [ "skim", "read" ],
    [ "pat", "rub", "touch", "pet", "feel" ],
    [ "brush", "swab", "scrub", "shine", "clean", "mop", "polish" ],
    [ "swing", "slide" ],
    [ "skip", "hop" ],
    [ "smell", "sniff" ],
    [ "swim", "bathe", "wade" ],
    [ "take", "get", "carry", "hold" ],
    [ "ask", "tell" ],
    [ "grin", "smile" ],
    [ "talk", "say" ],
    [ "hurl", "throw", "toss", "chuck" ],
    [ "set", "turn" ],
    [ "wait", "z" ],
    [ "surprise", "wake", "startle", "awake" ],
    [ "proceed", "run", "go", "walk" ],
    [ "brandish", "wave" ],
    [ "wear" ],
    [ "yell", "scream", "shout" ],
    [ "sneeze", "zork" ],
    [ "y", "yes", "affirmative" ],
    [ "no", "negative" ],
    [ "possibly", "dunno", "maybe" ],
    [ "pour", "spill" ],
    [ "fix", "repair" ],
    [ "lubricate", "oil" ],
    [ "t", "time" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "verbose" ],
    [ "apply" ],
    [ "board" ],
    [ "climb" ],
    [ "disembark" ],
    [ "enter" ],
    [ "exit" ],
    [ "flush" ],
    [ "fly" ],
    [ "kick" ],
    [ "kiss" ],
    [ "leave" ],
    [ "listen" ],
    [ "lock" ],
    [ "move" ],
    [ "pick" ],
    [ "play" ],
    [ "reach" ],
    [ "sleep" ],
    [ "shake" ],
    [ "step" ],
    [ "strike" ],
    [ "remove" ],
    [ "salute" ],
    [ "activate" ],
    [ "type" ],
    [ "unlock" ],
    [ "empty" ],
    [ "attract" ],
    [ "show" ],
    [ "taste" ],
    [ "escape" ],
    [ "scold" ],
] # verbs

nouns = [
    [ "door" ],
    [ "combination dial", "dial" ],
    [ "pad", "padlock", "lock" ],
    [ "can", "tin can" ],
    [ "ladder" ],
    [ "machin", "dispenser unit", "dispen", "niche", "unit" ],
    [ "canteen" ],
    [ "quantity of protein-rich liquid", "liquid", "food", "quantity", "fluid" ],
    [ "hole", "crevice", "crack" ],
    [ "metal", "key", "object" ],
    [ "rift", "precipice", "gulf", "hole" ],
    [ "drawer", "small desk", "desk" ],
    [ "cards", "kitchen access card", "card" ],
    [ "cards", "upper elevator access card", "card" ],
    [ "shuttle access card", "cards", "card" ],
    [ "lower elevator access card", "cards", "card" ],
    [ "large desk", "drawer", "desk" ],
    [ "can", "oil can" ],
    [ "carton", "cardboard box", "box" ],
    [ "cracked seventeen-centimeter fromitz board", "board", "boards" ],
    [ "B-series megafuse", "megafuse", "fuse" ],
    [ "K-series megafuse", "megafuse", "fuse" ],
    [ "good ninety-ohm bedistor", "bedistor" ],
    [ "door", "reactor elevator door" ],
    [ "flask", "glass flask" ],
    [ "magnet", "bar", "curved metal bar" ],
    [ "pair", "pliers", "pair of wide-nosed pliers" ],
    [ "machin", "chemical dispenser", "dispen" ],
    [ "red button", "button" ],
    [ "button", "blue button" ],
    [ "button", "green button" ],
    [ "button", "yellow button" ],
    [ "button", "gray button" ],
    [ "button", "brown button" ],
    [ "button", "black button" ],
    [ "button", "round white button" ],
    [ "button", "square white button" ],
    [ "compan", "compar", "multiple purpose robot", "robot", "floyd" ],
    [ "robot", "compan", "floyd", "mangled robot" ],
    [ "blue door", "door" ],
    [ "red door", "door" ],
    [ "button" ],
    [ "vehicle", "helicopter", "large vehicle" ],
    [ "button", "glowing button" ],
    [ "contro", "communication send console", "console" ],
    [ "hole", "funnel-shaped hole" ],
    [ "quantity", "chemical", "quantity of chemical fluid", "liquid", "fluid" ],
    [ "lazarus", "breast", "plate", "part", "medical robot breastplate" ],
    [ "red spool", "spool", "spools", "object" ],
    [ "label", "medicine bottle", "bottle" ],
    [ "medicine", "quantity of medicine" ],
    [ "robot", "broken robot", "achilles" ],
    [ "doorwa", "hole", "small doorway", "door" ],
    [ "board", "shiny seventeen-centimeter fromitz board", "boards" ],
    [ "door", "socket", "panel", "access panel" ],
    [ "first seventeen-centimeter fromitz board", "board", "boards" ],
    [ "fourth seventeen-centimeter fromitz board", "board", "boards" ],
    [ "board", "boards", "third seventeen-centimeter fromitz board" ],
    [ "board", "second seventeen-centimeter fromitz board", "boards" ],
    [ "fried seventeen-centimeter fromitz board", "board", "boards" ],
    [ "large metal cube", "lid", "socket", "cube" ],
    [ "fused ninety-ohm bedistor", "bedistor" ],
    [ "spool", "spools", "object", "green spool" ],
    [ "machin", "screen", "terminal", "keyboard" ],
    [ "reader", "machin", "microfilm reader", "screen", "openin" ],
    [ "cryo-elevator door", "door" ],
    [ "pile of computer output", "output", "paper", "printout", "pile" ],
    [ "card", "cards", "miniaturization access card" ],
    [ "suit", "pocket", "lab uniform", "uniform", "logo" ],
    [ "cards", "teleportation access card", "card" ],
    [ "piece", "paper", "piece of paper" ],
    [ "lab door", "door" ],
    [ "bio-lock door", "door" ],
    [ "radiation-lock door", "door" ],
    [ "brown spool", "spool", "spools", "object" ],
    [ "light", "portable lamp", "lamp", "lantern" ],
    [ "office door", "door" ],
    [ "desk" ],
    [ "gas mask", "mask" ],
    [ "memo" ],
    [ "white button", "button" ],
    [ "relay", "micro", "micro-relay" ],
    [ "speck", "boulder", "impurity" ],
    [ "unit", "depres", "device", "laser" ],
    [ "laser setting dial", "dial" ],
    [ "battery", "old battery" ],
    [ "battery", "object", "new battery" ],
    [ "monster", "bug", "microbe" ],
    [ "edge", "side", "silicon strip", "strip" ],
    [ "monster", "rat-ant", "mutant", "rat-like, ant-like man-sized monster" ],
    [ "hairy growling biped", "monster", "biped", "mutant", "troll" ],
    [ "creature", "grue", "monster", "lurking fanged creature", "mutant" ],
    [ "intnum", "number" ],
    [ "pseudo" ],
    [ "this", "that", "it", "random object", "him" ],
    [ "stairway", "steps", "stairs", "gangway" ],
    [ "deck", "floor", "ground", "earth" ],
    [ "port", "viewport", "window" ],
    [ "cliff" ],
    [ "ocean" ],
    [ "tables", "table" ],
    [ "shelf", "shelves" ],
    [ "lights", "light" ],
    [ "doorwa", "doorway", "portal", "openin" ],
    [ "contro", "panel", "dials", "gauges", "set of controls" ],
    [ "game", "hucka-", "chess", "hider-", "bocci" ],
    [ "pair of hands", "pair", "hands" ],
    [ "sleep", "sacred act of sleeping" ],
    [ "eggs", "spam", "smithe", "player", "admira" ],
    [ "we", "me", "myself", "you", "self" ],
    [ "Patrol-issue self-contained multi-purpose scrub brush", "brush", "scrubb", "scrubr" ],
    [ "chronometer", "wristwatch", "watch" ],
    [ "cards", "ID card", "card" ],
    [ "uniform", "pocket", "Patrol uniform", "suit" ],
    [ "blather", "ensign", "Ensign First Class" ],
    [ "ambassador", "alien ambassador" ],
    [ "piece", "piece of celery", "celery", "stalk" ],
    [ "pamphlet", "leaflet", "brochure" ],
    [ "escape pod", "pod" ],
    [ "web", "mass", "webbing", "safety web", "net" ],
    [ "towel" ],
    [ "provisions", "survival kit", "kit" ],
    [ "pie", "blob of red goo", "goo", "blob", "food" ],
    [ "stew", "blob of brown goo", "goo", "blob", "food" ],
    [ "blob of green goo", "beans", "goo", "blob", "food" ],
    [ "escape pod bulkhead", "door", "bulkhead" ],
    [ "wide bulkhead", "door", "bulkhead" ],
    [ "narrow bulkhead", "door", "bulkhead" ],
    [ "slot" ],
    [ "button", "beige button" ],
    [ "button", "tan button" ],
    [ "shuttle car", "car", "shuttl" ],
    [ "lever" ],
    [ "bed", "bunk" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Library",
    "Station 384",
    "Planetary Defense",
    "Radiation Lock West",
    "Radiation Lock East",
    "Auxiliary Booth",
    "ProjCon Office",
    "Radiation Lab",
    "Library Lobby",
    "Project Corridor",
    "Strip Near Station",
    "Lab Office",
    "Systems Corridor East",
    "Physical Plant",
    "Systems Corridor",
    "Strip Near Relay",
    "Booth 3",
    "Project Corridor East",
    "Cryo-Elevator",
    "Cryo-Anteroom",
    "Lab Storage",
    "SanFac F",
    "Miniaturization Booth",
    "Bio Lab",
    "Middle of Strip",
    "Course Control",
] # rooms

