# Config for PLUNDEREDHEARTS, in LLM style
#
#

[game]
path = "./infocom/plunderedhearts/COMPILED/plunderedhearts.z3"

setup = '''
plunderedhearts is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "everyt", "both", "all" ],
    [ "fore", "forward", "north", "n", "f" ],
    [ "south", "s" ],
    [ "east", "e" ],
    [ "w", "west" ],
    [ "down", "d", "downstairs" ],
    [ "upstairs", "u", "up" ],
    [ "nw", "northwest" ],
    [ "northe", "ne" ],
    [ "southwest", "sw" ],
    [ "se", "southe" ],
    [ "superbrief", "super" ],
    [ "invent", "i" ],
    [ "q", "quit" ],
    [ "applaud", "clap" ],
    [ "slap", "hit", "attack", "bash", "murder", "punch", "fight", "strike", "kill", "whack" ],
    [ "ride", "mount", "board" ],
    [ "burn", "melt" ],
    [ "climb", "crawl", "scale" ],
    [ "shut", "close" ],
    [ "cover" ],
    [ "cry", "gasp", "sob", "weep" ],
    [ "twirl", "dance", "pirouette" ],
    [ "destro", "wreck", "demoli", "damage", "smash", "crush", "trample", "break" ],
    [ "disembark", "debark" ],
    [ "sip", "swallow", "quaff", "drink" ],
    [ "dump", "drop" ],
    [ "taste", "nibble", "devour", "eat" ],
    [ "describe", "x", "study", "inspect", "examine", "observe" ],
    [ "withdr", "exit", "depart" ],
    [ "extinguish", "douse", "deactivate" ],
    [ "joggle", "wiggle", "fiddle" ],
    [ "load", "fill" ],
    [ "locate", "seek", "find" ],
    [ "repair", "whet", "fix", "sharpen" ],
    [ "pursue", "chase", "follow" ],
    [ "present", "hand", "give", "offer" ],
    [ "hello", "greet", "hi" ],
    [ "hint", "help" ],
    [ "hug", "embrace" ],
    [ "vault", "dive", "jump", "leap" ],
    [ "bow", "curtsey", "curtsy" ],
    [ "rap", "pound", "knock" ],
    [ "smile", "laugh" ],
    [ "watch", "look", "l" ],
    [ "shackle", "hobble", "manacle", "fetter", "bind" ],
    [ "marry", "wed" ],
    [ "pull", "move" ],
    [ "no", "nope", "nay", "never" ],
    [ "open" ],
    [ "shine", "signal", "point", "aim" ],
    [ "push", "press" ],
    [ "boost", "raise", "lift" ],
    [ "read", "skim", "browse" ],
    [ "remove" ],
    [ "tear", "rip" ],
    [ "tip", "roll" ],
    [ "oar", "row" ],
    [ "rummag", "search" ],
    [ "bounce", "shake" ],
    [ "shoot", "fire", "sling" ],
    [ "moan", "sigh" ],
    [ "sleep", "snooze", "nap", "doze" ],
    [ "stab", "cut", "slice" ],
    [ "sniff", "whiff", "smell" ],
    [ "wet", "soak" ],
    [ "stand", "rise" ],
    [ "lay", "stick", "dip", "sprinkle", "hang", "insert", "put", "place" ],
    [ "faint", "swoon" ],
    [ "get", "take", "carry", "hold", "grab" ],
    [ "speak", "talk" ],
    [ "thank", "thanks" ],
    [ "throw", "hurl", "toss" ],
    [ "moor", "attach", "tie", "weave", "secure", "fasten" ],
    [ "feel", "smooth", "grip", "rub", "touch" ],
    [ "rotate", "switch", "flick", "flip", "turn", "set", "spin" ],
    [ "undres", "disrobe", "strip" ],
    [ "unbar", "unlock" ],
    [ "unatta", "unweave", "untie", "unknot", "free", "loosen" ],
    [ "wait", "z" ],
    [ "wake", "rouse", "revive", "awake" ],
    [ "step", "run", "sidle", "procee", "walk" ],
    [ "wipe", "wash", "clean" ],
    [ "wear", "don" ],
    [ "what", "who", "whats", "whos" ],
    [ "where", "whither", "wheres" ],
    [ "shout", "shriek", "aaieee", "yell", "scream" ],
    [ "nod", "sure", "yes", "y", "yup", "ok", "okay" ],
    [ "verbose" ],
    [ "brief" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "approa" ],
    [ "ask" ],
    [ "bite" ],
    [ "blow" ],
    [ "bribe" ],
    [ "circle" ],
    [ "come" ],
    [ "descen" ],
    [ "dress" ],
    [ "empty" ],
    [ "enter" ],
    [ "feed" ],
    [ "go" ],
    [ "stop" ],
    [ "hear" ],
    [ "hide" ],
    [ "kick" ],
    [ "kiss" ],
    [ "launch" ],
    [ "lean" ],
    [ "leave" ],
    [ "let" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "muzzle" ],
    [ "pass" ],
    [ "pay" ],
    [ "pick" ],
    [ "play" ],
    [ "wring" ],
    [ "pour" ],
    [ "rape" ],
    [ "reach" ],
    [ "reflect" ],
    [ "return" ],
    [ "score" ],
    [ "show" ],
    [ "sit" ],
    [ "slide" ],
    [ "swim" ],
    [ "swing" ],
    [ "tap" ],
    [ "tell" ],
    [ "wave" ],
    [ "wrap" ],
    [ "zzmgck" ],
] # verbs

nouns = [
    [ "clothes", "pants", "britches", "breeches" ],
    [ "shirt", "clothes" ],
    [ "pile of clothes", "clothes" ],
    [ "dress", "frock", "clothes", "cotton frock" ],
    [ "dress", "beautiful ball gown", "gown", "clothes" ],
    [ "rag", "cloth" ],
    [ "linen chemise", "clothes", "chemise", "slip", "petticoat" ],
    [ "your kid slippers", "shoes", "slippers" ],
    [ "slingshot", "garter", "sling" ],
    [ "unmentionables", "smalls" ],
    [ "reticule", "your reticule" ],
    [ "money", "banknote", "note" ],
    [ "carbonate", "salts", "smelling salts", "tag" ],
    [ "bottle", "label", "leather bottle" ],
    [ "drops", "drug", "liquid", "laudanum" ],
    [ "brooch", "jewelled brooch", "clasp", "pin" ],
    [ "hat", "tricorne", "quill" ],
    [ "crulley", "Crulley", "pirate", "hook" ],
    [ "whip" ],
    [ "Davis", "davis" ],
    [ "cook", "Cookie", "cookie", "quick", "rodney" ],
    [ "seaman", "pirate", "sailor" ],
    [ "cook", "woman", "Lucy", "lucy" ],
    [ "butler" ],
    [ "men", "lady", "dancer", "woman", "ladies" ],
    [ "your father", "dimsford", "papa", "dad", "father" ],
    [ "villain", "Lafond", "lafond", "governor" ],
    [ "ring", "gold ring", "latin" ],
    [ "ring", "new ring", "latin" ],
    [ "air" ],
    [ "pistol", "gun" ],
    [ "patrol", "dragoo" ],
    [ "zzmgck", "it" ],
    [ "it" ],
    [ "direction", "direct" ],
    [ "number" ],
    [ "pseudo" ],
    [ "them", "it" ],
    [ "him", "himself" ],
    [ "her", "herself" ],
    [ "sailor", "men", "you", "man" ],
    [ "rope", "ladder" ],
    [ "sleep", "nap", "snooze" ],
    [ "floor", "ground", "deck" ],
    [ "key", "large key" ],
    [ "door", "lock" ],
    [ "walls", "wall" ],
    [ "ceiling", "ceilin", "roof" ],
    [ "water" ],
    [ "sea", "shallows", "ocean", "water", "lagoon" ],
    [ "sky" ],
    [ "moonlight", "moonbeam", "light", "beam" ],
    [ "nails", "hand", "finger", "hands", "your hand" ],
    [ "head", "your head" ],
    [ "eye", "your eyes", "eyes" ],
    [ "mouth", "snout", "lips", "lip", "your mouth" ],
    [ "protag", "it" ],
    [ "myself", "me", "yourself", "self", "i" ],
    [ "room", "area", "locati", "place" ],
    [ "house", "mansion", "library" ],
    [ "pit", "fire", "firepit" ],
    [ "step", "stairs", "stair", "stairw" ],
    [ "curtain" ],
    [ "glass", "window", "porthole" ],
    [ "tree", "trees" ],
    [ "Captain Jamison", "hero", "pirate", "captain", "jamison" ],
    [ "rapier", "sword" ],
    [ "sinistra", "island", "beach", "St. Sinistra", "cliff" ],
    [ "bushes", "soldiers", "dragoo" ],
    [ "skiff", "boat" ],
    [ "jasmine", "flower" ],
    [ "gazebo", "jasmine", "folly" ],
    [ "bench" ],
    [ "slat", "loose slat" ],
    [ "hole" ],
    [ "glass", "window" ],
    [ "door", "doors", "french door" ],
    [ "veranda", "porch" ],
    [ "vines", "vine" ],
    [ "hedge" ],
    [ "fence", "gate" ],
    [ "musicians", "orchestra" ],
    [ "long table", "table" ],
    [ "drapes", "curtain" ],
    [ "flame", "torch" ],
    [ "door", "painting", "portrait", "pictur" ],
    [ "sinistra", "island", "globe" ],
    [ "books", "book" ],
    [ "shelves", "bookcase", "shelf", "bookshelf" ],
    [ "power", "book" ],
    [ "knob" ],
    [ "bed" ],
    [ "divan", "couch" ],
    [ "pair of duelling pistols", "pistol", "gun" ],
    [ "ornate door", "door", "lock" ],
    [ "chair" ],
    [ "sill", "shutters", "window" ],
    [ "table" ],
    [ "spice", "pepper", "spices", "pinch", "pinch of spices" ],
    [ "pepper", "spices", "spice" ],
    [ "tray", "silver tray" ],
    [ "well" ],
    [ "food", "chicken", "viands", "fowl", "cold chicken" ],
    [ "flagon" ],
    [ "quantity of wine", "wine" ],
    [ "glass", "cup", "goblet", "blue goblet" ],
    [ "green goblet", "cup", "glass", "goblet" ],
    [ "railing" ],
    [ "rope" ],
    [ "chandelier", "pulley", "candle" ],
    [ "bed", "cot" ],
    [ "crack" ],
    [ "powder horn", "horn", "strap" ],
    [ "powder", "gunpow", "gunpowder", "shot" ],
    [ "door", "wooden door" ],
    [ "mouth", "lebs", "crocod", "crocodile", "croc" ],
    [ "water", "pool" ],
    [ "chains", "lock", "manacle", "chain", "pair of manacles" ],
    [ "door", "trapdo", "trapdoor", "well" ],
    [ "door", "iron door" ],
    [ "cell" ],
    [ "ship", "louise", "Helena Louise", "boat" ],
    [ "debris", "remains", "sail", "wood" ],
    [ "chest", "coffer", "lock", "box" ],
    [ "card", "invite", "invitation" ],
    [ "desk", "table" ],
    [ "quarte", "ship", "quarters", "cabin" ],
    [ "sill", "ledge" ],
    [ "cupboard", "large cupboard", "door", "bed" ],
    [ "frame", "canvas hatch", "hatch" ],
    [ "fence", "cage" ],
    [ "gate", "lock", "gap" ],
    [ "food", "ammuni", "food and ammunition supplies", "gunpow" ],
    [ "keg", "kegs", "casks", "cask" ],
    [ "sign" ],
    [ "fuse", "glow", "fire" ],
    [ "powder", "potions", "mess", "stains" ],
    [ "hole", "grate" ],
    [ "bit of mirror", "mirror" ],
    [ "knife", "dagger" ],
    [ "navigation wheel", "wheel" ],
    [ "cannon" ],
    [ "keg", "cask" ],
    [ "meat", "something", "slab of pork", "pork" ],
    [ "rope", "line" ],
    [ "pyramid", "casks", "cask", "pyramid of casks" ],
    [ "rum barrel", "keg", "barrel", "cask", "stains" ],
    [ "rum", "grog" ],
    [ "water barrel", "keg", "cask", "barrel" ],
    [ "chain" ],
    [ "windlass", "mooring winch", "winch", "barrel" ],
    [ "lever", "writing" ],
    [ "galley", "hut", "shack" ],
    [ "hawser", "rope", "stub of rope" ],
    [ "anchor" ],
    [ "forema", "mainma", "mast", "rigging" ],
    [ "oar", "pair of oars", "oars", "oarlock" ],
    [ "rock", "stone" ],
    [ "reefs", "reef" ],
    [ "paper", "missive", "letter" ],
] # nouns

rooms = [
    "Main Deck",
    "Parlour",
    "Veranda",
    "By the House",
    "East Hallway",
    "Bottom of Stairwell",
    "Supper Room",
    "Cabin",
    "Forecastle",
    "Deck",
    "Gallery",
    "Stair Landing",
    "Sleeping Cupboard",
    "Landing",
    "Galley",
    "Shallows",
    "THE CARIBBEAN, 16--",
    "Corner",
    "Foyer",
    "Cell",
    "Clearing",
    "Beach",
    "Stairwell",
    "Lawn",
    "Quarterdeck",
    "South Passage",
    "Hold",
    "Trade Entrance",
    "Captain's Quarters",
    "Kitchen",
    "Library",
    "Main Entrance",
    "Front Drive",
    "Upstairs Hall",
    "Anteroom",
    "Forest",
    "Dungeon",
    "Lafond's Bedroom",
    "Poop",
    "Bedroom",
    "Aft Hold",
    "Bowsprit",
    "In the Rigging",
    "In the Hedge",
    "Folly",
    "Guard's Bunkroom",
    "Crew's Quarters",
    "Crow's Nest",
    "Orchestra",
    "On the Ladder",
    "Ballroom",
    "North Passage",
    "Lagoon",
    "By the Ship",
    "Hall",
] # rooms

