# Config for RESTAURANT, in LLM style
#
#

[game]
path = "./infocom/restaurant/COMPILED/restaurant.z3"

setup = '''
restaurant is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "using", "with" ],
    [ "through", "thru" ],
    [ "on", "onto" ],
    [ "below", "beneath", "underneath", "under" ],
    [ "until", "till" ],
    [ "toward", "to" ],
    [ "along", "around" ],
    [ "both", "all" ],
    [ "inside", "into", "in" ],
    [ "outside", "out" ],
    [ "fore", "north", "f", "n", "forewa" ],
    [ "aft", "s", "south" ],
    [ "starbo", "e", "east", "sb" ],
    [ "p", "port", "west", "w" ],
    [ "down", "downstairs", "d" ],
    [ "up", "u" ],
    [ "nw", "northwest" ],
    [ "ne", "northeast" ],
    [ "sw", "southwest" ],
    [ "se", "southeast" ],
    [ "aim", "point" ],
    [ "check", "analyse", "analyze", "test" ],
    [ "reply", "answer", "respond" ],
    [ "inquire", "ask", "question", "query", "consult" ],
    [ "assault", "repel", "rape", "molest", "fight", "attack" ],
    [ "scratch", "scrape", "tidy", "clean", "freshen", "brush", "wipe", "wash" ],
    [ "purchase", "buy", "order" ],
    [ "summon", "call" ],
    [ "climb", "board", "scale" ],
    [ "shut", "close" ],
    [ "destroy", "break", "wreck", "demolish", "crush", "crack", "smash", "damage", "hurt" ],
    [ "drape", "wrap" ],
    [ "sip", "drink", "swallow", "guzzle" ],
    [ "eat", "gobble", "taste", "lick", "devour" ],
    [ "watch", "observe", "examine", "study", "describe", "explore", "inspect", "x" ],
    [ "doze", "faint", "snooze", "sleep", "nap" ],
    [ "fill", "flood" ],
    [ "discover", "find", "seek", "locate", "detect" ],
    [ "repair", "unjam", "fix", "adjust" ],
    [ "stalk", "follow", "pursue", "chase" ],
    [ "sell", "offer", "feed", "pass", "hand", "give" ],
    [ "greetings", "hello", "greet", "hi" ],
    [ "help", "hints", "hint" ],
    [ "conceal", "hide" ],
    [ "invent", "i" ],
    [ "jump", "leap", "dive" ],
    [ "murder", "kill", "stab", "waste" ],
    [ "flirt", "comfort", "console", "hug", "kiss" ],
    [ "bang", "rap", "knock" ],
    [ "leave", "depart", "exit", "withdraw" ],
    [ "listen" ],
    [ "peek", "stare", "l", "peer", "see", "look", "peep", "gaze" ],
    [ "nope", "no" ],
    [ "spill", "sprinkle", "pour" ],
    [ "move", "tug", "pull" ],
    [ "shove", "press", "push" ],
    [ "lay", "insert", "place", "set", "put", "stuff" ],
    [ "q", "logoff", "logout", "quit" ],
    [ "skim", "read" ],
    [ "relax", "rest", "meditate" ],
    [ "doff", "remove" ],
    [ "restore" ],
    [ "ring" ],
    [ "rub", "feel", "touch" ],
    [ "state", "gab", "chat", "speak", "say", "talk", "whisper" ],
    [ "dig", "frisk", "search", "rummage" ],
    [ "shake", "rattle" ],
    [ "shoot", "fire", "spray" ],
    [ "show", "display" ],
    [ "sit" ],
    [ "hit", "punch", "kick", "slap" ],
    [ "smell", "sniff" ],
    [ "wink", "grin", "smile" ],
    [ "apologize", "sorry" ],
    [ "start", "activate" ],
    [ "park", "stop" ],
    [ "wade", "bathe", "swim" ],
    [ "steal", "take", "grab", "carry", "seize" ],
    [ "thank", "thanks" ],
    [ "throw", "toss", "hurl" ],
    [ "flick", "toggle", "turn", "flip", "switch" ],
    [ "release", "version", "revision" ],
    [ "wait", "stay", "pause", "z" ],
    [ "awake", "surprise", "wake", "startle", "rouse" ],
    [ "come", "run", "head", "step", "proceed", "go", "steer", "drive", "approach", "return", "walk" ],
    [ "howl", "shout", "yell", "scream" ],
    [ "y", "yup", "yes", "sure", "aye", "yeah", "okay", "ok", "yep", "indeed" ],
    [ "address" ],
    [ "brief" ],
    [ "change" ],
    [ "count" ],
    [ "cover" ],
    [ "diagnose" ],
    [ "dine" ],
    [ "drop" ],
    [ "enjoy" ],
    [ "enter" ],
    [ "explain" ],
    [ "fiddle" ],
    [ "footnote" ],
    [ "get" ],
    [ "hang" ],
    [ "hear" ],
    [ "hold" ],
    [ "lie" ],
    [ "light" ],
    [ "lock" ],
    [ "look-inside" ],
    [ "nod" ],
    [ "open" ],
    [ "panic" ],
    [ "pay" ],
    [ "pick" ],
    [ "play" ],
    [ "refuse" ],
    [ "request" ],
    [ "restart" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "share" ],
    [ "slide" ],
    [ "sound" ],
    [ "stand" ],
    [ "superbrief" ],
    [ "tell" ],
    [ "undo" ],
    [ "unlock" ],
    [ "unscript" ],
    [ "use" ],
    [ "verbose" ],
] # verbs

nouns = [
    [ "ne", "south", "west", "east", "nw", "north", "se", "sw", "direction" ],
    [ "GO" ],
    [ "LG", "l.g" ],
    [ "problem", "frustration", "puzzle" ],
    [ "stairway", "stairs", "stair" ],
    [ "sucker", "this", "fucker", "it" ],
    [ "floor" ],
    [ "threat", "attack", "danger" ],
    [ "int.num", "number" ],
    [ "brick", "bricks", "wall", "walls" ],
    [ "here", "place", "room", "area" ],
    [ "chairs", "chair", "bench", "seat" ],
    [ "desk", "table" ],
    [ "sleep" ],
    [ "moonlight", "light", "lights", "lamp" ],
    [ "earth", "planet", "third planet" ],
    [ "goal", "object", "game", "object of the game" ],
    [ "sky" ],
    [ "hatch" ],
    [ "her" ],
    [ "him" ],
    [ "them" ],
    [ "yourself" ],
    [ "marv", "android", "robot", "marvin", "Marvin" ],
    [ "Ford Prefect", "prefect", "ford" ],
    [ "beeblebrox", "Zaphod Beeblebrox", "zaphod", "president" ],
    [ "woman", "trillian", "mcmillan", "Trillian", "tricia" ],
    [ "that" ],
    [ "glass", "glasses", "bottle", "beermat", "it" ],
    [ "lots of beer", "lots", "bitter", "beer", "pint" ],
    [ "plate", "cheese sandwich", "sandwich" ],
    [ "tool", "flathead screwdriver", "tools", "screwdriv" ],
    [ "tools", "tool", "brush", "toothbrush" ],
    [ "your gown", "gown", "robe", "loop", "pocket" ],
    [ "sleeve" ],
    [ "gift", "thing your aunt gave you which you don't know what it is", "thing" ],
    [ "guide", "copy", "The Hitchhiker's Guide" ],
    [ "babel fish", "fish" ],
    [ "towel", "towels" ],
    [ "satchel" ],
    [ "spaceship", "heart", "gold", "ship", "the Heart of Gold" ],
    [ "game", "milliways", "MILLIWAYS" ],
    [ "food", "your dinner", "dinner" ],
    [ "frobs", "frob", "red frob" ],
    [ "frobs", "green frob", "frob" ],
    [ "frobs", "frob", "big blue frob" ],
    [ "small blue frob", "frobs", "frob" ],
    [ "turns", "turn", "minute", "minutes" ],
    [ "herself", "himself", "you", "yourself" ],
    [ "hand", "hands" ],
    [ "face", "head" ],
    [ "eye", "eyes" ],
    [ "teeth" ],
    [ "ears", "ear" ],
    [ "windshield", "door", "windscreen", "window" ],
] # nouns

rooms = [
    "Pan-Galactic Gargle Blaster",
    "Crater Lip",
    "Hatchway",
    "Sirius Cybernetics Corporation",
    "Blighted Ground",
    "On the Ramp",
] # rooms

