# Config for SEASTALKER, in LLM style
#
#

[game]
path = "./infocom/seastalker/COMPILED/seastalker.z3"

setup = '''
seastalker is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "using", "with", "by" ],
    [ "thru", "through" ],
    [ "into", "inside", "in" ],
    [ "onto", "on" ],
    [ "under", "beneath", "underneath" ],
    [ "n", "north" ],
    [ "s", "south" ],
    [ "east", "e" ],
    [ "w", "west" ],
    [ "d", "down" ],
    [ "up", "u" ],
    [ "northw", "nw" ],
    [ "northe", "ne" ],
    [ "sw", "southw" ],
    [ "se", "southe" ],
    [ "tune", "adjust", "focus", "clear" ],
    [ "point", "aim" ],
    [ "analyse", "test", "check", "analyze" ],
    [ "reply", "answer", "respond" ],
    [ "capture", "arrest" ],
    [ "consult", "ask", "inquire", "question" ],
    [ "attack", "fight", "molest", "assault", "rape", "repel" ],
    [ "bring", "fetch" ],
    [ "brush", "clean", "wipe" ],
    [ "call" ],
    [ "climb", "board" ],
    [ "replace", "close", "reset" ],
    [ "match", "compare" ],
    [ "ford", "cross" ],
    [ "interrupt", "cut" ],
    [ "crush", "tear", "break", "smash", "destroy", "damage" ],
    [ "submerge", "dive", "descend" ],
    [ "swallow", "imbibe", "drink" ],
    [ "drop", "lower" ],
    [ "eat", "consume" ],
    [ "drain", "empty", "blow" ],
    [ "inspect", "study", "observe", "explore", "scrutinize", "describe", "examine" ],
    [ "extinguish", "douse" ],
    [ "flood", "fill" ],
    [ "locate", "find", "detect" ],
    [ "repair", "fix" ],
    [ "chase", "pursue", "follow", "trace" ],
    [ "offer", "donate", "give", "hand" ],
    [ "goodbye", "bye", "good-bye" ],
    [ "hi", "greetings", "hello", "greet" ],
    [ "hide", "crouch" ],
    [ "strangle", "kill" ],
    [ "knock", "rap" ],
    [ "leave" ],
    [ "look", "stare", "see", "peek", "gaze", "l" ],
    [ "prepare", "build", "make" ],
    [ "nope", "no", "negative", "nay" ],
    [ "pull", "tug" ],
    [ "press", "push" ],
    [ "put", "install", "place", "stuff", "load", "mount", "insert" ],
    [ "q", "quit" ],
    [ "lift", "raise" ],
    [ "peruse", "read", "skim" ],
    [ "restore" ],
    [ "ring", "peal" ],
    [ "rise", "ascend" ],
    [ "rub", "pet", "feel", "touch", "pat", "shade" ],
    [ "suspend", "save", "pause" ],
    [ "explain", "state", "say", "speak", "talk" ],
    [ "dig", "search" ],
    [ "blast", "shoot", "fire" ],
    [ "injure", "punch", "bite", "hurt", "hit", "slap", "kick" ],
    [ "smell", "sniff" ],
    [ "wink", "smile", "grin" ],
    [ "start", "activate", "engage" ],
    [ "superbrief", "super" ],
    [ "swim", "wade", "bathe" ],
    [ "get", "take" ],
    [ "thank", "thanks" ],
    [ "toss", "chuck", "hurl", "throw" ],
    [ "attach", "fasten", "secure", "tie" ],
    [ "flip", "shut", "swing", "switch" ],
    [ "uncuff", "unattach", "untie", "unfasten", "free", "unhook" ],
    [ "release", "edition", "version", "revision" ],
    [ "stay", "rest", "relax", "z", "wait", "meditate" ],
    [ "awake", "surprise", "startle", "wake" ],
    [ "go", "head", "drive", "proceed", "steer", "walk", "run" ],
    [ "name", "identify" ],
    [ "why", "when", "did", "how" ],
    [ "scream", "shout", "yell" ],
    [ "yeah", "yes", "affirm", "y", "10-4", "sure", "roger", "wilco", "okay", "aye", "yup", "ok" ],
    [ "apply" ],
    [ "arm" ],
    [ "brief" ],
    [ "burn" ],
    [ "come" ],
    [ "confront" ],
    [ "count" ],
    [ "diagnose" ],
    [ "dial" ],
    [ "discuss" ],
    [ "dock" ],
    [ "enter" ],
    [ "fit" ],
    [ "hang" ],
    [ "help" ],
    [ "i" ],
    [ "invent" ],
    [ "jump" ],
    [ "kick" ],
    [ "kiss" ],
    [ "know" ],
    [ "launch" ],
    [ "lean" ],
    [ "stand" ],
    [ "level" ],
    [ "listen" ],
    [ "lock" ],
    [ "move" ],
    [ "nod" ],
    [ "open" ],
    [ "pick" ],
    [ "play" ],
    [ "poke" ],
    [ "pour" ],
    [ "pump" ],
    [ "restart" ],
    [ "score" ],
    [ "screw" ],
    [ "script" ],
    [ "send" ],
    [ "set" ],
    [ "show" ],
    [ "sit" ],
    [ "sleep" ],
    [ "slide" ],
    [ "smoke" ],
    [ "stop" ],
    [ "medium" ],
    [ "fast" ],
    [ "strike" ],
    [ "surface" ],
    [ "swing" ],
    [ "tell" ],
    [ "time" ],
    [ "turn" ],
    [ "unlock" ],
    [ "unscript" ],
    [ "use" ],
    [ "verbose" ],
    [ "what" ],
] # verbs

nouns = [
    [ "monster", "slug", "snark", "Snark", "creature" ],
    [ "dart gun" ],
    [ "gun", "bazooka", "weapon" ],
    [ "aquadome", "station", "Aquadome", "dome" ],
    [ "window" ],
    [ "exercise track", "track" ],
    [ "ladder", "emergency ladder" ],
    [ "crew", "divers", "Aquadome crew" ],
    [ "badges", "badge" ],
    [ "red door", "door" ],
    [ "furniture", "locker", "bed", "table", "bunk" ],
    [ "blue door", "door" ],
    [ "furniture", "bed", "table", "bunk" ],
    [ "other locker", "locker" ],
    [ "Horvak's locker", "locker" ],
    [ "key", "Horvak's key" ],
    [ "diary" ],
    [ "picture", "photo", "photograph", "snapshot" ],
    [ "workshop door", "door" ],
    [ "tool", "workshop material" ],
    [ "door", "laboratory door" ],
    [ "comm center door", "door" ],
    [ "Aquadome sonar equipment", "screen", "sonar", "system", "equipm" ],
    [ "door", "galley door" ],
    [ "office door", "door" ],
    [ "Bly's desk", "desk", "drawer" ],
    [ "black box" ],
    [ "circuit" ],
    [ "station monitor" ],
    [ "docking tank control panel", "control", "panel", "knob", "knobs" ],
    [ "door", "storage door" ],
    [ "Emergency Survival Unit" ],
    [ "hypodermic syringe", "contents", "syringe", "needle" ],
    [ "grids", "grid", "fine grid" ],
    [ "Air Supply System" ],
    [ "access door" ],
    [ "special hook", "hook" ],
    [ "arrow" ],
    [ "special Fram Bolt Wrench" ],
    [ "electrolyte relay" ],
    [ "empty space" ],
    [ "turns", "minute", "turn" ],
    [ "they", "them", "it", "this" ],
    [ "floor" ],
    [ "company", "business", "unlimited", "Inventions Unlimited" ],
    [ "danger", "threat" ],
    [ "motive" ],
    [ "problem" ],
    [ "weapon" ],
    [ "explosive charge", "explosive", "charge" ],
    [ "boat" ],
    [ "control", "panel", "knob", "knobs", "control panel" ],
    [ "intercom" ],
    [ "button", "test button", "switch" ],
    [ "power", "supply" ],
    [ "call", "sos", "distress call" ],
    [ "sonar", "system" ],
    [ "surface" ],
    [ "alarm", "bell", "alarm bell" ],
    [ "videophone" ],
    [ "sound", "videophone", "picture" ],
    [ "transmitter" ],
    [ "cable", "undersea coaxial cable" ],
    [ "satellite" ],
    [ "damage" ],
    [ "sabotage" ],
    [ "compass direction", "direct" ],
    [ "sea water", "water", "seawater" ],
    [ "open sea", "ocean", "sea" ],
    [ "girl", "woman", "her", "she" ],
    [ "he", "boy", "man", "him" ],
    [ "you", "himself", "himself or herself", "herself", "yourself" ],
    [ "direct", "Aquadome directions" ],
    [ "here", "room", "area", "place" ],
    [ "air", "oxygen", "wind", "breeze" ],
    [ "tank", "docking tank" ],
    [ "tank", "test tank" ],
    [ "control", "tank control", "switch" ],
    [ "gate control", "control", "switch" ],
    [ "private matter", "matter" ],
    [ "evidence" ],
    [ "more" ],
    [ "deposit", "valuable ore deposit", "field", "nodule" ],
    [ "Tip's idea", "idea" ],
    [ "plan", "Bly's plan" ],
    [ "reason" ],
    [ "sonar operator", "man", "operator" ],
    [ "lab assistant", "assistant" ],
    [ "Doc's laboratory", "lab", "laboratory" ],
    [ "lab", "your laboratory", "laboratory" ],
    [ "chore", "work", "job" ],
    [ "traitor" ],
    [ "seat", "chairs", "chair" ],
    [ "underwater" ],
    [ "seastalker", "game", "SEASTALKER" ],
    [ "(something)" ],
    [ "p", "left", "port" ],
    [ "sb", "right", "starboard" ],
    [ "such things" ],
    [ "yourself", "we", "us" ],
    [ "arm", "your arm" ],
    [ "moisture", "stain", "gash" ],
    [ "Tip Randall", "tip", "randall" ],
    [ "Tip", "tip", "sailor", "randall" ],
    [ "sharon", "kemp", "Sharon Kemp" ],
    [ "Commander Bly" ],
    [ "mick", "antrim", "Mick Antrim" ],
    [ "horvak", "medic", "walt", "Doc Horvak", "doc" ],
    [ "siegel", "Marv Siegel", "marv" ],
    [ "bill", "diver", "greenup", "technician", "Bill Greenup" ],
    [ "Amy Lowell", "amy", "diver", "technician", "lowell" ],
    [ "Doctor Jerome Thorpe" ],
    [ "Doctor Jerome Thorpe", "jerome", "thorpe" ],
    [ "that" ],
    [ "tester", "testor", "computestor", "Computestor" ],
    [ "receiver" ],
    [ "scanner", "Microwave Security Scanner" ],
    [ "desk", "lab desk" ],
    [ "breaker", "circuit", "circuit breaker", "switch" ],
    [ "door", "storage door", "doorway" ],
    [ "office door", "door", "doorway" ],
    [ "file", "drawer", "cabinet", "file drawer", "files" ],
    [ "lot of business papers", "lot", "paper", "papers" ],
    [ "desk", "Kemp's desk" ],
    [ "chemical supply shelf", "shelf", "shelves" ],
    [ "bunch", "bunch of chemicals", "chemical", "supply", "supplies" ],
    [ "shelves", "electronic supply shelf", "shelf" ],
    [ "bunch", "electr", "supply", "bunch of electronic supplies", "supplies" ],
    [ "shelf", "mechanical supply shelf", "shelves" ],
    [ "bunch", "supply", "bunch of mechanical supplies", "mechanical", "supplies" ],
    [ "bench", "table", "workbench" ],
    [ "technician" ],
    [ "south doorway", "door", "doorway" ],
    [ "gangplank", "runway" ],
    [ "work counter", "workcounter", "counter" ],
    [ "gear", "control", "wall", "control gear" ],
    [ "valves", "gauge", "control gear", "gauges", "valve" ],
    [ "top", "entrance", "entry hatch", "hatch", "door" ],
    [ "viewport" ],
    [ "access panel", "panel" ],
    [ "light", "lights" ],
    [ "voltage regulator", "regulator" ],
    [ "wall", "sea wall" ],
    [ "handle", "lever", "reactor lever" ],
    [ "depth finder" ],
    [ "warning", "depth finder warning light", "light" ],
    [ "automatic", "auto" ],
    [ "manual" ],
    [ "sonarscope" ],
    [ "sonarscope warning light", "warning", "light" ],
    [ "alarm", "buzzer", "warning buzzer" ],
    [ "sonarphone", "phone" ],
    [ "hydrophone" ],
    [ "generator", "hole", "reactor" ],
    [ "button", "reactor starter", "starter" ],
    [ "turbine", "hydrojet", "engine", "system" ],
    [ "button", "starter", "engine starter" ],
    [ "joystick", "stick" ],
    [ "throttle", "speed" ],
    [ "faster", "fast", "maximum", "high" ],
    [ "cruise", "medium", "half" ],
    [ "minimum", "low", "slow", "slower" ],
    [ "off", "stop", "still" ],
    [ "present depth", "depth" ],
    [ "square", "sea square" ],
    [ "m", "meter", "meters", "metres" ],
    [ "autopilot" ],
    [ "control circuit", "circuit" ],
    [ "brass search light", "beam", "light" ],
    [ "whale" ],
    [ "overheating" ],
    [ "Frobton Bay", "bay", "surface" ],
    [ "arm", "extensor claw", "arms", "claw", "claws" ],
    [ "seat", "chair" ],
    [ "cluster", "instrument cluster", "gauges", "instrument" ],
    [ "that thing" ],
    [ "logbook", "Logbook", "book" ],
    [ "newspaper", "mag", "magazine", "cover" ],
    [ "article", "page", "story", "report" ],
    [ "capsule", "catalyst capsule" ],
    [ "other Gear", "gear", "gears" ],
    [ "gear", "divers' Gear", "gears" ],
    [ "Bly's Emergency Oxygen Gear", "gear" ],
    [ "canister", "gear", "straw", "valve", "Emergency Oxygen Gear" ],
    [ "badge", "your badge" ],
    [ "badge", "Tip's badge" ],
    [ "Sharon's badge", "badge" ],
    [ "tool", "Universal Tool" ],
    [ "tractor" ],
    [ "ramp" ],
    [ "ladder" ],
    [ "mike" ],
    [ "zzzzlg", "zzzlg" ],
    [ "bioceptor", "submarine", "sub", "scimitar" ],
    [ "help", "hint", "clue" ],
    [ "gates", "gate", "bumper" ],
    [  ],
    [ "roof" ],
    [ "myself", "i", "me" ],
    [ "door", "doorway" ],
    [ "keel", "freighter", "ship" ],
    [ "handle", "lever", "control" ],
] # nouns

rooms = [
    "Kemp's office",
    "Aquadome laboratory",
    "northwest deck",
    "reception area",
    "crawl space",
    "limbo",
    "storage room",
    "Aquadome office",
    "storage closet",
    "corridor",
    "galley",
    "comm center",
    "dome center",
    "workshop",
] # rooms

