# Config for SHERLOCK, in LLM style
#
#

[game]
path = "./infocom/sherlock/COMPILED/sherlock.z3"

setup = '''
sherlock is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "n", "north" ],
    [ "south", "s" ],
    [ "east", "e" ],
    [ "west", "w" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "northeast", "ne" ],
    [ "nw", "northwest" ],
    [ "southeast", "se" ],
    [ "southwest", "sw" ],
    [ "query", "ask", "interrogate" ],
    [ "attack" ],
    [ "board", "mount" ],
    [ "kneel", "bow" ],
    [ "destroy", "break", "damage", "smash" ],
    [ "kindle", "burn" ],
    [ "goodbye", "farewell", "bye" ],
    [ "call", "hail" ],
    [ "wipe", "smear", "sweep", "polish", "brush", "clean" ],
    [ "close", "slam" ],
    [ "tally", "count" ],
    [ "cover", "shield", "block" ],
    [ "chop", "cut", "slash" ],
    [ "detonate", "explode" ],
    [ "imbibe", "drink", "guzzle", "quaff", "swill", "sip" ],
    [ "drop", "dump" ],
    [ "eat", "swallow", "bite" ],
    [ "empty", "clear" ],
    [ "escape", "flee" ],
    [ "survey", "examine", "inspect", "trace", "describe", "see", "study", "x", "check" ],
    [ "scram", "withdraw", "depart", "exit" ],
    [ "douse", "snuff", "extinguish", "quench" ],
    [ "seek", "discover", "find" ],
    [ "wrap", "fold" ],
    [ "follow", "chase", "pursue" ],
    [ "negotiate", "deal", "bargain", "dicker", "haggle" ],
    [ "hand", "give" ],
    [ "heat", "warm" ],
    [ "hi", "greetings", "salute", "hello", "greet" ],
    [ "hints", "help", "invisiclues", "clue", "clues", "hint" ],
    [ "whack", "slap", "hit", "swat" ],
    [ "shh", "hush", "quiet", "sshhh", "shhhh", "sshh", "shhh", "shush" ],
    [ "inhale", "hypervent" ],
    [ "i", "inventory" ],
    [ "leap", "jump", "bound", "vault", "hurdle" ],
    [ "kill", "murder" ],
    [ "smooch", "kiss" ],
    [ "knock", "pound", "tap", "rap" ],
    [ "peer", "l", "gaze", "stare", "peek", "look" ],
    [ "wiggle", "hook", "jiggle", "loosen", "wobble" ],
    [ "harpo", "whistle", "marx", "gummo", "chico", "echo", "groucho", "punt", "zeppo", "hum", "sing" ],
    [ "move", "dislocate", "shift", "roll" ],
    [ "motion", "nod", "laugh", "sneer", "smile", "grin" ],
    [ "entice", "pay", "bribe" ],
    [ "fiddle", "toy", "play" ],
    [ "blind", "jab", "poke" ],
    [ "sprinkle", "pour", "spill" ],
    [ "tug", "yank", "drag", "pull" ],
    [ "stick", "shove", "press", "push", "thrust", "nudge" ],
    [ "lay", "put", "insert", "stuff", "place" ],
    [ "q", "quit" ],
    [ "raise", "lift", "hoist", "elevate" ],
    [ "grope", "reach" ],
    [ "skim", "browse", "read", "leaf" ],
    [ "release", "unjam", "free" ],
    [ "service", "repair" ],
    [ "reply", "respond" ],
    [ "preserve", "rescue", "assist", "aid" ],
    [ "rip", "tear" ],
    [ "talk", "utter", "say", "proclaim", "speak" ],
    [ "sift", "frisk", "search", "rummage", "ransack" ],
    [ "fire", "shoot" ],
    [ "display", "show" ],
    [ "squat", "sit", "crouch", "settle" ],
    [ "nap", "sleep", "snooze", "rest" ],
    [ "whiff", "smell", "sniff" ],
    [ "whirl", "spin" ],
    [ "stand", "rise" ],
    [ "pinch", "steal" ],
    [ "superbrief", "super" ],
    [ "bathe", "swim", "wade" ],
    [ "retrieve", "grab", "carry", "take", "keep", "seize", "catch", "snatch" ],
    [ "taste", "lick" ],
    [ "thank", "thanks" ],
    [ "fling", "hurl", "toss", "chuck", "pitch", "throw" ],
    [ "tie", "fasten", "secure" ],
    [ "touch", "scratch", "disturb" ],
    [ "rotate", "turn", "toggle", "twist" ],
    [ "strip", "undress", "disrobe" ],
    [ "unflatten", "extend", "unfold" ],
    [ "unhook", "undo", "untie", "unfasten" ],
    [ "use", "operate", "exploit", "employ" ],
    [ "wait", "loiter", "stay", "z" ],
    [ "awake", "revive", "awaken", "rouse", "wake" ],
    [ "proceed", "trudge", "walk", "step", "hike" ],
    [ "observe", "watch" ],
    [ "don", "wear" ],
    [ "wedge", "force" ],
    [ "what", "whats" ],
    [ "where", "wheres" ],
    [ "who", "whos" ],
    [ "scream", "shout", "howl", "yell", "cry" ],
    [ "yes", "y" ],
    [ "adjust" ],
    [ "aim" ],
    [ "answer" ],
    [ "approach" ],
    [ "aragon" ],
    [ "arrest" ],
    [ "ascend" ],
    [ "back" ],
    [ "blow" ],
    [ "boleyn" ],
    [ "breathe" ],
    [ "brief" ],
    [ "bring" ],
    [ "buy" ],
    [ "cast" ],
    [ "cleves" ],
    [ "climb" ],
    [ "conceal" ],
    [ "descend" ],
    [ "diagnose" ],
    [ "disembark" ],
    [ "dive" ],
    [ "dress" ],
    [ "drive" ],
    [ "embark" ],
    [ "enter" ],
    [ "exhale" ],
    [ "feed" ],
    [ "feel" ],
    [ "fell" ],
    [ "fill" ],
    [ "fix" ],
    [ "flip" ],
    [ "fly" ],
    [ "focus" ],
    [ "foo" ],
    [ "get" ],
    [ "gin" ],
    [ "go" ],
    [ "guess" ],
    [ "haul" ],
    [ "hear" ],
    [ "hide" ],
    [ "hold" ],
    [ "howard" ],
    [ "illuminate" ],
    [ "kick" ],
    [ "land" ],
    [ "launch" ],
    [ "lean" ],
    [ "leave" ],
    [ "let" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "maybe" ],
    [ "melt" ],
    [ "no" ],
    [ "notify" ],
    [ "open" ],
    [ "paddle" ],
    [ "parr" ],
    [ "password" ],
    [ "pat" ],
    [ "pet" ],
    [ "pick" ],
    [ "pocket" ],
    [ "point" ],
    [ "pray" ],
    [ "refuse" ],
    [ "remove" ],
    [ "rent" ],
    [ "replace" ],
    [ "restart" ],
    [ "restore" ],
    [ "retract" ],
    [ "retreat" ],
    [ "ride" ],
    [ "ring" ],
    [ "rob" ],
    [ "row" ],
    [ "rub" ],
    [ "save" ],
    [ "scale" ],
    [ "score" ],
    [ "script" ],
    [ "sell" ],
    [ "set" ],
    [ "seymour" ],
    [ "shake" ],
    [ "shine" ],
    [ "shut" ],
    [ "slide" ],
    [ "smoke" ],
    [ "start" ],
    [ "stop" ],
    [ "strike" ],
    [ "swing" ],
    [ "swordfish" ],
    [ "tell" ],
    [ "tip" ],
    [ "translate" ],
    [ ";tune" ],
    [ "unlock" ],
    [ "unscrew" ],
    [ "unscript" ],
    [ "verbose" ],
    [ "version" ],
    [ "wave" ],
    [ "weigh" ],
    [ "wind" ],
    [ "work" ],
] # verbs

nouns = [
    [ "intnum", "number" ],
    [ "box", "intnum", "safety deposit box" ],
    [ "ring" ],
    [ "shilling", "coin" ],
    [ "key" ],
    [ "intnum", "lock" ],
    [ "safety deposit boxes", "boxes" ],
    [ "pocket", "guard's pocket" ],
    [ "cabbie", "driver", "hansom cabbie" ],
    [ "driver", "cabbie", "growler cabbie" ],
    [ "cab", "hansom cab" ],
    [ "growler cab", "cab" ],
    [ "whistle" ],
    [ "blade", "ax", "wax", "axe" ],
    [ "torch" ],
    [ "shag", "tobacco" ],
    [ "bottles", "label", "bottle", "blue bottle" ],
    [ "brown bottle", "bottles", "label", "bottle" ],
    [ "orange pill", "pills", "pill" ],
    [ "pill", "pills", "yellow pill" ],
    [ "door", "front door" ],
    [ "door", "parlour door" ],
    [ "door", "study door" ],
    [ "bedroom door", "door" ],
    [ "door", "vault door" ],
    [ "door" ],
    [ "door", "door to the Jericho Parlour" ],
    [ "door", "Abbey door" ],
    [ "stores", "windows", "emporiums", "shops", "store", "window", "shop" ],
    [ "plate", "relief", "sign", "plaque" ],
    [ "window" ],
    [ "gaslight", "streetlight", "light", "streetlamp", "street-light", "gas-light", "lamp" ],
    [ "stair", "stairway", "step", "stairs", "steps" ],
    [ "sunlight", "light", "shaft of light", "shaft" ],
    [ "marble" ],
    [ "columns", "column" ],
    [ "birds", "ravens", "rook", "raven", "rooks", "bird" ],
    [ "boats", "ships" ],
    [ "Tower", "london", "tower" ],
    [ "them", "themselves" ],
    [ "self", "body", "yourself", "me", "i", "myself" ],
    [ "you", "myself", "yourself" ],
    [ "himself", "him" ],
    [ "her", "herself" ],
    [ "you", "watson", "doctor" ],
    [ "detective", "companion", "sherlock", "friend", "Holmes", "holmes" ],
    [ "dog" ],
    [ "guard" ],
    [ "bird", "pigeon" ],
    [ "sherman", "Sherman", "trainer" ],
    [ "companion", "boy", "urchin", "wiggins", "Wiggins" ],
    [ "official", "Prime Minister", "visitor", "minister", "man" ],
    [ "akbar", "Akbar" ],
    [ "moriarty", "professor", "Moriarty", "prof" ],
    [ "mrs", "hudson", "housekeeper", "Mrs Hudson" ],
    [ "man", "proprietor", "denkeeper" ],
    [ "man", "lonely librarian", "librarian" ],
    [ "man", "butler" ],
    [ "nannies" ],
    [ "Queen Victoria", "victoria", "queen" ],
    [ "people", "women", "shoppers", "crowds", "crowd", "housewives", "wives" ],
    [ "Palace guard", "guard" ],
    [ "urchins" ],
    [ "members" ],
    [ "st", "221-B Baker Street", "street" ],
    [ "house", "entry hall", "hall" ],
    [ "parlour", "parlor" ],
    [ "vestibule" ],
    [ "place", "York Place" ],
    [ "Marylebone Road", "road" ],
    [ "museum", "Madame Tussaud's", "tussauds" ],
    [ "chamber", "horrors", "Chamber of Horrors" ],
    [ "road", "Tottenham Court Road" ],
    [ "St Giles Circus", "circus", "giles" ],
    [ "Oxford Street", "st", "street" ],
    [ "st", "street", "Orchard Street" ],
    [ "st", "Audley Street", "street" ],
    [ "Kensington Gardens", "gardens" ],
    [ "club", "Diogenes Club" ],
    [ "st", "Great Russell Street", "street" ],
    [ "museum", "British Museum" ],
    [ "Manuscript Room", "room" ],
    [ "Grosvenor Place", "place" ],
    [ "Victoria Square", "square" ],
    [ "st", "Victoria Street", "street" ],
    [ "sanctuary", "Broad Sanctuary" ],
    [ "Parliament Square", "square" ],
    [ "house", "houses", "Houses of Parliament", "commons", "parliament" ],
    [ "Clock Tower" ],
    [ "Buckingham Palace Road", "road" ],
    [ "Queens Gardens", "gardens" ],
    [ "palace", "Buckingham Palace" ],
    [ "walk", "Birdcage Walk" ],
    [ "mall", "The Mall" ],
    [ "whitehall", "Whitehall" ],
    [ "Scotland Yard", "yard" ],
    [ "museum", "The Black Museum" ],
    [ "New Oxford Street", "st", "street" ],
    [ "garden", "Covent Garden" ],
    [ "st", "Fleet Street", "street" ],
    [ "the Embankment", "embankment" ],
    [ "On the Thames" ],
    [ "st", "Upper Thames Street", "street" ],
    [ "lane", "Pinchin Lane", "alley" ],
    [ "house", "Sherman's Shop", "shop" ],
    [ "Cheapside", "cheapside" ],
    [ "st", "Threadneedle Street", "street" ],
    [ "Bank of England", "bank", "england" ],
    [ "bank vault", "vault" ],
    [ "st", "King William Street", "street" ],
    [ "obelisk", "the Monument", "monument" ],
    [ "st", "Lower Thames Street", "street" ],
    [ "bridge", "London Bridge" ],
    [ "entrance", "Tower of London entrance" ],
    [ "lane", "alley", "Swan Lane" ],
    [ "Bar of Gold", "gold", "bar" ],
    [ "lair" ],
    [ "Nave" ],
    [ "South Aisle" ],
    [ "Jericho Parlour" ],
    [ "North Cloister" ],
    [ "South Transept" ],
    [ "North Transept" ],
    [ "Poets' Corner" ],
    [ "South Ambulatory" ],
    [ "Sanctuary" ],
    [ "North Ambulatory" ],
    [ "Evangelist Chapel" ],
    [ "Henry VII Chapel" ],
    [ "Confessor Chapel" ],
    [ "South Chapel Aisle" ],
    [ "North Chapel Aisle" ],
    [ "Innocents Corner" ],
    [ "drawbridge" ],
    [ "Byward Tower" ],
    [ "Outer Ward" ],
    [ "Bloody Tower" ],
    [ "Wakefield Tower" ],
    [ "Jewel Room" ],
    [ "Dungeon" ],
    [ "White Tower" ],
    [ "Tower Green" ],
    [ "Bowyer Tower" ],
    [ "Inside Traitors Gate" ],
    [ "Outside Traitors Gate" ],
    [ "salesman", "man", "vendor" ],
    [ "pound", "note", "quid", "pound note" ],
    [ "sixpence" ],
    [ "telescope", "scope" ],
    [ "rooms" ],
    [ "room" ],
    [ "direction" ],
    [ "that" ],
    [ "sesame" ],
    [ "itself", "that", "it" ],
    [ "forward", "right", "clockwise", "ahead" ],
    [ "left", "backward", "behind", "countercl" ],
    [ "fingers", "hand", "hands", "finger" ],
    [ "heart", "heartbeat" ],
    [ "feet", "foot" ],
    [ "ear", "ears" ],
    [ "head" ],
    [ "stomach", "hair", "legs", "leg", "arms", "arm", "shoulder", "nose", "that part of your body", "face", "lips", "throat", "eyes", "mouth", "eye", "shoulders", "body" ],
    [ "breath" ],
    [ "clothes", "clothing" ],
    [ "watermark", "mark" ],
    [ "hole", "holes", "bullet hole" ],
    [ "women", "shoppers", "crowds", "tourists", "people", "crowd" ],
    [ "pocket", "pockets" ],
    [ "pistol", "gun", "revolver" ],
    [ "letters", "letter", "mail" ],
    [ "jackknife", "knife" ],
    [ "lens", "glass", "magnifying glass" ],
    [ "papers", "paper", "newspaper" ],
    [ "violin", "fiddle" ],
    [ "paper", "verse", "poem", "papers", "clue paper" ],
    [ "phial", "vial" ],
    [ "slipper", "persian slipper" ],
    [ "pipe" ],
    [ "rowboat", "old boat", "boat" ],
    [ "oar", "weathered old oar" ],
    [ "oar", "Captain Bligh's oar" ],
    [ "clapper" ],
    [ "balls", "cotton balls", "ball", "cottonball" ],
    [ "tower", "ben", "bell", "Big Ben" ],
    [ "ss", "stethoscope", "steth" ],
    [ "dial" ],
    [ "bowler", "hat" ],
    [ "carnation", "flower", "flowers" ],
    [ "carnation", "flower" ],
    [ "gems", "gem", "opal", "scratch" ],
    [ "gem", "gems", "topaz", "scratch" ],
    [ "box", "pack", "pacquet of paper", "pacquet", "packet", "paper" ],
    [ "green piece of paper", "papers", "back", "paper" ],
    [ "papers", "back", "white piece of paper", "paper" ],
    [ "blue piece of paper", "back", "papers", "paper" ],
    [ "papers", "back", "orange piece of paper", "paper" ],
    [ "papers", "back", "yellow piece of paper", "paper" ],
    [ "brown piece of paper", "back", "papers", "paper" ],
    [ "flame", "candles", "candle", "bank", "bank of candles" ],
    [ "crayon" ],
    [ "coat" ],
    [ "lapel" ],
    [ "tomb", "inscription", "confessor", "Edward the Confessor's tomb" ],
    [ "tomb", "inscription", "Elizabeth's tomb" ],
    [ "tomb", "Henry V's tomb", "effigy", "coffin", "inscription" ],
    [ "tomb", "Alexander Pope's tomb", "inscription" ],
    [ "Charles Dickens's tomb", "tomb", "inscription" ],
    [ "tomb", "inscription", "sarcophagus", "Geoffrey Chaucer's tomb" ],
    [ "Anne of Cleve's tomb", "cleves", "tomb", "anne", "inscription" ],
    [ "tomb of the Little Princes in the Tower", "tomb", "urn", "inscription", "sarcophagus" ],
    [ "tomb", "Mary, Queen of Scots' tomb", "effigy", "inscription", "sarcophagus" ],
    [ "tomb", "Henry VII's tomb", "inscription" ],
    [ "tomb", "inscription", "Pitt the Younger's tomb" ],
    [ "figures", "figure", "allegorical figures" ],
    [ "light", "lamp", "lantern" ],
    [ "clump of moss", "moss", "clump" ],
    [ "rowboat", "Captain Bligh's boat", "boat" ],
    [ "anchor" ],
    [ "nelson", "statue", "statue of Admiral Lord Nelson" ],
    [ "regalia", "diamond", "the Crown Jewels", "jewels" ],
    [ "Moriarty's key", "key" ],
    [ "experiment", "testubes", "equipment", "beakers", "laboratory equipment", "pipettes" ],
    [ "etherium gas", "etherium", "gas" ],
    [ "mantel", "mantelpiece", "mantlepiece", "mantle" ],
    [ "bench", "workbench" ],
    [ "bag", "black bag" ],
    [ "statue of Charles I", "wax", "statue", "i", "charles" ],
    [ "william", "wax", "conqueror", "statue", "statue of William the Conqueror" ],
    [ "raleigh", "walter", "wax", "statue", "statue of Sir Walter Raleigh" ],
    [ "elizabeth", "figure of Queen Elizabeth", "wax", "figure" ],
    [ "becket", "wax", "thomas", "statue", "statue of Saint Thomas Becket" ],
    [ "statue of Sir Francis Drake", "francis", "wax", "statue", "drake" ],
    [ "wax", "john", "statue", "statue of King John" ],
    [ "wax", "statue", "fawkes", "statue of Guy Fawkes" ],
    [ "column", "Nelson's Column", "monument" ],
    [ "rope" ],
    [ "liquid", "drug", "cocaine", "clear, colourless liquid" ],
    [ "syringe", "needle" ],
    [ "morocco case", "case" ],
    [ "dead pigeon", "pigeon", "bird" ],
    [ "red piece of glass", "glass" ],
    [ "birds", "pigeons" ],
    [ "table", "bedside table" ],
    [ "bed" ],
    [ "book", "matchbook", "matches" ],
    [ "paddle" ],
    [ "oarlock" ],
    [ "book", "old book" ],
    [ "page", "book page", "introduction" ],
    [ "perambulator", "pram", "prams" ],
    [ "daisies", "marigolds", "flower", "petunias", "daffodils", "rose", "roses", "flowers", "peonies" ],
    [ "shaft" ],
    [ "table" ],
    [ "case", "jewel case" ],
    [ "girl's mouth", "mouth" ],
    [ "rubbing", "rubbings" ],
    [ "couch", "sofa" ],
    [ "speck", "cigar ash", "ash" ],
    [ "cigaret", "cigarette" ],
    [ "turban" ],
    [ "chain", "anchor chain" ],
    [ "railing", "rail" ],
    [ "opium", "fumes", "gas" ],
    [ "trinket", "trinkets", "baubles" ],
    [ "keys" ],
    [ "table", "desk" ],
    [ "eye", "Nelson's blind eye" ],
    [ "yeoman", "beefeater", "guard" ],
    [ "malmsey", "wine" ],
    [ "pool", "pool of malmsey", "malmsey", "wine" ],
    [ "butt", "barrel", "butt of malmsey", "keg" ],
    [ "gems", "garnet", "gem", "scratch" ],
    [ "stopper", "cork", "bung" ],
    [ "weapon", "mace" ],
    [ "chain" ],
    [ "armour", "suit of armour", "suit", "armor" ],
    [ "door", "portcullis" ],
    [ "wax", "head" ],
    [ "gem", "emerald", "scratch", "gems" ],
    [ "water", "river", "thames" ],
    [ "upstream", "downstream" ],
    [ "abbey", "tomb", "sculptures", "tombs", "statues" ],
    [ "heart", "doolittle", "eliza", "heartbeat", "girl" ],
    [ "zzzp" ],
    [ "minute", "hour", "minutes", "hours" ],
    [ "cloud", "ground", "surface", "floor", "ceiling", "sky", "fog", "clouds" ],
    [ "stomach", "ear", "hair", "legs", "leg", "arms", "arm", "ears", "hands", "shoulder", "heart", "nose", "foot", "feet", "head", "face", "lips", "hand", "throat", "eyes", "clothes", "mouth", "eye", "shoulders", "body" ],
    [ "walls", "wall" ],
    [ "match" ],
    [ "gem", "sapphire", "scratch", "gems" ],
    [ "gem", "scratch", "gems", "ruby" ],
    [ "tomb", "system", "statue", "inscription", "angels", "diagram", "cherubs", "angel", "cherub", "sarcophagus" ],
    [ "knights", "tomb", "suit", "armor", "knight", "armour", "inscription", "effigy" ],
    [ "ampule", "ampoule", "label", "etherium" ],
] # nouns

rooms = [
    "the Monument",
    "North Ambulatory",
    "Parliament Square",
    "Jericho Parlour",
    "Diogenes Club",
    "Orchard Street",
    "The Mall",
    "Lower Thames Street",
    "Whitehall",
    "Audley Street",
    "North Cloister",
    "Bloody Tower",
    "Nave",
    "Dungeon",
    "Great Russell Street",
    "On the Thames",
    "Queens Gardens",
    "Outer Ward",
    "Innocents Corner",
    "Threadneedle Street",
    "Inside Traitors Gate",
    "Sherman's Shop",
    "London Bridge",
    "British Museum",
    "221-B Baker Street",
    "White Tower",
    "Victoria Street",
    "North Chapel Aisle",
    "Swan Lane",
    "South Chapel Aisle",
    "Bar of Gold",
    "Tower of London entrance",
    "Byward Tower",
    "Grosvenor Place",
    "lair",
    "The Black Museum",
    "Jewel Room",
    "parlour",
    "Tower Green",
    "Birdcage Walk",
    "South Aisle",
    "Upper Thames Street",
    "Tottenham Court Road",
    "Cheapside",
    "Evangelist Chapel",
    "Manuscript Room",
    "vestibule",
    "Covent Garden",
    "Henry VII Chapel",
    "Outside Traitors Gate",
    "New Oxford Street",
    "Buckingham Palace Road",
    "Kensington Gardens",
    "Bank of England",
    "South Ambulatory",
    "Victoria Square",
    "Buckingham Palace",
    "Pinchin Lane",
    "Wakefield Tower",
    "Clock Tower",
    "Scotland Yard",
    "entry hall",
    "Marylebone Road",
    "bank vault",
    "Oxford Street",
    "Fleet Street",
    "King William Street",
    "South Transept",
    "Bowyer Tower",
    "St Giles Circus",
    "Chamber of Horrors",
    "the Embankment",
    "Confessor Chapel",
    "North Transept",
    "Sanctuary",
    "Madame Tussaud's",
    "Poets' Corner",
    "drawbridge",
    "York Place",
    "Houses of Parliament",
    "Broad Sanctuary",
] # rooms

