# Config for SORCERER, in LLM style
#
#

[game]
path = "./infocom/sorcerer/COMPILED/sorcerer.z3"

setup = '''
sorcerer is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "with", "using" ],
    [ "thru", "through" ],
    [ "on", "onto" ],
    [ "in", "inside", "into" ],
    [ "under", "below", "beneath", "underneath" ],
    [ "along", "around" ],
    [ "all", "both" ],
    [ "north", "n" ],
    [ "south", "s" ],
    [ "east", "e" ],
    [ "west", "w" ],
    [ "down", "d" ],
    [ "u", "up" ],
    [ "nw", "northwest" ],
    [ "northe", "ne" ],
    [ "sw", "southwest" ],
    [ "southe", "se" ],
    [ "superbrief", "super" ],
    [ "inventory", "i" ],
    [ "q", "quit" ],
    [ "reply", "answer", "respond" ],
    [ "ask", "query", "interrogate", "quiz" ],
    [ "attack", "fight", "assault", "injure", "hurt", "hit" ],
    [ "ride", "embark", "board" ],
    [ "ignite", "burn", "kindle", "combust" ],
    [ "scale", "climb" ],
    [ "recline", "repose", "lie" ],
    [ "shut", "close" ],
    [ "combin", "combo" ],
    [ "count", "tally" ],
    [ "traverse", "ford", "cross" ],
    [ "split", "cut", "cleave", "gash", "slice", "slash", "sever", "lacerate" ],
    [ "shit", "damn", "fuck" ],
    [ "wreck", "demolish", "destroy", "damage", "break", "crack", "smash" ],
    [ "excavate", "dig" ],
    [ "debark", "disembark" ],
    [ "imbibe", "swill", "sip", "drink", "quaff", "guzzle", "swallow" ],
    [ "dump", "release", "drop" ],
    [ "eat", "gobble", "ingest", "consume", "taste", "nibble", "devour" ],
    [ "exit", "depart", "withdraw" ],
    [ "watch", "describe", "check", "study", "examine", "inspect", "observe", "survey" ],
    [ "exorcise", "banish", "drive" ],
    [ "douse", "quench", "extinguish" ],
    [ "seek", "see", "find" ],
    [ "chase", "pursue", "follow" ],
    [ "unmemorize", "forget", "unlearn" ],
    [ "present", "bestow", "offer", "donate", "feed", "hand", "give" ],
    [ "greetings", "salutations", "hello", "hi" ],
    [ "help", "hint", "hints" ],
    [ "secrete", "ensconce", "conceal", "stash", "hide" ],
    [ "leap", "dive", "hurdle", "vault", "jump", "bound" ],
    [ "murder", "stab", "kill", "slay", "dispatch", "vanquish" ],
    [ "smooch", "kiss" ],
    [ "knock", "rap" ],
    [ "harken", "listen" ],
    [ "gaze", "l", "look", "stare" ],
    [ "melt", "liquify", "dissolve", "thaw" ],
    [ "shift", "dislocate", "move", "displa" ],
    [ "shove", "yank", "pull", "drag", "tug" ],
    [ "patch", "clog", "fix", "repair", "glue", "plug" ],
    [ "point", "gesture" ],
    [ "jab", "poke", "blind" ],
    [ "pour", "sprinkle", "spill" ],
    [ "nudge", "push", "press", "thrust" ],
    [ "insert", "lay", "place", "put", "stuff" ],
    [ "elevate", "raise", "hoist", "lift" ],
    [ "molest", "ravish", "defile", "rape" ],
    [ "skim", "read" ],
    [ "doff", "shed", "remove" ],
    [ "proclaim", "call", "utter", "say", "talk" ],
    [ "search", "ransack", "frisk", "rummage" ],
    [ "shake", "rattle", "jostle" ],
    [ "hone", "sharpen" ],
    [ "shoot", "discharge", "fire" ],
    [ "squat", "sit", "rest" ],
    [ "hop", "gambol", "cavort", "skip" ],
    [ "smell", "sniff", "whiff" ],
    [ "gyrate", "rotate", "spin", "whirl" ],
    [ "rise", "stand" ],
    [ "wade", "bathe", "swim" ],
    [ "swing", "thrust" ],
    [ "snatch", "grab", "hold", "take", "get", "seize", "carry", "catch", "confiscate" ],
    [ "thank", "thanks" ],
    [ "pitch", "hurl", "fling", "throw", "chuck", "toss" ],
    [ "secure", "tie", "attach", "fasten" ],
    [ "time", "t" ],
    [ "feel", "touch", "pat", "pet", "rub" ],
    [ "shut", "flip", "turn", "set" ],
    [ "unfasten", "unattach", "free", "unhook", "untie" ],
    [ "z", "wait" ],
    [ "rouse", "awake", "startle", "wake", "surprise" ],
    [ "proceed", "run", "step", "go", "advance", "tramp", "walk", "trudge", "hike" ],
    [ "motion", "brandish", "beckon", "wave" ],
    [ "polish", "wax", "shine" ],
    [ "wear", "don" ],
    [ "whats", "what" ],
    [ "wheres", "where" ],
    [ "whos", "who" ],
    [ "howl", "yell", "scream", "shout" ],
    [ "incant", "cast", "invoke" ],
    [ "know", "memorize", "learn" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "apply" ],
    [ "bite" ],
    [ "blow" ],
    [ "descen" ],
    [ "compar" ],
    [ "deflate" ],
    [ "enter" ],
    [ "fill" ],
    [ "fly" ],
    [ "inflat" ],
    [ "kick" ],
    [ "land" ],
    [ "launch" ],
    [ "lean" ],
    [ "leave" ],
    [ "light" ],
    [ "lock" ],
    [ "lower" ],
    [ "roll" ],
    [ "pay" ],
    [ "play" ],
    [ "open" ],
    [ "pick" ],
    [ "pump" ],
    [ "reach" ],
    [ "send" ],
    [ "show" ],
    [ "sleep" ],
    [ "nap" ],
    [ "snooze" ],
    [ "slide" ],
    [ "spray" ],
    [ "squeeze" ],
    [ "strike" ],
    [ "tell" ],
    [ "tortur" ],
    [ "unlock" ],
    [ "spells" ],
    [ "aimfiz" ],
    [ "frotz" ],
    [ "fweep" ],
    [ "gaspar" ],
    [ "gnusto" ],
    [ "golmac" ],
    [ "izyuk" ],
    [ "meef" ],
    [ "malyon" ],
    [ "pulver" ],
    [ "rezrov" ],
    [ "swanzo" ],
    [ "vardik" ],
    [ "vezza" ],
    [ "yomin" ],
    [ "yonk" ],
] # verbs

nouns = [
    [ "tree", "branch", "gnarled tree" ],
    [ "hellhound", "dog", "hound", "hellho" ],
    [ "boa", "constr", "snake", "boa constrictor" ],
    [ "sign", "signpost", "post", "signpo" ],
    [ "creatu", "snake", "group of unseen creatures", "snakes", "beetle" ],
    [ "moss and lichens", "moss", "lichen", "slime" ],
    [ "meadow", "field", "grass" ],
    [ "plague of locusts", "plague", "swarm", "locusts" ],
    [ "rapids", "waters", "river" ],
    [ "underg", "undergrowth" ],
    [ "banks", "river bank", "bank" ],
    [ "bed", "river bed" ],
    [ "falls", "fall", "waterf", "waterfall" ],
    [ "shit", "pile of bat guano", "pile", "guano" ],
    [ "label", "vials", "vial", "amber vial" ],
    [ "amber potion", "potion" ],
    [ "soiled scroll", "scroll" ],
    [ "spells", "fweep spell", "spell" ],
    [ "moat" ],
    [ "drawbr", "bridge", "wooden drawbridge" ],
    [ "rack", "pit", "torture devices", "device", "pendul" ],
    [ "letter", "vial", "label", "vials", "indigo vial" ],
    [ "indigo potion", "potion" ],
    [ "toll gate", "gate" ],
    [ "booth", "toll booth" ],
    [ "gnome", "pocket", "beard" ],
    [ "applia", "waxer", "floor waxer" ],
    [ "zorkmid tree", "branch", "twig", "tree", "bow" ],
    [ "coin", "toll", "zorkmid", "coins", "zorkmid coin" ],
    [ "dragon", "carvin", "carving of a dragon" ],
    [ "coal", "lumps of coal", "lumps" ],
    [ "bin", "coal bin" ],
    [ "upper coal chute", "chute" ],
    [ "lower coal chute", "chute" ],
    [ "strang", "self", "twin", "your older self", "older" ],
    [ "you" ],
    [ "your younger self", "younge", "self", "twin" ],
    [ "doors", "heavy door", "sign", "door" ],
    [ "dial", "combination dial" ],
    [ "rope", "coil" ],
    [ "timber", "wood", "beam", "beam of wood" ],
    [ "troglodyte", "troglo" ],
    [ "door", "kerosene lamp", "lamp", "compar", "bowl" ],
    [ "scroll", "smelly scroll" ],
    [ "vardik spell", "spells", "spell" ],
    [ "scroll", "shimmering scroll" ],
    [ "spells", "spell", "golmac spell" ],
    [ "shore", "beach", "sand" ],
    [ "waters", "ocean" ],
    [ "cove", "inlet", "lagoon" ],
    [ "clump", "weeds", "spense", "weed", "spenseweeds" ],
    [ "letter", "crate", "wooden crate", "label" ],
    [ "grue suit", "suit" ],
    [ "brass lantern", "lantern", "lamp" ],
    [ "repellent", "can", "can of grue repellent" ],
    [ "plants", "mass", "vine", "mass of wriggling vines", "vines" ],
    [ "pack of mutated grues", "pack", "grue", "grues" ],
    [ "device", "machin", "breeder", "plaque", "diabolic machinery" ],
    [ "knife", "diamond-studded knife", "dagger", "handle" ],
    [ "black marble door", "doors", "door" ],
    [ "doors", "shiny silver door", "door" ],
    [ "doors", "white wooden door", "door" ],
    [ "fortre", "fort", "rampar", "griffs" ],
    [ "flagpole", "flagpo", "pole" ],
    [ "flag of Quendor", "flag" ],
    [ "aqua vial", "vials", "label", "vial" ],
    [ "potion", "aqua potion" ],
    [ "cannon", "barrel" ],
    [ "pile of identical scrolls", "scroll", "pile" ],
    [ "ordinary scroll", "scroll" ],
    [ "spells", "yonk spell", "spell" ],
    [ "number", "intnum" ],
    [ "pseudo" ],
    [ "her", "him", "it", "that" ],
    [ "something" ],
    [ "cave-in", "dust and debris", "rubble", "dust", "debris" ],
    [ "ground", "field", "floor", "plateau" ],
    [ "highway", "path", "trail", "road" ],
    [ "tunnel", "corrid", "passag", "passage", "hallwa" ],
    [ "wall", "walls" ],
    [ "roof", "ceilin", "ceiling", "dome" ],
    [ "stairs", "stairw", "stairc", "stair" ],
    [ "hands", "your hand" ],
    [ "protagonist", "protag" ],
    [ "bat", "yourself" ],
    [ "enchan", "self", "yourself", "myself", "me" ],
    [ "lurking grue", "grue" ],
    [ "water", "pool", "trickle" ],
    [ "stars", "sky" ],
    [ "necromancer", "belboz", "Belboz" ],
    [ "room", "place", "chamber", "hall" ],
    [ "archwa", "doorway", "doorwa", "arch" ],
    [ "hole", "openin", "opening", "well" ],
    [ "forest", "woods", "trees", "blighted forest" ],
    [ "castle", "ruins", "egreth" ],
    [ "cave", "cavern" ],
    [ "Helistar", "helist" ],
    [ "Frobar", "frobar" ],
    [ "author", "meretz", "implem", "oracle" ],
    [ "demon", "spirit", "force", "jeearr", "Jeearr" ],
    [ "spell book", "book", "notes" ],
    [ "gnusto spell", "spells", "spell" ],
    [ "spells", "frotz spell", "spell" ],
    [ "spells", "rezrov spell", "spell" ],
    [ "yomin spell", "spells", "spell" ],
    [ "spells", "spell", "izyuk spell" ],
    [ "spells", "pulver spell", "spell" ],
    [ "vezza spell", "spells", "spell" ],
    [ "winks", "nap", "sleep", "snooze" ],
    [ "bed" ],
    [ "bird", "parrot", "polly", "pollib" ],
    [ "desk", "darkwood desk" ],
    [ "desk drawer", "drawer" ],
    [ "box", "lid", "writin", "tiny box" ],
    [ "aggthora", "jewel", "amulet", "magic amulet" ],
    [ "entrie", "diary", "notebo", "journa", "journal" ],
    [ "wheel", "infotater", "infota" ],
    [ "tapest", "wall hanging", "hangin" ],
    [ "small key", "key" ],
    [ "plant", "morgia plant", "plants" ],
    [ "scroll", "shiny scroll" ],
    [ "spells", "gaspar spell", "spell" ],
    [ "messag", "note", "scribbled note" ],
    [ "doors", "heavy wooden door", "door" ],
    [ "engrav", "list", "tenets", "tenet", "list of tenets" ],
    [ "recept", "mailbo", "receptacle" ],
    [ "enchan", "issue", "magazi", "label", "issue of Popular Enchanting" ],
    [ "letter", "orange vial", "vial", "label", "vials" ],
    [ "orange potion", "potion" ],
    [ "frobiz", "volume", "copy", "encycl", "copy of Encyclopedia Frobizzica" ],
    [ "scroll", "dusty scroll" ],
    [ "meef spell", "spells", "spell" ],
    [ "letter", "vial", "label", "vials", "ochre vial" ],
    [ "ochre potion", "potion" ],
    [ "cover", "matchb", "depleted matchbook", "printi", "matche" ],
    [ "calend", "legend", "calendar" ],
    [ "chest", "sturdy trunk", "lid", "trunk" ],
    [ "button", "star", "black button" ],
    [ "gray button", "button", "moon" ],
    [ "red button", "button", "knife" ],
    [ "button", "crown", "purple button" ],
    [ "button", "white button", "dove" ],
    [ "scroll", "moldy scroll" ],
    [ "aimfiz spell", "spells", "spell" ],
    [ "maze", "labyri", "glass maze" ],
    [ "hovel", "hut", "stone hovel" ],
    [ "firepl", "fireplace" ],
    [ "inscri", "statue" ],
    [ "chimney", "chimne" ],
    [ "shaft", "struct", "brick structure", "bricks", "openin" ],
    [ "quanti", "soot" ],
    [ "parchment scroll", "scroll" ],
    [ "swanzo spell", "spells", "spell" ],
    [ "ferocious dorn beast", "dorn", "dornbe", "beast", "dorns" ],
    [ "body", "corpse", "splattered body" ],
    [ "park", "amusement park", "bozbar" ],
    [ "gnome" ],
    [ "flumes", "flume" ],
    [ "log boat", "boat" ],
    [ "car" ],
    [ "hawker" ],
    [ "ball", "rubber ball" ],
    [ "bunnie", "bunny", "hopping bunny", "rabbit" ],
    [ "glittering scroll", "scroll" ],
    [ "malyon spell", "spells", "spell" ],
    [ "machin", "bandit", "odd machine", "displa" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Inside the Glass Maze",
    "Your Quarters",
    "Top of Falls",
    "Barracks",
    "Servants' Quarters",
    "Tree Room",
    "Twisted Forest",
    "Outside Store",
    "Pit of Bones",
    "Grue Lair",
    "Sooty Room",
    "Lobby",
    "Tree Branch",
    "Ocean Shore South",
    "Store Room",
    "Flume",
    "Crater",
    "End of Highway",
    "Shaft Bottom",
    "Belboz's Quarters",
    "Torture Chamber",
    "Surface of Lagoon",
    "Mammoth Cavern",
    "Elbow Room",
    "Chamber of Living Death",
    "Mine Field",
    "Winding Tunnel",
    "Park Entrance",
    "Store",
    "Dial Room",
    "River Bank",
    "Highway",
    "Lagoon Shore",
    "Belboz's Hideout",
    "Meadow",
    "Arcade",
    "Top of Chute",
    "Hidden Cave",
    "Hall of Carvings",
    "Near Stagnant Pool",
    "Armory",
    "Haunted House",
    "Drawbridge",
    "Edge of Chasm",
    "Hollow",
    "Slimy Room",
    "Lagoon Floor",
    "Hallway",
    "Cellar",
    "Turret",
    "Hall of Eternal Pain",
    "Slanted Room",
    "Entrance Hall",
    "Frobar's Quarters",
    "Dungeon",
    "West End of Midway",
    "East End of Midway",
    "Toll Gate",
    "Edge of Crater",
    "Library",
    "Helistar's Quarters",
    "Bare Passage",
    "Apprentice Quarters",
    "Parade Ground",
    "Coal Mine",
    "Snake Pit",
    "Chamber of the Circle",
    "Casino",
    "Shaft Top",
    "Mouth of River",
    "Outside Glass Arch",
    "Gun Emplacement",
    "Roller Coaster",
    "River Bed",
    "Bend",
    "Ocean Shore North",
    "Stone Hut",
    "Ruins",
    "Fort Entrance",
    "Coal Bin Room",
    "Forest Edge",
] # rooms

