# Config for SPELLBREAKER, in LLM style
#
#

[game]
path = "./infocom/spellbreaker/COMPILED/spellbreaker.z3"

setup = '''
spellbreaker is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "n", "north" ],
    [ "south", "s" ],
    [ "e", "east" ],
    [ "w", "west" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "ne", "northeast" ],
    [ "northwest", "nw" ],
    [ "southeast", "se" ],
    [ "southwest", "sw" ],
    [ "all", "both" ],
    [ "super", "superbrief" ],
    [ "inventory", "i" ],
    [ "quit", "q" ],
    [ "respond", "reply", "answer" ],
    [ "ask", "query", "quiz" ],
    [ "hit", "strike", "fight", "attack", "assault" ],
    [ "ride", "board", "embark" ],
    [ "ignite", "burn" ],
    [ "climb", "scale" ],
    [ "close", "zip", "shut" ],
    [ "traverse", "ford", "cross" ],
    [ "prune", "slash", "split", "slice", "sever", "divide", "cut" ],
    [ "shit", "fuck", "damn" ],
    [ "scratch", "break", "smash", "destroy", "crack", "wreck" ],
    [ "excavate", "dig" ],
    [ "debark", "disembark" ],
    [ "swallow", "drink", "sip" ],
    [ "release", "drop", "dump" ],
    [ "consume", "eat", "taste" ],
    [ "withdraw", "exit", "depart" ],
    [ "check", "describe", "inspect", "examine", "observe", "watch" ],
    [ "launch", "fly" ],
    [ "pursue", "follow", "chase" ],
    [ "unlearn", "forget" ],
    [ "hand", "feed", "offer", "give" ],
    [ "hi", "hello" ],
    [ "hint", "help" ],
    [ "hide", "conceal" ],
    [ "jump", "dive", "leap" ],
    [ "kill", "stab", "slay", "murder" ],
    [ "knock", "rap" ],
    [ "look", "l", "gaze", "stare" ],
    [ "thaw", "melt" ],
    [ "shift", "move" ],
    [ "tug", "pull", "drag" ],
    [ "open", "unzip" ],
    [ "clog", "block", "plug" ],
    [ "patch", "fix", "repair" ],
    [ "point", "gesture" ],
    [ "jab", "poke", "blind" ],
    [ "spill", "pour", "empty" ],
    [ "shove", "press", "push" ],
    [ "wedge", "lay", "put", "insert", "stuff", "place", "fit" ],
    [ "raise", "lift" ],
    [ "remove", "shed" ],
    [ "call", "talk", "say" ],
    [ "rummage", "search" ],
    [ "shake" ],
    [ "fire", "shoot" ],
    [ "sit", "rest", "meditate" ],
    [ "skip", "hop", "cavort", "gambol" ],
    [ "sniff", "smell" ],
    [ "whirl", "rotate", "spin" ],
    [ "rise", "stand" ],
    [ "swim", "wade", "bathe" ],
    [ "swing", "thrust" ],
    [ "catch", "take", "get", "hold", "carry", "snatch", "grab" ],
    [ "thanks", "thank" ],
    [ "throw", "pitch", "toss", "hurl" ],
    [ "fasten", "tie", "attach" ],
    [ "t", "time" ],
    [ "pet", "pat", "rub", "feel", "touch" ],
    [ "flip", "turn" ],
    [ "unfasten", "free", "unattach", "untie" ],
    [ "wait", "z" ],
    [ "rouse", "awake", "wake", "surprise", "startle" ],
    [ "walk", "proceed", "go", "run", "step" ],
    [ "wave" ],
    [ "yell", "scream", "shout" ],
    [ "cast", "invoke", "incant" ],
    [ "memorize", "learn" ],
    [ "inscribe", "write", "scribe", "print" ],
    [ "loosen", "lever", "pry" ],
    [ "bury", "plant" ],
    [ "yes", "y", "okay" ],
    [ "nope", "no" ],
    [ "purchase", "buy" ],
    [ "slaver", "drool", "gurgle", "salivate" ],
    [ "admire", "compliment" ],
    [ "bargain", "haggle" ],
    [ "sympathize", "empathize" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restar" ],
    [ "restor" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "apply" ],
    [ "bite" ],
    [ "blow" ],
    [ "descen" ],
    [ "lie" ],
    [ "compare" ],
    [ "count" ],
    [ "enter" ],
    [ "extinguish" ],
    [ "fill" ],
    [ "find" ],
    [ "inflat" ],
    [ "kick" ],
    [ "kiss" ],
    [ "land" ],
    [ "lean" ],
    [ "leave" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "roll" ],
    [ "pay" ],
    [ "play" ],
    [ "pick" ],
    [ "pump" ],
    [ "reach" ],
    [ "read" ],
    [ "send" ],
    [ "sharpen" ],
    [ "show" ],
    [ "sleep" ],
    [ "nap" ],
    [ "snooze" ],
    [ "slide" ],
    [ "squeeze" ],
    [ "tell" ],
    [ "tortur" ],
    [ "unlock" ],
    [ "wear" ],
    [ "what" ],
    [ "where" ],
    [ "who" ],
    [ "yawn" ],
    [ "spells" ],
    [ "frotz" ],
    [ "gnusto" ],
    [ "malyon" ],
    [ "rezrov" ],
    [ "yomin" ],
    [ "blorple" ],
    [ "lesoch" ],
    [ "snavig" ],
    [ "girgol" ],
    [ "jindak" ],
    [ "espnis" ],
    [ "caskly" ],
    [ "liskon" ],
    [ "throck" ],
    [ "tinsot" ],
    [ "label" ],
    [ "sell" ],
    [ "trade" ],
    [ "lurk" ],
    [ "erase" ],
    [ "copy" ],
    [ "love" ],
    [ "pray" ],
] # verbs

nouns = [
    [ "spell book", "notes", "book" ],
    [ "blorple spell", "spells", "spell" ],
    [ "lesoch spell", "spells", "spell" ],
    [ "snavig spell", "spells", "spell" ],
    [ "scroll", "flimsy scroll" ],
    [ "girgol spell", "spells", "spell" ],
    [ "jindak spell", "spells", "spell" ],
    [ "dusty scroll", "scroll" ],
    [ "espnis spell", "spells", "spell" ],
    [ "white scroll", "scroll" ],
    [ "tinsot spell", "spells", "spell" ],
    [ "scroll", "dirty scroll" ],
    [ "throck spell", "spells", "spell" ],
    [ "scroll", "stained scroll" ],
    [ "spells", "spell", "caskly spell" ],
    [ "scroll", "damp scroll" ],
    [ "spells", "liskon spell", "spell" ],
    [ "malyon spell", "spells", "spell" ],
    [ "gnusto spell", "spells", "spell" ],
    [ "frotz spell", "spells", "spell" ],
    [ "rezrov spell", "spells", "spell" ],
    [ "yomin spell", "spells", "spell" ],
    [ "original", "spells", "spell" ],
    [ "scroll", "vellum scroll" ],
    [ "burin", "engrave", "magic burin", "scribe" ],
    [ "cubes", "cube" ],
    [ "serpent", "snake", "creature", "mass" ],
    [ "idol", "statue", "rodent idol", "sculpture", "god" ],
    [ "teeth", "fangs", "fang" ],
    [ "mouth", "maw" ],
    [ "opal eye", "eye" ],
    [ "eye", "shard", "opal shard", "fragment" ],
    [ "aabbcc", "zipper" ],
    [ "channel" ],
    [ "pipe", "inflow pipe", "pipes" ],
    [ "pipe", "outflow pipe", "pipes" ],
    [ "stone hut", "entrance", "building", "hut", "stone" ],
    [ "man", "hermit" ],
    [ "track", "cliff", "path", "trail" ],
    [ "rock", "rocks", "avalanche", "boulder" ],
    [ "cave", "cavern" ],
    [ "latch", "box", "symbol", "gold box", "lid" ],
    [ "ogre" ],
    [ "grouper nest", "rocks", "coral", "nest", "pile" ],
    [ "bottle" ],
    [ "grouper", "fish" ],
    [ "berg", "ice floe", "icefloe", "iceberg", "floe" ],
    [ "pipe", "channel" ],
    [ "crack", "chunk" ],
    [ "door", "trap door", "opening" ],
    [ "bureau", "massive cabinet", "cabinet" ],
    [ "key", "wrought iron key" ],
    [ "book", "moldy book" ],
    [ "talons", "dot", "roc", "bird" ],
    [ "roc egg", "egg" ],
    [ "roc", "roc chick", "chick" ],
    [ "door", "shop door" ],
    [ "zm", "coin", "gold coin", "money", "zorkmid" ],
    [ "salesman", "man", "merchant" ],
    [ "carpet", "rug", "scruffy red carpet" ],
    [ "carpet", "rug", "beautiful blue carpet" ],
    [ "label" ],
    [ "fragment", "lava fragment" ],
    [ "outcropping" ],
    [ "glyphs", "pillar" ],
    [ "mechanism", "door", "vault door" ],
    [ "iron door", "door" ],
    [ "vases", "treasure", "gold", "jewels" ],
    [ "junk", "paste", "pile of junk", "gilt", "lead" ],
    [ "alarm fairy", "fairy" ],
    [ "first pile", "piles", "pile" ],
    [ "piles", "second pile", "pile" ],
    [ "lines", "scratch", "line" ],
    [ "rock", "green eyed rock", "boulder" ],
    [ "rock", "boulder", "brown eyed rock" ],
    [ "shears", "pair of pruning shears" ],
    [ "weed", "plant", "ragweed", "tree" ],
    [ "engrave", "carving", "inset" ],
    [ "knob", "arm", "rose", "compass rose", "arms" ],
    [ "rune", "north rune", "runes" ],
    [ "rune", "east rune", "runes" ],
    [ "rune", "west rune", "runes" ],
    [ "rune", "south rune", "runes" ],
    [ "rune", "northeast rune", "runes" ],
    [ "rune", "northwest rune", "runes" ],
    [ "rune", "southeast rune", "runes" ],
    [ "rune", "southwest rune", "runes" ],
    [ "hole", "door", "octagonal hole" ],
    [ "alabaster plug", "plug" ],
    [ "bag", "sack" ],
    [ "cell door", "door" ],
    [ "qword", "handwritten word" ],
    [ "number", "intnum" ],
    [ "pseudo" ],
    [ "them", "object", "it", "him" ],
    [ "it" ],
    [ "lights", "light", "photons" ],
    [ "hole" ],
    [ "ceilin", "roof", "ceiling" ],
    [ "ice" ],
    [ "air" ],
    [ "hands", "your hand" ],
    [ "face", "your head", "head" ],
    [ "your eyes", "eye", "eyes" ],
    [ "it", "protag" ],
    [ "i", "myself", "self", "me", "yourself" ],
    [ "chamber", "room", "place" ],
    [ "wall", "north wall" ],
    [ "wall", "east wall" ],
    [ "wall", "west wall" ],
    [ "wall", "south wall" ],
    [ "northeast wall", "wall" ],
    [ "northwest wall", "wall" ],
    [ "wall", "southeast wall" ],
    [ "wall", "southwest wall" ],
    [ "rubble", "dust", "dirt", "debris" ],
    [ "floor", "ground", "field" ],
    [ "exit", "passage", "corridor" ],
    [ "walls", "wall" ],
    [ "lurking grue", "grue" ],
    [ "grues", "shapes", "troop", "grue" ],
    [ "water" ],
    [ "belboz", "necromancer", "Belboz" ],
    [ "sleep", "nap" ],
    [ "magic" ],
    [ "knife", "dagger" ],
    [ "chunk of rye bread", "bread", "chunk", "food", "loaf" ],
    [ "herring", "smoked fish", "food", "fish", "sardine" ],
    [ "sorcerer", "enchanter", "mage", "mages" ],
    [ "orator", "speaker", "guildmaster" ],
    [ "Orkan of Thriff", "orkan" ],
    [ "sneffle", "Sneffle", "baker" ],
    [ "Hoobly", "hoobly", "brewer" ],
    [ "Gzornenplatz", "huntsman", "gzornenplatz" ],
    [ "poet", "Ardis", "ardis" ],
    [ "shadow", "shadowy figure", "figure", "being", "twin" ],
    [ "smoke", "cloud of orange smoke", "cloud" ],
    [ "construction", "hypercube", "tesseract", "square", "construct" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Soft Room",
    "In Channel",
    "Mid-Ocean",
    "Guild Hall",
    "Oubliette",
    "No Place",
    "String Room",
    "Wilderness",
    "Light Room",
    "Open Ocean",
    "Nondescript Room",
    "Dark Room",
    "Boulder",
    "Ruined Pipe",
    "Changing Room",
    "Ocean Floor",
    "Fire Room",
    "Dark Cave",
    "In Pipe",
] # rooms

