# Config for Starcross, in an LLM style
#
#

########
## GAME
########
[game]
path = "./infocom/starcross/COMPILED/starcross.z3"

# setup text copied from wikipedia
setup = '''
The player's ship, the Starcross, is fitted with a mass detector to look for "quantum black holes", which are such powerful sources of energy that one could provide a wealth of riches. When the mass detector finally discovers an anomaly, however, it is not a black hole but something else entirely: a massive craft of unknown origin and composition.

The player must dock with the mysterious ship and gain entry to its interior. Once inside, the player discovers a wide variety of alien plant and animal species and an array of unfamiliar technology. 
'''

# text files giving descriptions 
background_files = [
    ["./infocom/starcross/manual.rno",
    "INTRODUCTION(.*)the one-sixth gravity of Luna."
    ],
    ["./infocom/starcross/starcross.txt",
    "THE SHIP FROM THE STARS(.*)a circular Earth orbit..."
    ],
]

background_urls = [
]

## Not making use of the walkthrough, so far
walkthrough_urls = [
]

[syntax]
verbs = [
    [ "using", "through", "with" ],
    [ "in", "into", "inside" ],
    [ "underneath", "under", "beneath" ],
    [ "n", "foreward", "fore", "north", "f", "forward" ],
    [ "aft", "south", "s" ],
    [ "cw", "sb", "east", "starboard", "e" ],
    [ "west", "w", "ccw", "p", "port" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "superbrief", "super" ],
    [ "inventory", "i" ],
    [ "quit", "q" ],
    [ "reply", "answer" ],
    [ "injure", "fight", "attack", "hurt", "hit" ],
    [ "recline", "sit", "lay", "climb", "lie" ],
    [ "stand" ],
    [ "curse", "damn" ],
    [ "drink", "imbibe", "swallow" ],
    [ "drop", "release" ],
    [ "eat", "taste", "bite" ],
    [ "whats", "examine", "describe", "what" ],
    [ "seek", "where", "find", "see" ],
    [ "blast", "shoot", "fire", "burn", "zap" ],
    [ "follow", "pursue", "chase" ],
    [ "offer", "hand", "give", "feed", "donate" ],
    [ "hi", "hello" ],
    [ "leap", "jump" ],
    [ "dispatch", "stab", "slay", "kill", "murder" ],
    [ "rap", "knock" ],
    [ "intercept", "dock", "land", "rendezvous" ],
    [ "gaze", "l", "look", "stare" ],
    [ "sort", "sift", "search", "rummage" ],
    [ "move" ],
    [ "point", "aim", "gesture" ],
    [ "pull", "tug" ],
    [ "break", "block", "smash", "destroy", "damage" ],
    [ "plug", "patch", "repair", "glue", "fix" ],
    [ "jab", "blind", "poke" ],
    [ "press", "push" ],
    [ "insert", "put", "stuff", "place" ],
    [ "lift", "raise" ],
    [ "rape", "molest" ],
    [ "read", "skim" ],
    [ "pat", "feel", "rub", "pet", "touch" ],
    [ "skip", "hop" ],
    [ "smell", "sniff" ],
    [ "wade", "swim", "bathe" ],
    [ "hold", "carry", "get", "take" ],
    [ "ask", "tell" ],
    [ "grin", "smile" ],
    [ "talk", "say" ],
    [ "hurl", "throw", "chuck", "toss" ],
    [ "fasten", "tie", "buckle", "attach", "hook", "secure" ],
    [ "flip", "turn", "shut" ],
    [ "plot", "set" ],
    [ "untie", "unbuckle", "free", "detach", "unhook", "unattach", "unfasten" ],
    [ "surprise", "wake", "startle", "awake" ],
    [ "walk", "proceed", "go", "run" ],
    [ "brandish", "wave" ],
    [ "wear", "don" ],
    [ "shout", "scream", "yell" ],
    [ "y", "yes", "confirm", "affirmative" ],
    [ "cancel", "negative", "no" ],
    [ "r", "range" ],
    [ "angle", "theta" ],
    [ "elevation", "phi" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "version" ],
    [ "verbose" ],
    [ "again" ],
    [ "apply" ],
    [ "board" ],
    [ "close" ],
    [ "dig" ],
    [ "disembark" ],
    [ "enter" ],
    [ "exit" ],
    [ "fly" ],
    [ "blow" ],
    [ "kick" ],
    [ "kiss" ],
    [ "launch" ],
    [ "leave" ],
    [ "listen" ],
    [ "lock" ],
    [ "empty" ],
    [ "lower" ],
    [ "play" ],
    [ "open" ],
    [ "pick" ],
    [ "reach" ],
    [ "script" ],
    [ "unscript" ],
    [ "shake" ],
    [ "slide" ],
    [ "step" ],
    [ "strike" ],
    [ "remove" ],
    [ "unlock" ],
    [ "wait" ],
    [ "zork" ],
    [ "is" ],
    [ "report" ],
] # verbs

nouns = [
    [ "number", "intnum" ],
    [ "pseudo" ],
    [ "him", "random object", "that", "this", "it" ],
    [ "planters", "box", "planter", "boxes", "plant" ],
    [ "steps", "stairs", "stairway", "ladder" ],
    [ "dirt", "floor", "ground", "earth" ],
    [ "debris", "garbage", "leaves" ],
    [ "pair of hands", "hands", "pair" ],
    [ "adventurer", "cretin" ],
    [ "myself", "me", "self", "we", "you" ],
    [ "registration" ],
    [ "status", "situation", "report" ],
    [ "artifact" ],
    [ "alarm", "bell" ],
    [ "button", "red button" ],
    [ "mass detector", "screen", "detector" ],
    [ "button", "blue button" ],
    [ "map", "mass detector output", "chart", "output" ],
    [ "program", "course" ],
    [ "um08", "mass UM08" ],
    [ "mass UM12", "um12" ],
    [ "mass UM24", "um24" ],
    [ "mass UM28", "um28" ],
    [ "um31", "mass UM31" ],
    [ "um52", "mass UM52" ],
    [ "um70", "mass UM70" ],
    [ "um91", "mass UM91" ],
    [ "mass AB40", "ab40", "ceres" ],
    [ "ax87", "mass AX87" ],
    [ "ax32", "mass AX32" ],
    [ "ax01", "mass AX01" ],
    [ "mass AX71", "ax71" ],
    [ "ship US75", "us75" ],
    [ "Mars", "mars" ],
    [ "spaces", "ship", "starcross" ],
    [ "control couch", "seat", "couch" ],
    [ "seat belt", "belt", "seatbelt" ],
    [ "console", "panel", "control" ],
    [ "viewport", "porthole", "window", "port" ],
    [ "bunk", "bed", "cot" ],
    [ "space suit", "suit", "spaces" ],
    [ "suit", "spaces", "tattered suit" ],
    [ "rope", "safety line", "line" ],
    [ "hook" ],
    [ "airlock" ],
    [ "outer door", "door", "bulkhead" ],
    [ "door", "bulkhead", "inner door" ],
    [ "power", "computer" ],
    [ "instruction sheet", "instructions", "sheet", "paper" ],
    [ "tape library", "player", "vcr", "library", "recorder" ],
    [ "rods", "key", "rod", "black rod" ],
    [ "red outer door", "door", "airlock", "bulkhead" ],
    [ "metal relief", "bumps", "relief", "sculpture", "surface" ],
    [ "bump", "eighth, ninth, or tenth bumps", "column" ],
    [ "bump", "first, second, third, fourth, fifth, sixth, or seventh bumps", "column" ],
    [ "small bump", "hexagon", "bump", "column" ],
    [ "red inner door", "door", "airlock", "bulkhead" ],
    [ "giant spider", "spider", "besnap", "gurthark" ],
    [ "rods", "yellow rod", "object", "rod", "key" ],
    [ "object", "translator" ],
    [ "airlock", "blue outer door", "door" ],
    [ "airlock", "blue inner door", "door", "bulkhead" ],
    [ "bulkhead", "door", "airlock", "yellow outer door" ],
    [ "alien", "reptile", "scorched alien" ],
    [ "rods", "key", "rod", "pink rod" ],
    [ "airlock", "door", "yellow inner door", "bulkhead" ],
    [ "door", "airlock", "bulkhead", "green outer door" ],
    [ "green inner door", "door", "airlock", "bulkhead" ],
    [ "piece", "fragment", "black visor fragment" ],
    [ "rods", "rod", "key", "clear rod", "rainbow" ],
    [ "laser", "projector", "holographic projector" ],
    [ "light beam", "energy", "light", "beam" ],
    [ "planet", "system", "model" ],
    [ "alien", "chieftain", "weasel chieftain", "chief" ],
    [ "rods", "brown rod", "rod", "key" ],
    [ "alien", "alien tribesmen", "aliens", "weasel" ],
    [ "palisade", "wall" ],
    [ "receptacle", "sweeper", "mouse", "maintenance mouse" ],
    [ "sweeper", "maintenance mouse", "receptacle", "tray", "mouse" ],
    [ "hole", "door", "mouse hole" ],
    [ "disk", "disks", "red disk" ],
    [ "disk", "blue disk", "disks" ],
    [ "dial" ],
    [ "field", "globe", "ball", "silver sphere", "sphere" ],
    [ "field", "bowl" ],
    [ "apparatus", "projector" ],
    [ "beam of energy", "beam" ],
    [ "rods", "blue rod", "rod", "key" ],
    [ "trash bin", "bin" ],
    [ "rods", "green rod", "rod", "key" ],
    [ "alien skeleton", "skeleton" ],
    [ "violet rod", "rods", "rod", "key" ],
    [ "sign", "chewed sign" ],
    [ "lurking grue", "grue" ],
    [ "nest" ],
    [ "nest", "smashed nest" ],
    [ "rods", "red rod", "rod", "key" ],
    [ "ant", "rat-ant" ],
    [ "computer" ],
    [ "power", "on-off switch", "switch" ],
    [ "access panel", "panel" ],
    [ "slot", "hole" ],
    [ "metal and ceramic square", "card", "square" ],
    [ "rods", "rod", "gold rod", "key" ],
    [ "gun", "raygun", "barrel", "ray gun" ],
    [ "rods", "silver rod", "rod", "key" ],
    [ "tree" ],
    [ "slot", "hole", "spot", "silver slot" ],
    [ "slot", "hole", "white slot", "panel" ],
    [ "slot", "black slot", "hole", "panel" ],
    [ "rods", "white rod", "rod", "key" ],
    [ "hatch", "door" ],
    [ "unicorn" ],
    [ "cover", "hatch", "door", "metal hatch" ],
    [ "wall" ],
    [ "bubble" ],
    [ "slot", "hole", "gold slot" ],
    [ "drive bubble", "bubble" ],
    [ "control bubble", "bubble" ],
    [ "slot", "hole", "brown slot" ],
    [ "slot", "hole", "pink slot" ],
    [ "slot", "hole", "green slot" ],
    [ "slot", "blue slot", "hole" ],
    [ "slot", "violet slot", "hole" ],
    [ "screen", "pink screen" ],
    [ "small pink square", "square" ],
    [ "large pink square", "square" ],
    [ "button", "spot", "brown spot" ],
    [ "button", "spot", "green spot" ],
    [ "blue spot", "button", "spot" ],
    [ "violet spot", "spot", "button" ],
    [ "slot", "hole", "crystal slot" ],
    [ "basket", "pocket", "rack", "metal basket", "carton" ],
    [ "spear", "spears" ],
    [ "hut", "huts" ],
    [ "cycad", "shrub", "vegetation", "conifer", "grass" ],
    [ "button", "indicators", "control", "dials", "gauges" ],
    [ "bars", "cage", "cages" ],
    [ "funeral offering", "totems", "fetish", "fruits", "grain" ],
    [ "knobs", "protrusion", "handhold", "knob" ],
    [ "enunciator panel", "light", "panel", "lights", "symbol" ],
    [ "slot", "hole", "yellow slot" ],
    [ "red slot", "hole", "slot" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Green Airlock",
    "On Control Bubble",
    "Top of Tree",
    "Observatory",
    "Drive Bubble",
    "Blue Airlock",
    "Green Hall",
    "Red Dock",
    "Zoo",
    "On Drive Bubble",
    "Room on Ring Two",
    "Yellow Airlock",
    "Village Center",
    "In the Warren",
    "Floating in Air",
    "Control Bubble",
    "Control Bubble Entrance",
    "Bridge",
    "Broken Cage",
    "Computer Room",
    "Nesting Cage",
    "Garage",
    "Dense Forest",
    "Yellow Dock",
    "Outskirts of Village",
    "Red Airlock",
    "Bubbles",
    "Spherical Ship",
    "Control Room",
    "Up a Tree",
    "Metal Floor",
    "Cargo Hold",
    "Inside Grue Cage",
    "Fore End",
    "Village Suburbs",
    "Room on Ring Four",
    "Airlock",
    "Laboratory",
    "Drive Bubble Entrance",
    "Blue Dock",
    "Center of the Warren",
    "Yellow Hall",
    "Floating in Space",
    "Thin Forest",
    "Repair Room",
    "Among Debris",
    "Melted Spot",
    "Green Dock",
    "Guard Room",
    "Umbilical",
    "Room on Ring One",
    "Red Hall",
    "Weapons Deck",
    "Grassland",
    "Outside Ship",
    "Living Quarters",
    "Blue Hall",
    "Storage",
    "Base of Tree",
] # rooms

