# Config for STATIONFALL, in LLM style
#
#

[game]
path = "./infocom/stationfall/COMPILED/s6.z3                                                            "

setup = '''
stationfall is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "everyt", "all", "both" ],
    [ "f", "north", "fore", "n" ],
    [ "aft", "s", "south" ],
    [ "sb", "east", "starboard", "e" ],
    [ "port", "west", "w", "p" ],
    [ "down", "downstairs", "d" ],
    [ "up", "u", "upstairs" ],
    [ "nw", "northwest" ],
    [ "northe", "ne" ],
    [ "southwest", "sw" ],
    [ "southe", "se" ],
    [ "super", "superbrief" ],
    [ "invent", "i" ],
    [ "q", "quit" ],
    [ "status", "score" ],
    [ "reply", "answer" ],
    [ "applaud", "clap" ],
    [ "slap", "strike", "hit", "stab", "attack", "fight", "slay", "kill" ],
    [ "trap", "catch" ],
    [ "climb", "scale" ],
    [ "shut", "seal", "close" ],
    [ "attach", "connect" ],
    [ "cross", "ford" ],
    [ "demoli", "break", "damage", "destro", "smash", "pop", "wreck" ],
    [ "unplug", "disconnect", "detach" ],
    [ "dismount", "disembark", "debark" ],
    [ "release", "drop", "dump" ],
    [ "gobble", "swallow", "drink", "eat", "ingest", "devour" ],
    [ "watch", "describe", "examine", "inspect", "observe", "study" ],
    [ "withdr", "depart", "exit" ],
    [ "extinguish", "stop", "deactivate" ],
    [ "find", "seek" ],
    [ "repair", "fix" ],
    [ "uncrumple", "flatten", "straighten", "uncrease" ],
    [ "chase", "pursue", "follow" ],
    [ "sell", "hand", "offer", "give", "donate" ],
    [ "hello", "hi" ],
    [ "hints", "help", "hint" ],
    [ "jump", "leap", "vault", "dive" ],
    [ "knock", "rap" ],
    [ "look", "l" ],
    [ "pull", "move", "lead" ],
    [ "nah", "no", "nope", "uh-uh" ],
    [ "open", "unseal" ],
    [ "shine", "aim", "point" ],
    [ "spill", "pour" ],
    [ "iron", "push", "press" ],
    [ "lift", "raise", "boost" ],
    [ "browse", "read", "skim" ],
    [ "save", "rescue" ],
    [ "rummag", "search" ],
    [ "zap", "blast", "shoot", "fire" ],
    [ "skip", "hop" ],
    [ "doze", "sleep", "nap", "snooze" ],
    [ "slice", "cut" ],
    [ "smell", "whiff", "sniff" ],
    [ "rise", "stand" ],
    [ "start", "activa" ],
    [ "insert", "place", "stuff", "stick", "put" ],
    [ "get", "take", "grab", "hold", "carry" ],
    [ "talk", "speak" ],
    [ "taste", "lick", "nibble" ],
    [ "thanks", "thank" ],
    [ "throw", "toss", "hurl" ],
    [ "time", "t" ],
    [ "pat", "poke", "pet", "touch", "feel", "stroke", "scratch" ],
    [ "rotate", "turn", "dial", "spin", "set", "switch", "flip", "tune", "flick" ],
    [ "undres", "strip" ],
    [ "valida", "stamp" ],
    [ "wait", "z" ],
    [ "wake", "rouse", "awake" ],
    [ "procee", "sidle", "step", "run", "walk" ],
    [ "wipe", "wash", "clean" ],
    [ "don", "wear" ],
    [ "whos", "what", "who", "whats" ],
    [ "wheres", "where" ],
    [ "scream", "yell", "shout" ],
    [ "ok", "sure", "yup", "yes", "okay", "y" ],
    [ "sneeze", "zork" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagno" ],
    [ "restar" ],
    [ "restor" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "apply" ],
    [ "approa" ],
    [ "ask" ],
    [ "attract" ],
    [ "bite" ],
    [ "blow" ],
    [ "board" ],
    [ "burn" ],
    [ "call" ],
    [ "circle" ],
    [ "come" ],
    [ "comfort" ],
    [ "compar" ],
    [ "cover" ],
    [ "count" ],
    [ "crumpl" ],
    [ "descen" ],
    [ "dig" ],
    [ "dress" ],
    [ "drill" ],
    [ "empty" ],
    [ "enter" ],
    [ "exercise" ],
    [ "feed" ],
    [ "fill" ],
    [ "footnote" ],
    [ "greet" ],
    [ "go" ],
    [ "hear" ],
    [ "hide" ],
    [ "hug" ],
    [ "kick" ],
    [ "kiss" ],
    [ "launch" ],
    [ "leave" ],
    [ "let" ],
    [ "lie" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "maybe" ],
    [ "measure" ],
    [ "pick" ],
    [ "play" ],
    [ "plug" ],
    [ "pray" ],
    [ "reach" ],
    [ "remove" ],
    [ "roll" ],
    [ "say" ],
    [ "scare" ],
    [ "scold" ],
    [ "shake" ],
    [ "show" ],
    [ "sit" ],
    [ "slide" ],
    [ "spray" ],
    [ "swing" ],
    [ "tap" ],
    [ "tell" ],
    [ "tickle" ],
    [ "tie" ],
    [ "type" ],
    [ "unlock" ],
    [ "untie" ],
    [ "use" ],
    [ "wrap" ],
] # verbs

nouns = [
    [ "it", "zzmgck" ],
    [ "it" ],
    [ "direction", "direct" ],
    [ "number", "three", "one", "two" ],
    [ "pseudo" ],
    [ "it", "them" ],
    [ "her", "herself", "himself", "him" ],
    [ "ground", "floor", "deck" ],
    [ "walls", "wall" ],
    [ "ceilin", "roof", "ceiling" ],
    [ "air" ],
    [ "store", "room", "office", "shop" ],
    [ "port", "viewport", "window" ],
    [ "sign" ],
    [ "equipment", "machin" ],
    [ "stall", "sanfac fixture", "bathtub", "stalls", "shower" ],
    [ "hole" ],
    [ "ladder" ],
    [ "hands", "finger", "your hand", "hand" ],
    [ "your tongue", "tongue" ],
    [ "it", "protag" ],
    [ "self", "me", "yourself", "myself", "i" ],
    [ "everybody", "everyone", "crew" ],
    [ "hucka", "game", "hider", "games" ],
    [ "beast", "lurking grue", "grue" ],
    [ "keypad" ],
    [ "desk" ],
    [ "wardrobe" ],
    [ "cubicle" ],
    [ "village" ],
    [ "bed", "beds" ],
    [ "sleep", "nap", "snooze" ],
    [ "hull welder", "welder" ],
    [ "Assignment Completion Form QX-17-T", "form", "qx-17-t", "forms" ],
    [ "Robot Use Authorization Form JZ-59-G", "jz-59-g", "form", "forms" ],
    [ "form", "Class Three Spacecraft Activation Form HB-56-V", "hb-56-v", "forms" ],
    [ "watch", "chronometer", "wristwatch" ],
    [ "cards", "ID card", "card" ],
    [ "pocket", "Patrol uniform", "uniform" ],
    [ "box", "boxes", "pallet", "pallets of boxes" ],
    [ "compar", "three", "robot", "Floyd", "floyd" ],
    [ "robot", "two", "helen", "Helen" ],
    [ "one", "robot", "rex", "Rex" ],
    [ "spacetruck", "truck", "spacecraft" ],
    [ "spacetruck hatch", "hatch", "door" ],
    [ "copilot seat", "seat", "chair" ],
    [ "pilot seat", "seat", "chair" ],
    [ "radio", "SB radio" ],
    [ "survival kit", "kit" ],
    [ "Thermos bottle", "thermos", "bottle" ],
    [ "food", "soup", "blue soup" ],
    [ "goo", "blob of gray goo", "blob", "custard", "food" ],
    [ "goo", "yogurt", "blob", "blob of orange goo", "food" ],
    [ "bedistor", "twenty-ohm bedistor" ],
    [ "frequency", "jammer", "sockets" ],
    [ "dispen", "machin", "dispenser" ],
    [ "bit", "large drill bit", "bits" ],
    [ "timer" ],
    [ "board", "system monitor board" ],
    [ "log reader", "recorder", "reader", "machin" ],
    [ "log", "tape", "log tape", "notation" ],
    [ "safe", "lock" ],
    [ "key" ],
    [ "stamp", "validation stamp" ],
    [ "zapgun", "gun", "fusor-beam zapgun" ],
    [ "spool", "lilac nanofilm spool", "nanofilm", "spools" ],
    [ "machin", "exercise machine" ],
    [ "dryer" ],
    [ "presser" ],
    [ "spool", "puce nanofilm spool", "nanofilm", "spools" ],
    [ "seven-pointed star", "star" ],
    [ "hyperdiode", "diodes", "M-series hyperdiode", "diode" ],
    [ "eternal flame", "flame" ],
    [ "pulpit" ],
    [ "switch" ],
    [ "unit", "fdu", "fpu", "dispen", "Food Processing and Dispensing Unit" ],
    [ "coffee", "cup of coffee", "cup" ],
    [ "detonator" ],
    [ "hyperdiode", "diodes", "blackened hyperdiode", "diode" ],
    [ "magazine" ],
    [ "reader", "nanofilm reader" ],
    [ "shrubbery", "plants", "garden", "shrubs" ],
    [ "storage bin", "bin", "lock" ],
    [ "grating", "grate", "shaft", "cover", "air shaft grating" ],
    [ "dot", "spot", "pattern of dots", "spots", "dots" ],
    [ "pedestal" ],
    [ "skeleton", "alien skeleton" ],
    [ "heating chamber", "chamber" ],
    [ "bit", "medium drill bit", "bits" ],
    [ "Oliver", "robot", "oliver" ],
    [ "spool", "mauve nanofilm spool", "nanofilm", "spools" ],
    [ "can", "trash can", "pail" ],
    [ "fw-83-q", "form", "crumpled form", "forms" ],
    [ "neatly ironed Illegal Space Village Entry Form FW-83-Q", "form", "fw-83-q", "forms" ],
    [ "drill" ],
    [ "bit", "small drill bit", "bits" ],
    [ "elevator" ],
    [ "elevator shaft", "shaft" ],
    [ "button" ],
    [ "door", "auto-door" ],
    [ "security door", "door" ],
    [ "box", "ID reader", "reader" ],
    [ "notebook", "diary" ],
    [ "twenty-prong fromitz board", "prongs", "boards", "board" ],
    [ "note" ],
    [ "holding tank", "tank" ],
    [ "Plato", "robot", "plato" ],
    [ "volume", "tome", "Plato's volume of poetry", "poetry", "book" ],
    [ "ray", "stun ray", "raygun", "gun" ],
    [ "lift", "forklift" ],
    [ "pyramid" ],
    [ "iris hatch", "hatch" ],
    [ "crystal ball", "ball" ],
    [ "simulation booth", "cylind", "booth", "booths", "chamber" ],
    [ "lamp", "light", "headlamp" ],
    [ "foil", "reflective foil", "platinum", "piece" ],
    [ "bag", "plastic bag" ],
    [ "vacuum taffy", "taffy", "food" ],
    [ "cage" ],
    [ "Arcturian balloon creature", "creature", "pet" ],
    [ "leash" ],
    [ "panel", "ceiling panel" ],
    [ "stick", "nip", "stick of ostrich nip" ],
    [ "instruction sheet", "sheet" ],
    [ "prongs", "boards", "twelve-prong fromitz board", "board" ],
    [ "hyperdiode", "diodes", "diode", "J-series hyperdiode" ],
    [ "scrap sculpture", "sculpture" ],
    [ "roulette wheel", "wheel" ],
    [ "pair", "pair of dice", "dice" ],
    [ "locker" ],
    [ "space suit", "suit" ],
    [ "counter" ],
    [ "nectar", "cup", "cup of nectar", "food" ],
    [ "textbook", "book" ],
    [ "piece", "piece of paper", "paper" ],
    [ "platinum detector", "detector" ],
    [ "door", "hatch", "inner door" ],
    [ "door", "hatch", "outer door" ],
    [ "airlock" ],
    [ "explosive", "cylind", "label" ],
    [ "spray can", "can" ],
    [ "box", "strong box", "lock" ],
    [ "galakmid", "coin" ],
    [ "pet", "bird", "pile", "ostrich" ],
    [ "letter" ],
    [ "innocuous machine", "machin" ],
    [ "pair of magnetic boots", "pair", "boots", "spaceboots" ],
    [ "junk", "garbage", "trash", "pile" ],
] # nouns

rooms = [
    "Laundry",
    "Auxiliary Barracks",
    "Level Five",
    "Astro Lab",
    "South Junction",
    "Mayor's Office",
    "Barracks SanFac",
    "Officers' Quarters B",
    "Cargo Bay",
    "Gym",
    "Auxiliary SanFac",
    "Scientists' Quarters",
    "In Space",
    "Opium Den",
    "Grimy Passage",
    "Tube",
    "Workshop",
    "Rec Shop",
    "Astro Office",
    "Meeting Room 1",
    "Mess Hall",
    "Top of Air Shaft",
    "Greasy Straw",
    "Level Six",
    "Officers' Quarters C",
    "Bank",
    "End of Corridor",
    "Airlock",
    "Officers' Quarters A",
    "Factory",
    "Armory",
    "Shaft at Level Nine",
    "Holding Tank Level",
    "Studio",
    "Casino",
    "Docking Bay #2",
    "Fortune Teller",
    "Flophouse",
    "Junk Yard",
    "Engineering Lab",
    "Level Four",
    "East Junction",
    "Main Storage",
    "Robot Shop",
    "Pawn Shop",
    "Field Office",
    "Station Control",
    "Air Shaft",
    "Bio Office",
    "North Connection",
    "Female Barracks",
    "Cargo Bay Entrance",
    "Officers SanFac",
    "Bottom of Air Shaft",
    "Broadway",
    "Grocery",
    "Level Three",
    "Printing Plant",
    "Sick Bay",
    "Main Street",
    "Warehouse",
    "Saloon",
    "Meeting Room 2",
    "Makeshift Connector",
    "Docking Bay #4",
    "Engineering Office",
    "Elevator",
    "Trading Post",
    "Alley",
    "Bio Lab",
    "Briefing Room",
    "Loan Shark",
    "Missionary",
    "Male Barracks",
    "Storage",
    "Library",
    "Pet Store",
    "North Junction",
    "Docking Bay #3",
    "Chapel",
    "Paper Recycling Plant",
] # rooms

