# Config for SUSPENDED, in LLM style
#
#

[game]
path = "./infocom/suspended/COMPILED/suspended.z3"

setup = '''
suspended is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "through", "using", "with" ],
    [ "in", "inside", "into" ],
    [ "north", "n" ],
    [ "south", "s" ],
    [ "e", "east" ],
    [ "w", "west" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "inventory", "i" ],
    [ "q", "quit" ],
    [ "harder", "expert", "advanced" ],
    [ "reply", "answer" ],
    [ "attack", "injure", "hurt", "hit", "fight" ],
    [ "lie", "recline", "lay", "climb", "sit" ],
    [ "stand" ],
    [ "count", "total" ],
    [ "curse", "damn" ],
    [ "cut", "snip", "slice" ],
    [ "swallow", "imbibe", "drink" ],
    [ "drop", "release" ],
    [ "taste", "bite", "eat" ],
    [ "examine", "analyze", "describe" ],
    [ "where", "seek", "find", "see" ],
    [ "zap", "shoot", "burn", "fire", "blast" ],
    [ "follow", "pursue", "chase" ],
    [ "hand", "donate", "offer", "feed", "give" ],
    [ "hi", "hello" ],
    [ "help", "hint" ],
    [ "setup", "configure", "custom" ],
    [ "jump", "leap" ],
    [ "kill", "murder", "slay", "stab", "dispatch" ],
    [ "knock", "rap" ],
    [ "l", "gaze", "stare", "look" ],
    [ "sift", "sort", "rummage", "search" ],
    [ "move" ],
    [ "point", "aim" ],
    [ "tug", "pull", "drag", "yank" ],
    [ "destroy", "break", "damage", "block", "smash" ],
    [ "link", "plug" ],
    [ "jab", "blind", "poke" ],
    [ "press", "push" ],
    [ "put", "stuff", "position", "insert", "place" ],
    [ "ask", "query", "whats", "what" ],
    [ "lift", "raise" ],
    [ "rape", "molest" ],
    [ "read", "skim" ],
    [ "repair", "fix" ],
    [ "trade", "exchange", "swap", "replace" ],
    [ "pet", "pat", "rub" ],
    [ "skip", "hop" ],
    [ "sniff", "smell" ],
    [ "swim", "bathe", "wade" ],
    [ "carry", "grasp", "hold", "take", "steal", "get" ],
    [ "grin", "smile" ],
    [ "toss", "throw", "hurl", "chuck" ],
    [ "touch", "feel" ],
    [ "flip", "turn", "shut" ],
    [ "set" ],
    [ "surprise", "startle", "awake", "wake" ],
    [ "walk", "run", "go", "proceed", "travel" ],
    [ "halt", "stop" ],
    [ "brandish", "wave" ],
    [ "install", "wear", "don" ],
    [ "shout", "yell", "scream" ],
    [ "confirm", "yes", "affirmative", "y" ],
    [ "no" ],
    [ "report", "r" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "version" ],
    [ "apply" ],
    [ "attach" ],
    [ "board" ],
    [ "close" ],
    [ "dig" ],
    [ "disembark" ],
    [ "enter" ],
    [ "exit" ],
    [ "why" ],
    [ "fly" ],
    [ "blow" ],
    [ "impossible" ],
    [ "kick" ],
    [ "kiss" ],
    [ "leave" ],
    [ "listen" ],
    [ "location" ],
    [ "lower" ],
    [ "play" ],
    [ "open" ],
    [ "pick" ],
    [ "unplug" ],
    [ "reach" ],
    [ "script" ],
    [ "unscript" ],
    [ "shake" ],
    [ "slide" ],
    [ "step" ],
    [ "strike" ],
    [ "detach" ],
    [ "remove" ],
    [ "activate" ],
    [ "wait" ],
    [ "zork" ],
    [ "is" ],
    [ "arr" ],
    [ "arl" ],
    [ "rl" ],
] # verbs

nouns = [
    [ "number", "intnum" ],
    [ "listening", "listen" ],
    [ "dragging", "draggi" ],
    [ "backwa", "left", "back" ],
    [ "right", "forward" ],
    [ "loc", "location" ],
    [ "pseudo" ],
    [ "her", "that", "him", "it", "random object" ],
    [ "robot", "robots", "Iris", "iris" ],
    [ "robots", "robot", "waldo", "Waldo" ],
    [ "sensa", "robot", "robots", "Sensa" ],
    [ "Auda", "auda", "robot", "speaker", "robots" ],
    [ "poet", "Poet", "robots", "robot" ],
    [ "robots", "whiz", "robot", "Whiz" ],
    [ "Two Robots" ],
    [ "mechan", "People", "object", "humans", "creatu" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Hell",
    "UD Tube",
] # rooms

