# Config for SUSPECT, in LLM style
#
#

[game]
path = "./infocom/suspect/COMPILED/suspect.z3"

setup = '''
suspect is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "with", "using" ],
    [ "through", "thru" ],
    [ "inside", "into", "in" ],
    [ "under", "underneath", "beneath" ],
    [ "north", "n" ],
    [ "south", "s" ],
    [ "east", "e" ],
    [ "west", "w" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "again", "g" ],
    [ "check", "dust", "test", "analyze" ],
    [ "reply", "answer" ],
    [ "question", "inquire", "ask" ],
    [ "fight", "attack", "hit" ],
    [ "wipe", "brush", "clean", "wash" ],
    [ "burn", "ignite", "incinerate" ],
    [ "phone", "call", "dial" ],
    [ "climb" ],
    [ "compare", "match" ],
    [ "count" ],
    [ "damn", "piss", "hell", "curse", "fuck", "shit" ],
    [ "cut", "pierce", "slice" ],
    [ "destroy", "break", "smash", "damage" ],
    [ "imbibe", "sip", "guzzle", "swig", "swallow", "drink" ],
    [ "drop" ],
    [ "eat", "taste", "sample", "consume" ],
    [ "describe", "examine", "inspect" ],
    [ "where", "find", "seen", "there" ],
    [ "chase", "trace", "follow", "pursue" ],
    [ "donate", "offer", "hand", "give" ],
    [ "handcuff", "cuff" ],
    [ "hi", "hello" ],
    [ "crouch", "hide" ],
    [ "i", "inventory" ],
    [ "taunt", "kick", "bite" ],
    [ "kill" ],
    [ "rap", "knock" ],
    [ "l", "look", "stare", "gaze" ],
    [ "mix", "make" ],
    [ "pick", "pry" ],
    [ "pour", "spill" ],
    [ "tug", "drag", "pull" ],
    [ "push", "press" ],
    [ "place", "put", "stuff", "insert" ],
    [ "q", "quit" ],
    [ "lift", "raise" ],
    [ "rape", "molest", "assault" ],
    [ "skim", "read", "peruse" ],
    [ "ring", "peal" ],
    [ "shade", "rub", "touch", "pet", "pat", "feel" ],
    [ "talk", "say" ],
    [ "dig", "search" ],
    [ "show", "confront" ],
    [ "hurt", "punch", "injure", "slap" ],
    [ "sniff", "smell" ],
    [ "super", "superbrief" ],
    [ "grab", "steal", "lead", "carry", "get", "hold", "take" ],
    [ "explain", "tell" ],
    [ "thanks", "thank" ],
    [ "chuck", "throw", "toss", "hurl" ],
    [ "fasten", "secure", "attach", "tie" ],
    [ "time", "t" ],
    [ "flip", "turn", "shut" ],
    [ "unattach", "untie", "unfasten", "unhook", "free", "uncuff" ],
    [ "version", "release" ],
    [ "z", "stay", "wait" ],
    [ "revive", "awake", "resuscitate", "wake" ],
    [ "run", "proceed", "go", "walk" ],
    [ "what", "whats", "who" ],
    [ "did", "when", "why", "how" ],
    [ "yes", "no", "y", "maybe" ],
    [ "continue", "c" ],
    [ "was", "is" ],
    [ "reveal", "disclose" ],
    [ "accuse" ],
    [ "arrest" ],
    [ "order" ],
    [ "brief" ],
    [ "close" ],
    [ "dance" ],
    [ "diagnose" ],
    [ "enter" ],
    [ "fingerprint" ],
    [ "flush" ],
    [ "goodbye" ],
    [ "hang" ],
    [ "help" ],
    [ "interview" ],
    [ "jump" ],
    [ "kiss" ],
    [ "know" ],
    [ "stand" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "move" ],
    [ "open" ],
    [ "peek" ],
    [ "wear" ],
    [ "remove" ],
    [ "restart" ],
    [ "restore" ],
    [ "revive" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "sit" ],
    [ "space" ],
    [ "strike" ],
    [ "unlock" ],
    [ "unmask" ],
    [ "unscript" ],
    [ "unspace" ],
    [ "use" ],
    [ "verbose" ],
    [ "join" ],
    [ "watch" ],
    [ "wave" ],
    [ "write" ],
    [ "tip" ],
] # verbs

nouns = [
    [ "her", "them", "him", "him or her", "group" ],
    [ "you", "himself or herself", "herself", "himself", "yourself" ],
    [ "such things" ],
    [ "reporter" ],
    [ "reporter", "myself", "me", "yourself" ],
    [ "costume", "western outfit", "outfit" ],
    [ "holster", "loop", "gunbelt", "loops" ],
    [ "pen" ],
    [ "notebook", "notes" ],
    [ "overcoat", "coat", "reporter's overcoat" ],
    [ "Michael", "wellman", "michael", "mike", "sheik" ],
    [ "Veronica", "veronica", "titania", "ashcroft", "queen" ],
    [ "veronica", "corpse", "Veronica's body", "body", "titania" ],
    [ "bullet", "silver bullet", "object" ],
    [ "costume", "fairy costume", "titania" ],
    [ "stain" ],
    [ "cloth", "cloth sample", "sample" ],
    [ "fairy mask", "mask" ],
    [ "hair", "dark hair" ],
    [ "Veronica's hair", "hair" ],
    [ "Alicia's hair", "hair" ],
    [ "Linda's hair", "hair" ],
    [ "vital signs", "signs", "breath", "pulse" ],
    [ "police", "cops" ],
    [ "girl", "Alicia", "alicia", "barron" ],
    [ "overcoat", "coat", "wet overcoat" ],
    [ "label" ],
    [ "Alicia's car", "car" ],
    [ "lasso", "lariat", "lariat (no, you left it with your coat)", "rope" ],
    [ "lasso", "lariat", "rope" ],
    [ "richard", "ashcroft", "Richard", "werewolf" ],
    [ "explorer", "hunter", "marston", "Colonel Marston", "robert" ],
    [ "meade", "linda", "ballerina", "Linda" ],
    [ "asher", "alan", "al", "harlequin", "Senator Asher" ],
    [ "Cochrane", "astronaut", "cochrane", "bill", "spaceman" ],
    [ "vampire", "samuel", "sam", "ostmann", "Ostmann" ],
    [ "Smythe", "butler", "smythe", "gorilla" ],
    [ "trashbasket", "basket", "trash basket", "trash" ],
    [ "bartender", "johnson", "jack", "Johnson", "domino" ],
    [ "refill", "liquor", "drink" ],
    [ "detective" ],
    [ "hair analysis", "analysis" ],
    [ "analysis", "mask analysis" ],
    [ "analysis", "stain analysis" ],
    [ "irrelevant analysis", "analysis" ],
    [ "glass analysis", "analysis" ],
    [ "trenchcoat", "coat" ],
    [ "Sergeant Duffy", "duffy" ],
    [ "raincoat", "coat" ],
    [ "car", "police car" ],
    [ "western mask", "mask" ],
    [ "costume", "mask", "sheik costume" ],
    [ "costume", "harem costume", "mask" ],
    [ "ballerina costume", "mask", "costume" ],
    [ "costume", "werewolf costume", "mask" ],
    [ "costume", "mask", "harlequin costume" ],
    [ "costume", "mask", "explorer costume" ],
    [ "costume", "mask", "astronaut costume" ],
    [ "costume", "mask", "vampire costume" ],
    [ "costume", "gorilla costume", "mask" ],
    [ "pumpkin" ],
    [ "door", "front door" ],
    [ "bell", "doorbell" ],
    [ "bell", "doorbell", "front doorbell" ],
    [ "velvet ribbon", "ribbon" ],
    [ "door", "east entry hall door" ],
    [ "west entry hall door", "door" ],
    [ "desk", "secretary" ],
    [ "window seat", "seat" ],
    [ "door", "morning room door" ],
    [ "table", "end table" ],
    [ "sitting room door", "door" ],
    [ "west closet door", "door" ],
    [ "wicker hamper", "hamper" ],
    [ "east closet door", "door" ],
    [ "guest", "party guest", "devil" ],
    [ "door", "east bath door" ],
    [ "door", "media room door" ],
    [ "television", "projection TV", "tv" ],
    [ "record", "VCR", "vcr" ],
    [ "bookcase", "shelf", "shelves" ],
    [ "tapes", "videotape" ],
    [ "west office door", "door" ],
    [ "door", "north office door" ],
    [ "south office door", "door" ],
    [ "large desk", "desk" ],
    [ "desk", "small desk" ],
    [ "file cabinet", "cabinet" ],
    [ "shelf", "shelves", "trash", "papers" ],
    [ "prizes", "prize", "ribbon", "office debris", "toner" ],
    [ "computer" ],
    [ "floppies", "disk", "disks" ],
    [ "sale" ],
    [ "folder", "manila folder" ],
    [ "purchase and sale agreement", "agreement" ],
    [ "trust" ],
    [ "trust folder", "folder" ],
    [ "papers", "sheaf of documents", "documents", "sheaf" ],
    [ "paper", "sheet", "sheet of paper", "list" ],
    [ "marble fireplace", "fireplace", "fire", "chimney" ],
    [ "picture", "portrait", "faces" ],
    [ "mantel" ],
    [ "rug", "oriental rug" ],
    [ "north library door", "door" ],
    [ "table", "side table" ],
    [ "chair", "armchair", "comfy chair" ],
    [ "book", "paperback book" ],
    [ "pots", "plant", "pot", "plants" ],
    [ "chandelier" ],
    [ "table" ],
    [ "board", "sideboard" ],
    [ "china cabinet", "cabinet" ],
    [ "door", "back door" ],
    [ "workbench", "bench" ],
    [ "mercedes", "Mercedes 280SL", "car", "280sl" ],
    [ "BMW 320i", "bmw", "car", "320i" ],
    [ "trunk", "BMW's trunk" ],
    [ "trunk", "Mercedes' trunk" ],
    [ "tool chest", "chest", "toolchest" ],
    [ "crowbar" ],
    [ "alarm", "burglar alarm" ],
    [ "Ballroom", "ballroom" ],
    [ "bar" ],
    [ "band" ],
    [ "player", "record player" ],
    [ "music" ],
    [ "fieldstone fireplace", "fireplace", "fire", "chimney" ],
    [ "house", "doghouse" ],
    [ "doberman", "dog", "pinscher", "Doberman pinscher" ],
    [ "door", "north hallway door" ],
    [ "west hall door", "door" ],
    [ "door", "west bath door" ],
    [ "door", "linen closet door" ],
    [ "garage door", "door", "doors" ],
    [ "door", "walkway door" ],
    [ "sun room door", "door" ],
    [ "door", "east hall door" ],
    [ "door", "french door", "doors" ],
    [ "door", "glass", "window", "sliding glass door" ],
    [ "door", "barn door" ],
    [ "such thing" ],
    [ "they", "it", "he", "she" ],
    [ "number", "intnum" ],
    [ "sky", "weather", "clouds", "rain" ],
    [ "midnight" ],
    [ "handcuffs", "handcuff", "cuffs", "cuff" ],
    [ "water" ],
    [ "phone", "telephone" ],
    [ "fingerprints", "print", "fingerprint", "prints" ],
    [ "basin", "sink", "tap" ],
    [ "stall", "bath", "shower" ],
    [ "toilet" ],
    [ "here" ],
    [ "corridor", "hall", "hallway" ],
    [ "floor", "room" ],
    [ "death", "killing", "dead", "murder" ],
    [ "theft", "embezzlement" ],
    [ "horses", "grue", "horse" ],
    [ "goblet", "glass", "broken glass" ],
    [ "film", "liquid" ],
    [ "receipt", "costume receipt" ],
    [ "shop", "Costumes Unlimited" ],
    [ "jack", "Jack" ],
    [ "editor", "Earl Davis Jackson", "jackson" ],
    [ "business card", "card" ],
    [ "basket", "wastebasket", "waste basket" ],
    [ "heated discussion", "discussion", "argument" ],
    [ "cab", "taxi" ],
    [ "hands" ],
    [ "food", "oeuvres", "munchies" ],
    [ "armchair", "chair" ],
    [ "couch", "sofa" ],
    [ "curtains" ],
    [ "window" ],
    [ "house" ],
    [ "key", "keys" ],
    [ "stairs", "stair" ],
    [ "party" ],
    [ "richard", "ashcroft", "werewolf" ],
    [ "zzkjlk" ],
] # nouns

rooms = [
    "Back Porch",
    "Sun Room",
    "West Coat Closet",
    "Hall at Office",
    "Entry Hall",
    "Near Fireplace",
    "Front Hall West",
    "West of House",
    "Dining Room",
    "Sitting Room",
    "Near Kitchen",
    "Outside House",
    "Front Hall",
    "Patio",
    "Hall at Dining Room",
    "Back Entry",
    "Near Bar",
    "North Hall",
    "Media Room",
    "Linen Closet",
    "Library",
    "Near French Door",
    "Living Room",
    "Garage",
    "South Entrance",
    "Kitchen",
    "Garden",
    "North Entrance",
    "Near Band",
    "Hall Near Bath",
    "Dance Floor",
    "Circular Driveway",
    "North of House",
    "Morning Room",
    "East Coat Closet",
    "Front Porch",
    "Police Laboratory",
    "West End of Hallway",
    "Hall Near Coat Closet",
    "Covered Walkway",
    "Barn",
    "Pond",
    "East Hall End",
    "East Bath",
    "Front Hall East",
    "Center Entrance",
    "Office",
    "West of Garage",
    "West Bath",
    "East Hall at Bath",
] # rooms

