# Config for WISHBRINGER, in LLM style
#
#

[game]
path = "./infocom/wishbringer/COMPILED/j2.z3"

setup = '''
wishbringer is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "corridor", "hallway", "hall" ],
    [ "east", "e", "right" ],
    [ "w", "west", "left" ],
    [ "nuts", "mixed", "nut" ],
    [ "to", "toward" ],
    [ "using", "with" ],
    [ "thru", "through" ],
    [ "on", "onto" ],
    [ "between", "into", "inside", "beyond", "in" ],
    [ "out", "outside" ],
    [ "beneath", "under", "underneath", "below" ],
    [ "along", "around" ],
    [ "both", "everything", "all" ],
    [ "across", "over" ],
    [ "north", "n" ],
    [ "s", "south" ],
    [ "d", "down" ],
    [ "up", "u" ],
    [ "southw", "ne", "northw", "northe", "southe" ],
    [ "superbrief", "super" ],
    [ "i", "inventory" ],
    [ "q", "quit" ],
    [ "time", "t" ],
    [ "g", "again" ],
    [ "respond", "reply", "answer" ],
    [ "question", "query", "quiz", "interrogate", "ask" ],
    [ "fight", "attack", "assault", "injure", "hurt" ],
    [ "ignite", "burn" ],
    [ "clean", "sweep" ],
    [ "scale", "climb" ],
    [ "slam", "close" ],
    [ "tally", "count" ],
    [ "cross", "traverse" ],
    [ "tear", "rip", "cut", "slash" ],
    [ "smash", "destroy", "wreck", "erase", "demolish", "damage", "crack", "break", "trash" ],
    [ "dig", "excavate" ],
    [ "drink", "guzzle", "sip" ],
    [ "drop", "dump" ],
    [ "gobble", "devour", "eat", "consume", "swallow", "nibble" ],
    [ "enter" ],
    [ "withdraw", "depart", "scram", "exit" ],
    [ "examine" ],
    [ "quench", "douse", "extinguish", "snuff" ],
    [ "seek", "find" ],
    [ "follow", "pursue", "chase" ],
    [ "hand", "offer", "present", "bestow", "show", "give", "donate", "deliver" ],
    [ "farewell", "salute", "hi", "goodbye", "afternoon", "bye", "greet", "hello", "greetings" ],
    [ "aid", "help" ],
    [ "hide", "conceal" ],
    [ "hint", "hints" ],
    [ "leap", "dive", "jump" ],
    [ "kill", "slap", "whack", "slay", "hit", "murder", "punch", "wound", "strike", "stab" ],
    [ "kiss", "smooch" ],
    [ "knock", "rap", "pound" ],
    [ "recline", "lie" ],
    [ "stare", "gaze", "peek", "peer", "l", "look" ],
    [ "shift", "roll", "move" ],
    [ "unseal", "open" ],
    [ "shove", "yank", "tug", "pull", "drag" ],
    [ "entice", "bribe", "pay" ],
    [ "fiddle", "play", "cavort", "toy" ],
    [ "gesture", "point" ],
    [ "poke", "blind", "jab" ],
    [ "spill", "pour", "sprinkle" ],
    [ "push", "nudge", "press", "thrust" ],
    [ "put", "wedge", "stuff", "force", "stash", "place", "insert", "lay" ],
    [ "lift", "raise", "hoist", "elevate" ],
    [ "defile", "molest", "ravish", "rape", "hump" ],
    [ "skim", "read" ],
    [ "detach", "release", "unfasten", "free", "unhook", "undo", "untie" ],
    [ "rescue", "preserve" ],
    [ "grovel", "bow", "kneel" ],
    [ "utter", "call", "say", "speak", "talk" ],
    [ "rummage", "ransack", "search", "frisk" ],
    [ "shake", "jostle", "rattle" ],
    [ "shoot" ],
    [ "sit", "squat" ],
    [ "sleep", "nap", "rest", "snooze" ],
    [ "smell", "sniff" ],
    [ "whirl", "spin", "rotate" ],
    [ "squash", "squeeze", "crush" ],
    [ "rise", "stand" ],
    [ "bathe", "wade", "swim" ],
    [ "snatch", "carry", "hold", "take", "seize", "get", "confiscate", "grab", "steal", "catch" ],
    [ "thank", "thanks" ],
    [ "fling", "toss", "hurl", "throw", "chuck", "pitch" ],
    [ "attach", "fasten", "tie", "secure" ],
    [ "rub", "pet", "pat", "disturb", "touch", "feel" ],
    [ "flip", "turn", "set" ],
    [ "employ", "exploit", "use" ],
    [ "wait", "loiter", "z" ],
    [ "wake", "awaken", "surprise", "rouse", "awake", "startle" ],
    [ "step", "crawl", "run", "advanc", "hike", "tramp", "hop", "walk", "proceed", "trudge", "skip", "go" ],
    [ "smile", "grin", "wave", "nod", "laugh", "sneer" ],
    [ "don", "wear" ],
    [ "yearn", "hope", "dream", "wish" ],
    [ "shout", "scream", "yell", "howl" ],
    [ "affirm", "yup", "y", "nope", "okay", "sure", "ok", "positi", "yes", "nay", "negative", "naw", "no", "aye" ],
    [ "nw" ],
    [ "se" ],
    [ "sw" ],
    [ "verbose" ],
    [ "brief" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "back" ],
    [ "bite" ],
    [ "blow" ],
    [ "buy" ],
    [ "ascend" ],
    [ "descend" ],
    [ "shut" ],
    [ "fill" ],
    [ "fly" ],
    [ "feed" ],
    [ "hear" ],
    [ "heel" ],
    [ "cover" ],
    [ "kick" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "pray" ],
    [ "pick" ],
    [ "empty" ],
    [ "reach" ],
    [ "remove" ],
    [ "replace" ],
    [ "ride" ],
    [ "swing" ],
    [ "taste" ],
    [ "tell" ],
    [ "unlock" ],
] # verbs

nouns = [
    [ "lid", "mailbox", "big mailbox", "box" ],
    [ "lid", "boxes", "mailbox", "little mailbox", "box" ],
    [ "boots", "patrol" ],
    [ "Bridge" ],
    [ "covered bridge", "bridge" ],
    [ "arch", "sign" ],
    [ "North of Bridge" ],
    [ "troll", "creature" ],
    [ "toll gate", "gate" ],
    [ "Cliff Bottom" ],
    [ "face", "wall", "cliff" ],
    [ "dead branch", "branch" ],
    [ "bird", "vulture" ],
    [ "trunk", "gnarled tree trunk", "tree" ],
    [ "Creepy Corner" ],
    [ "Spooky Copse" ],
    [ "Twilight Glen" ],
    [ "iron gate", "gate", "gates", "bars", "lock" ],
    [ "Open Grave" ],
    [ "cemetery", "graveyard" ],
    [ "monuments", "tombstone", "stone", "tombstones", "stones" ],
    [ "hole", "grave", "open grave" ],
    [ "bough", "willow tree", "trees", "boughs", "tree" ],
    [ "vapor", "mists", "mist", "vapors", "eldritch vapor" ],
    [ "hole", "opening" ],
    [ "head", "handle", "umbrella" ],
    [ "trees", "tree" ],
    [ "Rotary East" ],
    [ "cinema", "building", "theater", "movie theater", "theatre" ],
    [ "marquee" ],
    [ "door", "lock", "entry", "entrance" ],
    [ "ticket", "stub" ],
    [ "Theater Lobby" ],
    [ "lobby" ],
    [ "carton", "box" ],
    [ "prices", "schedule", "list", "showtimes" ],
    [ "Inside Theater" ],
    [ "chair", "seat", "seats", "chairs" ],
    [ "aisles", "aisle" ],
    [ "pair", "pair of 3D glasses", "spectacles", "sunglasses", "glasses" ],
    [ "movie", "show", "screen", "movie screen", "film" ],
    [ "Park" ],
    [ "water", "fountain" ],
    [ "coin", "money", "gold coin", "gold" ],
    [ "fish", "goldfish" ],
    [ "piranha", "fish" ],
    [ "statue", "commemoration", "fathers", "woman" ],
    [ "center", "town", "village" ],
    [ "Rotary West" ],
    [ "building", "headqu", "police station", "office", "statio" ],
    [ "door", "police station door", "lock", "entry", "entrance" ],
    [ "Police Station" ],
    [ "drawer", "desk" ],
    [ "police radio", "radio" ],
    [ "candy", "piece of chocolate", "piece", "chocolate" ],
    [ "Rotary South" ],
    [ "building", "library" ],
    [ "library door", "door", "lock", "entry", "entrance" ],
    [ "paper", "violet note", "slip", "note" ],
    [ "Circulation Desk" ],
    [ "circulation desk", "desk" ],
    [ "museum", "hall" ],
    [ "clutter of books", "book", "books" ],
    [ "Museum" ],
    [ "display", "exhibits", "exhibit" ],
    [ "fossil", "boxes", "fossil exhibit", "exhibit", "mailbox" ],
    [ "case", "display case" ],
    [ "hole", "chaos", "sculpture" ],
    [ "being", "old woman", "one", "lady", "woman" ],
    [ "Rotary North" ],
    [ "Church" ],
    [ "speaker", "loudspeaker" ],
    [ "candle", "light" ],
    [ "church door", "door", "lock", "entry", "entrance" ],
    [ "church", "synago", "building", "temple" ],
    [ "debris", "glass", "bits" ],
    [ "Jail Cell" ],
    [ "cells", "cell" ],
    [ "bars", "cell door", "lock", "door" ],
    [ "furniture", "bunk", "bed" ],
    [ "blanket", "thick blanket" ],
    [ "cement", "hole", "concrete", "opening" ],
    [ "underside", "bunk", "bed", "bottom" ],
    [ "Pleasure Wharf" ],
    [ "Wharf's End" ],
    [ "sharks", "fin", "fins", "shark" ],
    [ "sea", "water", "bay", "ocean" ],
    [ "Video Arcade" ],
    [ "arcade", "building", "entry", "entrance" ],
    [ "humanoids", "stunted humanoids" ],
    [ "machine", "game", "game machine", "unit", "logo" ],
    [ "grid", "screen", "video screen", "map", "message" ],
    [ "blinking star", "star", "cursor" ],
    [ "slot" ],
    [ "stick", "joystick" ],
    [ "switch", "big red button", "button" ],
    [ "brass token", "token" ],
    [ "Tidal Pool" ],
    [ "conch shell", "shell" ],
    [ "beach", "sand", "bank" ],
    [ "Lighthouse" ],
    [ "beacon", "lighthouse", "house" ],
    [ "Fog" ],
    [ "Steep Trail" ],
    [ "number", "intnum" ],
    [ "pseudo" ],
    [ "that", "it" ],
    [ "grime", "filth", "dust", "dirt" ],
    [ "floor", "lawn", "ground", "grass" ],
    [ "road", "street", "path" ],
    [ "wall", "walls" ],
    [ "ceiling" ],
    [ "your hand", "hands", "hand" ],
    [ "protag", "yourself" ],
    [ "i", "me", "myself", "yourself" ],
    [ "room", "area", "place" ],
    [ "post", "message", "sign", "signpost" ],
    [ "corner" ],
    [ "voices", "music", "voice", "sound" ],
    [ "her", "she" ],
    [ "he", "him" ],
    [ "them", "they" ],
    [ "direction" ],
    [ "silver whistle", "whistle" ],
    [ "Misty Island" ],
    [ "Throne Room" ],
    [ "wizard's hat", "hat" ],
    [ "tasmania", "Princess Tasmania", "platypus" ],
    [ "platypus", "King Anatinus", "anatinus" ],
    [ "crowd" ],
    [ "building", "palace", "castle", "entrance" ],
    [ "that", "fireplace", "scepter", "chest", "throne" ],
    [ "stone", "light", "rock", "small stone", "wishbringer" ],
    [ "Flight", "flight" ],
    [ "freedom", "Freedom" ],
    [ "rain", "rainwater" ],
    [ "foresight", "Foresight" ],
    [ "Luck", "luck" ],
    [ "Advice", "advice" ],
    [ "darkness", "dark" ],
    [ "moon" ],
    [ "West of House" ],
    [ "house" ],
    [ "front door", "door", "boards", "entry", "entrance" ],
    [ "mail", "advert", "leaflet", "ad" ],
    [ "Rocky Path" ],
    [ "river", "water" ],
    [ "South of Bridge" ],
    [ "that" ],
    [ "boss", "man", "postmaster", "Mr. Crisp", "crisp" ],
    [ "gravedigger", "man", "digger" ],
    [ "Sgt. MacGuffin", "man", "macguffin" ],
    [ "Miss Voss", "voss", "lady", "woman" ],
    [ "purse", "book", "books", "things", "Miss Voss's things" ],
    [ "horse", "seahorse" ],
    [ "horse", "dead seahorse", "seahorse" ],
    [ "pelican", "bird" ],
    [ "lady", "gail", "old woman", "woman" ],
    [ "Cliff Edge" ],
    [ "building", "shop", "Magick Shoppe", "store", "shoppe" ],
    [ "door", "Magick Shoppe door", "lock", "entry", "entrance" ],
    [ "Magick Shoppe" ],
    [ "clock", "grandfather clock", "dial", "moon", "time" ],
    [ "magic tricks", "paraph", "tricks", "trick", "puzzle" ],
    [ "cards", "joke", "card", "naughty jokes", "jokes" ],
    [ "case", "glass case" ],
    [ "curtain" ],
    [ "mail", "mysterious envelope", "letter", "envelope" ],
    [ "mysterious envelope", "envelope" ],
    [ "mail", "letter" ],
    [ "metal can", "nuts", "lid", "can" ],
    [ "nuts", "lid", "squashed can", "can" ],
    [ "false bottom", "bottom" ],
    [ "pussy", "Chaos", "kitty", "chaos", "cat" ],
    [ "End of Story" ],
    [ "Hilltop" ],
    [ "hill", "hilltop" ],
    [ "building", "Post Office", "office" ],
    [ "door", "Post Office door", "lock", "entry", "entrance" ],
    [ "Post Office" ],
    [ "service counter", "counter" ],
    [ "poster", "wanted poster" ],
    [ "Outside Cemetery" ],
    [ "Outside Cottage" ],
    [ "mutt", "poodle", "dog" ],
    [ "mutt", "hound", "dog", "hellhound" ],
    [ "alexis", "Alexis" ],
    [ "bone", "old bone" ],
    [ "cottage door", "door", "lock", "entry", "entrance" ],
    [ "cottage", "building", "home", "house" ],
    [ "Cottage" ],
    [ "case", "bookcase" ],
    [ "steel key", "key" ],
    [ "scrawled message", "message" ],
    [ "book", "photos", "photographs", "books", "books and photographs" ],
    [ "tower" ],
    [ "walkway", "drawbridge", "bridge" ],
    [ "moat", "water" ],
    [ "stair", "steps", "stairway", "stairs" ],
    [ "Round Chamber" ],
    [ "series", "painting", "pictur", "series of paintings", "sequence" ],
    [ "metal crank", "crank" ],
    [ "hallway", "hall", "corridor", "entrance" ],
    [ "Vestibule" ],
    [ "hatchway", "door", "hatch" ],
    [ "ladder" ],
    [ "Torture Chamber" ],
    [ "medical instrument", "instruments" ],
    [ "shackles", "bonds", "chain", "chains" ],
    [ "jacket", "white lab coat", "smock", "coat" ],
    [ "rusty key", "key" ],
    [ "clamps", "machine", "clamp", "mechanism", "torture machine" ],
    [ "lever" ],
    [ "Fuzziness" ],
    [ "Laboratory" ],
    [ "scope", "antique telescope", "telescope" ],
    [ "window" ],
    [ "kitten", "black cat", "kitty", "cat" ],
    [ "ice", "chemicals", "water" ],
    [ "panel", "control panel" ],
    [ "second switch", "switch" ],
    [ "switch", "first switch" ],
    [ "broomstick", "broom" ],
    [ "Underground" ],
    [ "Grue's Nest" ],
    [ "beast", "little beast", "animal", "grub", "grue" ],
    [ "refrigerator", "fridge", "frige" ],
    [ "bottle" ],
    [ "milk", "liquid", "grue milk" ],
    [ "earthworm", "worm" ],
    [ "debris", "bone", "bones", "swords" ],
    [ "fog", "mist", "isle", "island" ],
    [ "Lake Edge" ],
    [ "x", "sand", "tracks", "message" ],
    [ "hole", "trap", "pit", "snare" ],
    [ "pile of leaves", "leaves" ],
    [ "tasmania", "platypus" ],
    [ "River Outlet" ],
    [ "trail" ],
    [ "Lookout Hill" ],
    [ "underside", "stump" ],
    [ "shoe", "horseshoe" ],
    [ "pond", "lake", "water" ],
    [ "zzzp" ],
] # nouns

rooms = [
] # rooms

