# Config for WITNESS, in LLM style
#
#

[game]
path = "./infocom/witness/COMPILED/witness.z3"

setup = '''
witness is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "using", "with" ],
    [ "through", "thru" ],
    [ "in", "inside", "into" ],
    [ "beneath", "under", "underneath" ],
    [ "north", "n" ],
    [ "south", "s" ],
    [ "e", "east" ],
    [ "w", "west" ],
    [ "d", "down" ],
    [ "up", "u" ],
    [ "test", "analyse", "dust", "check", "analyze" ],
    [ "answer", "reply" ],
    [ "ask", "question", "inquire" ],
    [ "fight", "attack" ],
    [ "wipe", "brush", "clean" ],
    [ "call" ],
    [ "climb" ],
    [ "match", "compare" ],
    [ "shit", "fuck", "curse", "piss", "damn" ],
    [ "break", "damage", "smash", "destroy" ],
    [ "swallow", "imbibe", "drink" ],
    [ "drop" ],
    [ "consume", "eat" ],
    [ "describe", "inspect", "examine" ],
    [ "douse", "extinguish" ],
    [ "find", "where", "seen", "there" ],
    [ "chase", "follow", "pursue", "trace" ],
    [ "offer", "donate", "give", "hand" ],
    [ "cuff", "handcuff" ],
    [ "hello", "hi" ],
    [ "hide", "crouch" ],
    [ "inventory", "i" ],
    [ "bite", "kick", "taunt" ],
    [ "kill" ],
    [ "knock", "rap" ],
    [ "lean", "stand", "prop" ],
    [ "stare", "look", "l", "gaze" ],
    [ "tug", "pull" ],
    [ "push", "press" ],
    [ "stuff", "place", "put", "insert" ],
    [ "quit", "q" ],
    [ "raise", "lift" ],
    [ "molest", "rape", "assault" ],
    [ "read", "skim", "peruse" ],
    [ "restore", "continue", "resume" ],
    [ "peal", "ring" ],
    [ "touch", "shade", "pat", "pet", "feel", "rub" ],
    [ "save", "suspend", "pause" ],
    [ "say", "explain", "talk" ],
    [ "dig", "search" ],
    [ "shoot", "blast", "fire" ],
    [ "injure", "hurt", "punch", "hit", "slap" ],
    [ "sniff", "smell" ],
    [ "super", "superbrief" ],
    [ "lead", "get", "take", "steal", "carry", "hold", "remove" ],
    [ "thank", "thanks" ],
    [ "throw", "chuck", "hurl", "toss" ],
    [ "attach", "tie", "secure", "fasten" ],
    [ "time", "t" ],
    [ "flip", "turn", "shut" ],
    [ "untie", "unattach", "unhook", "uncuff", "unfasten", "free" ],
    [ "release", "version", "revision", "edition" ],
    [ "wait", "stay", "z", "stop", "meditate" ],
    [ "surprise", "awake", "wake", "startle" ],
    [ "go", "walk", "run", "proceed" ],
    [ "what", "whats", "who" ],
    [ "how", "did", "why", "when" ],
    [ "maybe", "yes", "y", "no" ],
    [ "accuse" ],
    [ "apply" ],
    [ "arrest" ],
    [ "brief" ],
    [ "close" ],
    [ "confront" ],
    [ "dial" ],
    [ "enter" ],
    [ "fingerprint" ],
    [ "goodbye" ],
    [ "help" ],
    [ "kiss" ],
    [ "know" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "make" ],
    [ "move" ],
    [ "open" ],
    [ "peek" ],
    [ "pick" ],
    [ "play" ],
    [ "restart" ],
    [ "revive" ],
    [ "script" ],
    [ "show" ],
    [ "sit" ],
    [ "smoke" ],
    [ "space" ],
    [ "strike" ],
    [ "tell" ],
    [ "unlock" ],
    [ "unscript" ],
    [ "unspace" ],
    [ "use" ],
    [ "verbose" ],
] # verbs

nouns = [
    [ "midnight" ],
    [ "her", "she", "him", "him or her", "he" ],
    [ "himself", "herself", "yourself", "himself or herself" ],
    [ "such things" ],
    [ "detective", "me", "i", "myself" ],
    [ "phong", "Mr. Phong", "man" ],
    [ "pair", "shoes", "shoe", "pair of Phong's shoes" ],
    [ "phong", "Mr. Phong" ],
    [ "dad", "man", "Mr. Linder", "linder", "father" ],
    [ "pair", "pair of Linder's shoes", "shoes", "shoe" ],
    [ "dad", "Mr. Linder", "linder", "father" ],
    [ "man", "Mr. Stiles", "stiles", "visitor" ],
    [ "writer", "stiles", "stranger", "Mr. Stiles", "visitor" ],
    [ "pair of Stiles's shoes", "pair", "shoes", "shoe" ],
    [ "Monica", "woman", "monica" ],
    [ "pair", "shoes", "pair of Monica's shoes", "shoe" ],
    [ "Monica", "monica" ],
    [ "asta", "feline", "cat", "beast" ],
    [ "Terry", "terry" ],
    [ "mother", "late Mrs. Linder", "linder", "wife", "virginia" ],
    [ "Sergeant Duffy", "police", "duffy" ],
    [ "hint", "help" ],
    [ "window", "panes", "pane", "frame" ],
    [ "faucet", "basin", "spigot", "sink" ],
    [ "toilet" ],
    [ "bathroom door" ],
    [ "bedroom" ],
    [ "bedroom door" ],
    [ "back door" ],
    [ "bathroom" ],
    [ "here" ],
    [ "garden", "vegetable", "kitchen garden", "herb", "herbs" ],
    [ "gate", "front gate" ],
    [ "bell", "door bell", "doorbell" ],
    [ "driveway", "way" ],
    [ "footprints", "prints", "set", "set of footprints" ],
    [ "cast", "side-yard cast" ],
    [ "woods", "thicket", "forest", "bamboo woods" ],
    [ "back gate", "gate" ],
    [ "back-yard cast", "cast" ],
    [ "cast" ],
    [ "window", "panes", "pane", "frame", "office window" ],
    [ "green wire piece", "wire", "piece" ],
    [ "putty", "chunk", "chunk of putty" ],
    [ "door", "back door", "lock" ],
    [ "grass", "lawn" ],
    [ "rocks", "boulder", "rock" ],
    [ "table", "dressing table", "desk", "bench" ],
    [ "make-up", "stuff", "stuff on the table" ],
    [ "poster", "bunch of movie posters" ],
    [ "case", "bookcase", "books", "book case", "book" ],
    [ "record collection", "record", "music" ],
    [ "bedroom door", "door" ],
    [ "cedar door", "door" ],
    [ "pullman", "counter" ],
    [ "window", "panes", "pane", "bath window", "frame" ],
    [ "plant", "potted plants", "plants" ],
    [ "tub", "bathtub" ],
    [ "shower", "head" ],
    [ "toilet door", "door" ],
    [ "redwood door", "door" ],
    [ "window", "panes", "pane", "Linder's window", "frame" ],
    [ "clothes", "papers", "stuff", "newspapers", "stuff in the room" ],
    [ "bed", "poster", "four-poster bed", "four-poster" ],
    [ "dresser" ],
    [ "fireplace", "fieldstone fireplace" ],
    [ "fire" ],
    [ "pile", "wood pile" ],
    [ "davenport", "sofa", "divan", "couch" ],
    [ "club chair", "chair" ],
    [ "coffee table", "table" ],
    [ "program", "radio", "music", "volume" ],
    [ "liquor cabinet", "cabinet" ],
    [ "door", "double door" ],
    [ "dining table", "table" ],
    [ "benches", "dining bench", "bench" ],
    [ "lock", "door", "French door" ],
    [ "swinging door", "door" ],
    [ "window", "panes", "pane", "frame", "kitchen window" ],
    [ "cabinet" ],
    [ "silver", "set of silverware", "set" ],
    [ "glass collection", "glasses", "glass" ],
    [ "china", "set of china", "set" ],
    [ "cupboard" ],
    [ "food", "bunch", "bunch of canned food", "foods" ],
    [ "kitchen clock", "clock" ],
    [ "refrigerator", "fridge", "appliance" ],
    [ "bunch of cold food", "bunch", "food", "foods" ],
    [ "range" ],
    [ "hood", "range hood" ],
    [ "mixer" ],
    [ "toaster" ],
    [ "door", "kitchen door" ],
    [ "butler's door", "door" ],
    [ "tables", "end table", "table" ],
    [ "window", "panes", "bedroom window", "pane", "frame" ],
    [ "flower arrangement", "arrangement" ],
    [ "shrine", "scroll" ],
    [ "platform", "shoe platform" ],
    [ "shoe", "shoes", "other shoes" ],
    [ "lock", "door", "front door" ],
    [ "storage door", "door" ],
    [ "linen", "linens", "sheets" ],
    [ "towels", "towel" ],
    [ "office door", "door" ],
    [ "desk" ],
    [ "stuff on the desk", "souvenir", "letter", "piles", "stuff" ],
    [ "newspapers", "newspaper" ],
    [ "carved chair", "throne", "chair" ],
    [ "wooden chair", "chair" ],
    [ "chair" ],
    [ "file cabinet", "cabinet" ],
    [ "lot", "paper", "lot of business papers", "papers" ],
    [ "picture" ],
    [ "case", "grandfather clock", "clock", "lock", "door" ],
    [ "keyhole" ],
    [ "gunpowder", "powder" ],
    [ "sample", "powder", "sample of powder" ],
    [ "pair", "wires", "pair of green wires" ],
    [ "button", "butler's button" ],
    [ "lounge" ],
    [ "garage door", "door", "lock" ],
    [ "auto", "car", "sedan", "bentley", "blue sedan" ],
    [ "convertible", "auto", "car", "mg", "red sport car" ],
    [ "window", "car window" ],
    [ "car" ],
    [ "workshop door", "door", "lock" ],
    [ "spools", "wire", "other wire", "spool", "wires" ],
    [ "wire", "spool", "green wire spool" ],
    [ "green wire" ],
    [ "wire" ],
    [ "junction box", "box" ],
    [ "saw" ],
    [ "hammer" ],
    [ "rope" ],
    [ "spade" ],
    [ "hoe" ],
    [ "rake" ],
    [ "hose" ],
    [ "shelf", "shelves" ],
    [ "wind", "air", "breeze" ],
    [ "such thing" ],
    [ "it", "them", "they" ],
    [ "mystery book", "book" ],
    [ "receipt", "ticket", "gun receipt", "paper", "bookmark" ],
    [ "telegram" ],
    [ "matchbook", "book", "matches", "match book" ],
    [ "gun", "pistol", "snub-nosed Colt", "colt", "roscoe" ],
    [ "pair of handcuffs", "nippers", "pair", "cuffs", "handcuff" ],
    [ "house" ],
    [ "fence" ],
    [ "mud", "dirt", "ground" ],
    [ "area", "floor" ],
    [ "Brass Lantern", "lantern", "restaurant" ],
    [ "program", "music" ],
    [ "cocktail", "drink", "belt" ],
    [ "smoke", "camel", "weed", "cigarette" ],
    [ "note", "threatening note" ],
    [ "glass", "shard", "pile of broken glass", "pile", "fragment" ],
    [ "broom" ],
    [ "hidden handgun", "gun", "pistol", "handgun", "heater" ],
    [ "gun", "muddy handgun", "pistol", "handgun", "heater" ],
    [ "handgun" ],
    [ "shot", "gunshot", "shooting", "explosion" ],
    [ "medical report", "paper", "report" ],
    [ "autopsy" ],
    [ "clock key", "key" ],
    [ "keys", "set", "key", "set of house keys" ],
    [ "key" ],
    [ "handwriting", "writing" ],
    [ "fingerprints", "fingerprint" ],
    [ "crime", "murder", "killing" ],
    [ "suicide" ],
    [ "euthanasia", "conspiracy", "killing", "crime", "other crime" ],
    [ "company", "Pacific Trade Associates", "associates", "pta", "business" ],
    [ "danger", "threat", "problem", "wrong" ],
    [ "climate", "weather" ],
    [ "receiver", "phone", "telephone" ],
    [ "coroner", "morgue", "doctor", "ambulance" ],
    [ "wires", "wire", "black wire" ],
    [ "wires", "wire", "white wire" ],
    [ "love affair", "affair" ],
    [ "boot", "mud", "pair", "pair of muddy boots", "boots" ],
    [ "chairs", "chair" ],
    [ "lamp" ],
    [ "bed" ],
    [ "telephone call", "call" ],
    [ "bribe", "payoff", "loot", "money" ],
    [ "Linder's will", "testament", "will" ],
    [ "number", "intnum" ],
    [ "tumor", "tumour", "cancer", "carcinoma" ],
    [ "body of Mr. Linder", "body", "linder", "wound", "corpse" ],
    [ "day", "today", "date" ],
    [ "search warrant", "warrant" ],
    [ "ticket stub", "ticket", "stub" ],
    [ "water" ],
    [ "mirror" ],
    [ "closet" ],
    [ "worm", "can of worms", "worms", "can" ],
    [ "snack", "breakfast", "dinner", "meal" ],
    [ "film", "movie", "show" ],
    [ "four", "two", "three", "five" ],
    [ "fifteen", "twenty", "thirty", "ten" ],
    [ "place", "walls", "wall", "room" ],
    [ "door" ],
    [ "zzkjlk" ],
] # nouns

rooms = [
    "hallway",
    "toilet room",
    "storage closet",
    "side yard",
    "bathroom",
    "dining room",
    "front porch",
    "front yard",
    "entry",
    "office porch",
    "butler's room",
    "limbo",
    "office",
    "back yard",
    "Linder's bedroom",
    "workshop",
    "driveway",
    "rock garden",
    "kitchen",
    "driveway entrance",
    "Monica's bedroom",
    "tub room",
    "living room",
    "office path",
    "butler's bathroom",
    "garage",
] # rooms

