# Config for ZORK3, in LLM style
#
#

[game]
path = "./infocom/zork3/COMPILED/zork3.z3"

setup = '''
zork3 is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "thru", "with", "through", "using" ],
    [ "inside", "in", "into" ],
    [ "on", "onto" ],
    [ "beneath", "below", "under", "underneath" ],
    [ "north", "n" ],
    [ "s", "south" ],
    [ "east", "e" ],
    [ "w", "west" ],
    [ "d", "down" ],
    [ "up", "u" ],
    [ "northwest", "nw" ],
    [ "northe", "ne" ],
    [ "sw", "southwest" ],
    [ "se", "southe" ],
    [ "super", "superbrief" ],
    [ "inventory", "i" ],
    [ "q", "quit" ],
    [ "reply", "answer" ],
    [ "fight", "attack", "injure", "hit", "hurt" ],
    [ "clean", "brush" ],
    [ "incinerate", "burn", "ignite" ],
    [ "barf", "lose", "chomp" ],
    [ "climb", "sit" ],
    [ "ford", "cross" ],
    [ "pierce", "cut", "slice" ],
    [ "fuck", "curse", "damn", "shit" ],
    [ "smash", "destroy", "break", "block", "damage" ],
    [ "drink", "imbibe", "swallow" ],
    [ "consume", "bite", "taste", "eat" ],
    [ "what", "describe", "whats", "examine" ],
    [ "drive", "begone", "exorcise", "banish", "cast" ],
    [ "extinguish", "douse" ],
    [ "where", "see", "find", "seek" ],
    [ "follow", "chase", "come", "pursue" ],
    [ "offer", "hand", "give", "donate", "feed" ],
    [ "hello", "hi" ],
    [ "incant", "chant" ],
    [ "leap", "dive", "jump" ],
    [ "taunt", "bite", "kick" ],
    [ "stab", "dispatch", "murder", "slay", "kill" ],
    [ "knock", "rap" ],
    [ "stare", "look", "l", "gaze" ],
    [ "grease", "lubricate", "oil" ],
    [ "melt", "liquify" ],
    [ "mumble", "sigh" ],
    [ "ulysses", "odysseus" ],
    [ "fix", "plug", "glue", "patch", "repair" ],
    [ "plugh", "xyzzy" ],
    [ "spill", "pour" ],
    [ "tug", "yank", "pull" ],
    [ "push", "press" ],
    [ "stuff", "place", "put", "hide", "insert" ],
    [ "raise", "lift" ],
    [ "molest", "rape" ],
    [ "read", "skim" ],
    [ "peal", "ring" ],
    [ "rub", "pat", "pet", "feel", "touch" ],
    [ "skip", "hop" ],
    [ "sniff", "smell" ],
    [ "wade", "bathe", "swim" ],
    [ "thrust", "swing" ],
    [ "catch", "get", "take", "hold", "remove", "carry", "grab" ],
    [ "tell", "ask" ],
    [ "toss", "hurl", "chuck", "throw" ],
    [ "attach", "secure", "tie", "fasten" ],
    [ "temple", "treasure" ],
    [ "shut", "flip", "set", "turn" ],
    [ "free", "unhook", "untie", "release", "unattach", "unfasten" ],
    [ "wait", "z" ],
    [ "wake", "surprise", "startle", "awake" ],
    [ "go", "proceed", "step", "walk", "run" ],
    [ "brandish", "wave" ],
    [ "winnage", "win" ],
    [ "shout", "scream", "yell" ],
    [ "again", "g" ],
    [ "count" ],
    [ "drop", "release" ],
    [ "jab", "blind", "poke" ],
    [ "say", "talk" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "activate" ],
    [ "apply" ],
    [ "back" ],
    [ "blast" ],
    [ "blow" ],
    [ "board" ],
    [ "bug" ],
    [ "close" ],
    [ "command" ],
    [ "deflate" ],
    [ "dig" ],
    [ "disembark" ],
    [ "disenchant" ],
    [ "echo" ],
    [ "enchant" ],
    [ "enter" ],
    [ "exit" ],
    [ "fill" ],
    [ "frobozz" ],
    [ "hatch" ],
    [ "inflat" ],
    [ "stab" ],
    [ "kiss" ],
    [ "launch" ],
    [ "lean" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "move" ],
    [ "roll" ],
    [ "open" ],
    [ "pick" ],
    [ "play" ],
    [ "puncture" ],
    [ "pray" ],
    [ "pump" ],
    [ "repent" ],
    [ "talk" ],
    [ "search" ],
    [ "send" ],
    [ "shake" ],
    [ "slide" ],
    [ "spin" ],
    [ "spray" ],
    [ "squeeze" ],
    [ "stand" ],
    [ "stay" ],
    [ "strike" ],
    [ "unlock" ],
    [ "wear" ],
    [ "wind" ],
    [ "wish" ],
    [ "zork" ],
    [ "is" ],
] # verbs

nouns = [
    [ "voices", "guards", "offici", "voice" ],
    [ "stalag", "rock structure", "crystal" ],
    [ "Royal Seal of Dimwit Flathead", "carvin", "render", "seal" ],
    [ "cleft" ],
    [ "machine", "temporizer", "gold machine" ],
    [ "machine", "pressurizer", "dryer", "grey machine" ],
    [ "wires", "black machine", "pipes", "machine", "motors" ],
    [ "button" ],
    [ "seat", "area" ],
    [ "seat", "chair" ],
    [ "dial", "display", "console" ],
    [ "iron door", "door" ],
    [ "stone door", "door" ],
    [ "door", "wooden door" ],
    [ "sceptre", "jewels" ],
    [ "jewelled knife", "knife", "jewels" ],
    [ "golden ring", "ring", "jewels" ],
    [ "pedestal" ],
    [ "steel cage", "cage" ],
    [ "plaque", "text" ],
    [ "plaque", "text", "bronze plaque" ],
    [ "device", "robot" ],
    [ "woman", "hooded figure", "shadow", "figure", "man" ],
    [ "hood" ],
    [ "cloak" ],
    [ "reeds" ],
    [ "viewing table", "surface", "table" ],
    [ "torch" ],
    [ "burned-out torch", "torch" ],
    [ "cliff" ],
    [ "stone wall", "wall" ],
    [ "water", "surface", "lake" ],
    [ "golden amulet", "object", "amulet" ],
    [ "floor", "bottom", "sand" ],
    [ "lamp", "lantern" ],
    [ "plant", "plants and algae", "algae", "plants" ],
    [ "shiny object", "object", "amulet" ],
    [ "ledge" ],
    [ "bread", "piece of waybread", "waybread", "piece" ],
    [ "rope" ],
    [ "trees", "tree" ],
    [ "wooden staff", "staff" ],
    [ "broken staff", "staff" ],
    [ "chest" ],
    [ "man", "friend" ],
    [ "pile of assorted valuables", "valuables", "pile", "treasure" ],
    [ "timbers", "broken timber", "pile" ],
    [ "wooden ladder", "ladder" ],
    [ "repellent", "can", "Frobozz Magic Grue Repellent" ],
    [ "chasm", "aqueduct", "duct" ],
    [ "channel" ],
    [ "moss and lichen", "lichen", "moss" ],
    [ "cover", "manhole cover" ],
    [ "key", "strange key" ],
    [ "indicator", "dial" ],
    [ "craft", "Viking Ship", "boat", "ship" ],
    [ "gift", "odor", "vial" ],
    [ "potion", "contents", "heavy but invisible liquid", "fluid", "liquid" ],
    [ "water", "ocean", "Flathead Ocean" ],
    [ "rock", "great rock", "stone" ],
    [ "fish" ],
    [ "rubble", "rock", "rocks", "boulder" ],
    [ "dust and debris", "dust", "debris" ],
    [ "chasm", "ravine", "gorge" ],
    [ "tunnel", "crawlway", "passage" ],
    [ "eastern wall", "wall" ],
    [ "southern wall", "wall" ],
    [ "western wall", "wall" ],
    [ "wall", "northern wall" ],
    [ "water", "quantity" ],
    [ "quantity of water", "water", "h2o", "liquid", "quantity" ],
    [ "lamp", "broken lantern", "lantern" ],
    [ "sword", "orcrist", "blade", "glamdring" ],
    [ "warning note", "text", "note", "warning" ],
    [ "cpslt", "slot", "small slot", "slit" ],
    [ "steel door", "door" ],
    [ "book", "text", "lore", "very ancient book" ],
    [ "ladder" ],
    [ "intdir", "direction" ],
    [ "statue", "guard", "Guardians of Zork", "guards", "guardian" ],
    [ "compass rose", "rose" ],
    [ "dungeon master", "man", "master" ],
    [ "man", "master", "dungeon master", "dungeon" ],
    [ "mirror", "structure" ],
    [ "panel" ],
    [ "stone channel", "hole", "channel" ],
    [ "wall", "wooden wall" ],
    [ "wall", "runes", "text", "engrav" ],
    [ "t-bar", "bar", "T-bar" ],
    [ "panel", "wall", "black panel" ],
    [ "bronze door", "door" ],
    [ "cell door", "door" ],
    [ "arrow", "compass arrow" ],
    [ "button", "large button" ],
    [ "pole", "long pole" ],
    [ "mahogany panel", "panel", "wall" ],
    [ "abyss", "pit", "flaming pit" ],
    [ "parapet" ],
    [ "panel", "wall", "pine panel" ],
    [ "red beam of light", "beam", "light" ],
    [ "red button", "button" ],
    [ "panel", "wall", "red panel" ],
    [ "post", "short pole", "grip", "pole", "handgrip" ],
    [ "indicator", "sundial", "arrow", "dial" ],
    [ "panel", "yellow panel", "wall" ],
    [ "panel", "wall", "white panel" ],
    [ "wooden bar", "bar" ],
    [ "secret door", "door" ],
    [ "old man", "man" ],
    [ "hole" ],
    [ "intnum", "number" ],
    [ "pseudo" ],
    [ "her", "him", "it", "random object", "them" ],
    [ "blessings", "graces" ],
    [ "steps", "staircase", "stairway", "stairs" ],
    [ "aviator", "sailor", "footpad" ],
    [ "floor", "dirt", "ground", "sand" ],
    [ "grue", "lurking grue" ],
    [ "breath", "lungs", "mouth", "blast of air", "air" ],
    [ "cretin", "you", "myself", "me", "self" ],
    [ "cretin", "adventurer" ],
    [ "passage", "trail", "path" ],
    [ "zorkmid" ],
    [ "hand", "pair", "hands", "pair of hands" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Southern Shore",
    "Damp Passage",
    "Engravings Room",
    "East Corridor",
    "Dungeon Entrance",
    "On the Lake",
    "High Arch",
    "Key Room",
    "Prison Cell",
    "Ladder Top",
    "Button Room",
    "Timber Room",
    "North Corridor",
    "South Corridor",
    "Museum Entrance",
    "Aqueduct View",
    "Room 8",
    "West Corridor",
    "Junction",
    "Ladder Bottom",
    "Western Shore",
    "Drafty Room",
    "Inside Mirror",
    "Tight Squeeze",
    "Dark Place",
    "Beam Room",
    "Parapet",
    "Scenic Vista",
    "Great Door",
    "Water Slide",
    "Barren Area",
    "Jewel Room",
    "Cliff",
    "Hallway",
    "Narrow Corridor",
    "Technology Museum",
    "Royal Puzzle Entrance",
    "Royal Hall",
    "Lake Shore",
    "Underwater",
    "Cliff Ledge",
    "Land of Shadow",
    "Endless Stair",
    "Dead End",
    "Sacrificial Altar",
    "Foggy Room",
    "Narrow Room",
    "Flathead Ocean",
    "Treasury of Zork",
    "Hairpin Loop",
    "Crystal Grotto",
    "Machine Room",
    "Aqueduct",
    "Creepy Crawl",
    "Side Room",
    "Cliff Base",
    "Room in a Puzzle",
] # rooms

