# Config for ZORK2, in LLM style
#
#

[game]
path = "./infocom/zork2/COMPILED/zork2.z3"

setup = '''
zork2 is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "through", "with", "using", "thru" ],
    [ "in", "inside", "into" ],
    [ "on", "onto" ],
    [ "beneath", "under", "underneath", "below" ],
    [ "north", "n" ],
    [ "s", "south" ],
    [ "east", "e" ],
    [ "west", "w" ],
    [ "down", "d" ],
    [ "up", "u" ],
    [ "nw", "northwest" ],
    [ "northe", "ne" ],
    [ "sw", "southwest" ],
    [ "se", "southe" ],
    [ "super", "superbrief" ],
    [ "i", "inventory" ],
    [ "q", "quit" ],
    [ "reply", "answer" ],
    [ "attack", "fight", "hurt", "hit", "injure" ],
    [ "clean", "brush" ],
    [ "incinerate", "ignite", "burn" ],
    [ "lose", "barf", "chomp" ],
    [ "climb", "sit" ],
    [ "cross", "ford" ],
    [ "cut", "slice", "pierce" ],
    [ "fuck", "curse", "shit", "damn" ],
    [ "destroy", "block", "break", "damage", "smash" ],
    [ "drink", "imbibe", "swallow" ],
    [ "consume", "bite", "taste", "eat" ],
    [ "whats", "what", "describe", "examine" ],
    [ "banish", "exorcise", "begone", "drive", "cast" ],
    [ "extinguish", "douse" ],
    [ "see", "where", "seek", "find" ],
    [ "pursue", "chase", "follow", "come" ],
    [ "give", "donate", "feed", "offer" ],
    [ "hi", "hello" ],
    [ "incant", "chant" ],
    [ "jump", "dive", "leap" ],
    [ "taunt", "kick" ],
    [ "kill", "murder", "slay", "dispatch" ],
    [ "rap", "knock" ],
    [ "l", "look", "stare", "gaze" ],
    [ "oil", "lubricate", "grease" ],
    [ "liquify", "melt" ],
    [ "mumble", "sigh" ],
    [ "odysseus", "ulysses" ],
    [ "repair", "fix", "patch", "plug", "glue" ],
    [ "plugh", "xyzzy" ],
    [ "spill", "pour" ],
    [ "tug", "yank", "pull" ],
    [ "press", "push" ],
    [ "place", "stuff", "hide", "insert", "put" ],
    [ "lift", "raise" ],
    [ "molest", "rape" ],
    [ "read", "skim" ],
    [ "peal", "ring" ],
    [ "rub", "feel", "pat", "touch", "pet" ],
    [ "skip", "hop" ],
    [ "smell", "sniff" ],
    [ "bathe", "wade", "swim" ],
    [ "thrust", "swing" ],
    [ "get", "catch", "carry", "remove", "take", "grab", "hold" ],
    [ "tell", "ask" ],
    [ "throw", "chuck", "hurl", "toss" ],
    [ "fasten", "attach", "tie", "secure" ],
    [ "treasure", "temple" ],
    [ "set", "shut", "flip", "turn" ],
    [ "release", "unfasten", "unhook", "unattach", "free", "untie" ],
    [ "wait", "z" ],
    [ "awake", "wake", "startle", "surprise" ],
    [ "walk", "step", "go", "run", "proceed" ],
    [ "brandish", "wave" ],
    [ "win", "winnage" ],
    [ "scream", "yell", "shout" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "activate" ],
    [ "apply" ],
    [ "back" ],
    [ "blast" ],
    [ "blow" ],
    [ "board" ],
    [ "bug" ],
    [ "close" ],
    [ "command" ],
    [ "count" ],
    [ "deflate" ],
    [ "dig" ],
    [ "disembark" ],
    [ "disenchant" ],
    [ "drop" ],
    [ "echo" ],
    [ "enchant" ],
    [ "enter" ],
    [ "exit" ],
    [ "fill" ],
    [ "frobozz" ],
    [ "hatch" ],
    [ "inflat" ],
    [ "stab" ],
    [ "kiss" ],
    [ "launch" ],
    [ "lean" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "move" ],
    [ "roll" ],
    [ "open" ],
    [ "pick" ],
    [ "play" ],
    [ "poke" ],
    [ "puncture" ],
    [ "pray" ],
    [ "pump" ],
    [ "repent" ],
    [ "talk" ],
    [ "say" ],
    [ "search" ],
    [ "send" ],
    [ "shake" ],
    [ "slide" ],
    [ "spin" ],
    [ "spray" ],
    [ "squeeze" ],
    [ "stand" ],
    [ "stay" ],
    [ "strike" ],
    [ "unlock" ],
    [ "wear" ],
    [ "wind" ],
    [ "wish" ],
    [ "zork" ],
] # verbs

nouns = [
    [ "stream" ],
    [ "ravine", "chasm" ],
    [ "moss", "mosses" ],
    [ "arbor", "bush", "roses" ],
    [ "bridge" ],
    [ "passage", "crawlway", "tunnel" ],
    [ "east wall", "wall" ],
    [ "south wall", "wall" ],
    [ "west wall", "wall" ],
    [ "north wall", "wall" ],
    [ "water", "quantity" ],
    [ "wish", "bless" ],
    [ "well" ],
    [ "unicorn" ],
    [ "animal", "unicorn" ],
    [ "hedges", "hedge" ],
    [ "chest", "rotten wooden chest", "trunk" ],
    [ "treasure", "golden dragon statuette", "dragon", "statuette" ],
    [ "huge red dragon", "worm", "dragon", "smaug" ],
    [ "worm", "huge dead dragon", "dragon", "smaug" ],
    [ "woman", "princess", "beautiful princess", "lady" ],
    [ "door", "door partly covered in cobwebs" ],
    [ "stone", "enormous menhir", "rock", "menhir" ],
    [ "stone", "menhir", "f", "enormous menhir", "rock" ],
    [ "gigantic dog collar", "treasure", "collar" ],
    [ "bat", "club", "wooden club" ],
    [ "diamond shaped window", "window" ],
    [ "three-headed dog", "dog", "cerberus", "hound", "monster" ],
    [ "pole", "heads", "set of poled heads", "poles", "head" ],
    [ "marble crypt", "grave", "tomb", "crypt" ],
    [ "door", "crypt door" ],
    [ "door", "letter", "secret door" ],
    [ "guardian", "keeper", "lizard", "head" ],
    [ "candles", "knives", "vellum", "alembic", "arcane item" ],
    [ "bench", "table", "Wizard's workbench", "workbench" ],
    [ "stands", "stand", "ruby stand" ],
    [ "stands", "stand", "sapphire stand" ],
    [ "stands", "stand", "diamond stand" ],
    [ "stands", "stand", "black obsidian stand" ],
    [ "black crystal sphere", "palantir", "sphere", "ball" ],
    [ "diploma", "degree" ],
    [ "set", "rack", "set of used wands", "wands", "wand" ],
    [ "nicked swords", "sword", "swords" ],
    [ "small bottles", "bottle" ],
    [ "label", "warning label" ],
    [ "case", "Wizard's trophy cabinet", "cabinet" ],
    [ "case", "smashed trophy cabinet", "cabinet" ],
    [ "circle", "pentagram", "star" ],
    [ "aquarium", "glass" ],
    [ "clear crystal sphere", "palantir", "sphere" ],
    [ "snake", "serpent", "baby sea serpent" ],
    [ "snake", "dead sea serpent", "serpent" ],
    [ "door", "stone door" ],
    [ "matches", "matchbook", "match" ],
    [ "gnome", "Volcano Gnome" ],
    [ "balloon", "basket" ],
    [ "label", "blue label" ],
    [ "safe", "box" ],
    [ "braided wire", "rope", "wire" ],
    [ "brick" ],
    [ "krebf", "debris from an explosion" ],
    [ "broken balloon", "balloon", "basket" ],
    [ "round button", "button" ],
    [ "button", "square button" ],
    [ "triangular button", "button" ],
    [ "card", "note" ],
    [ "cloth bag", "bag" ],
    [ "treasure", "crown", "gaudy crown" ],
    [ "palantir", "red crystal sphere", "sphere", "ball" ],
    [ "fancy violin", "treasure", "stradivarius", "violin" ],
    [ "ice", "glacier", "mass" ],
    [ "flask", "stoppered glass flask filled with liquid" ],
    [ "piece", "paper", "green piece of paper", "instructions" ],
    [ "hole", "slot" ],
    [ "hook" ],
    [ "lamp", "lantern", "light" ],
    [ "lamp", "lantern", "light", "broken brass lantern" ],
    [ "table", "large oblong table" ],
    [ "mangled cage", "cage" ],
    [ "treasure", "pearl necklace", "pearls", "necklace" ],
    [ "cakes", "icing", "cake frosted with green letters", "letter", "cake" ],
    [ "cakes", "cake frosted with blue letters", "icing", "letter", "cake" ],
    [ "cake frosted with orange letters", "cakes", "icing", "letter", "cake" ],
    [ "cakes", "cake frosted with red letters", "icing", "letter", "cake" ],
    [ "leak" ],
    [ "tears", "pool", "pool of tears" ],
    [ "priceless zorkmid", "treasure", "zorkmid", "gold", "coin" ],
    [ "stamp", "treasure", "Flathead stamp" ],
    [ "green book", "cover", "books", "book" ],
    [ "cover", "blue book", "books", "book" ],
    [ "cover", "white book", "books", "book" ],
    [ "books", "purple book", "book" ],
    [ "receptacle" ],
    [ "robby", "robot", "c3po", "r2d2" ],
    [ "treasure", "ruby" ],
    [ "box", "steel box" ],
    [ "solid steel cage", "cage" ],
    [ "package of candy", "treasure", "candy", "package", "grasshoppers" ],
    [ "etchings", "wall with etchings", "wall" ],
    [ "string", "fuse", "coil", "black string" ],
    [ "bucket", "wooden bucket" ],
    [ "posts", "group of wooden posts", "post" ],
    [ "treasure", "stack of zorkmid bills", "money", "bills", "stack" ],
    [ "treasure", "art", "portrait", "portrait of J. Pierpont Flathead", "painting" ],
    [ "bank brochure", "piece", "paper", "brochure" ],
    [ "large stone cube", "cube", "letter", "vault" ],
    [ "shimmering curtain of light", "curtain", "light" ],
    [ "gnome", "Gnome of Zurich", "zurich" ],
    [ "box", "safety deposit box" ],
    [ "door", "door made of oak" ],
    [ "barred window", "window" ],
    [ "metal lid", "lid" ],
    [ "table" ],
    [ "narrow crack", "crack" ],
    [ "hole", "keyhole" ],
    [ "letter opener", "opener" ],
    [ "key", "rusty iron key" ],
    [ "palantir", "blue crystal sphere", "sphere" ],
    [ "structure", "gazebo" ],
    [ "newspaper", "paper" ],
    [ "mat", "placem", "place mat" ],
    [ "teapot", "china teapot", "pot" ],
    [ "liquid", "h2o", "water", "quantity of water", "quantity" ],
    [ "quantity of salty water", "liquid", "h2o", "water", "quantity" ],
    [ "delicate gold key", "treasure", "key" ],
    [ "ribbon" ],
    [ "perfect rose", "rose" ],
    [ "djinn", "devil", "genie", "demon" ],
    [ "wizard", "magician", "man", "Wizard of Frobozz", "sorceror" ],
    [ "Wizard's magic wand", "wand" ],
    [ "sword", "orcrist", "blade", "glamdring", "elvish sword" ],
    [ "Frobozz Magic Grue Repellent", "repellent", "can" ],
    [ "sphere" ],
    [ "footpad" ],
    [ "compass" ],
    [ "intnum", "number" ],
    [ "pseudo" ],
    [ "it", "her", "him", "them", "random object" ],
    [ "graces", "blessings" ],
    [ "stairway", "staircase", "stairs", "steps" ],
    [ "sailor", "footpad", "aviator" ],
    [ "floor", "ground", "sand", "dirt" ],
    [ "lurking grue", "grue" ],
    [ "air", "blast of air", "breath", "mouth", "lungs" ],
    [ "self", "me", "you", "cretin", "myself" ],
    [ "cretin", "adventurer" ],
    [ "trail", "path", "passage" ],
    [ "zorkmid" ],
    [ "hands", "pair", "pair of hands", "hand" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Volcano Core",
    "Path Near Stream",
    "Posts Room",
    "North End of Garden",
    "Lava Room",
    "East Teller's Room",
    "Small Room",
    "Menhir Room",
    "Cerberus Room",
    "Guarded Room",
    "End of Ledge",
    "Stone Bridge",
    "Murky Room",
    "Riddle Room",
    "Vault",
    "Carousel Room",
    "Ice Room",
    "Volcano Bottom",
    "Narrow Tunnel",
    "Dragon Room",
    "Cobwebby Corridor",
    "Volcano by Viewing Ledge",
    "Machine Room",
    "Fresco Room",
    "Dusty Room",
    "Top of Well",
    "Tea Room",
    "Chairman's Office",
    "Room of Blue Mist",
    "Stairway",
    "Formal Garden",
    "Narrow Ledge",
    "Dark Tunnel",
    "Trophy Room",
    "Pearl Room",
    "Dreary Room",
    "Deep Ford",
    "Dragon's Lair",
    "Crypt Anteroom",
    "Wizard's Quarters",
    "Ledge in Ravine",
    "Wide Ledge",
    "Tiny Room",
    "Foot Bridge",
    "Circular Room",
    "Gazebo",
    "Marble Hall",
    "Shallow Ford",
    "Room of Black Mist",
    "Cage",
    "Topiary",
    "West Teller's Room",
    "Room 8",
    "Inside the Barrow",
    "Pool Room",
    "Dingy Closet",
    "West Viewing Room",
    "Safety Depository",
    "Pentagram Room",
    "Volcano Near Small Ledge",
    "Volcano Near Wide Ledge",
    "Great Cavern",
    "Aquarium Room",
    "Lava Tube",
    "Crypt",
    "Wizard's Workroom",
    "East Viewing Room",
    "Wizard's Workshop",
    "Library",
    "Volcano View",
    "Kennel",
    "Room of Red Mist",
    "Room of White Mist",
    "Cool Room",
    "Low Room",
    "Landing",
] # rooms

