# Config for ZORKZERO, in LLM style
#
#

[game]
path = "./infocom/zorkzero/COMPILED/zorkzero.z3"

setup = '''
zorkzero is a text-based adventure game from Infocom.
'''

background_files = [
]

background_urls = [
]

walkthrough_urls = [
]

[syntax]
verbs = [
    [ "to", "toward" ],
    [ "using", "with" ],
    [ "thru", "through" ],
    [ "on", "atop", "upon", "onto" ],
    [ "outside", "out" ],
    [ "into", "inside", "in" ],
    [ "beneath", "underneath", "under", "below" ],
    [ "next", "before", "near", "by" ],
    [ "along", "around" ],
    [ "both", "everything", "all" ],
    [ "n", "north" ],
    [ "south", "s" ],
    [ "east", "e" ],
    [ "w", "west" ],
    [ "belowdecks", "downstairs", "down", "d" ],
    [ "upstairs", "u", "up" ],
    [ "nw", "northw", "northwest" ],
    [ "northe", "ne", "northeast" ],
    [ "southw", "sw", "southwest" ],
    [ "southeast", "se", "southe" ],
    [ "credit", "credits" ],
    [ "i", "inventory" ],
    [ "q", "quit" ],
    [ "status", "score" ],
    [ "fight", "kill", "slap", "attack", "stab", "strike", "murder", "hit" ],
    [ "mount", "board" ],
    [ "purchase", "order", "buy" ],
    [ "trap", "catch" ],
    [ "scale", "climb" ],
    [ "shut", "close", "shutter" ],
    [ "ford", "cross" ],
    [ "decipher", "decode", "anagram" ],
    [ "crack", "smash", "break", "demolish", "destroy", "wreck", "damage" ],
    [ "debark", "dismount", "disembark", "withdraw", "depart", "exit" ],
    [ "sip", "drink" ],
    [ "drop", "release", "dump" ],
    [ "devour", "eat", "swallow" ],
    [ "describe", "examine", "watch", "x", "study", "observe", "inspect" ],
    [ "deactivate", "extinguish" ],
    [ "seek", "find" ],
    [ "pursue", "chase", "follow" ],
    [ "give", "hand", "offer" ],
    [ "hi", "hello" ],
    [ "clues", "clue", "invisiclues", "hints", "help", "hint" ],
    [ "vault", "leap", "jump", "dive" ],
    [ "rap", "knock" ],
    [ "activate", "light", "start" ],
    [ "look", "l" ],
    [ "greet", "meet" ],
    [ "pull", "move" ],
    [ "uh-uh", "nope", "no", "nah" ],
    [ "unshutter", "open" ],
    [ "point", "fire", "wave", "aim" ],
    [ "spill", "pour" ],
    [ "pray", "worship" ],
    [ "press", "push" ],
    [ "raise", "boost", "lift" ],
    [ "skim", "browse", "read" ],
    [ "remove", "unwrap" ],
    [ "save", "rescue" ],
    [ "reply", "say", "guess", "answer", "utter" ],
    [ "search", "rummage" ],
    [ "send", "ship", "mail" ],
    [ "bounce", "shake" ],
    [ "hop", "skip" ],
    [ "nap", "snooze", "rest", "doze", "sleep" ],
    [ "slice", "cut", "chop" ],
    [ "sniff", "smell" ],
    [ "stand", "rise" ],
    [ "stuff", "install", "stick", "insert", "put", "place" ],
    [ "hold", "get", "take", "carry", "grab" ],
    [ "speak", "talk" ],
    [ "taste", "lick", "nibble" ],
    [ "thank", "thanks" ],
    [ "toss", "cast", "hurl", "throw" ],
    [ "tie", "attach", "fasten" ],
    [ "time", "t" ],
    [ "pet", "touch", "pat", "rub", "feel" ],
    [ "set", "steer", "rotate", "revolve", "spin", "turn", "dial" ],
    [ "unfasten", "unattach", "free", "unstrap", "untie", "unknot" ],
    [ "z", "wait" ],
    [ "awake", "rouse", "wake" ],
    [ "proceed", "step", "walk", "go", "run" ],
    [ "clean", "sweep", "clear", "wash", "shine", "soak", "wipe" ],
    [ "wear", "don" ],
    [ "scream", "yell", "shout" ],
    [ "yes", "sure", "okay", "yup", "yeah", "y", "ok", "yep" ],
    [ "sizul", "fublitskee", "mordex", "xzilch", "hildebud", "eldablitz", "lizowurt", "zastic", "aulderfoo", "fzorty" ],
    [ "zipso", "furgalneti", "flodoor" ],
    [ "define" ],
    [ "verbose" ],
    [ "brief" ],
    [ "superbrief" ],
    [ "color" ],
    [ "diagnose" ],
    [ "mode" ],
    [ "restart" ],
    [ "restore" ],
    [ "undo" ],
    [ "notify" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "approach" ],
    [ "ask" ],
    [ "behead" ],
    [ "bite" ],
    [ "blow" ],
    [ "burn" ],
    [ "call" ],
    [ "circle" ],
    [ "consult" ],
    [ "cough" ],
    [ "count" ],
    [ "cover" ],
    [ "crawl" ],
    [ "date" ],
    [ "descend" ],
    [ "dig" ],
    [ "doff" ],
    [ "empty" ],
    [ "enter" ],
    [ "feed" ],
    [ "fill" ],
    [ "fly" ],
    [ "hang" ],
    [ "hear" ],
    [ "hide" ],
    [ "kick" ],
    [ "kiss" ],
    [ "lead" ],
    [ "leave" ],
    [ "let" ],
    [ "lie" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "map" ],
    [ "maybe" ],
    [ "measure" ],
    [ "pay" ],
    [ "pick" ],
    [ "play" ],
    [ "reach" ],
    [ "ride" ],
    [ "roll" ],
    [ "saddle" ],
    [ "show" ],
    [ "sing" ],
    [ "sink" ],
    [ "sit" ],
    [ "slide" ],
    [ "snap" ],
    [ "suck" ],
    [ "swat" ],
    [ "swim" ],
    [ "swing" ],
    [ "tell" ],
    [ "tip" ],
    [ "unlock" ],
    [ "use" ],
    [ "wrap" ],
    [ "yawn" ],
    [ "zap" ],
] # verbs

nouns = [
    [ "calendar" ],
    [ "epaulette", "axe", "epaulet", "template", "elephant", "raven", "compass", "burner", "volcano", "bowtie", "crayon", "dagger", "brush", "pencil", "celery", "cobra", "skull", "inkwell", "medal", "it", "helmet", "avocado", "ax", "triangle", "cigar", "poison", "knife", "ball", "match", "stick", "trophy", "stamp" ],
    [ "moose", "it", "locket" ],
    [ "decree", "proclamation" ],
    [ "time" ],
    [ "doorbell", "bell" ],
    [ "portcullis" ],
    [ "moat" ],
    [ "piece", "rubber", "worm", "earthworm" ],
    [ "elm", "small elm tree", "tree" ],
    [ "cannonball", "ball" ],
    [ "murder hole", "hole" ],
    [ "wheel" ],
    [ "fish tank", "tank", "aquarium" ],
    [ "clump", "weed", "clump of spenseweed", "spenseweed" ],
    [ "nutcracker", "lobster", "cracker" ],
    [ "fish", "star", "starfish" ],
    [ "torches", "torch", "bickering torch" ],
    [ "torches", "torch", "muttering torch" ],
    [ "plant", "shrubs", "flora", "plants", "shrub", "shrubbery", "tree" ],
    [ "bird", "ornament", "flamingo" ],
    [ "pennant", "banners", "pennants", "banner" ],
    [ "rebus" ],
    [ "animal", "flattened camel", "camel", "representation" ],
    [ "mouse", "animal", "flattened mouse", "representation" ],
    [ "snake", "animal", "flattened snake", "representation" ],
    [ "animal", "goose", "flattened goose", "representation" ],
    [ "flattened fish", "fish", "animal", "representation" ],
    [ "animal", "flattened slime monster", "monster", "representation" ],
    [ "twelve paintings", "paintings", "portraits" ],
    [ "printing", "bag" ],
    [ "bar of food", "bar", "food" ],
    [ "throne", "tassles", "large golden throne" ],
    [ "sceptre", "scepter" ],
    [ "throne", "small throne" ],
    [ "candle" ],
    [ "the letter y", "y" ],
    [ "key", "iron key" ],
    [ "Dimwit's bed", "bed" ],
    [ "cloak", "writing", "label" ],
    [ "writing", "embroider", "glove" ],
    [ "machicolation", "hole" ],
    [ "remains", "bodies" ],
    [ "slab", "flattest slab" ],
    [ "shortest slab", "slab" ],
    [ "longest slab", "slab" ],
    [ "dustiest slab", "slab" ],
    [ "slab", "darkest slab" ],
    [ "oldest slab", "slab" ],
    [ "slab", "newest slab" ],
    [ "trapdoor", "door", "trap door" ],
    [ "hole" ],
    [ "triplet", "triplets", "quintuplet", "quadruplet" ],
    [ "cap", "seaman's cap", "hat" ],
    [ "spiders", "giant spider", "spider" ],
    [ "cobwebs", "web", "cobweb", "webs" ],
    [ "stoppered glass flask filled with liquid", "flask" ],
    [ "liquid", "clear liquid" ],
    [ "metronome" ],
    [ "chair", "comfy chair" ],
    [ "maiden", "iron maiden" ],
    [ "chamber", "water chamber" ],
    [ "lid", "pit", "snake pit" ],
    [ "snake", "mass", "writhing mass of snakes" ],
    [ "door" ],
    [ "peggleboz", "Peggleboz" ],
    [ "pegboard", "board" ],
    [ "peg" ],
    [ "set", "rules", "instructions", "set of instructions" ],
    [ "carpeting", "carpet" ],
    [ "set", "weights", "dumbbell" ],
    [ "wands", "wand" ],
    [ "altar" ],
    [ "screwdriver", "driver" ],
    [ "booth", "left booth" ],
    [ "booth", "right booth" ],
    [ "ominous black button", "button" ],
    [ "inscription", "sled", "toboggan" ],
    [ "cage" ],
    [ "snake", "rope" ],
    [ "door", "vault door" ],
    [ "dial" ],
    [ "certificate", "stock", "stock certificate" ],
    [ "notice" ],
    [ "pits", "pit", "bottomless pit" ],
    [ "monogram", "light", "lamp", "lantern", "brass lantern" ],
    [ "root", "roots" ],
    [ "fungus", "fungi", "ear fungus" ],
    [ "shoulder", "brogmoid", "brogmoids", "giant brogmoid", "toe", "ear" ],
    [ "wax", "hunk", "hunk of brogmoid ear wax", "earwax" ],
    [ "man", "mounted soldier", "horse", "knight", "soldier" ],
    [ "soldier", "man", "pawn", "foot soldier" ],
    [ "woman", "queen" ],
    [ "man", "man atop a castle tower", "rook", "tower", "castle" ],
    [ "high priest", "man", "priest", "bishop" ],
    [ "man", "royal leader", "leader", "king" ],
    [ "crown" ],
    [ "robe" ],
    [ "blueprint" ],
    [ "hammer" ],
    [ "hardhat", "hat" ],
    [ "south", "nw", "east", "sw", "ne", "west", "se", "direction", "north" ],
    [ "pseudoxxx" ],
    [ "dirigible" ],
    [ "controls", "control" ],
    [ "left button", "button" ],
    [ "button", "right button" ],
    [ "fireplace" ],
    [ "fresco" ],
    [ "vase" ],
    [ "ladder", "stepladder" ],
    [ "rock", "hexagonal block", "block" ],
    [ "fan" ],
    [ "zzmgck", "it" ],
    [ "it" ],
    [ "numbers", "int.num", "number" ],
    [ "himself", "him" ],
    [ "her", "herself" ],
    [ "right", "that way", "left" ],
    [ "grues", "lurking grue", "grue" ],
    [ "sailor" ],
    [ "nap", "snooze", "sleep" ],
    [ "lullabye", "lullaby", "song" ],
    [ "wall", "walls" ],
    [ "passage", "tunnel", "passageway" ],
    [ "roof", "ceiling" ],
    [ "slime" ],
    [ "water", "water in the small vial", "gloops", "gloop" ],
    [ "water", "gloops", "gloop", "water in the large vial" ],
    [ "yourself" ],
    [ "here", "location", "area", "there", "place", "room", "hall" ],
    [ "building", "cluster" ],
    [ "archway", "arch" ],
    [ "pane", "glass", "window", "windows", "panes" ],
    [ "keyhole", "lock", "hole" ],
    [ "sign" ],
    [ "step", "flight", "gangway", "stair", "steps", "stairs", "stairway", "staircase" ],
    [ "ladder" ],
    [ "bone", "pile", "adventurer", "skeletons", "creature", "pile of old bones", "bones", "skeleton" ],
    [ "bomb", "anti-pit bomb", "label" ],
    [ "booth", "toll booth" ],
    [ "toll gate", "gate" ],
    [ "exact change basket", "basket" ],
    [ "milky orb", "orb" ],
    [ "orb", "fiery orb" ],
    [ "smoky orb", "orb" ],
    [ "glittery orb", "orb" ],
    [ "number", "ticket" ],
    [ "box", "writing" ],
    [ "repellent", "pellet", "pellet of squid repellent" ],
    [ "executioner", "man" ],
    [ "lots of zorkmids", "zorkmids" ],
    [ "fanucci", "Double Fanucci", "fannucci" ],
    [ "table", "chair", "card table" ],
    [ "broom" ],
    [ "left door", "door", "writing" ],
    [ "right door", "door", "writing" ],
    [ "center door", "door", "writing" ],
    [ "shovel" ],
    [ "jesters", "jester", "man", "joker" ],
    [ "spike", "barfoo", "middle name", "hideoz", "elderbar", "goozums", "buck", "magglebar", "zippy", "foofoonap", "bivotar", "syovar", "urgwitz" ],
    [ "jester's name", "fernap", "barbazzo" ],
    [ "pocket", "jester's pocket" ],
    [ "bells", "bell", "jester's hat", "hat" ],
    [ "jester's shoe", "shoe" ],
    [ "suit", "jester's suit" ],
    [ "funny paper", "piece", "paper", "newspaper", "comics" ],
    [ "bug", "bedbug", "giant bedbug" ],
    [ "nose", "red clown nose" ],
    [ "slate", "dusty slate" ],
    [ "scroll", "paper" ],
    [ "small table", "table" ],
    [ "left shell", "shell" ],
    [ "shell", "center shell" ],
    [ "shell", "right shell" ],
    [ "bill", "money", "zorkmid bill" ],
    [ "large arched door", "door" ],
    [ "small louvered door", "door" ],
    [ "bozbar", "tower", "Tower of Bozbar" ],
    [ "post", "peg", "left peg" ],
    [ "post", "center peg", "peg" ],
    [ "post", "right peg", "peg" ],
    [ "weight", "1-ugh weight" ],
    [ "weight", "2-ugh weight" ],
    [ "weight", "3-ugh weight" ],
    [ "weight", "4-ugh weight" ],
    [ "weight", "5-ugh weight" ],
    [ "6-ugh weight", "weight" ],
    [ "pair", "etching", "pair of goggles", "goggles" ],
    [ "crate", "writing" ],
    [ "manuscript" ],
    [ "cup" ],
    [ "potions", "potion", "liquid", "magic potion" ],
    [ "cookpot", "pot" ],
    [ "cookfire", "fire" ],
    [ "yellow dock", "dock" ],
    [ "red dock", "dock" ],
    [ "blue dock", "dock" ],
    [ "green dock", "dock" ],
    [ "royal yacht", "boat", "yacht" ],
    [ "rose", "controls", "control", "compass" ],
    [ "plaque", "brass plaque" ],
    [ "red button", "button" ],
    [ "blue button", "button" ],
    [ "button", "green button" ],
    [ "yellow button", "button" ],
    [ "white button", "button" ],
    [ "bathysphere", "bell", "door", "hatch", "sphere" ],
    [ "porthole", "port", "hole" ],
    [ "jewel", "ruby", "moby ruby" ],
    [ "lights", "light", "exterior light" ],
    [ "waldo" ],
    [ "hand-hole", "hole", "control" ],
    [ "lever", "up-down lever" ],
    [ "freshwater fish", "fish" ],
    [ "saddle" ],
    [ "bird", "rooster", "vane" ],
    [ "boulder", "rock" ],
    [ "cave" ],
    [ "gravel" ],
    [ "more gravel", "gravel" ],
    [ "even more gravel", "gravel" ],
    [ "st", "galepath", "foobus", "shrine", "idol", "saint" ],
    [ "bowl", "carafe" ],
    [ "elixir", "liquid" ],
    [ "stole", "fox" ],
    [ "unicorns", "herd", "unicorn", "herd of unicorns" ],
    [ "odd green bridge", "bridge" ],
    [ "instruments", "music" ],
    [ "stream" ],
    [ "fixture", "camel" ],
    [ "cactus", "cacti" ],
    [ "oasis", "pool", "spring" ],
    [ "stand", "platform", "conductor's stand" ],
    [ "violin", "fancy violin", "stradivarius" ],
    [ "book", "Encyclopedia Frobozzica", "frobozzica", "encyclopedia" ],
    [ "famathria", "flies", "it" ],
    [ "member of the Flathead family", "flathead" ],
    [ "st", "wiskus", "bovus", "quakko", "honko", "saint", "balhu" ],
    [ "wizard", "frobozz", "Wiazard of Frobozz" ],
    [ "armor", "armour", "suit", "suit of armor" ],
    [ "lance" ],
    [ "head", "bargth", "oracle", "mouth" ],
    [ "depression" ],
    [ "amulet" ],
    [ "mountains", "Flathead Mountains", "mountain" ],
    [ "runes" ],
    [ "hole", "six-sided hole" ],
    [ "birch tree", "tree", "birch" ],
    [ "jewel", "jerrimore", "sapphire" ],
    [ "sandstone arch", "arch", "bridge" ],
    [ "man", "statue" ],
    [ "flower" ],
    [ "rock", "rocky spire", "spire" ],
    [ "easle", "easel" ],
    [ "painting", "landscape" ],
    [ "fjord", "the Flathead Fjord" ],
    [ "mountains", "Gray Mountains" ],
    [ "surface", "lake", "ice", "mirror" ],
    [ "reflection" ],
    [ "scale model", "model" ],
    [ "muck", "delta", "marsh", "swamp", "bog", "bayou" ],
    [ "huge lily pad", "pad" ],
    [ "otto", "ugly toad", "toad" ],
    [ "small lily pad", "pad" ],
    [ "telescope", "spyglass" ],
    [ "fly", "large fly" ],
    [ "fly", "larger fly" ],
    [ "fly", "even larger fly" ],
    [ "fly", "the largest fly" ],
    [ "river", "the Frigid River" ],
    [ "ocean", "the Flathead Ocean", "sea" ],
    [ "statue of Dimwit Flathead", "dimwit", "statue", "flathead" ],
    [ "poem" ],
    [ "wall hangings", "hanging", "hangings" ],
    [ "door", "trap door" ],
    [ "trunk" ],
    [ "robe", "wizardly robe" ],
    [ "saucepan", "pan" ],
    [ "notebook" ],
    [ "sizul", "fublitskee", "mordex", "xzilch", "hildebud", "eldablitz", "lizowurt", "sacred word", "zastic", "aulderfoo", "fzorty" ],
    [ "harmonica" ],
    [ "pile of stones", "stones", "pile", "cairn", "stone" ],
    [ "four-gloop vial", "vial", "writing" ],
    [ "pine", "ancient pine tree", "tree" ],
    [ "key", "rusty key" ],
    [ "fungus", "fungi", "toe fungus" ],
    [ "cousin", "irving", "sammy", "fungus", "little fungus", "barnaby", "melvin", "sherman", "omar", "ricardo", "julius", "seymour", "boris", "myron", "lester" ],
    [ "bat", "club", "wooden club" ],
    [ "nest" ],
    [ "silk tie", "tie" ],
    [ "sickly witch", "witch" ],
    [ "prickly witch", "witch" ],
    [ "nine-gloop vial", "vial", "writing" ],
    [ "pen", "quill pen", "quill" ],
    [ "granola mine", "mine" ],
    [ "granola" ],
    [ "card", "recipe card", "recipe" ],
    [ "wine", "banquet meal", "food" ],
    [ "drinking straw", "straw" ],
    [ "nut", "shell", "nutshell", "unopened walnut", "walnut" ],
    [ "walnut shell", "shell", "nutshell" ],
    [ "nut", "walnut" ],
    [ "platter", "platter of hellhound bones", "bones" ],
    [ "appetizer", "teriyaki", "tray", "tray of roc teriyaki" ],
    [ "cake" ],
    [ "keg", "wine", "wine keg" ],
    [ "pile of napkins", "linen", "pile", "napkins" ],
    [ "parchment", "piece", "scrap of parchment", "paper", "scrap" ],
    [ "Lord Dimwit Flathead the Excessive", "dimwit", "flathead" ],
    [ "table", "tables" ],
    [ "cauldron", "kettle" ],
    [ "man", "angry wizard", "wizard", "megaboz" ],
    [ "quotation" ],
    [ "village" ],
    [ "stump", "tree stump" ],
    [ "chest", "treasure chest" ],
    [ "crown", "gaudy crown" ],
    [ "gates", "door", "gate", "outer gate" ],
    [ "locker" ],
    [ "poster of Ursula Flathead", "ursula", "poster", "flathead" ],
    [ "steel key", "key" ],
    [ "elm", "gnarled elm tree", "tree" ],
    [ "elm", "ungnarled elm tree", "tree" ],
    [ "elm", "mighty elm tree", "tree" ],
    [ "engraving", "tenets", "engraved tenet", "tenet" ],
    [ "bookkeeping", "bookkeeper" ],
    [ "coin", "zorkmid", "zorkmid coin", "money" ],
    [ "toad", "toads", "pair", "pair of stone toads" ],
    [ "address", "package" ],
    [ "ceramic perch", "print", "lettering", "writing", "perch" ],
    [ "ceramic pigeon", "writing", "reproduction", "lettering", "pigeon", "bird", "print" ],
    [ "Frobozzco Building", "building", "hq", "headquarters" ],
    [ "memo" ],
    [ "damaged instruction booklet", "book", "booklet", "instructions" ],
    [ "T-square", "t-square" ],
    [ "torches", "torch" ],
    [ "button" ],
    [ "ground", "floor", "sand" ],
    [ "hands", "fingers", "finger", "palm", "hand" ],
    [ "toes", "feet", "toe", "foot" ],
    [ "head" ],
    [ "eye", "eyes" ],
    [ "nostril", "nose" ],
    [ "mouth" ],
    [ "protagonist" ],
    [ "diploma", "document" ],
    [ "zilbeetha" ],
    [ "brogmoidism" ],
    [ "flatheadia" ],
    [ "ineptitude", "ring" ],
] # nouns

rooms = [
    "West of House",
    "Plain",
    "Construction",
] # rooms

