# Config for ZORK 1, in an LLM style
#
#

########
## ZORK1
########
[game]
path = "./infocom/zork1/COMPILED/zork1.z3"

# setup text copied from wikipedia
setup = '''
Zork is a text-based adventure game wherein the player explores the ruins of the Great Underground Empire. The player types text commands for their character to traverse locations, solve puzzles, and collect treasure. The game has hundreds of locations, each with a name and description, and the player's commands interact with the objects, obstacles, and creatures within them. Commands can be one or two words (e.g., "get lamp" or "north") or more complex phrases (e.g., "put the lamp and sword in the case"). The command must fit the location's context (e.g., "get lamp" works only if a lamp is present). The program acts as a narrator, describing to the player their location and the results of certain actions. If the game does not understand the player's commands, it asks for the player to retype their actions. The program's replies are typically in a sarcastic, conversational tone, much as a Game Master would use in leading players in a tabletop role-playing game.

Much of the game world is composed of puzzles that must eventually be solved, such as a set of buttons on a dam or a maze to be traversed. Some puzzles have more than one solution. For instance, since the "Loud Room" is too overwhelmingly loud for the player to perform actions, the player can either empty the nearby dam to stop the sound of water falling, or shout "echo" in the room to change its acoustics.[3][6] In the first episode, or Zork I, a thief character is wandering the underground as well, taking items that have been left behind or even stealing from the player's possessions. The player can fight or evade the thief, and can recover stolen items from the thief's treasure room. Some locations contain antagonists that the player must fight or overcome. Beginning in Zork II the player can learn magic spells to use in puzzles and combat.[5] In dark areas, the player must carry a lantern or other light source to avoid being eaten by a monster called a grue. There is a limit to how much "inventory" one can carry, determined by the combined weight of objects, rather than the quantity.

A principal goal of each episode is to collect all the treasures, many of which are hidden behind puzzles. As treasures are collected or tasks are accomplished, the player's score increases, providing a rough measure of how much of the game has been completed. The player may traverse the game world and solve puzzles in almost any order, although some passageways require problem-solving to get through, and some puzzles require the player to possess something gained from solving a different puzzle.

Plot
Zork does not follow a linear storyline. Most of the setting is established through the game's written descriptions of items and locations, as well as manuals in later game releases. Long before the time the game is set in, the Quendor empire, having conquered everywhere above ground, built a massive cave complex to expand. Two hundred years later, the ruler Lord Dimwit Flathead renamed the empire to the Great Underground Empire and spent his reign building massive, largely pointless projects such as an underground dam and the royal museum. A century later, the empire's overspending caused it to collapse, and all the residents left. The abandoned empire is the setting of the three episodes of Zork.

Zork I begins with the unnamed player character near a white house in a small, self-contained area; most of the game occurs underground, as do the subsequent episodes.
'''

# no text files giving descriptions for the ZORK series
background_files = [
]

background_urls = [
    ["https://www.retrogamedeconstructionzone.com/2020/06/zork-1-review-fully-realized-fantasy.html",
    "Among the canon of early text adventures(.*)the true stuff of fantasy."
    ],
    ["https://www.metzomagic.com/showArticle.php?index=145",
    "You are standing in an open field(.*)go a little bit mad in the process."
    ]
]

## Not making use of the walkthrough, so far
walkthrough_urls = [
    ["https://web.mit.edu/marleigh/www/portfolio/Files/zork/transcript.html",
    "(.*)"
    ]
]


[syntax]
verbs = [
    [ "through", "using", "with", "thru" ],
    [ "into", "in", "inside" ],
    [ "on", "onto" ],
    [ "underneath", "below", "beneath", "under" ],
    [ "north", "n" ],
    [ "s", "south" ],
    [ "e", "east" ],
    [ "w", "west" ],
    [ "d", "down" ],
    [ "u", "up" ],
    [ "northwest", "nw" ],
    [ "northe", "ne" ],
    [ "southwest", "sw" ],
    [ "se", "southe" ],
    [ "superbrief", "super" ],
    [ "inventory", "i" ],
    [ "q", "quit" ],
    [ "answer", "reply" ],
    [ "attack", "fight", "hit", "injure", "hurt" ],
    [ "clean", "brush" ],
    [ "ignite", "burn", "incinerate" ],
    [ "barf", "chomp", "lose" ],
    [ "climb", "sit" ],
    [ "cross", "ford" ],
    [ "pierce", "slice", "cut" ],
    [ "shit", "fuck", "curse", "damn" ],
    [ "smash", "break", "destroy", "damage", "block" ],
    [ "drink", "imbibe", "swallow" ],
    [ "taste", "bite", "consume", "eat" ],
    [ "whats", "examine", "describe", "what" ],
    [ "cast", "begone", "banish", "exorcise", "drive" ],
    [ "douse", "extinguish" ],
    [ "seek", "where", "find", "see" ],
    [ "come", "chase", "follow", "pursue" ],
    [ "feed", "give", "offer", "donate" ],
    [ "hi", "hello" ],
    [ "chant", "incant" ],
    [ "dive", "leap", "jump" ],
    [ "kick", "taunt" ],
    [ "kill", "slay", "dispatch", "murder" ],
    [ "knock", "rap" ],
    [ "gaze", "l", "stare", "look" ],
    [ "lubricate", "grease", "oil" ],
    [ "melt", "liquify" ],
    [ "mumble", "sigh" ],
    [ "odysseus", "ulysses" ],
    [ "patch", "repair", "fix", "glue", "plug" ],
    [ "plugh", "xyzzy" ],
    [ "pour", "spill" ],
    [ "tug", "yank", "pull" ],
    [ "push", "press" ],
    [ "insert", "put", "place", "hide", "stuff" ],
    [ "raise", "lift" ],
    [ "molest", "rape" ],
    [ "read", "skim" ],
    [ "ring", "peal" ],
    [ "touch", "feel", "pat", "rub", "pet" ],
    [ "skip", "hop" ],
    [ "sniff", "smell" ],
    [ "wade", "swim", "bathe" ],
    [ "thrust", "swing" ],
    [ "remove", "hold", "catch", "carry", "get", "take", "grab" ],
    [ "ask", "tell" ],
    [ "throw", "toss", "hurl", "chuck" ],
    [ "tie", "attach", "secure", "fasten" ],
    [ "treasure", "temple" ],
    [ "flip", "turn", "set", "shut" ],
    [ "release", "unfasten", "free", "unhook", "unattach", "untie" ],
    [ "wait", "z" ],
    [ "surprise", "awake", "startle", "wake" ],
    [ "proceed", "step", "go", "walk", "run" ],
    [ "brandish", "wave" ],
    [ "winnage", "win" ],
    [ "shout", "scream", "yell" ],
    [ "verbose" ],
    [ "brief" ],
    [ "diagnose" ],
    [ "restart" ],
    [ "restore" ],
    [ "save" ],
    [ "score" ],
    [ "script" ],
    [ "unscript" ],
    [ "version" ],
    [ "activate" ],
    [ "apply" ],
    [ "back" ],
    [ "blast" ],
    [ "blow" ],
    [ "board" ],
    [ "bug" ],
    [ "close" ],
    [ "command" ],
    [ "count" ],
    [ "deflate" ],
    [ "dig" ],
    [ "disembark" ],
    [ "disenchant" ],
    [ "drop" ],
    [ "echo" ],
    [ "enchant" ],
    [ "enter" ],
    [ "exit" ],
    [ "fill" ],
    [ "frobozz" ],
    [ "hatch" ],
    [ "inflat" ],
    [ "stab" ],
    [ "kiss" ],
    [ "launch" ],
    [ "lean" ],
    [ "leave" ],
    [ "light" ],
    [ "listen" ],
    [ "lock" ],
    [ "lower" ],
    [ "make" ],
    [ "move" ],
    [ "roll" ],
    [ "open" ],
    [ "pick" ],
    [ "play" ],
    [ "poke" ],
    [ "puncture" ],
    [ "pray" ],
    [ "pump" ],
    [ "repent" ],
    [ "talk" ],
    [ "say" ],
    [ "search" ],
    [ "send" ],
    [ "shake" ],
    [ "slide" ],
    [ "spin" ],
    [ "spray" ],
    [ "squeeze" ],
    [ "stand" ],
    [ "stay" ],
    [ "strike" ],
    [ "unlock" ],
    [ "wear" ],
    [ "wind" ],
    [ "wish" ],
    [ "zork" ],
] # verbs

nouns = [
    [ "boards", "board" ],
    [ "teeth", "set of teeth", "overboard" ],
    [ "wall", "surrounding wall", "walls" ],
    [ "wall", "granite wall" ],
    [ "bird", "songbird" ],
    [ "white house", "house" ],
    [ "forest", "pines", "trees", "hemlocks" ],
    [ "branch", "tree" ],
    [ "mountain", "mountain range", "range" ],
    [ "water", "quantity" ],
    [ "water", "liquid", "quantity", "h2o", "quantity of water" ],
    [ "chimney" ],
    [ "spirits", "force", "ghosts", "fiends", "number of ghosts" ],
    [ "crystal skull", "skull", "head", "treasure" ],
    [ "cage", "basket", "dumbwaiter" ],
    [ "lunch", "food", "sandwich", "dinner" ],
    [ "vampire", "bat" ],
    [ "brass bell", "bell" ],
    [ "bell", "red hot brass bell" ],
    [ "axe", "ax", "bloody axe" ],
    [ "bolt", "nut" ],
    [ "bubble", "green bubble" ],
    [ "altar" ],
    [ "page", "prayer", "black book", "book", "books" ],
    [ "lantern", "broken lantern", "lamp" ],
    [ "scepter", "sceptre", "treasure" ],
    [ "pile", "broken timber", "timbers" ],
    [ "table", "kitchen table" ],
    [ "table" ],
    [ "bag", "brown sack", "sack" ],
    [ "chests", "chest", "toolchests", "group of tool chests", "group" ],
    [ "yellow button", "button", "switch" ],
    [ "button", "brown button", "switch" ],
    [ "button", "red button", "switch" ],
    [ "blue button", "button", "switch" ],
    [ "case", "trophy case" ],
    [ "carpet", "rug" ],
    [ "treasure", "chalice", "silver", "cup" ],
    [ "garlic", "clove", "clove of garlic" ],
    [ "treasure", "fork", "trident", "crystal trident" ],
    [ "eye", "cyclops", "monster" ],
    [ "gates", "dam", "gate" ],
    [ "cover", "trap-door", "trapdoor", "trap door", "door" ],
    [ "window", "boarded window" ],
    [ "door" ],
    [ "stone door", "door" ],
    [ "stone barrow", "barrow", "tomb" ],
    [ "glass bottle", "container", "bottle" ],
    [ "crack" ],
    [ "treasure", "casket", "coffin", "gold coffin" ],
    [ "grating", "grate" ],
    [ "tool", "pump", "tools", "hand-held air pump", "air-pump" ],
    [ "huge diamond", "diamond", "treasure" ],
    [ "treasure", "jade figurine", "figurine" ],
    [ "blade", "knives", "knife", "nasty knife" ],
    [ "skeleton", "bones", "body" ],
    [ "lantern", "burned-out lantern", "lamp" ],
    [ "treasure", "coins", "bag", "leather bag of coins" ],
    [ "brass lantern", "lantern", "light", "lamp" ],
    [ "treasure", "large emerald", "emerald" ],
    [ "advertisement", "mail", "booklet", "leaflet" ],
    [ "pipe", "drip", "leak" ],
    [ "pdp10", "machine", "dryer", "lid" ],
    [ "magic boat", "raft", "boat" ],
    [ "small mailbox", "box", "mailbox" ],
    [ "matches", "match", "matchbook" ],
    [ "mirror", "reflection", "enormous" ],
    [ "painting", "treasure", "art", "canvas" ],
    [ "pair", "candles", "pair of candles" ],
    [ "gunk", "small piece of vitreous slag", "piece", "slag" ],
    [ "bodies", "pile of bodies", "pile", "body", "remains" ],
    [ "leaf", "pile", "pile of leaves", "leaves" ],
    [ "boat", "punctured boat", "pile", "plastic" ],
    [ "boat", "pile of plastic", "pile", "plastic", "valve" ],
    [ "treasure", "bar", "platinum bar", "platinum" ],
    [ "pot", "pot of gold", "gold", "treasure" ],
    [ "inscription", "prayer" ],
    [ "railing", "wooden railing", "rail" ],
    [ "rainbow" ],
    [ "river" ],
    [ "red buoy", "buoy" ],
    [ "hemp", "rope", "coil" ],
    [ "knife", "rusty knife", "knives" ],
    [ "sand" ],
    [ "jewel", "treasure", "sapphire", "sapphire-encrusted bracelet", "bracelet" ],
    [ "driver", "tool", "tools", "screwdriver" ],
    [ "skeleton key", "key" ],
    [ "tool", "tools", "shovel" ],
    [ "coal", "pile", "small pile of coal", "heap" ],
    [ "ladder", "wooden ladder" ],
    [ "treasure", "beetle", "scarab", "bug", "beautiful jeweled scarab" ],
    [ "large bag", "bag" ],
    [ "stiletto" ],
    [ "switch" ],
    [ "lettering", "wooden door", "writing", "door" ],
    [ "sword", "blade", "glamdring", "orcrist" ],
    [ "ancient map", "parchment", "map" ],
    [ "label", "print", "fineprint", "tan label" ],
    [ "robber", "person", "man", "thief" ],
    [ "pedestal" ],
    [ "ivory", "torch", "treasure" ],
    [ "books", "guide", "guidebooks", "book", "tour guidebook" ],
    [ "troll" ],
    [ "treasure", "jewels", "chest", "trunk", "trunk of jewels" ],
    [ "tube", "tooth", "paste" ],
    [ "gunk", "material", "viscous material" ],
    [ "inscription", "wall", "engravings", "wall with engravings" ],
    [ "manual", "paper", "piece", "ZORK owner's manual" ],
    [ "wall", "cliff", "ledge", "walls" ],
    [ "cliffs", "cliff", "white cliffs" ],
    [ "wrench", "tool", "tools" ],
    [ "control panel", "panel" ],
    [ "nest", "bird's nest" ],
    [ "treasure", "egg", "jewel-encrusted egg" ],
    [ "treasure", "egg", "broken jewel-encrusted egg" ],
    [ "treasure", "bauble", "beautiful brass bauble" ],
    [ "treasure", "canary", "golden clockwork canary" ],
    [ "treasure", "canary", "broken clockwork canary" ],
    [ "intnum", "number" ],
    [ "pseudo" ],
    [ "him", "them", "it", "random object", "her" ],
    [ "blessings", "graces" ],
    [ "staircase", "stairway", "steps", "stairs" ],
    [ "aviator", "sailor", "footpad" ],
    [ "ground", "dirt", "sand", "floor" ],
    [ "grue", "lurking grue" ],
    [ "air", "mouth", "blast of air", "lungs", "breath" ],
    [ "you", "cretin", "me", "self", "myself" ],
    [ "cretin", "adventurer" ],
    [ "trail", "passage", "path" ],
    [ "zorkmid" ],
    [ "hand", "hands", "pair", "pair of hands" ],
    [ "zzmgck" ],
] # nouns

rooms = [
    "Cold Passage",
    "Drafty Room",
    "Shore",
    "Gas Room",
    "Clearing",
    "Reservoir North",
    "North-South Passage",
    "Mine Entrance",
    "Attic",
    "Stream",
    "Reservoir South",
    "Bat Room",
    "Gallery",
    "Sandy Beach",
    "Kitchen",
    "Machine Room",
    "Temple",
    "Rocky Ledge",
    "Stone Barrow",
    "Frigid River",
    "Torch Room",
    "Smelly Room",
    "Dam Lobby",
    "Forest Path",
    "Loud Room",
    "End of Rainbow",
    "Atlantis Room",
    "Slide Room",
    "White Cliffs Beach",
    "Stream View",
    "Ladder Top",
    "Treasure Room",
    "Living Room",
    "Dam Base",
    "Squeaky Room",
    "Canyon View",
    "Timber Room",
    "Coal Mine",
    "Twisting Passage",
    "Forest",
    "Reservoir",
    "Dead End",
    "Narrow Passage",
    "East of Chasm",
    "Maze",
    "Sandy Cave",
    "Round Room",
    "Entrance to Hades",
    "Chasm",
    "Egyptian Room",
    "Maintenance Room",
    "Ladder Bottom",
    "South of House",
    "Engravings Cave",
    "North of House",
    "Up a Tree",
    "On the Rainbow",
    "Aragain Falls",
    "Canyon Bottom",
    "Studio",
    "Deep Canyon",
    "Cyclops Room",
    "Strange Passage",
    "Cave",
    "Land of the Dead",
    "Cellar",
    "Winding Passage",
    "Mirror Room",
    "Grating Room",
    "West of House",
    "The Troll Room",
    "Shaft Room",
    "Altar",
    "Damp Cave",
    "Behind House",
    "East-West Passage",
    "Dome Room",
    "Dam",
] # rooms

